### ISSUE TITLE
[UI] [Touch] Multitouch doesn't work

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#100]
It's gonna be tough getting some hardware for testing, but it seems multi-touch actions like using the Shift key on the keyboard does not work.

Perhaps adding a document-wide touch event handler that would activate each element touched could fix the issue. *Can the onclick event be triggered by JS?* [yes](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click)

[this might help?](https://hammerjs.github.io/touch-emulator/)

P.S: #100 🎉

**Comment by GitSquared** [comment]
Added "investigation" tag and question mark to reflect that this issue isn't confirmed and i'm currently not able to test it.

If you're reading this, and you happen to have a large enough multi-touch screen, please contact me. Any help confirming this would be much appreciated.

**Comment by GitSquared** [comment]
@Beall619 Thank you, much appreciated.

**Comment by Beall619** [comment]
So i can can confirm that holding the on screen shift key, and then attempting to touch another button will pull the mouse and click it on the second press. Eg.. It is preferring the most recent press.

Also, i had to play around trying to right click things. 

Xfce4 whiskermenu wont do it, actually clicks the first spot..

Desktop icons and Thunar easily right click.

Google Chrome has another touch screen feature(as of right now) that requires the user to hold an area to right clock it.


I just thought that was interesting, it is very gui specific.

**Comment by GitSquared** [comment]
Damned. So i guess i'll have to write a custom touch handler or something.

Thanks for the info. I'll try and make something up, say for around next week if i can spare the time.

**Comment by GitSquared** [comment]
(Locking this until i make progress on it, thank you all)

**Comment by GitSquared** [comment]
Starting to work on this since i now have hardware to test it with (finally).
First try: 91c6d64

**Comment by GitSquared** [comment]
:tada:

**Comment by OriginMayo** [comment]
dragging two fingers away from each other or towards each other anywhere on the keyboard also creates quite a ridiculus amount of text input to the terminal, so large - i have to term the proc to regain control of the ui.
