### ISSUE TITLE
Incorrect display style in wide screen

### ISSUE THREAD

**Issue by zijian666** [GitSquared/edex-ui#1000]
as shown in the figure 

![Snipaste_2021-01-04_15-10-49](https://user-images.githubusercontent.com/70065868/103593494-f3120100-4f30-11eb-9860-32699a7f692c.png)

**Comment by wrac4242** [comment]
#989 has the same error for econnreset,

**Comment by GitSquared** [comment]
See #832 for tracking widescreen display errors, + the error that @wrac4242 pointed out.
