### ISSUE TITLE
rdp multiple system

### ISSUE THREAD

**Issue by shrw** [GitSquared/edex-ui#1004]
how can i rdp to multiple servers 
also having to access the files over ssh or ftp.

**Comment by Gilestech** [comment]
Hello Gab, how you doing

**Comment by GitSquared** [comment]
> Hello Gab, how you doing

Very good, thank you!

> how can i rdp to multiple servers
> also having to access the files over ssh or ftp.

@shrw I'm afraid this is a general terminal usage question that is out of scope for this repository. eDEX doesn't have any built-in support for interacting with remote servers.
