### ISSUE TITLE
windons上无法启动软件

### ISSUE THREAD

**Issue by USD-yang** [GitSquared/edex-ui#1005]
![Snipaste_2021-01-16_11-10-13](https://user-images.githubusercontent.com/62836949/104795748-a90c0380-57eb-11eb-9286-af09cd58c94c.jpg)

## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ 1] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year
 - [ ]点击运行安装包,安装完成后会提示软件已停止工作,并给出windows自定义选项,请问这个问题怎么解决
---

## ### Problem
![Snipaste_2021-01-16_11-10-13](https://user-images.githubusercontent.com/62836949/104795804-eec8cc00-57eb-11eb-81f7-3bb8832ba899.jpg)

(Write your report here. Screenshots and step-by-step instructions can help a lot!)

**Comment by GitSquared** [comment]
I don't think windows 7 is supported, sorry.
