### ISSUE TITLE
Uncaught TypeError: Cannot read property 'en' of undefined on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Dashon1** [GitSquared/edex-ui#1008]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
Everything works except typing. Whenever I type something the text disappears from the terminal and I get the above error.

Full Error:
Uncaught TypeError: Cannot read property 'en' of undefined
⬤  debug     at /tmp/.mount_eDEX-UdOydvd/resources/app.asar/node_modules/xterm-addon-ligatures/lib/xterm-addon-ligatures.js

Screenshot:
![image](https://user-images.githubusercontent.com/40647198/105577488-9f305600-5d3f-11eb-80d0-2bdc468992e3.png)

Steps to reproduce:
1. Assuming this problem is unique to Tumbleweed, so will start with that.
2. Open vs. 2.2.5.
3. Press any key on the keyboard.

System Info:
Operating System: openSUSE Tumbleweed 20210121
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.7-1-default
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-7500U CPU @ 2.70GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 620

**Comment by Dashon1** [comment]
I just checked and version 2.2.4 has the same issue. Tumbleweed may be missing a dependency somewhere.

**Comment by wrac4242** [comment]
#924 has the issue, it seems to be font related

**Comment by Dashon1** [comment]
Ahh. I see I am using a custom system font in kde. I thought that this would use the terminal font which should be a standard one. Is there a way for me to force eDex to use a different font from the system.

**Comment by wrac4242** [comment]
i belive you have to create a custom theme and bring in your own font, just from what i can tell by [this](https://github.com/GitSquared/edex-ui/wiki/Themes) and [this](https://github.com/GitSquared/edex-ui/wiki/Fonts) wiki page

**Comment by Dashon1** [comment]
Thanks. Perhaps I could just edit one of the included theme's or copy it and just change the font.

**Comment by Dashon1** [comment]
I'll close this since it seems to be related to another issue. Thanks for your help.

**Comment by Dashon1** [comment]
Bringing my own theme's and fonts still doesn't get rid of the error for some reason. Even though they seem to be applying everywhere but the terminal.

**Comment by rajkumarraiyan** [comment]
Thanks for your help

**Comment by rajkumarraiyan** [comment]
Thanks
