### ISSUE TITLE
Doesn't Load Sources Referenced in .*shrc

### ISSUE THREAD

**Issue by CodeConcerto** [GitSquared/edex-ui#1012]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Although .*shrc executes perfectly, the first instance refuses to load referenced sources. Ex. I have a .zsh_custom file running as source /home/concerto/.zsh_custom in .zshrc, which isn't run in eDEX. I tested this by running sleep, which did not trigger. I know this repo is no longer actively developed, but a similar [issue](https://github.com/GitSquared/edex-ui/issues/805) was reported back in November that I wanted to expand upon. It doesn't simply not output sourced files, it outright ignores them. The same thing happens with bash. Oddly enough, this issue isn't present in fish from what I can see.

**Comment by GitSquared** [comment]
Is [this](https://github.com/GitSquared/edex-ui/issues/805#issuecomment-720504428) true in your case too?

**Comment by GitSquared** [comment]
Closing as stale/no answer
