### ISSUE TITLE
can't display chinese

### ISSUE THREAD

**Issue by xukongwen** [GitSquared/edex-ui#1023]
## Technical information
**Using version:**
 - [ x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

can't display chinese.

(Write your report here. Screenshots and step-by-step instructions can help a lot!)

**Comment by wrac4242** [comment]
hey, can you please send a screenshot of what it looks like when you try to display chinese

**Comment by wrac4242** [comment]
and could the issue be with the founts installed, i see that its macOS, but it works on linux 
![image](https://user-images.githubusercontent.com/42539664/107112801-42aa5c00-6852-11eb-8d8c-181b0aeda578.png)

**Comment by xukongwen** [comment]
<a href="https://imgchr.com/i/yYRPtH"><img src="https://s3.ax1x.com/2021/02/06/yYRPtH.png" alt="yYRPtH.png" border="0" /></a>

hi, this is the screenshot, i'm use a m1 mac, and it shows this error message to me everytime.

and can this cool app run as defaut shell for mac?

thanks

**Comment by xukongwen** [comment]
<a href="https://imgchr.com/i/yYRRED"><img src="https://s3.ax1x.com/2021/02/06/yYRRED.png" alt="yYRRED.png" border="0" /></a>

**Comment by wrac4242** [comment]
hey, it seems to be related to [this](https://github.com/GitSquared/edex-ui/issues/982#issuecomment-752450810), can you try building/running from source to see if that is the issue

**Comment by wrac4242** [comment]
similar issue to #982 in error

**Comment by GitSquared** [comment]
new v2.2.6 version coming out in a few minutes will have (experimental) native support for apple silicon, check the macos-arm64 download. This should fix the font issue.

IP address issue is tracked at #982 indeed.
