### ISSUE TITLE
not opening on linx on chromeboox

### ISSUE THREAD

**Issue by catdh1099** [GitSquared/edex-ui#1026]
not opening on Linux on Chromebook plz help. 

## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here. Screenshots and step-by-step instructions can help a lot!)

**Comment by wrac4242** [comment]
hey, how are you trying to run it

**Comment by catdh1099** [comment]
on a chrombook

**Comment by wrac4242** [comment]
hi, can we have some more infomation, such as which version you are running

**Comment by Animus-Surge** [comment]
Hello! Unfortunately linux apps cannot run directly on a chromebook yet, and we can't determine exactly how you are trying to run eDEX without anymore information. If you could give us some more information such as the linux version you are trying to run in ChromeOS and the version of ChromeOS, that would be super helpful. Cheers!

**Comment by GitSquared** [comment]
Please reopen if needed, but I would guess this is out of scope for this repo. Thanks @Animus-Surge & @wrac4242.

**Comment by earthandy** [comment]
![image](https://user-images.githubusercontent.com/62155569/132953347-8cf3013d-614e-40e2-9c7a-129cd5b5c225.png)
but  not  show the ui window
