### ISSUE TITLE
Theme creator

### ISSUE THREAD

**Issue by Alonely0** [GitSquared/edex-ui#1027]
You could add a feature for creating a theme by clicking objects and setting color, moving elements to other positions and then inject the custom CSS, etc. Create a theme for eDEX is very difficult if you don't know how JSON works or if you don't have CSS knowledge (that's my case).

**Comment by wrac4242** [comment]
possibly can be done by having a template CSS code, and an ability to modify that, and refresh the display colour/theme, however i am not sure how that would work on the display
