### ISSUE TITLE
Elevating privileges fails

### ISSUE THREAD

**Issue by Dennisbonke** [GitSquared/edex-ui#1030]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [x] I attended [Defcon](https://defcon.org/) last year

---

## Problem

When you try to execute `sudo <cmd>` or try to become root with `su - root` sudo complains about effective uid not being zero and su reports an authentication failure. I've attached a screenshot that shows the results.
![Screenshot from 2021-02-11 01-14-50](https://user-images.githubusercontent.com/8709509/107589559-93310900-6c06-11eb-863e-f9d5fc49ca93.png)

**Comment by wrac4242** [comment]
hi, which distro are you using?
As apparently ubuntu has switching users like that disabled by default, use `sudo -i` instead, if that is the case

**Comment by wrac4242** [comment]
[based on this thread](https://askubuntu.com/questions/446570/why-does-su-fail-with-authentication-error)
i am also unable to replicate the issue

**Comment by GitSquared** [comment]
Closing as unrelated to eDEX - check your filesystem ops
