### ISSUE TITLE
Disable audio feedback when in Password Mode

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#1039]
cf: #1038 @schuelermine

> With sound enabled, a recording of you typing your password tells the attacker how long your password is.

**Comment by pyrocto** [comment]
On at least OS X 10.13.6, this currently doesn't work.  When using `sudo`, the keyboard shows the password characters I'm typing and beeps.

**Comment by schuelermine** [comment]
are you in password mode? you need to enable it explicitly, it does not get activated whenever sudo is used.

**Comment by pyrocto** [comment]
I was unaware of it.  How does one enable it?

**Comment by GitSquared** [comment]
@pyrocto the default [shortcut](https://github.com/GitSquared/edex-ui/wiki/Keyboard-shortcuts) is `Ctrl+Shift+P` to toggle it on/off.
