### ISSUE TITLE
2.2.5 macOS framebuffer errors

### ISSUE THREAD

**Issue by rinchen** [GitSquared/edex-ui#1047]
## Technical information
**Using version:**
 - [X] `latest` (latest release, currently `v2.2.5`)

**Running on:**
 - [X] macOS 11.2.1 Big Sur

**How comfortable you are with your system and/or IT in general:**
 - [X] My machine is fully under my control, tell me what you need

---

## Problem

2.2.5 won't go full screen at start nor when you manually attempt to toggle full screen. Framebuffer errors appear in the output. Also, the app consistently asks for network access on startup. 

$ ./eDEX-UI
▶  start     Starting eDEX-UI v2.2.5
ℹ  info      With Node 12.16.3 and Electron 10.2.0
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /Users/joey/Library/Application Support/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
☒  complete  Frontend window created!
…  watching  Waiting for frontend connection...
ℹ  info      Multithread worker started at 99201
ℹ  info      Multithread worker started at 99202
ℹ  info      Multithread worker started at 99203
ℹ  info      Multithread worker started at 99207
ℹ  info      Multithread worker started at 99205
ℹ  info      Multithread worker started at 99209
ℹ  info      Multithread worker started at 99212
[99133:0217/151014.430402:ERROR:gles2_cmd_decoder.cc(7062)] [.RendererMainThread-0x7ff903045c00]GL ERROR :GL_INVALID_OPERATION : glGetIntegerv: incomplete framebuffer
[99133:0217/151014.430539:ERROR:gles2_cmd_decoder.cc(7062)] [.RendererMainThread-0x7ff903045c00]GL ERROR :GL_INVALID_OPERATION : glGetIntegerv: incomplete framebuffer
[99133:0217/151014.440391:ERROR:gles2_cmd_decoder.cc(7062)] [.RendererMainThread-0x7ff903045c00]GL ERROR :GL_INVALID_OPERATION : glGetIntegerv: incomplete framebuffer
[99133:0217/151014.440440:ERROR:gles2_cmd_decoder.cc(7062)] [.RendererMainThread-0x7ff903045c00]GL ERROR :GL_INVALID_OPERATION : glGetIntegerv: incomplete framebuffer
[99133:0217/151014.448218:ERROR:gles2_cmd_decoder.cc(4968)] [.RendererMainThread-0x7ff903045c00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[99133:0217/151014.448467:ERROR:gles2_cmd_decoder.cc(4968)] [.RendererMainThread-0x7ff903045c00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[99133:0217/151014.497382:ERROR:gles2_cmd_decoder.cc(4968)] [.RendererMainThread-0x7ff903045c00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
[99133:0217/151014.497532:ERROR:gles2_cmd_decoder.cc(4968)] [.RendererMainThread-0x7ff903045c00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
✔  success   Connected to frontend!
◼  Startup   Timer run for: 11.70s
[99133:0217/151014.617945:ERROR:gles2_cmd_decoder.cc(4968)] [.RendererMainThread-0x7ff903045c00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glClear: framebuffer incomplete
ℹ  info      Resized TTY to  138 027
ℹ  info      UpdateChecker: Running latest version.
☒  complete  Shutting down...
☒  complete  Terminal exited { exitCode: 0, signal: 1 } undefined

**Comment by GitSquared** [comment]
The app needs network access to display some of its widgets, doesn't granting it make the permission pop-up go away?

The framebuffers errors should be unrelated. Are you running on Apple Silicon? I'm pushing a new version in a few minutes, v2.2.6, that will have experimental apple m1 builds (look for the macos arm64 download).

**Comment by rinchen** [comment]
Hi @GitSquared,

The errors do not show up until I give the program network access (which as mentioned earlier is a dialog showing up at every launch).

As for hardware, see attached. 
<img width="239" alt="Screen Shot 2021-02-22 at 10 22 19 " src="https://user-images.githubusercontent.com/44416/108745049-e2751480-74f7-11eb-8eea-999270aec642.png">

**Comment by rinchen** [comment]
I just tried 2.2.6 and the framebuffer errors are gone but the network access and lack of full screen remain.

<img width="1107" alt="Screen Shot 2021-02-22 at 10 30 11 " src="https://user-images.githubusercontent.com/44416/108746031-09801600-74f9-11eb-8175-f3d0f2846ac7.png">

**Comment by GitSquared** [comment]
Thanks for trying it out.

- Fullscreen: Can you please check in the settings modal (Ctrl+Shift+S) the values for `forceFullscreen` and `allowWindowed`? Also, are you by any chance using a desktop tiling utility? (stuff like [yabai](https://github.com/koekeishiya/yabai))
- Firewall modal: The wording here is a bit concerning as eDEX doesn't need *incoming* connections. What does the mentioned Firewall pane show for this app?

**Comment by rinchen** [comment]
- forceFullscreen - not present
- allowWindows - False
- Tiling manager - no I'm not
- Firewall - "Allow incoming connections"

Edit settings gives an error
<img width="951" alt="Screen Shot 2021-02-24 at 09 54 45 " src="https://user-images.githubusercontent.com/44416/109036106-8391d580-7686-11eb-92c9-a3d0d0b3c823.png">


✖  error     TypeError: electron.shell.openItem is not a function: Uncaught TypeError: electron.shell.openItem is not a function
⬤  debug     at file:///Applications/eDEX-UI.app/Contents/Resources/app.asar/ui.html 1:16
✖  error     Lost connection to frontend

I attempted to save the settings to a file. I got a positive response that it was saved to `settings.json` but for the life of me I can't find the file.

**Comment by GitSquared** [comment]
You should be able to find the file in `~/Library/Application Support/eDEX-UI`. Maybe try to delete everything in that folder and start edex again.

Re: Firewall, if you can "block the app from asking permission" or similar, do it - i'll investigate why it's asking for this

**Comment by rinchen** [comment]
Deleting the App Support directory got me full screen. 👍

**Comment by rinchen** [comment]
I removed the firewall entry and reattempted twice but I still get the prompt. Also now that I'm looking at it I found another bug.

<img width="298" alt="Screen Shot 2021-02-24 at 13 27 13 " src="https://user-images.githubusercontent.com/44416/109061616-1bea8300-76a4-11eb-98a1-9b1725c790a7.png">

**Comment by wrac4242** [comment]
#1052 had that issue, it seems to be fixed soon, possibly try running from source to see if it still is an issue

**Comment by GitSquared** [comment]
So only thing left here is the firewall pop-up issue.

**Comment by pyrocto** [comment]
Whenever I make *any* change to the default settings.json, it refuses to go to fullscreen after a restart.  Removing settings.json allows it to go full screen again.  I'm on OS X 10.13.6.
