### ISSUE TITLE
Top Processes widget not displaying any data

### ISSUE THREAD

**Issue by Hellaphant75** [GitSquared/edex-ui#1052]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.7-pre`)
 - [ x] `latest` (latest release, currently `v2.2.6`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ]x Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

(Write your report here. Screenshots and step-by-step instructions can help a lot!)

The Top Processes widget is not displaying any info. In version 2.2.2 there was a text box that let you configure the App before displaying the UI. As of now when I ran the release version of the program no such box appeared causing the Top Processes widget to malfunction. Please let me know how I can help.

![top_processes](https://user-images.githubusercontent.com/10968605/108773699-be7ff600-752c-11eb-8c4a-a3f7683894b9.png)

**Comment by kbarni** [comment]
Note that this affects also the "Active Processes" window. The CPU and Mem columns display "NaN%" for every item.

**Comment by Animus-Surge** [comment]
Happening on windows as well. Will look into this.

**Comment by GitSquared** [comment]
I'm taking a look at the code rn. I think some API changes in systeminformation broke the current imp.

**Comment by GitSquared** [comment]
Thanks for reporting! Will get a patch release out once I fix armv7 CI builds.

**Comment by Hellaphant75** [comment]
Thanks. This is a great project!!!!!

**Comment by GitSquared** [comment]
Thank you <3

**Comment by Dax911** [comment]
![image](https://user-images.githubusercontent.com/35853302/109563934-04493b00-7aa6-11eb-9704-2588f630e8ae.png)
This is also happening on the x86.AppImage
It worked fine on the previous release (the version where you announced that you weren't going to maintain the repo)

**Comment by GitSquared** [comment]
Yes, this has been fixed on master but not released yet.

**Comment by GitSquared** [comment]
Fix released in [v2.2.7](https://github.com/GitSquared/edex-ui/releases/tag/v2.2.7)

**Comment by Hellaphant75** [comment]
Thanks. I'll check it out!!!
