### ISSUE TITLE
Win 10 WSL Ubuntu 18.04 Binary launch failure

### ISSUE THREAD

**Issue by fkan-ec** [GitSquared/edex-ui#1055]
▶  start     Starting eDEX-UI v2.2.6
ℹ  info      With Node 12.18.3 and Electron 11.3.0
ℹ  info      Renderer is Chrome 87.0.4280.141
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/fkan/.config/eDEX-UI
☐  pending   Mirroring internal assets...
The futex facility returned an unexpected error code.Aborted

**Comment by wrac4242** [comment]
which version did you download? is it the linux app image or windows exe, and what happens if you run from source?

**Comment by GitSquared** [comment]
edex cannot be started from within wsl, use the Windows version directly.
