### ISSUE TITLE
Top processes show as NaN%

### ISSUE THREAD

**Issue by sadata7** [GitSquared/edex-ui#1062]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.7-pre`)
 - [x] `latest` (latest release, currently `v2.2.6`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

See attached screenshots. NaN% also appears for all items in the expanded view. Running under Linux Mint 20.1 on Dell OptiPlex 7080 (Core i9-10900, 64 GB RAM).

![Selection_192](https://user-images.githubusercontent.com/80186985/110228963-7faa5280-7ed3-11eb-9e04-1eb18d5edabf.png)
![Selection_194](https://user-images.githubusercontent.com/80186985/110228961-7c16cb80-7ed3-11eb-8bde-6a525727e4a0.png)

**Comment by Itai-Nelken** [comment]
I have the same problem on MacOS 11.2.2 intel.

**Comment by wrac4242** [comment]
see, #1052 fixed in master, not in latest release
