### ISSUE TITLE
Progressive consumption of Memory/RAM

### ISSUE THREAD

**Issue by juniorgerdet** [GitSquared/edex-ui#1066]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.7-pre`)
 - [x] `latest` (latest release, currently `v2.2.6`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

when Edex-UI is open by longtime consume progressively all Memory/Ram i'm using debian 10.3 (buster)

Before open Edex-UI:
![image](https://user-images.githubusercontent.com/4742111/110323601-33523600-7feb-11eb-8645-ae8322d9afb6.png)

After a couple hours:
![image](https://user-images.githubusercontent.com/4742111/110331754-e3c53780-7ff5-11eb-9178-2604285f78aa.png)

After close the Edex-UI keep proccess:
![image](https://user-images.githubusercontent.com/4742111/110332155-5c2bf880-7ff6-11eb-9ed0-812eeef15153.png)

**Comment by wrac4242** [comment]
this is very similar to #1057, except different operating system

**Comment by GitSquared** [comment]
Please reopen if still there after 5bf9018
