### ISSUE TITLE
eDEX-UI-macOS-arm64.dmg issue

### ISSUE THREAD

**Issue by daniellaera** [GitSquared/edex-ui#1067]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.7-pre`)
 - [ x] `latest` (latest release, currently `v2.2.6`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [ x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

The image explains
After installing on apple m1 bigsur

![Screenshot 2021-03-08 at 23 28 44](https://user-images.githubusercontent.com/8995710/110390334-1eff4f00-8066-11eb-98fa-1d480055e575.png)

**Comment by poly-genic** [comment]
Same issue here.

`❯ codesign -v /Applications/eDEX-UI.app`
`/Applications/eDEX-UI.app: code has no resources but signature indicates they must be present`

**Comment by poly-genic** [comment]
Was it not signed correctly?
