### ISSUE TITLE
Windows bug when I start eDEX-UI

### ISSUE THREAD

**Issue by WqxLoveCoding** [GitSquared/edex-ui#1087]
![image](https://user-images.githubusercontent.com/57825815/111089615-8e45d900-8567-11eb-9c1f-38e6469cb9af.png)
![image](https://user-images.githubusercontent.com/57825815/111089645-aae21100-8567-11eb-973b-dc33b9e55a68.png)

**Comment by SpilC** [comment]
I get everthing office xD

**Comment by wrac4242** [comment]
are you behind any firewalls? 
also can you give more information of the version you are running, 
if you are not running from source, could you try that

**Comment by sangshuduo** [comment]
it's better to support proxy to solve problems behind firewall like this issue.

**Comment by wrac4242** [comment]
i am checking to see if a firewall somewhere is causing an issue, or something else is causing the issue

Could someone who is experiencing this issue please give me more info in their 
version, 
operating system, 
and whether they are behind firewalls for not

**Comment by GitSquared** [comment]
See #1050
