### ISSUE TITLE
Mac M1 - Gatekeeper

### ISSUE THREAD

**Issue by ameeno** [GitSquared/edex-ui#1088]
## Technical information
Cannot launch latest m1 app due to gatekeeper. homebrew installs x86 version.

 - [ x] `latest` (latest release, currently `v2.2.6`)

**Running on:**

 - [x ] macOS arm64

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [x ] I attended [Defcon](https://defcon.org) last year

---

## Problem

So Homebrew installs x86 edex-ui. I downloaded and moved to applications the arm64 version, but am unable to launch it due to an unknown developer.

What's the command to unlock the app?

Could it be in the wiki/faq?

**Comment by Animus-Surge** [comment]
I believe [this may be of help.](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac#:~:text=Control%2Dclick%20the%20app%20icon,you%20can%20any%20registered%20app.)

**Comment by GitSquared** [comment]
Apple Silicon are broken atm either way, sorry... tracked in #1054
