### ISSUE TITLE
listen EACCES: permission denied 0.0.0.0:3000

### ISSUE THREAD

**Issue by ourfor-pp** [GitSquared/edex-ui#1091]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.7-pre`)
 - [x] `latest` (latest release, currently `v2.2.6`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem
![image](https://user-images.githubusercontent.com/45449335/111601987-e140ba00-880d-11eb-87cd-4ce16d1a6b7c.png)

(Write your report here. Screenshots and step-by-step instructions can help a lot!)

**Comment by wrac4242** [comment]
could you make sure you are running it as administrator if it asks, 
if that doesnt work, could you try running from source?

**Comment by GitSquared** [comment]
also check that you have nothing running on local :3000

**Comment by Spinestars** [comment]
> also check that you have nothing running on local :3000

I checked the port occupancy list, port 3000 is not occupied, and I used the super administrator to execute it.
But in the end, it still reports a permission denial error

**Comment by Spinestars** [comment]
It is indeed a port problem. When I modified the configuration file `%APPDATA%\eDEX -ui\settings.json` and changed the port in the configuration file to 30000, the software started normally.
