### ISSUE TITLE
always run on my laptop screen but my prime screen is that extend one

### ISSUE THREAD

**Issue by sangshuduo** [GitSquared/edex-ui#1092]
I use a big screen to connect my laptop and I set it as my prime screen from win10 system settings. but edex-ui always show screen on my laptop's small screen. May I know how to make it running on my extend screen? Thanks.

**Comment by GitSquared** [comment]
Change `monitor` in the [settings](https://github.com/GitSquared/edex-ui/wiki/settings.json).
