### ISSUE TITLE
CPU temperature not displaying any value.

### ISSUE THREAD

**Issue by uKaigo** [GitSquared/edex-ui#1101]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [x] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem
The temperature indicator of the CPU is not showing anything, instead displaying `null`.

![screenshot](https://user-images.githubusercontent.com/37600692/113430475-a06da700-93b0-11eb-8244-19970dcfa772.png)

It's not working in `v2.2.6` either.

**Comment by wrac4242** [comment]
could you try running from the source itself?

**Comment by uKaigo** [comment]
Done, and the same thing happens.

**Comment by GitSquared** [comment]
Mmmh. Let's try checking the reported value directly from the system information library.

Could you:
- start edex from source
- open the debugger (`ctrl+shift+i`)
- paste this in the Console: `window.si.cpuTemperature().then(d => console.log(d))`
- share the results here?

Here's a screenshot of what it should look like once you're done.

![image](https://user-images.githubusercontent.com/24496417/113474704-d6bf2b00-9471-11eb-85e5-2390e679792d.png)

Thanks for your help!

**Comment by uKaigo** [comment]
Here's what I get:
![image](https://user-images.githubusercontent.com/37600692/113480168-73c99600-9469-11eb-8a19-fdbe3d343b81.png)

**Comment by wrac4242** [comment]
which linux distro are you on, as a few dont have a sensor package installed by default

**Comment by uKaigo** [comment]
Mint 20.1 Ulyssa

**Comment by GitSquared** [comment]
Could you try these two shell commands:

`cat /sys/class/thermal/thermal_zone*/type  2>/dev/null; echo "-----"; cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null;`

`for mon in /sys/class/hwmon/hwmon*; do for label in "$mon"/temp*_label; do if [ -f $label ]; then value=$(echo $label | rev | cut -c 7- | rev)_input; if [ -f "$value" ]; then echo $(cat "$label")___$(cat "$value");  fi; fi; done; done;`

They should help us determine what sensors are available on your hardware and successfully detected by the kernel.

**Comment by uKaigo** [comment]
There's no `thermal_zone*` folder in `/sys/class/thermal/` (only `cooling_device*`).

The last command only returned a 0 exit code (without echoing anything).

Though running `sensors` I get
```
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +41.5°C  (high = +70.0°C)
```

**Comment by GitSquared** [comment]
Interesting, what directories are there in `/sys/class/hwmon`?

The `sensors` output show a thermometer on the PCI bridge but that's not what edex is looking for. I've pulled up the specs of your CPU (using the model name from the first screenshot you posted), and I'm starting to think it might not have an on-die thermal diode at all, but maybe I'm mistaken.

Here's what `sensors` looks like for me, for reference:

```
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +47.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +42.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +39.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +40.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +39.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +40.0°C  (high = +100.0°C, crit = +100.0°C)
Core 4:        +41.0°C  (high = +100.0°C, crit = +100.0°C)
Core 5:        +39.0°C  (high = +100.0°C, crit = +100.0°C)

BAT0-acpi-0
Adapter: ACPI interface
in0:          12.64 V  
curr1:       1000.00 uA 

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +25.0°C  (crit = +107.0°C)
```

You can see there's both a PCI bridge sensor and on-die sensors on the cpu, which is what edex is trying to find.

**Comment by uKaigo** [comment]
I see. There's only one directory in `/sys/class/hwmon`:
`hwmon0 -> ../../devices/pci0000:00/0000:00:18.3/hwmon/hwmon0`

**Comment by GitSquared** [comment]
Well that confirms it, you're missing the hardware sensor we're trying to read... I'm going to close this for now but I'll look with downstream dependencies to see if it's worth reading other sensors as a fallback and displaying that in edex.

Thanks for submitting a report & going through the debugging steps!
