### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by xiaomengheiheihei** [GitSquared/edex-ui#1103]
## Technical information
**Using version:**
 -  v2.2.7

**Running on:**
 -  macOS Catalina 10.15.7

**How comfortable you are with your system and/or IT in general:**
 - [x] My machine is fully under my control, tell me what you need
---

## Problem

(Write your report here. Screenshots and step-by-step instructions can help a lot!)
![image](https://user-images.githubusercontent.com/22885348/113806716-64ae5500-9795-11eb-8cf8-93967d13c7ee.png)

I did not read the source code, but look at the appearance should be a certificate problem?

**Comment by GitSquared** [comment]
Are you using a VPN?
