### ISSUE TITLE
Overlap on Second Screen

### ISSUE THREAD

**Issue by leander-hass** [GitSquared/edex-ui#1107]
## Technical information
**Using version:**
 - [ x ] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [ ] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ x ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ x ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

I have two screens and I let eDEX spawn in the second screen. When I launch it in Fullscreen-Mode it startes with the dimensions of my primary screen (wich is bigger) and I am not able to resize it. I fixed this Problem by launching it in Window-Mode and then switching with the Hotkey to Fullscreen.

Unimportant: When I launch it in Windowed, the Window keeps growing in small steps, dont know if its an easy fix but it doesnt concern me (as I instantly switch to Fullscreen).

Pls dont destroy me, this is my first Issue ever :)

**Comment by GitSquared** [comment]
Thanks for making an issue!
Could you tell me:
- what you've set in edex's `monitor` setting
- exact resolution of your displays
- if you have display scaling enabled - e.g the value of this box in windows' display settings:

![image](https://user-images.githubusercontent.com/24496417/115115576-8a0d4100-9f95-11eb-851d-b9d9a58957a5.png)

**Comment by leander-hass** [comment]
My main Display is 2560x1440 with 125% Scaling and my second display is 1680 x 1050 with 100% scaling.
(When I drag the oversized newly opened window to my main display the window-size fits exactly the screen.)
"monitor" is set to "1".

**Comment by kooshlash** [comment]
No transmission or mtu
