### ISSUE TITLE
Newest Version (v2.2.7) wouldn't start on windows 10.

### ISSUE THREAD

**Issue by innocentius** [GitSquared/edex-ui#1108]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [x] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem
I have tested a few versions (v2.2.7, 2.2.6, 2.0.1, 1.0.0) and none of them run on my windows 10 machine (v.2.2.2 runs good on ubuntu 18.04). 
I noticed you closed a few issues reported saying you are no longer supporting v2. However, since you recently re-opened support for eDEX-UI, I wonder when would the support for windows restart again?

I would note few things for you to recreate the bug: I'm running on Japanese language pack win10, dual screen both running on 1920*1080. GPU is NVIDIA 1070.

**Comment by wrac4242** [comment]
could you try building from master, so we can rule out build issues

**Comment by GitSquared** [comment]
> However, since you recently re-opened support for eDEX-UI, I wonder when would the support for windows restart again?

"Support" in this sense refers to fixing new bugs for the project as a whole, on all platforms - windows included ;)

Edex works on Windows out of the box for most people, but quirks happen. As @wrac4242 pointed out you should attempt to build the project from source, instructions are in the README.

You may also want to simply run edex from a Terminal/Powershell window to get runtime logs and see if there is an error there, first.
The binary should be somewhere in %AppData%/Local i think?

**Comment by innocentius** [comment]
> > However, since you recently re-opened support for eDEX-UI, I wonder when would the support for windows restart again?
> 
> "Support" in this sense refers to fixing new bugs for the project as a whole, on all platforms - windows included ;)
> 
> Edex works on Windows out of the box for most people, but quirks happen. As @wrac4242 pointed out you should attempt to build the project from source, instructions are in the README.
> 
> You may also want to simply run edex from a Terminal/Powershell window to get runtime logs and see if there is an error there, first.
> The binary should be somewhere in %AppData%/Local i think?

I hate myself for not already tried running the binary in cmd. Doing so revealed that my PATH environment variable don't have powershell.exe path included, added that and everything is a-OK.

**Comment by GitSquared** [comment]
No worries! Glad you could figure it out.
