### ISSUE TITLE
High CPU usage; display nan% in memory; launch error report 3 times pop-up Dialog

### ISSUE THREAD

**Issue by maxs-marcel** [GitSquared/edex-ui#1114]
1.CPU高占用
![image](https://user-images.githubusercontent.com/65930792/116499188-26144200-a8de-11eb-8ec1-369006c5ac43.png)
2.内存显示NaN%
![image](https://user-images.githubusercontent.com/65930792/116499248-4fcd6900-a8de-11eb-8ab3-692930847242.png)
3.初始开启程序报错
![image](https://user-images.githubusercontent.com/65930792/116499297-6ecbfb00-a8de-11eb-8e21-199cd38677e2.png)

**Comment by maxs-marcel** [comment]
最后一个问题已解决, 解决方式:
windows系统下, 修改hosts文件 在最底行增加
199.232.68.133 raw.githubusercontent.com
但是第一个和第二个问题仍然存在

**Comment by GitSquared** [comment]
1 & 2 are limitations on Windows, afraid we can't do much better. Regarding 3, some github IP addresses are blocked for users in China, we need to support proxies - see #1050.

Thanks for the report and the translation!

**Comment by GitSquared** [comment]
(Just fixed the NaN% in memory thing)

**Comment by apLundell** [comment]
I'm afraid I'm still seeing the very high CPU usage on the latest windows version.   
It seems to spawn an ever-increasing number of threads until >99% of my CPU is dedicated to edex.    
I've rolled back to a version from last year.    The version from mid 2020 I've rolled back to uses more CPU than you'd expect for a terminal, of _course_, but it uses a stable amount that doesn't increase over time.

**Comment by GitSquared** [comment]
@apLundell Could you share your machine specs and the version number that you've rolled back to? (can be found in the header of the Settings menu)

Performance on Windows is difficult to get right, see [this comment](https://github.com/GitSquared/edex-ui/discussions/1129#discussioncomment-814880), but thread starvation (what you're experiencing with a lot of process spawns) should not be happening.

**Comment by apLundell** [comment]
Sure. I'm on 
* Windows 10 (64bit) 
*  Intel i5-7600 & 3.8ghz
* 16gb of ram
* NVIDIA GeForce GTX 1070


As for versions... I guess I was confused about what version I had.   The version that *works* is reporting as "v3.0.0-pre" and if they file dates are to be trusted, It looks like I downloaded this on 5/5/2020.    I guess that makes this a dev build? I don't remember why I installed a dev build. That's not something I would normally do.

The versions that DON'T work for me, are the packaged windows releases. Like 2.2.7.   Those work fine initially, but fifteen minutes later my system is unusable.

So perhaps whatever my problem is, you've already fixed it.  If so : Thanks!

**Comment by GitSquared** [comment]
@apLundell Indeed, -pre are dev builds, but v2.2.7 should be better than a dev build from May last year.

Could you try downloading one of the latest dev builds by going to https://github.com/GitSquared/edex-ui/actions/runs/938949307 and scrolling down to "Artifacts", to check that it is not a problem with the packaged versions?

**Comment by apLundell** [comment]
I just tried the v2.2.8-pre version and it worked great.  

Just to make sure I wasn't leading you on a goose-chase, I re-installed v2.2.7.   It's still broken for me.   It's not subtle.  I just leave it running for five minutes and my computer is barely usable. 

Now I'm back on version v.2.2.8-pre and it's working great again.   I'm going to leave it running overnight to make sure, but it really seems like whatever the problem is, it's not in this version.

I hope this helps you track the problem down.

**Comment by GitSquared** [comment]
Hmmm. Maybe some bad commit made its way into 2.2.7. I should make a release in the coming weeks either way.

Thanks for trying it out & reporting back!
