### ISSUE TITLE
Mac OS Temperature is struck at 129C

### ISSUE THREAD

**Issue by ruthvik-17** [GitSquared/edex-ui#1115]
<img width="663" alt="Screenshot 2021-04-29 at 5 11 47 PM" src="https://user-images.githubusercontent.com/52532568/116546855-c3d43500-a90f-11eb-86c7-ec079555e9e5.png">
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [x] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

The temperature on the UI is struck at 129C when my system is reporting around 70C.

System details:
Mac Book Pro, 6-Core Intel Core i7
macOS Catalina 10.15.7

Attached is the screenshot while running `powermetrics --samplers smc |grep -i "CPU die temperature"` command.

**Comment by GitSquared** [comment]
We rely on https://github.com/sebhildebrandt/osx-temperature-sensor for temperature readings on macOS... Do you happen to have Node installed so we could verify it's a bug there?

**Comment by ruthvik-17** [comment]
Down due to Covid without access to my system. I do have node; I will get
back once I'm discharged.

**Comment by GitSquared** [comment]
Thanks for the reply. Get well soon my friend!

**Comment by ZRunner** [comment]
I just checked, on macOS 11.3.1. Here's the result of the NPM package:
```
{
  main: 86.75,
  cores: [
    76, 77,  69,  76,
    67, 71, 129, 129
  ],
  max: 129
}
```
So it looks like eDEX-UI is taking the max temperature instead of the main one :)

**Comment by GitSquared** [comment]
Yeah but... that's what we want. The problem is two cores are reporting to be at 129°C, which is impossible because they would be literally melting.

I'll look into where this info is read from...

**Comment by urbfigviera** [comment]
Ok I understand u now

**Comment by ItsMyIsland** [comment]
![1621284745446.jpg](https://user-images.githubusercontent.com/84348378/118556565-41c27980-b721-11eb-845a-b952fe68d9d6.jpg)![1621285180347.jpg](https://user-images.githubusercontent.com/84348378/118556576-45560080-b721-11eb-96e5-3768be4b2f4b.jpg)![1621285317564.jpg](https://user-images.githubusercontent.com/84348378/118556587-47b85a80-b721-11eb-8d86-44ce0224aac1.jpg)![1621285452061.jpg](https://user-images.githubusercontent.com/84348378/118556598-4a1ab480-b721-11eb-8929-962902770508.jpg)

**Comment by kooshlash** [comment]
Fat

**Comment by MrPaschenko** [comment]
Stuck at -1°C on MacBook Air M1
