### ISSUE TITLE
Uncaught Error: connect ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by cikichen** [GitSquared/edex-ui#1126]
![image](https://user-images.githubusercontent.com/1478821/120091180-459bc600-c13b-11eb-9f32-4fe595d1efc9.png)

## Technical information
**Using version:**
 - [ ] `latest` (latest release, currently `v2.2.7`)

**Running on:**
 - [ ] macOS

## Problem
![image](https://user-images.githubusercontent.com/1478821/120091203-7aa81880-c13b-11eb-8f0d-31c7342ad94a.png)
![image](https://user-images.githubusercontent.com/1478821/120091211-8a276180-c13b-11eb-9c1b-166f50e90034.png)

```
uname -a
```
Darwin.bbrouter 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64

**Comment by GitSquared** [comment]
See #1050
