### ISSUE TITLE
Ctrl + C issue in terminal on Windows

### ISSUE THREAD

**Issue by Killian-A** [GitSquared/edex-ui#1127]
## Technical information
**Using version:**
 - [x] `latest` (latest release, currently `v2.2.7`)
 
**Running on:**

 - [x] Windows

**How comfortable you are with your system and/or IT in general:**
 - [x] My machine is fully under my control, tell me what you need

---

## Problem

Doing ctrl + C to copy text in the terminal sends ctrl + C to the terminal and closes current command

Also, no context menu on right click so i cant copy another way

Either add the context menu or prevent ctrl+C from being sent to the terminal if text is selected ?

**Comment by GitSquared** [comment]
Use ctrl+shift+C / V for copy-paste actions. You can check all available shortcuts with ctrl+shift+k.
