### ISSUE TITLE
Uncaught Error: connect ECONNREFUSED 0.0.0.0:443 at events.js 292:7

### ISSUE THREAD

**Issue by liangsir1992** [GitSquared/edex-ui#1130]
## Technical information
**Using version:**
 - [ ] `latest` (latest release, currently `v2.2.7`)

**Running on:**
 - [ ] Linux (Deepin20.2.1)

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly

---

## Problem
![image](https://user-images.githubusercontent.com/11485856/120411093-ce5a7200-c386-11eb-8b6e-a6bb0f3e88d9.png)

**Comment by GitSquared** [comment]
Sorry you had to experience that. Something to do with regulated networks blocking out connections to GitHub-raw. Tracked in #1050
