### ISSUE TITLE
Ubuntu 20.04_Changed Terminal Setting.  Now won't open but running.  Need to access settings

### ISSUE THREAD

**Issue by davidjsullivan8** [GitSquared/edex-ui#1134]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [X ] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ X] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [X ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

Hello,
Seeking help, please.  Tried to find a fix and not seeing anything I'm able to use.  Sorry if I missed it.
Trying to run eDEX-UI-Linux-x86_64.AppImage - v2.2.7 - on Ubuntu 20.04.2 LTS - 64 bit.
It ran fine from the shortcut on the desktop until I went and changed the terminal to Terminator instead of Bash.
I can see It running:
![image](https://user-images.githubusercontent.com/70658144/122404084-eae0d780-cf4c-11eb-99f9-aae8098f25db.png)
Just need help to access the settings to revert the change.  Sorry for the hassle.  Let me know if you need more info.  Appreciate the help.  Thank you.  
djs

**Comment by GitSquared** [comment]
Hey!
You should be able to open `~/.config/eDEX-UI/settings.json` with a text editor and revert your change.

Hope this helps

**Comment by plkmmmmmm** [comment]
Cool

**Comment by 3598ad** [comment]
สวัสดีGithub.🙂ผม3598ad
ผมเพิ่งใด้รับemailจากคุณเมื่อไม่กี่นาทีที่ผ่านมา.ฉันแน่นอนยฉันต้องการคุณเสมอในการช่วยเหลือฉันในการสร้างแอฟพลิเคชั่นแรกของฉัน
และโปรแกรมนักพัฒนาของ ANDROID และ Google
แต่สิ่งที่ฉันจะบอกคุณระยะหลังมานี้ประมาณสัก2-3อาทิตยที่ผ่านมาฉันยังไม่ใด้ติดต่อถึงคุณ!ฉันคิดว่าน่าจะมีบุคลสวมรอยเป็นฉันเข้าไปขอข้อมูลดังกล่าวในgithub
ด้วยความเคารพ
อย่างสูง
ADEKA
PRODUCTIONS.

ในวันที่ ศ. 18 มิ.ย. 2021 10:39 plkmmmmmm ***@***.***>
เขียนว่า:
