### ISSUE TITLE
Missing icons cause panic

### ISSUE THREAD

**Issue by pyrocto** [GitSquared/edex-ui#1156]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [ ] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [x] I attended [Defcon](https://defcon.org) last year

---

## Problem

There are a few problems being caused by missing icons.  First, the missing `audio` icon means that mp3s and so forth merely show up as unknown files.  Second, the HTML templates for the audio player and the PDF renderer and so on all cause panics because of the missing icons for the controls.

The list of icons is missing at least `audio`, `zoomin`, `zoomout`, `arrowback`, `arrownext`, `playarrow`, `volumeup`, and `fullscreen`.

These icons seem like reasonable replacements if the original source is now missing. 
https://github.com/danklammer/bytesize-icons

**Comment by 15279797616** [comment]
> ## Technical information
> **Using version:**
>  - [x] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
>  - [ ] `latest` (latest release, currently `v2.2.7`)
>  - [ ] `vX.X.X` (specify other version)
> 
> **Running on:**
>  - [ ] Linux
>  - [ ] Windows
>  - [x] macOS
> 
> **How comfortable you are with your system and/or IT in general:**
>  - [ ] I'm kind of lost, honestly
>  - [ ] I know what's up, I could help you run some commands or checks
>  - [ ] My machine is fully under my control, tell me what you need
>  - [x] I attended [Defcon](https://defcon.org) last year
> 
> ---
> 
> ## Problem
> 
> There are a few problems being caused by missing icons.  First, the missing `audio` icon means that mp3s and so forth merely show up as unknown files.  Second, the HTML templates for the audio player and the PDF renderer and so on all cause panics because of the missing icons for the controls.
> 
> The list of icons is missing at least `audio`, `zoomin`, `zoomout`, `arrowback`, `arrownext`, `playarrow`, `volumeup`, and `fullscreen`.
> 
> These icons seem like reasonable replacements if the original source is now missing. 
> https://github.com/danklammer/bytesize-icons
>
