### ISSUE TITLE
edex-ui does not start, stuck on 'Settings loaded!'

### ISSUE THREAD

**Issue by shikonomi** [GitSquared/edex-ui#1168]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [x] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

So I've reinstalled Arch about a week ago. Afair edex-ui was working properly, at least on awesomewm+lightdm, so I've installed it again (currently running on GNOME 41.alpha, but also tried awesomewm again), but it didn't work (tried both AUR and Appimage ver).
I've noticed the issue #655, so tried to update kernel, but it didn't work.

## This is my output of: [shell] -ilc echo -n "_SHELL_ENV_DELIMITER_"; env; echo -n "_SHELL_ENV_DELIMITER_"

SHELL=/bin/bash
SESSION_MANAGER=local/tora:@/tmp/.ICE-unix/546,unix/tora:/tmp/.ICE-unix/546
COLORTERM=truecolor
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_MENU_PREFIX=gnome-
LC_ADDRESS=ja_JP.UTF-8
LC_NAME=ja_JP.UTF-8
XMODIFIERS=@im=ibus
DESKTOP_SESSION=gnome
LC_MONETARY=ja_JP.UTF-8
PWD=/home/neko
LOGNAME=neko
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=x11
SYSTEMD_EXEC_PID=554
XAUTHORITY=/home/neko/.Xauthority
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/neko
MOTD_SHOWN=pam
GDM_LANG=en_US.UTF-8
HOME=/home/neko
LC_PAPER=ja_JP.UTF-8
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=GNOME
VTE_VERSION=6402
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/3559ca1d_c88a_4e14_b0e3_8e83bdd0638e
XDG_SESSION_CLASS=user
TERM=xterm-256color
LC_IDENTIFICATION=en_US.UTF-8
USER=neko
GNOME_TERMINAL_SERVICE=:1.212
DISPLAY=:0
SHLVL=1
LC_TELEPHONE=ja_JP.UTF-8
QT_IM_MODULE=ibus
LC_MESSAGES=en_US.UTF-8
LC_MEASUREMENT=ja_JP.UTF-8
LC_CTYPE=en_US.UTF-8
XDG_RUNTIME_DIR=/run/user/1000
LC_TIME=ja_JP.UTF-8
LC_COLLATE=C
XDG_DATA_DIRS=/home/neko/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
GDMSESSION=gnome
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/neko
LC_NUMERIC=ja_JP.UTF-8
_=/usr/bin/env
_SHELL_ENV_DELIMITER_

**Comment by pyrocto** [comment]
When you run it from the command line, what does it report on stderr?  Are there any errors in the javascript console?

**Comment by shikonomi** [comment]
No, it just loads until the message "Settings loaded!" and nothing else happens.
Maybe something's with my node.js, since I've first installed the other version of it, and then got back to normal one, tho not sure.
