### ISSUE TITLE
Using A LOT of cpu

### ISSUE THREAD

**Issue by Venus007e** [GitSquared/edex-ui#1169]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.8-pre`)
 - [x] `latest` (latest release, currently `v2.2.7`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org) last year

---

## Problem

(Write your report here. Screenshots and step-by-step instructions can help a lot!)

It is using A LOT of cpu like in the pictures:

![image](https://user-images.githubusercontent.com/77722743/131891766-b4dccb1d-9d2e-4a30-92ad-8d60875abfa7.png)

![image](https://user-images.githubusercontent.com/77722743/131891922-20058036-283d-4b13-bb9a-37b8b7613b53.png)

Is this normal? If not, what can i do about it?

**Comment by parkerlreed** [comment]
https://github.com/GitSquared/edex-ui/issues?q=CPU+usage

**Comment by Jacksack2000** [comment]
Same here.
Edex ui eats up all cpu. 
GitSquared mentioned in another thread that this problem is known and he has to release an update. This was 20march I think. Nothing happened so far. Probably he hasn't had any time to do it.

**Comment by Jacksack2000** [comment]
As it is right now
It is unusable for win10 people.

**Comment by Jacksack2000** [comment]
Ok, it's dead my darling.

**Comment by GitSquared** [comment]
Not entirely, but yeah, wontfix for now (it works on _most_ machines, win10 included). Announcement/update soon, sorry for the lack of answers and clarity.

**Comment by EmNem543** [comment]
same issues on MacOS
