### ISSUE TITLE
no network connection on macOS

### ISSUE THREAD

**Issue by PIndividual** [GitSquared/edex-ui#1171]
Every time I start up e-dux, the system pups to a notification asking me to allow incoming network or not, even if I click allow, e-DUX still appears to be offline.
<img width="488" alt="Screen Shot 2021-09-13 at 7 04 01 PM" src="https://user-images.githubusercontent.com/62368342/133072854-8221c43b-535b-43bc-b0d2-9018d266b967.png">

**Comment by PIndividual** [comment]
![Screen Shot 2021-09-13 at 7 04 28 PM](https://user-images.githubusercontent.com/62368342/133072920-9a79d897-6fbf-422b-9927-4231cfe817a6.png)

**Comment by Animus-Surge** [comment]
You need to edit the field in the settings that changes what IP eDEX pings to check internet connection.
