### ISSUE TITLE
Run in MacOS Mojave fail.

### ISSUE THREAD

**Issue by Anderson-Liu** [GitSquared/edex-ui#190]
Version: I try both run from source code and install latest release mac os package.
Here is the log:

```
⬤  debug     Error: Got 404 (Not Found) response from server
✖  error     InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.: Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
⬤  debug     at file:///Users/anderson/Code/edex-ui/src/classes/terminal.class.js 166:29
●  note      UpdateChecker: Could not fetch latest release from GitHub's API.
⬤  debug     Error: Got 404 (Not Found) response from server
✖  error     [object Event]: Uncaught [object Event]
⬤  debug     at file:///Users/anderson/Code/edex-ui/src/classes/terminal.class.js 111:43
```

And here is the screenshot, which network traffic offline, file system display nothing, and terminal display nothing and can not type anything:
![image](https://user-images.githubusercontent.com/8468372/47445703-29e61b80-d7ec-11e8-9640-d2cb25057c86.png)

Here is the screenshot when I click enter:
![image](https://user-images.githubusercontent.com/8468372/47445728-35394700-d7ec-11e8-9516-d0dd11b175ad.png)

**Comment by GitSquared** [comment]
Thanks for your report!

Looks like the background process containing the actual terminal fails to start, so the UI can't connect to it.

Are you running anything on local ports between 3000-3100?

Is the log you provided from the parent terminal or electron devtools?

**Comment by Anderson-Liu** [comment]
Thank you! I have solve the problem. It's because I run something in 3000 port!

**Comment by GitSquared** [comment]
Glad to hear that!
Know that [you can change the port](https://github.com/GitSquared/edex-ui/wiki/settings.json) used by eDEX-UI if you want to keep port 3000 available.

**Comment by Anderson-Liu** [comment]
Okay, thank you so much!
