### ISSUE TITLE
`cd` does not respect directories with spaces

### ISSUE THREAD

**Issue by dvdmuckle** [GitSquared/edex-ui#219]
When clicking on a directory icon in the file browser, the created `cd` command does not add backslashes or otherwise escape spaces in directories that have spaces in their names. My guess is this may also extend to directories with other special characters as well.

**Comment by Beall619** [comment]
It sounds like the program needs to add quotations to all paths before trying to enter them in cd.

**Comment by GitSquared** [comment]
Yup, can confirm i didn't plan for this. Will publish a fix soon.

**Comment by dvdmuckle** [comment]
This does extend to other characters, and in fact you can abuse this bug by naming directories things like `thing || rm -rf /`.

**Comment by GitSquared** [comment]
@dvdmuckle I published a temporary fix, but I'll try to make a more advanced function to escape directories & file names properly. Will mention this issue when this gets pushed.

**Comment by dvdmuckle** [comment]
Tested, works properly. Thanks for the quick response!

**Comment by GitSquared** [comment]
You're welcome. I'll make a release tomorrow to bundle a bunch of day-1 fixes.
