### ISSUE TITLE
Unicode Glyphs and powerline symbols are not rendered correctly

### ISSUE THREAD

**Issue by xypnox** [GitSquared/edex-ui#220]
Here is the screenshot of my default terminal, as you can see symbols such as ` ` and `☐` are rendered correctly. (Font: Iosevka)

![2018-11-21_714x-02-56-59_scrot](https://user-images.githubusercontent.com/25076171/48803939-53d22580-ed39-11e8-81ea-85f8e4ff56c2.png)

However in the terminal of eDex ui, these symbols are not rendered correctly:
![2018-11-21_1920x-03-01-55_scrot](https://user-images.githubusercontent.com/25076171/48804198-fa1e2b00-ed39-11e8-9220-79d23e996dcf.png)

**Comment by GitSquared** [comment]
You'll need to change the terminal font to something that supports unicode symbols. If you got Iosevka installed on your system, just make a copy of the theme you want to use (in `.config/eDEX-UI/themes`), edit the file and change the terminal - fontFamily value. Save the file with a different name so it won't be overwritten when you restart edex. [More info here.](https://github.com/GitSquared/edex-ui/wiki/Themes)

If you don't have the font installed system-wide, you'll also want to [take a look at this.](https://github.com/GitSquared/edex-ui/wiki/Fonts)
