### ISSUE TITLE
Changing themes in a running instance overflows memory over time.

### ISSUE THREAD

**Issue by dvdmuckle** [GitSquared/edex-ui#221]
Using the file browser, if you change the theme of eDEX-UI a number of times, it starts to slow down and eventually grinds to a halt with the message `[17916:0100/000000.413673:FATAL:memory.cc(22)] Out of memory. size=262144`. It appears that when reloading a theme, the previous session is still being saved in memory, or something like that. This takes a number of theme changes to trigger on a machine with 16gb of RAM, though a smaller machine like my 8gb laptop doesn't take many theme changes.

**Comment by GitSquared** [comment]
([related source code](https://github.com/GitSquared/edex-ui/blob/master/src/_renderer.js#L300))

**Comment by gandf** [comment]
Each theme applied stay 3 process WmiPrvSE.exe running on Windows.
Run eDEX-UI and close it stay 3 WmiPrvSE.exe.
Bug is present even if you don't change theme.

**Comment by GitSquared** [comment]
Hold up, could that be a windows specific issue?

**Comment by gandf** [comment]
After others tests, several exe stay in live after change theme on Windows. I don't have tested on other OS. List on windows :
- conhost.exe
- cmd.exe
- NETSTAT.exe
- WMIC.exe or sometime replaced by WmiPrvSE.exe
Change theme or close eDEX-UI don't release these process.

**Comment by GitSquared** [comment]
Damned, that looks bad. Processes are related to systeminformation dependency i believe, but they should close.

Handling of node.js child processes on windows is a fucking unbearable mess and that's an understatement. Thanks for the detailed info, @gandf . I'll see what i can do.

**Comment by gandf** [comment]
This code create processes.
`initMods();`

This code should destroy processes but it don't do it before close app.
`delete window.mods;`

**Comment by GitSquared** [comment]
Yeah doing a namespace cleanup before shutting down is not a bad idea. Will implement this ASAP and see if it helps things.

**Comment by gandf** [comment]
I think, solution 2 can works with taskkill :
[stackoverflow](https://stackoverflow.com/questions/32705857/cant-kill-child-process-on-windows)

**Comment by GitSquared** [comment]
@dvdmuckle Could you please confirm on which OS you first had the issue?

**Comment by dvdmuckle** [comment]
@GitSquared Fedora 28.

**Comment by GitSquared** [comment]
(self-note: fix by implementing a `themeOverride` var in the core thread with the renderer's theme loader asking for it at startup, and effectively replacing the current messy recreation of modules by a full page reload)
