### ISSUE TITLE
eDEX unfocuses after initializing fullscreen

### ISSUE THREAD

**Issue by captainscorch** [GitSquared/edex-ui#223]
Hello,

first: Thank you for the amazing work with this! Having so much fun with this project. Everything is running fine, the globe seems to be working too. But once I close the App, I see at least 20 of these messages in the Terminal (I'm working with macOS). It seems like there's an error when the api tries to grab data to parse it to the locationGlobe.. Any idea what could cause this?

Also, something else: When I hit npm start the fullscreen opens for 1 second and then it switches back to my desktop and the terminal window and I have to open the electron app manually. Is this intended?

Thanks again! terminal output is below:

`⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh`

**Comment by GitSquared** [comment]
The ipinfo related error is due to the small API service i set up getting overloaded with all the fame. I'm working on rescaling it properly around the world.

About that switching window error, can you confirm that you're on windows?

**Comment by captainscorch** [comment]
Well, that explains the problem then haha.

Regarding your question, I did close every other application besides terminal and it still happened. The weird thing is, Electron is opened, the menu bar shows the electron menu etc. 
I'm getting following info and I think this might be related to the problem:

ℹ  info      Creating window...
Electron *** WARNING: Textured window <AtomNSWindow: > is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
