### ISSUE TITLE
Network widget overlaps with keyboard on 21:9 screens

### ISSUE THREAD

**Issue by Phundrak** [GitSquared/edex-ui#225]
Hello,
First of all, great job with this awesome project, that is really impressive! I’ve been playing around for about half an hour now, and I really enjoy it, however I immediately noticed something:
On ultra-wide screens (21:9), or at least on mine (2560x1080), there is an overlap of the network widget with the keyboard widget, as you can see on the image below
![2018-11-21-143722_2560x1080_scrot](https://user-images.githubusercontent.com/1893080/48846077-72b6d300-ed9e-11e8-866c-fa39787c27e0.png)

You can also see the Enter key is not correctly drawn on my 21:9 screen. I can confirm however that I do not have these issues on my regular 16:9 (1920x1080) screen.

I don’t think I’ll have time for now to look myself into this issue, however I think I will participate a bit some time soon on the keyboard side of the project.

Keep up with the great work!

**Comment by GitSquared** [comment]
Thanks for the report! Commit underway.

**Comment by Phundrak** [comment]
I confirm it has now been fixed, thanks!
