### ISSUE TITLE
Cannot set Progress Element

### ISSUE THREAD

**Issue by bannsec** [GitSquared/edex-ui#226]
I get a bunch of `TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.` when running this. The error is in: src/classes/filesystem.class.js 270:38.

I'm running a vanilla ubuntu:bionic docker image.

**Comment by michaelcv** [comment]
I have the same error on Windows 10. Just the line that differs : /resources/app.asar/classes/filesystem.class.js 1:12210 .

**Comment by GitSquared** [comment]
@michaelcv The different line is because you're running the package app with minified source code.

@bannsec I'm going to try and add a safeguard against this, should be easy enough i think.

**Comment by GitSquared** [comment]
@bannsec can you confirm this works?

**Comment by baryluk** [comment]
I also had this issue today with prebuilt AppImage for Linux x86_64, and figured out it will be some division / nan issue, maybe because I am running of live cd right now, and unionfs have a lot of weird mount points some of them of size zero or used space zero.

Not sure how to test it then, without doing complex build myself.

**Comment by baryluk** [comment]
BTW. I am not sure if isNAN will be sufficient. In some situations the results could be infinity too. Which is not a nan. i.e. is used = 10MB and size = 0 as reported by unionfs (I know it is weird), used / size will be infinity.

**Comment by baryluk** [comment]
One way is to do:

`used / size <= 1.0` instead. It will be false for both NaN and infinity, and in weird situations that used > size.

**Comment by GitSquared** [comment]
@baryluk Nice one. Will implement this.
