### ISSUE TITLE
Clicking on Edux-UI keyboard while typing causing unstoppable type spam.

### ISSUE THREAD

**Issue by AidanPrehatny** [GitSquared/edex-ui#229]
click on some keys on the keyboard in the UI while typing with a physical keyboard will cause the terminal to endlessly spam the keys in the terminal.

**Comment by Kelier** [comment]
yeah, I notice that too.

![image](https://user-images.githubusercontent.com/16694478/48880694-87ea3b00-ee4c-11e8-9406-c78fc17a2480.png)

**Comment by GitSquared** [comment]
@Kelier wow, seems like you got every issue at the same time. :/

**Comment by Kelier** [comment]
It's just my luck 😂

**Comment by GitSquared** [comment]
Can reproduce the bug. I tried implementing a fix by disabling the virtual keyboard when the physical one is in active use, that didn't work out. Seems the issue is that `mouseUp` events are not fired by chromium when the virtual keys gets spammed.

**Comment by GitSquared** [comment]
Hold up. Found it.
