### ISSUE TITLE
Errors on loading on Windows 10 x64/NVidia Quadro P2000 - can not read proporty

### ISSUE THREAD

**Issue by MattMacs** [GitSquared/edex-ui#234]
Related to issue #217, but on Win10 using NVidia...
<img width="1191" alt="error" src="https://user-images.githubusercontent.com/5098566/48896653-6be49a80-ee48-11e8-816b-9d52155325e1.png">

**Comment by GitSquared** [comment]
I guess #217 isn't specific to AMD gpus then.

Still the same issue though.
