### ISSUE TITLE
npm and brew command not found but it run correctly in other

### ISSUE THREAD

**Issue by fuergaosi233** [GitSquared/edex-ui#236]
![image](https://user-images.githubusercontent.com/22197568/48900862-893c5780-ee8e-11e8-96c5-aecf6c8bca27.png)
in edex-ui
![image](https://user-images.githubusercontent.com/22197568/48900879-96594680-ee8e-11e8-8121-a36a713087f0.png)
in iterm2

**Comment by GitSquared** [comment]
Same as #232 - this is an issue with your setup and unrelated to eDEX.

Maybe node is added to your $PATH by iTerm.

**Comment by GitSquared** [comment]
See #366 - more elaborate fix coming in 2.0
