### ISSUE TITLE
install fails on fresh npm install - win10 x64

### ISSUE THREAD

**Issue by chppppp** [GitSquared/edex-ui#241]
c:\lou\edex-ui-master>npm run install-windows

> edex-ui@1.0.1 preinstall-windows c:\lou\edex-ui-master
> npm install --global --production windows-build-tools && npm install --global node-gyp && setx PYTHON "%USERPROFILE%\.windows-build-tools\python27\python.exe"

> windows-build-tools@5.0.0 postinstall C:\Users\ys4admin\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

Downloading vs_BuildTools.exe
[>                                            ] 0.0% (0 B/s)
Downloaded vs_BuildTools.exe. Saved to C:\Users\ys4admin\.windows-build-tools\vs_BuildTools.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Python 2.7.15 is already installed, not installing again.

Now configuring the Visual Studio Build Tools..

All done!

+ windows-build-tools@5.0.0
updated 1 package in 20.734s
C:\Users\ys4admin\AppData\Roaming\npm\node-gyp -> C:\Users\ys4admin\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js
+ node-gyp@3.8.0
updated 1 package in 6.067s

SUCCESS: Specified value was saved.

> edex-ui@1.0.1 install-windows c:\lou\edex-ui-master
> npm install && cd src && npm install && ..\node_modules\.bin\electron-rebuild -f -w node-pty && cd ..

> edex-ui@1.0.1 prepare c:\lou\edex-ui-master
> npm run snyk-protect

> edex-ui@1.0.1 snyk-protect c:\lou\edex-ui-master
> snyk protect

Snyk couldn't patch the specified vulnerabilities because GNU's patch is not available. Please install 'patch' and try again.
 For more information please see our support page: https://support.snyk.io/snyk-cli/snyk-protect-requires-the-patch-binary.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@1.0.1 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edex-ui@1.0.1 snyk-protect script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ys4admin\AppData\Roaming\npm-cache\_logs\2018-11-22T16_44_08_590Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@1.0.1 prepare: `npm run snyk-protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edex-ui@1.0.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ys4admin\AppData\Roaming\npm-cache\_logs\2018-11-22T16_44_08_732Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@1.0.1 install-windows: `npm install && cd src && npm install && ..\node_modules\.bin\electron-rebuild -f -w node-pty && cd ..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edex-ui@1.0.1 install-windows script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ys4admin\AppData\Roaming\npm-cache\_logs\2018-11-22T16_44_08_836Z-debug.log

c:\lou\edex-ui-master>

**Comment by GitSquared** [comment]
This was something used in CI to patch eventual vulnerabilities. I removed it from the user-facing scripts.

**Comment by chppppp** [comment]
it works!
