### ISSUE TITLE
There is no key-repeat when using the physical keyboard

### ISSUE THREAD

**Issue by skamsie** [GitSquared/edex-ui#242]
When using the 'letter' keys on the physical keyboard, there is no key repeat, as in keeping the key pressed does not repeatedly input that character. This works fine for arrow keys and backspace, also when clicking on the virtual keyboard.

```
Mac OS HighSierra
MacBook Pro (13-inch, 2017)
```

**Comment by GitSquared** [comment]
Physical keyboard input is handled at the OS level. I'm afraid i can't do much. Maybe look into your system keyboard settings?

**Comment by skamsie** [comment]
@GitSquared the keyboard works fine for everything else... what to look for in the keyboard settings?

**Comment by GitSquared** [comment]
Frankly i'm not really sure, i only barely use macOS to test eDEX on it. I guess something like "key repeat"? Sorry i can't be of much help.
