### ISSUE TITLE
[Request] Add configuration option for ANSI keyboard layout, alongside ISO

### ISSUE THREAD

**Issue by leijurv** [GitSquared/edex-ui#244]
<img width="937" alt="screen shot 2018-11-22 at 9 42 20 am" src="https://user-images.githubusercontent.com/3837873/48917295-eb6b6d00-ee3a-11e8-84f5-ddeec7aae5af.png">

This is close, but the position of the backslash key is wrong, and there's an extra key that isn't really there, and the alignment of the bottom row with the home row is shifted right by about half a key, it should be moved to the left (in the ANSI layout). 

My keyboard looks more like this:
![image](https://user-images.githubusercontent.com/3837873/48917354-266da080-ee3b-11e8-997d-1039730984c9.png)

(however, I'm on a MacBook and the bottommost row really is FN, CTRL, ALT, CMD, space, CMD, ALT, arrow keys, but that matters less)

**Comment by leijurv** [comment]
Sad. @gitsquared why?

**Comment by GitSquared** [comment]
@leijurv Priorities. PRs welcome tho.
