### ISSUE TITLE
Is this based on Chromium?

### ISSUE THREAD

**Issue by rugk** [GitSquared/edex-ui#246]
> **Is this a real terminal?**
> Currently Windows, the latest macOS and any Linux distro that can run Chromium (AppImage package).

https://github.com/GitSquared/edex-ui#what-os-can-this-thing-run-on

So is this based on Chromium (Electron??!) or sues code from Chromium or why does it state this?

**Comment by GitSquared** [comment]
This is an Electron app, which is basically Chromium+Node.js.

Node.js runs pretty much everywhere, but Chromium has more needs (GUI support etc). What the README means is that if your linux distro can run Chromium, it'll run Electron - and eDEX.
