### ISSUE TITLE
Requires manually installing a lot of deps on MacOS

### ISSUE THREAD

**Issue by moonpatroller** [GitSquared/edex-ui#249]
Ran npm run build-darwin
Then had to manually install:
 signale
 clipboardy
 node-pty
 systeminformation
 smoothie
 xterm
 attach.js

Now it's complaining about a dependency of a dependency.

**Comment by GitSquared** [comment]
Weird. Did you run the npm script (`build-darwin`) on the root of the repository? (= not in /src or something).

Are you sure it didn't print anything unusual?

**Comment by hasDarren** [comment]
I ran into the same issues with needing to manually install everything. After I manually install all of the above dependencies, I ran into these errors.

✖  error     Error: Cannot find module './node_modules/xterm/lib/addons/attach/attach.js': Uncaught Error: Cannot find module './node_modules/xterm/lib/addons/attach/attach.js'
⬤  debug     at module.js 545:5
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined

**Comment by GitSquared** [comment]
This is an old NPM bug. See the links below for workarounds and reports.

https://stackoverflow.com/questions/18401606/npm-doesnt-install-module-dependencies
https://github.com/npm/npm/issues/1341
https://npm.community
