### ISSUE TITLE
Performance issues on Windows 10 x64 

### ISSUE THREAD

**Issue by bbrulard** [GitSquared/edex-ui#250]
Hi,

Launching eDEX-UI raise processor usage to 100% after a few seconds.

Spawns a lot of those process 

![image](https://user-images.githubusercontent.com/22780646/48922684-7a49ab00-ee76-11e8-9f50-b5f0b6889098.png)

Also a lot of thoses in the terminal: 

![image](https://user-images.githubusercontent.com/22780646/48922712-a06f4b00-ee76-11e8-9796-d2df38265662.png)

Not sur if related, but if the request to ipinfo.now.sh is the issue, can we turn off the request location part?

**Comment by bbrulard** [comment]
Seems related to #238 , nvm.

**Comment by GitSquared** [comment]
Duplicate indeed. But thanks for the screenshot.
