### ISSUE TITLE
Issue with modules

### ISSUE THREAD

**Issue by dchu650** [GitSquared/edex-ui#252]
✖  error     Error: Cannot find module './node_modules/xterm/lib/addons/attach/attach.js': Uncaught Error: Cannot find module './node_modules/xterm/lib/addons/attach/attach.js'
⬤  debug     at module.js 545:5
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined
●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
⬤  debug     Error: TypeError: Cannot read property 'latitude' of undefined

_Originally posted by @hasDarren in https://github.com/GitSquared/edex-ui/issues/249#issuecomment-441137535_

**Comment by GitSquared** [comment]
Duplicate.
