### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by dread-uo** [GitSquared/edex-ui#253]
Hello! I'd like to know if you plan to support Android; it would be awesome to have this running on tablets and smartphones.

**Comment by GitSquared** [comment]
No. This is a desktop app and it would need to a complete rewrite of both the UI and the internals to work on "mobile" devices. Sorry!

**Comment by qgustavor** [comment]
How much it depends on Electron and Node? Can those be switched with Cordova or PhoneGap, keeping the HTML/CSS/JS interface?

**Comment by GitSquared** [comment]
A good half of the code depends heavily on the Node.js ecosystem.

**Comment by qgustavor** [comment]
So the interface code isn't separated from the code which integrates with the system? I imagined it worked like a Node server handling system integration and a Electron process handling the user interface with some level of separation.

My plan, if it worked like that, would be making something to simulate the Node server and make it work in a website. Things like keyboard handling, CPU and memory usage and other things which websites can't handle would be faked. The terminal and file system could be something like [JSLinux](https://bellard.org/jslinux/).

**Comment by GitSquared** [comment]
No, currently the code is organized by UI elements (globe, memory map etc) but everything collecting system info is in the same thread as the renderer.

I'm planning to change that and rewrite most of the architecture, to prepare for a remote monitoring feature and fix huge performance issues.

**Comment by clragon** [comment]
any progress on this? having this on Android would be pretty lit

**Comment by GitSquared** [comment]
@clragon It would need to be a new, separate app and codebase and I'm not interested into starting this project, sorry.
