### ISSUE TITLE
[PERFORMANCE] Always high cost on CPU

### ISSUE THREAD

**Issue by poppinlp** [GitSquared/edex-ui#254]
Thanks for a really cool app! 👍 

I opened this on my mac with nothing changed in settings. Then it costs a lot on CPU:

![image](https://user-images.githubusercontent.com/1970625/48931007-17681a80-ef2f-11e8-94ca-bf68db4635bf.png)

- macOS 10.14.1
- i7 2.8GHz

Wish for a better performance or maybe some switches to disable some realtime features. :)

**Comment by GitSquared** [comment]
Upcoming. Related to progress on #238.

**Comment by poppinlp** [comment]
Thanks. 👍
