### ISSUE TITLE
Identifier 'os' has already been declared and missing stuff

### ISSUE THREAD

**Issue by Zardoz89** [GitSquared/edex-ui#257]
✖  error     SyntaxError: Identifier 'os' has already been declared: Uncaught ady been declared
⬤  debug     at file:///home/luis/repos/personal/edex-ui/src/classes/sysinfo.c

and : 
![imagen](https://user-images.githubusercontent.com/888483/48937304-f80cc580-ef0d-11e8-8a30-b1f3b6816e39.png)

**Comment by GitSquared** [comment]
89bf203
