### ISSUE TITLE
MacOS / Compilation Error

### ISSUE THREAD

**Issue by ekdual** [GitSquared/edex-ui#258]
Hi,

On MACOS Mojave
On NPM 6.4.1 

1. Run _**npm install snyk**_ ==> **OK**
2. Run _**npm run snyk-protect**_ ==> **OK**
3. Run **_npm install_** ==> **OK**

Then i launch **_npm run build-darwin_** ==> **KO** with error message below (after several minutes compilation) 
---------------------------------------
_**src/ui 2.html -> prebuild-src/ui 2.html
src/ui.html -> prebuild-src/ui.html
/Users/eric/Documents/GitHub/edex-ui/prebuild-src/classes/filesystem.class.js -  ❌

**/Users/eric/Documents/GitHub/edex-ui/prebuild-minify.js:51
                            throw minified.error;
                            ^**
SyntaxError: Unterminated string constant
    at JS_Parse_Error.get (eval at <anonymous> (/Users/eric/Documents/GitHub/edex-ui/node_modules/uglify-es/tools/node.js:21:1), <anonymous>:75:23)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@1.0.1 prebuild-darwin: `mkdir prebuild-src && cp -Rv src/* prebuild-src/ && node prebuild-minify.js && cd prebuild-src && npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edex-ui@1.0.1 prebuild-darwin script.**_

---------------------------------------

A clue please **?**
Thanks and congrat for your good Job : it's a very nice Term

**Comment by GitSquared** [comment]
That was a syntax error i accidentally commited to master because i'm trying to fix as many bugs as possible and i really need to take a break and sleep for a while.
It's been fixed :)
