### ISSUE TITLE
WSL Bash Terminal on Windows 10 Host

### ISSUE THREAD

**Issue by gaiaweylyn** [GitSquared/edex-ui#261]
Is there currently a good method for directly connecting to bash in a WSL instance with the edex-ui installed on the Windows 10 host? If not, would it be feasible to add such integration in the future?

**Comment by clragon** [comment]
Of course thats possible. just change the shell value to `bash.exe` or use `wsl` directly to bash into whatever distro you want.

**Comment by gaiaweylyn** [comment]
Awesome! Right. Will do some resting later on.

**Comment by GitSquared** [comment]
@clragon's answer is correct. Also note that clipboard access may not work when using WSL, see #231.
