### ISSUE TITLE
Detached tracking ends in dead end

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#262]
When ran on windows (where the file browser is detached), navigating into a folder that cannot be displayed, for example root dirs like `C:\`, the file view will display "CANNOT DISPLAY CURRENT WORKING DIRECTORY" which renders it useless since we cannot change the directory it is displaying when being detached.

**Comment by GitSquared** [comment]
Related to #235 - i guess i didn't understand it correctly. I'll see how i can handle this.

**Comment by clragon** [comment]
Displaying all windows mount points just like the folders would be very nice, This would also allow to change the selected disk, whic currently isnt possible.

**Comment by GitSquared** [comment]
Not a bad idea, please make a separate issue to request this.

**Comment by GitSquared** [comment]
So what I did is the display will still print the error message but it'll go back to the previous folder after a delay of a second.

**Comment by clragon** [comment]
This is till happening to me in the newest release, 1.1.1
@GitSquared

**Comment by GitSquared** [comment]
@clragon it doesn't go back after a second?
