### ISSUE TITLE
Crashing when running certain apps

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#263]
When running certain apps from the console, for example [Nano for windows](https://github.com/lhmouse/nano-win) eDEX-UI crashes instantly.

**Comment by GitSquared** [comment]
Now that's fucked up. No error messages or anything, even when spawning eDEX from a shell?

**Comment by clragon** [comment]
Here is what the console output shows. by the way, those chars are broken....

```
C:\Users\clragon\AppData\Local\Programs\edex-ui>
Ôû║  start                        Starting eDEX-UI v1.0.1
i  info                         With Node 8.9.3 and Electron 2.0.13
i  info                         Renderer is Chrome 61.0.3163.100
Ôû║  Startup                      Initialized timer...
i  info                         Base config dir is C:\Users\clragon\AppData\Roaming\eDEX-UI
[ ]  pending                      Loading settings file...
ÔêÜ  success                      Settings loaded!
[ ]  pending                      Creating new terminal process on port 3000
ÔêÜ  success                      Terminal back-end initialized!
i  info                         Creating window...
...  watching                     Waiting for frontend connection...
[├ù]  complete                     Frontend window is up!
i  info                         UpdateChecker: Running latest version.
ÔêÜ  success                      Connected to frontend!
[Ôûê] Startup                      Timer run for: 12.93s
i  info                         Resized TTY to  089 038
i  info                         Resized TTY to  138 036
Error while tracking TTY working directory:  Unsupported OS
[├ù]  complete                     Terminal exited 3221225786 undefined
[├ù]  complete                     Shutting down...
```

**Comment by GitSquared** [comment]
Yeah the logger is meant for *nix terminals with proper UTF8 and escape sequences support.

The `Terminal exited 3221225786 undefined` line comes from [this part](https://github.com/GitSquared/edex-ui/blob/master/src/_boot.js#L147), which traces back to [this one](https://github.com/GitSquared/edex-ui/blob/master/src/classes/terminal.class.js#L265) which means [node-pty](https://github.com/Microsoft/node-pty) is the one that failed.

Node-pty is maintained by Microsoft, which explains the ~~absolutely unhelpful~~ **`3221225786`** exit code, ~~big M hates meaningful errors~~ they care a lot about the quality of their code since they bought GitHub.

I think we might have to report this to them.

**Comment by GitSquared** [comment]
@clragon Would you mind reporting this upstream? I'd do it but i got no windows machine to test with right now and i don't want to make another mess lol.

**Comment by clragon** [comment]
@GitSquared sure, I just don't exactly know how I do that?

**Comment by GitSquared** [comment]
> @GitSquared sure, I just don't exactly know how I do that?

@clragon Just make an issue at https://github.com/Microsoft/node-pty, include the exit code mentioned above - it might help.

Thank you very much!

**Comment by clragon** [comment]
@GitSquared but what exactly is the issue I'm reporting?

**Comment by GitSquared** [comment]
@GitSquared Well that would be that node-pty crashes with a `3221225786` code when running certain apps.

**Comment by clragon** [comment]
@GitSquared works fine in a normal terminal though, only crashes inside eDEX-UI

**Comment by GitSquared** [comment]
@clragon node-pty version is `0.7.8` (latest i think)
