### ISSUE TITLE
Terminal window doesn't resize in windowed mode

### ISSUE THREAD

**Issue by aedelsten** [GitSquared/edex-ui#264]
If you hit F11 to put into windowed mode, you can resize the window (which I like) but the terminal window doesn't resize so text/input can render unseen/offscreen.

WAR is to hit F11 twice (once to go fullscreen, once to go back to windowed).

Low priority (loving edex.. so cool, great work! 👍  ).

**PC**
- Windows 10 x64 (still on build 1803)
- GeForce RTX 2070
- Two monitors (1 x 2160p, 1 x 1920x1200)

**Comment by GitSquared** [comment]
Weird that i didn't think of this. Low priority but easy to fix so that's coming right up.

(thank you! :heart:)
