### ISSUE TITLE
Doesn't react to alt+F4

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#265]
I dont know if this is intended, but closing the app with alt+F4 on windows doesn't work, it will print the characters into the console instead.

**Comment by GitSquared** [comment]
Weird. Alt+f4 works on *nix as far as i can tell.

**Comment by ow** [comment]
Yeah, doesn't work on Windows 10 for me at all. I have to end task 3x processes.

**Comment by GitSquared** [comment]
@clragon Are you running from source?

**Comment by clragon** [comment]
@GitSquared what do you mean by that?

**Comment by GitSquared** [comment]
@clragon Do you run eDEX through git and npm or just the binary?

**Comment by clragon** [comment]
@GitSquared I run the cmopiled binary from the releases page.
