### ISSUE TITLE
Disk view in file browser

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#266]
It would be very nice to have a view of all disks as folders when exiting one with the file browser on windows. This would also allow changing the current disk.

**Comment by GitSquared** [comment]
Note that this would be for all platforms, not only windows.

**Comment by clragon** [comment]
@GitSquared I though Linux has `/` which you cannot "exit", you could only enter or leave a mount point, if I'm correct there.

**Comment by clragon** [comment]
Would be extra cool if it would get the disk icons from Windows and colors them depending on theme.

**Comment by GitSquared** [comment]
![edex-newfsdisp-showcase](https://user-images.githubusercontent.com/24496417/50426147-54edf980-0887-11e9-9c90-96c08f9f0c23.gif)

**Comment by clragon** [comment]
hot
