### ISSUE TITLE
Support for parameters for shell

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#267]
![screenshot_1](https://user-images.githubusercontent.com/11785085/48954262-0af0bb80-ef49-11e8-8fe1-20d5178de5f6.png)

As seen in this picture, trying to pass any parameters to the selected shell app will result in a launch failure.
I'd love it, if this could be supported.

**Comment by GitSquared** [comment]
They call me the fastest keyboard in the west.
