### ISSUE TITLE
Zombie-Processes?

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#268]
![screenshot_2](https://user-images.githubusercontent.com/11785085/48955619-07f8c980-ef4f-11e8-9f5d-56bcb9fe29ce.png)

After murdering eDEX-UI over the taskbar right click with "close", those two processes remain running in the background, and you have to kill the manually.

**Comment by clragon** [comment]
Could be, though this isn't actually a forceful way of exiting a program. I think windows just sends the sigterm equivalent, and not a sigkill, so the process should handle it and exit normally?

**Comment by GitSquared** [comment]
There's already a handler for SIGTERM (or equivalent). IMO problem is the windows task manager being kind of fucked up and node.js child process management on windows being WAY too fucked up. Not a good mix.

Anyway hopefully when i'll change the way edex spawns subprocesses on windows to solve 238 this should disappear.
