### ISSUE TITLE
File browser enhancements

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#269]
![screenshot_1](https://user-images.githubusercontent.com/11785085/48955656-3ecedf80-ef4f-11e8-9def-4cd8834249f3.png)

If it doesnt disrupt the functions of other terminals, it would be nice if there would be quotes around paths that have spaces, just like when you drag and drop any file into cmd.

It would also be neat to have an option to hide or show system files (like desktop.ini) in windows.

**Comment by GitSquared** [comment]
System files would need to be a different issue, i'm afraid. I would need to filter them by extension.

**Comment by clragon** [comment]
I'm afraid, that isnt so. Windows has a system with which you can tag any file or folder with the "hidden" and "system" tag. This can be easily accessed over `cmd` using the `attrib` command. Thats what I mean by "system files".

**Comment by GitSquared** [comment]
I believe hidden files are actually greyed out already. But i don't think Node's `fs` provides the "system" attribute as a metadata on files. Will need deeper investigation anyway.
