### ISSUE TITLE
Filesystem panel did not change when using tmux

### ISSUE THREAD

**Issue by bruce30262** [GitSquared/edex-ui#271]
Screenshot:
<img width="683" alt="default" src="https://user-images.githubusercontent.com/4478350/48956135-2b8e3500-ef8c-11e8-965f-566cc472fd69.png">

As we can see if we change the directory inside tmux, the `FILESYSTEM` panel is still in the directory before we launch the tmux session.

**Comment by clragon** [comment]
I think this is actually because tmux is running a shell in a shell and the tracking only focuses on the outer layered shell which also sets the current work directory variable on which the tracking relies. This isn't a bug but rather just how this works.

**Comment by GitSquared** [comment]
Correct explanation by @clragon. However, i'm unable to fix it because i have no way of tracking sub-sub-processes through node-pty. You might be interested by #260.
