### ISSUE TITLE
Write a blog post about the making of eDEX

### ISSUE THREAD

**Issue by chppppp** [GitSquared/edex-ui#272]
Feel free to close this if you'd like but I figure I would ask!

I am a js n00b and I would love some kind of basic writeup on how you wrote this project. I am sure others would love that as well. It would prob score you some good points on HN/Reddit :) 

Thanks!

**Comment by GitSquared** [comment]
This is kind of heartbreaking but it's been 2 years and the fact is i've moved on. I still keep this project alive and it might get a revival at some point, but until then... closing this.
