### ISSUE TITLE
Phone-like shift key

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#273]
I've seen that multi-touch support isnt there yet, and this won't fix it, but it could at least temporarily allow using the shift key with touch input and later on still be useful.

Idea: when touching the shift key it will lock in pressed state until another key is pressed and it is "used" to capitalize any letter or until you just press the shift key again to release it.

This said, I don't exactly know how touch input in desktop devices works and I cannot test it myself, but I though I might put this in here.

**Comment by GitSquared** [comment]
You could just use capslock while waiting for #100 to be fixed. Also while this is technically easy to implement i'm not sure how it will be toggled on/off. I'm considering closing this one unless someone else is interested.
