### ISSUE TITLE
make default font UTF-8 unicode compatible

### ISSUE THREAD

**Issue by Clinan** [GitSquared/edex-ui#276]
Hi, We need Chinese
best wish.

**Comment by clragon** [comment]
Maybe he meant a chinese keyboard layout

**Comment by GitSquared** [comment]
I don't even know what that looks like

**Comment by dmcslt** [comment]
chinese support

**Comment by MycroftHolmes1989** [comment]
I would love to have UTF-8 support as well. Then I can rice up the terminal with Oh-my-zsh.

**Comment by GitSquared** [comment]
@MycroftHolmes1989 It's shipping in 2.0.0 in a few days :-)

You can always use a custom font in the meantime.
