### ISSUE TITLE
Some suggestions about displaying information

### ISSUE THREAD

**Issue by dmknght** [GitSquared/edex-ui#277]
Hi! I've seen your project and i really really love it. I think there are some thing that you can add into next version:
1. Showing current network interface name (ethernet, wireless, tunnel, ...)
2. Showing if user is using VPN or Tor service.
3. Add option to replace keyboard layout by other layout (monitoring inbound and outbound connection; other opening applications - this is kinda like showing tasks when type Alt + Tab; ). The reason is i think some users don't have touch screen, and Keyboard layout slows my typing speed.
Anyway thanks for awesome project. Please keep it up :p

**Comment by GitSquared** [comment]
1 - Technically possible, will see how i can display it in the UI
2 - This one is a bit more tricky and i'm not sure i can make it work reliably, but i'll check it out

And about 3) there has been requests to hide the virtual keyboard so i'll probably make that possible, but i'm not really keen on having another cool widget that would be only for desktop users - keep in mind the primary target here is touchscreens. Will look into it.

**Comment by dmknght** [comment]
I played conky configuration before and conky has `if_running` api to check running tasks so checks tor status is very easy. I hope it will be easy in your project too.
About displaying VPN, there are many vpn services so i think it is harder. But showing something likes `You are protected under Tor / <VPN name>` would be hollywood-awesome!
About 1, It is hard if users have `Virtual interfaces` (Virtualbox, VMware, docker). Maybe filter it is hard @@
About 3, there is monitoring connection from my conky. I hope you will have new idea with this :D 
![screenshot from 2018-11-24 18-21-55](https://user-images.githubusercontent.com/29118926/48967709-71440f80-f017-11e8-9af9-976bfb4a6e1f.png)

**Comment by GitSquared** [comment]
@dmknght Love the conky screenshot. You should definitely post that on [r/unixporn](https://reddit.com/r/unixporn)!

I'm afraid going through all the processes to look for something name "tor" or "VPN" would be too resource-intensive and not worth the pain. And regarding the network interface, eDEX already filters through all the interfaces available to find the right one to monitor, so it'd be easy for me to just print the name somewhere.
