### ISSUE TITLE
bloated software

### ISSUE THREAD

**Issue by neocris** [GitSquared/edex-ui#280]
i had the most horrible experience trying to install this piece of junk

it started by downloading python 2.7 when i have it installed already, doesn't perform a standard check to whereas it is needed or not just snatch it

tons of GBs of dependencies for a simple **terminal desktop**, the install script doesn't even provide an install progress status, it just starts downloading whatever it has and leaves one in the waiting oblivious to where it stands on the overall process. after 1,5GB of downloading i just killed it on cold blood but if it was pulling the all visual studio crap it was on the way to a nice 7GB(!) dump

at the very least provide a warning on the readme file about the full dependencies before the users start getting this giga load on their drives

**Comment by GitSquared** [comment]
You were trying to install all the necessaries tools and software to run the code from source, which is only meant for developers.

Precompiled binaries (about 60 Mo) are available on the Releases page.
