### ISSUE TITLE
Don't automatically install .desktop file

### ISSUE THREAD

**Issue by eadwu** [GitSquared/edex-ui#284]
The AppImage currently installs a `.desktop` file for eDEX in `~/.local/share/applications` when run. On some package management tools, `.desktop` files are already generated on a per package basis already. At the same time, I prefer knowing what/where the files a particular application creates go, and without searching, one would only find out about `~/.config/eDEX-UI`.

**Comment by GitSquared** [comment]
The AppImage asks whether or not you want it to integrate the app with your system (aka placing a .desktop file) via a pop-up on launch. This is a non-issue.
![screenshot from 2018-11-24 17-36-17](https://user-images.githubusercontent.com/24496417/48970682-8f0d7680-f00f-11e8-930c-ae6d64b22819.png)

**Comment by eadwu** [comment]
Oh, guess this is a NixOS issue with `appimage-run` since I don't see that prompt at all.

**Comment by morphx666** [comment]
I did get the prompt when running version 2.2.2
Version 2.2.4 doesn't seem to generate it.

I'm running Ubuntu 20.10
