### ISSUE TITLE
Windows change theme color

### ISSUE THREAD

**Issue by mkbcaptain** [GitSquared/edex-ui#290]
When i navigate to the theme folder and i change the tron.json theme color values, then launch eDEX-UI, it defaults back, is there a reason for this? How should i go about changing the colors?

**Comment by GitSquared** [comment]
From [the wiki](https://github.com/GitSquared/edex-ui/wiki/Themes):

> If you want to create your own theme, you should save it as a new file instead of overwriting an included theme, otherwise it will get removed the next time you launch eDEX.

tl;dr save your theme with a different name otherwise it gets printed over.

**Comment by mkbcaptain** [comment]
AHH!  Yes, make perfect sense!  Thank you!

**Comment by mkbcaptain** [comment]
Last question, is there a way to remove the keyboard?
