### ISSUE TITLE
Error when opening new Tab if port is already in use

### ISSUE THREAD

**Issue by r15ch13** [GitSquared/edex-ui#296]
Opening a new Tab if port `3002` is already in use (by another web application on my system) it reports the following error and dies.
![port in use error](https://user-images.githubusercontent.com/432127/49017354-f69b0180-f188-11e8-8cb5-deb402602e1b.png)
![tty not spawned error](https://user-images.githubusercontent.com/432127/49017447-29dd9080-f189-11e8-91b6-a029bd1facb5.png)

It might be better to skip the port if it's already in use.

**Comment by GitSquared** [comment]
This is expected behavior. Automatic port selection isn't available (yet). See the wiki for how to select a different port if you need to keep 3000 available.
