### ISSUE TITLE
Last line cut off on 1.1.1

### ISSUE THREAD

**Issue by jajaperson** [GitSquared/edex-ui#302]
Kind of similar to #291 . After upgrading, overflow no longer was visible, but the bottom line on the terminal (e.g. the vim command line) is hidden underneath the keyboard/file system bar.

**System**: MacOS Sierra
**Shell**: `bash`

![Screen shot of Issue](https://user-images.githubusercontent.com/25611007/49080168-b9646b80-f27d-11e8-9fec-5c85ad8f95c8.png)

**Comment by SerpentChris** [comment]
The same thing happens with 1.1.1 in Mojave for me.

**Comment by GitSquared** [comment]
@akbiggs It's a bit of a hack because xterm.js' fit addon tends to cut smaller than the actual available size.

I'm wondering if the bug isn't related to you guys having a different screen ratio than 16:9 (i know some macOS devices use 16:10 or whatever), could you confirm this? @SerpentChris @jajaperson

**Comment by akbiggs** [comment]
Yup, you're right. I'm on a 16:10 display.

**Comment by GitSquared** [comment]
@akbiggs All right. If you confirm that it works as intended on 16:9, i'll make a workaround for this by testing the screen resolution before applying this "fix".

Mind if you give me the exact screen res of your 16:10 display?

**Comment by akbiggs** [comment]
2880 x 1800

Thanks so much for the speedy responses! This is super cool!!!

**Comment by jajaperson** [comment]
I'm on a 1440 x 900 (16:10) display.

**Comment by GitSquared** [comment]
@akbiggs Could you confirm the fix is working?

**Comment by fsegouin** [comment]
Having the same issue on a 3440x1440 monitor.

**Comment by eimantasbucys** [comment]
Same issue, using 1.1.2 on 1920x1080
![edex-ui](https://user-images.githubusercontent.com/35905527/51077272-c9f56780-16ac-11e9-9379-c8a4a2cfa33f.png)

**Comment by ask-compu** [comment]
having this issue in Ubuntu 14.04 in windowed mode
[Screenshot](https://i.imgur.com/FPsrt8X.png)

**Comment by ask-compu** [comment]
Having this issue in Ubuntu 14.04 in windowed mode
[Screenshot](https://i.imgur.com/TRgUpgQ.png)
Seems to be fixed if I resize the window in a certain way
[Screenshot 2](https://i.imgur.com/oYRp4GE.png)

**Comment by GitSquared** [comment]
@ask-compu This is because only a few aspect ratios are supported by eDEX and the windowed mode isn't locked to any of those. I opened #413 to address this. Thanks for the screenshots.
