### ISSUE TITLE
Add dev tools keybinding/menu item

### ISSUE THREAD

**Issue by seanCodes** [GitSquared/edex-ui#306]
First off, can’t tell you how much joy this thing brings me, so thank you so much for making it. :hearts:

I’d really like to mess around with the layout and try theming, but it’s tough to do without building the app from source. Would it be possible to add a shortcut/menu item for toggling the web inspector? That way HTML/CSS could easily be inspected and messed with.

Seems like it could be done pretty easily with [sindresorhus/electron-debug](https://github.com/sindresorhus/electron-debug). If I get a chance I’ll try and create a PR, but this is my first time dabbling with editing an electron app.

**Comment by GitSquared** [comment]
No need to add another dependency, i think i can create a new keyboard shortcut to enable it in "production". Like Ctrl+Shift+I or something. I'll look into it!

**Comment by GitSquared** [comment]
@seanCodes Implemented, expect updated binary release for next weekend
