### ISSUE TITLE
Typing has some latency

### ISSUE THREAD

**Issue by akbiggs** [GitSquared/edex-ui#309]
Typing commands into the shell has a small perceivable amount of latency, making the shell feel slow.

My computer's specs:  
![image](https://user-images.githubusercontent.com/843918/49133700-d311ad00-f295-11e8-96de-087a450792b0.png)

**Comment by GitSquared** [comment]
You're typing with a physical keyboard, right?

**Comment by akbiggs** [comment]
Yes

**Comment by GitSquared** [comment]
This should be just another example of shitty optimization, like #238. I guess you'll have to wait for me to get better multi-threading in place (currently a lot of work happens in the renderer process, which is an absolute performance nightmare.)

ETA within the next month.

**Comment by akbiggs** [comment]
Oddly enough, it seems to improve if I replace "rows+1" with "rows" in that terminal.js bit, but this is completely anecdotal and might just be a placebo.

**Comment by AnantTiwari-Naman** [comment]
2 years later, and this issue seems to not have been resolved. In my case Asus E203MAH-FD004T (with an SSD) has a 5 - 10 second lag.

**Comment by GitSquared** [comment]
Your SSD won't help. Performance depends on GPU acceleration and raw CPU power. Your machine seems to be a high-efficiency low-power device which may not have sufficient raw speed.
