### ISSUE TITLE
Clipboard doesn't work on OSX

### ISSUE THREAD

**Issue by akbiggs** [GitSquared/edex-ui#310]
Version: 1.1.1
OS: Mac OS X High Sierra

Copying: "TypeError: Cannot read property 'copy' of undefined"
"Uncaught TypeError: Cannot read property 'copy' of undefined at file:///Applications/eDEX-UI.app/Contents/Resources/app.asar/classes/clipboardButtons.class.js 1:549"

Pasting: "TypeError: Cannot read property 'paste' of undefined"
"Uncaught TypeError: Cannot read property 'paste' of undefined at file:///Applications/eDEX-UI.app/Contents/Resources/app.asar/classes/clipboardButtons.class.js 1:683"

**Comment by akbiggs** [comment]
Just built from the latest source instead of using the release binary and this seems to be fixed.

**Comment by GitSquared** [comment]
Yup, fixed that one. Expect a new binary release for this weekend.
