### ISSUE TITLE
Allow skipping the intro animations.

### ISSUE THREAD

**Issue by akbiggs** [GitSquared/edex-ui#315]
The several seconds of loading animations and cool fades and stuff can be a bit annoying, especially when developing on the app and restarting it frequently. Having a setting to turn off the "intro" animations and loading screen and stuff would be awesome.

[Here's a hacked-together commit you can cherrypick to test out skipping the intro by setting "skipIntro"=true in your settings](https://github.com/akbiggs/edex-ui/commit/4e63706639cd13ef7b78e148fa0ba0b89fb4ca04).

**Comment by GitSquared** [comment]
Current implementation reduces the initialization time from an average of 20 seconds to about 5, when either the `"nointro": true` option is set in the settings.json file, or the `--nointro` command line flag is present.

I also updated the `npm start` command in the main package.json file to include the `--nointro` flag by default.

Should've thought about this sooner, i'm kind of mad at myself.
