### ISSUE TITLE
Filebrowser overflow

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#319]
Seems like when switching tabs mutiple times (?) the filebrowser reloads the files but does not clear them resulting in lots of duplicates. It even resultued in so many duplicates that it started lagging.

I'm unsure if this is reproducable.

**Comment by GitSquared** [comment]
Did this happen while running from v1.1.1 or master?
Technically speaking the renderer function inside the filesystem display class switch all the DOM at once so i don't really see how can this bug be possible.

**Comment by clragon** [comment]
I always run the latest compiled binary release

**Comment by GitSquared** [comment]
This should have been fixed on master then. Thanks for the report anyway.
