### ISSUE TITLE
Allowing terminal tab titles?

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#321]
Would it be possible to make the tab title the terminal title, therefore allowing the console app to change the tab title?

like for example if the title would be `Ubuntu`, the tab title would be `MAIN - Ubuntu` ?

**Comment by GitSquared** [comment]
Nope. I've tried to implement this but currently node-pty doesn't give an access to the TTY's running process (what is displayed as a title in most emulators).
