### ISSUE TITLE
Raise coolness factor - Wireguard VPN status

### ISSUE THREAD

**Issue by Strykar** [GitSquared/edex-ui#323]
Integrate Wireguard VPN status
https://lkml.org/lkml/2018/8/2/663
https://www.wireguard.com/quickstart/

@GitSquared  Suggestion: it might be a good option to toggle the keyboard to flip over and display a bunch of other metrics in its place. This could placate both desktop and tablet users.

Here's some VPN status ideas from Wireguard's own console output and Luci-OpenWRT:
```
root@Archer-C20v4:~# wg
interface: wire_guard
  public key: 34QxM4UnJoann7BWDdL+mTb2g6Org1akxujMZp3/LRw=
  private key: (hidden)
  listening port: 1234

peer: 1YEl0qWKWZWIEtVf7QpSBJ2Ax3D24wlQIzZn2rrzfyg=
  endpoint: 192.168.1.142:1234
  allowed ips: 0.0.0.0/0, ::/0
  latest handshake: 11 seconds ago
  transfer: 3.71 KiB received, 308.00 KiB sent
  persistent keepalive: every 25 seconds
```
![wireguard_](https://user-images.githubusercontent.com/2946372/49172758-e68d4880-f367-11e8-9dca-b885736990b1.png)

**Comment by Strykar** [comment]
@GitSquared What do you mean when you say Vendor, it's released under GPL2, and beats IPsec?

**Comment by GitSquared** [comment]
I mean it's a specific piece of external software on a specific operating system.

**Comment by Strykar** [comment]
Wireguard is literally the future VPN protocol, see Linus Torvald's comment in the LKML link I posted. In any case, this makes TLS/IPsec feel like 1998.
