### ISSUE TITLE
Logs into Root

### ISSUE THREAD

**Issue by LambertStrategy** [GitSquared/edex-ui#324]
It's a wonderful app, pretty incredible to be frank. However, it logs me into root bash, not at the level I need for normal terminal operations with Homebrew. Does anyone know how to set the proper path for my user level so I'm not at root?

Having said that, pretty happy that I can use this beautiful sci-fi tool to get into my root user without needing to restart and cycle into reboot.

**Comment by GitSquared** [comment]
I don't know what your setup is and i'm not sure about what "root bash" means, but [you can change the terminal process ran by eDEX by changing the `shell` option](https://github.com/GitSquared/edex-ui/wiki/settings.json).
