### ISSUE TITLE
Bin AUR Package

### ISSUE THREAD

**Issue by ShayBox** [GitSquared/edex-ui#325]
I'm proposing a binary AUR package, the devices this program was created to run on likely have slow processors, having to compile this takes a long time on some devices.

I have an HP Stream 7, I've tried to install this many times, both packages, it takes so long for each attempt I have to keep it on the charger or it will die, the device runs so slow because it has 900mb of ram, and then it will run into some problem or just not compile in time and error because it took so long.

**Comment by GitSquared** [comment]
Sorry but you're never going to successfully run eDEX on a machine with 900mb of RAM anyway.

You can download prebuilt binaries on this repo. I'll look into better AUR support in general, but right now i'm not the maintainer of those packages.
