### ISSUE TITLE
How about multi-screen support

### ISSUE THREAD

**Issue by kingfengji** [GitSquared/edex-ui#326]
Yo I believe most of us use more than one screen , is it possible to display this ***badass*** on multiple screens, or at least maybe we can config to choose which screen to display? 

I mean, I got 3 screens but currently this badass only appears on the primary screen (in the middle), don't know how to make it to show up on my left.

Thanks yo!

**Comment by whycantidraw** [comment]
You should be able to choose which monitor to spawn eDEX on with the monitor key in settings.json.

**Comment by kingfengji** [comment]
@whycantidraw Thanks! 
Right, set the "monitor" key in settings.json can pick which monitor to spawn. Thanks for the tip.
The only question remains is how can I start multiple monitors,,,

**Comment by GitSquared** [comment]
@kingfengji Multi-monitor support is planned, but don't expect it to come anytime soon, it needs a lot of work ^^

**Comment by kingfengji** [comment]
@GitSquared  you take your time man.

-------
"Please, Sir, I Want Some More." 
- Oliver Twist
