### ISSUE TITLE
Xresources Theme?

### ISSUE THREAD

**Issue by Solace7** [GitSquared/edex-ui#327]
I've copied the chalkboard theme and started replacing the colors to match my .Xresources file and the thought came to me to try and see if it would be possible to implement this without having to do the copy paste from file to file, or whenever I change my .Xresources. 

At first glance https://github.com/stayradiated/termcolors looks like maybe a way to generate the json, but as far as the format I haven't looked more into it (I will once I'm done with my class)

Perhaps a way like polybar, or other applications if a wrapper could be made for xrdb to accomplish this. I'll look into it and if I find away I'll make a pull request

**Comment by GitSquared** [comment]
I'm up for PR on this one, but this is not a feature I plan to implement myself.

Feel free to re-open if you really want to, but be aware that I'm going to rewrite a significant portion of eDEX in the next weeks.

**Comment by Solace7** [comment]
I've been using wpgtk to set my wallpaper and have a colorscheme generated by it. And I found a way to partially achieve what I was going for by creating a theme that gets changed everytime I change wallpapers. (The only thing I havent figured out how to change automatically is individual r,g,b values so they'd have to be changed manually), but if anyone wants to test it out, just install wpgtk. Put the template files in your template directory and link the file that isnt .base to a edex-ui theme file


[wpg_edex-ui_template.zip](https://github.com/GitSquared/edex-ui/files/3880875/wpg_edex-ui_template.zip)
