### ISSUE TITLE
Stuck on Main Screen

### ISSUE THREAD

**Issue by IgnacioGaldames** [GitSquared/edex-ui#328]
I'm on OSX  10.14.1. I can't move it to my second screen, it's stuck on my macron screen. I can't move it or attach it to my second monitor.

**Comment by iammrbt** [comment]
same issue on windows for me

**Comment by GitSquared** [comment]
You tried to use the `monitor` setting?

**Comment by iammrbt** [comment]
> You tried to use the `monitor` setting?

Sorry I'm slightly noobish. How do you do that?

**Comment by GitSquared** [comment]
See the wiki on this repo. There's a parameter you can add to the settings.json file called "monitor" that will allow you to choose on which monitor eDEX will spawn.

**Comment by jsuelwald** [comment]
Yes, i tried that noiw, i have three Displays on Windows 10.
Using ctrl-shift-s i changed the "monitor"-setting to 1, edex-ui still starts on the main display.

**Comment by KaKi87** [comment]
> Using ctrl-shift-s i changed the "monitor"-setting to 1, edex-ui still starts on the main display

Same. I actually have a laptop with 2 external screens : value `1` behaves just like value `0` (laptop screen) while only value `2` works for one of the two external screens.

**Comment by GitSquared** [comment]
I think the monitor parameter might be 1-indexed, meaning it starts at 1, not 0.

**Comment by jalovisko** [comment]
> I think the monitor parameter might be 1-indexed, meaning it starts at 1, not 0.

That's right, but openning settings.json right in eDEX-UI reveals that it is 0-indexed there. Can be set to any number in any other editor though.
