### ISSUE TITLE
IP showing

### ISSUE THREAD

**Issue by bp-brainiak** [GitSquared/edex-ui#329]
I hace more than one NIC on windows and only shows me one (one of those are virtual) it will be good idea to show a combo to select the nic

**Comment by GitSquared** [comment]
eDEX will select the first network interface that isn't identified by a local/loopback IP address. Choosing another one is not a feature i'm planning to implement, sorry - it's already messy enough as it is.

**Comment by bp-brainiak** [comment]
Got it, thanks anyway, great software :)
