### ISSUE TITLE
keyboard visual error

### ISSUE THREAD

**Issue by jemd15** [GitSquared/edex-ui#330]
When you press the ALTGR button in your physical keyboard, you can see on screen keyboard highlight also the CTRL button

**Comment by GitSquared** [comment]
Cannot reproduce, what's your keyboard layout?

**Comment by jemd15** [comment]
I have a spanish keyboard layout.

The issue looks like this:

(https://user-images.githubusercontent.com/19212855/49233015-d01cd680-f3d3-11e8-8e4b-16c5e6fde4b4.png)

**Comment by clragon** [comment]
This also happens over here, with a german (swiss) keyboard layout.

**Comment by DrDeath** [comment]
confirmed, also on German keyboard layout (de-DE)

**Comment by Raczaron** [comment]
Same thing happen in fr-FR keyboard layout.

This can be caused by the fact than ALTGR is the same thing for the computer than CTRL + ALT.
I use CTRL + ALT regulary on old systems that does not have ALTGR key.

**Comment by jemd15** [comment]
I thought the same, but the CTRL and ALTGR should have different key codes or in the background is the same as press CTRL + ALT?

**Comment by GitSquared** [comment]
(Concerned code is at [line 1071 in the keyboard script](https://github.com/GitSquared/edex-ui/blob/8eb55d008c5123c08bae5845b61577b6dd325bcf/src/classes/keyboard.class.js#L1071))

**Comment by GitSquared** [comment]
OK, I could reproduce the issue. It seems that on Windows, two events are fired when the `altgr` key is pressed - one for the actual `altgraph` keycode, and one extra that's coded as a control key.

So this is platform-specific. I'll see if I can add a work-around, or maybe get a more sane event source.

**Comment by GitSquared** [comment]
Damnit. So I guess it's just working on Linux then.

**Comment by jemd15** [comment]
I can't reproduce the error on Mac 😞

**Comment by clragon** [comment]
This issue is still happening to me to this day.

Pressing the ALTGR key will highlight the CTRL (which won't go back to normal until I press it manually)
Happens on a german (swiss) keyboard layout.

**Comment by jemd15** [comment]
Yes, still happen on Spanish layout.

**Comment by GitSquared** [comment]
@clragon Issue is fixed for me. What OS are you using?

**Comment by clragon** [comment]
Windows 10, 1809 Build 17763.379
as always.

**Comment by GitSquared** [comment]
OK, I'll check it out.

**Comment by GitSquared** [comment]
Reproduced :heavy_check_mark:

**Comment by GitSquared** [comment]
This should do it.
