### ISSUE TITLE
Support external modules

### ISSUE THREAD

**Issue by itaisteinherz** [GitSquared/edex-ui#334]
First of all, I wanted to thank @GitSquared for making eDEX-UI 👍🏻
The app is really cool, and I have a suggestion that I think could make it even better.

I see the UI as a collection of modules / plugins that are currently hard-coded into the project, and I think there should be a way for users to develop and use their own modules. For example, I could make a Home Assistant module to control my smart appliances, or a Git module to have a Git GUI built into the UI. This would make the app extremely extensible and useful for many different use-cases.

Let me know what you think about the idea.

**Comment by GitSquared** [comment]
This is a long-term planned feature, there's a reason the app was made this way to begin with ;)

I need to rewrite the whole module system though, to include multithreading among other things. So this'll have to wait for a bit.

**Comment by GitSquared** [comment]
I'm referencing this everywhere, so I'm going to pin the issue.

As a quick update since there haven't been any messages in this thread since November, I'm currently planning to finish the remote monitoring feature first to have a finished API to expose to eventual custom modules.

No ETA on any of this yet, but definitely still planned.

**Comment by itaisteinherz** [comment]
@GitSquared Let me know when the API is ready and I'll be happy to contribute and help get this landed 🙃

**Comment by michaelsharpe** [comment]
Definitely willing to help with any modularization that is needed, or for that matter stripping out the interface to run on the web against a remote server.  Modularizing and componentizing the interface would be a huge boon; even having a terminal library in react that could be utilized and composed in various ways would be awesome.

**Comment by chabad360** [comment]
If I may, I'd suggest that an easy way to make modules would be to provide a [bitbar](https://getbitbar.com/)/[argos](https://github.com/p-e-w/argos) style of plugins, where it's just a shell script that can have it's output interpreted to mean different things, like for a graph (output):

```
type: graph
title: CPU Temp

68
67
66
67
67
```

It could provide an action/command to insert (or change a view), so for a table:

```
type: table
title: DB Tables

Name|Rows|Action
users|34|SELECT * FROM users;
items|123|SELECT * FROM items;
```

This would allow for making relatively capable modules rather quickly, and it would likely greatly increase the number of modules the would exist.

**Comment by wsturgiss** [comment]
I'd like to see alternate keyboard.css loading options.  Myself, and perhaps others who use strange keyboard layouts might appreciate keyboard layouts that match their physical keyboards.  I use an ortholinear keyboard and I'm currently working on making a matching keyboard.css and keyboard json for my particular keyboard, and while there is functionality for switching json files, it would be nice to have easy css switching to go with it.
