### ISSUE TITLE
Random beeping when using eDEX-UI

### ISSUE THREAD

**Issue by jrmcintyre** [GitSquared/edex-ui#335]
Is the beeping on purpose? and if so, can I turn it off?

**Comment by jrmcintyre** [comment]
Windows 10 Powershell

**Comment by clragon** [comment]
thats not random that's literally just powershell when you for example press backspace but there are no chars left to delete. I hate it lol @jrmcintyre

**Comment by GitSquared** [comment]
Welp. Either use cmd.exe or deal with it i guess.

**Comment by clragon** [comment]
cmd has the beep too, the only solution is muting the terminal app in the sound mixer

**Comment by GitSquared** [comment]
everyday there's someone to remind me why i don't use Windows

**Comment by jrmcintyre** [comment]
@GitSquared what OS do you use?

**Comment by GitSquared** [comment]
@jrmcintyre Debian GNU/Linux, [or as I've recently taken to calling it...](https://www.reddit.com/r/copypasta/comments/63oudw/gnu_linux/)

**Comment by clragon** [comment]
this guy is amazing. first he uses the best joke in the west, the in the west joke and then he comes in here with the good ol' Linux copypasta
