### ISSUE TITLE
Add a custom env setting

### ISSUE THREAD

**Issue by tandriamil** [GitSquared/edex-ui#336]
Hi,

I don't know how environment variables are managed, but they are not consistent between my standard terminal (MacOS) and the terminal opened in edex-UI.

`$PATH` value for **standard terminal** :
``
/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
``

`$PATH` value for **Edex-UI terminal** :
``
/usr/bin:/bin:/usr/sbin:/sbin
``

MacOS version : Mojave - 10.14.1
eDex-UI version : 1.1.1

Thank you.

**Comment by GitSquared** [comment]
Uh, those 2 $PATH variables you provided are exactly the same.

**Comment by tandriamil** [comment]
Sorry, did not check after copy/paste. I edited the original post, the `$PATH` environment variable into Edex-UI terminal is valued to `/usr/bin:/bin:/usr/sbin:/sbin`.

When looking at the way of [path handling on MacOS](https://www.cyberciti.biz/faq/appleosx-bash-unix-change-set-path-environment-variable), I think that you could just add the content of the following files to `$PATH` :
- `/etc/paths` : text file containing one path per line.
- `/etc/paths.d/*` : multiple files, each file containing additional paths.

**Comment by GitSquared** [comment]
Currently the shell process' environment is set from the `process.env` variable, which means it just gets the same env as the electron application. [See this relevant code.](https://github.com/GitSquared/edex-ui/blob/master/src/classes/terminal.class.js#L289)

I don't plan to add complex, system-specific modifications to the default env - i know env handling on macOS is kind of messy compared to other systems, with the terminal emulator(s) doing a lot more work to provide usable variables - but I might consider adding a custom env option to the settings.

This will need some time, though - and I'm currently taking a bit of a break to work on some paid stuff instead, eDEX has an operating cost.

As always thanks for the report.

**Comment by tandriamil** [comment]
Okay, anyway it is just for convenience.

Thank you for this project, and the quick response.
Have a good day ! 😄
