### ISSUE TITLE
Keyboard layouts with klc files?

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#340]
Would it be possible for the app to load klc files (or xklc files on linux) to make a keyboard layout?

Here is an example file 
[swiss_no_dead_keys.zip](https://github.com/GitSquared/edex-ui/files/2636100/swiss_no_dead_keys.zip)

And here a screenshot from a program (the microsoft keyboard layout editor) that loads those files
![screenshot_1](https://user-images.githubusercontent.com/11785085/49331024-2ede7d80-f597-11e8-805e-edd6eb0cb793.png)
![screenshot_2](https://user-images.githubusercontent.com/11785085/49331039-60574900-f597-11e8-9216-9ec30207c5b6.png)

**Comment by GitSquared** [comment]
Nope, sorry. I need the specific information we have in eDEX's layout file.

**Comment by clragon** [comment]
Did you look inside the klc file? I don't see anything missing

**Comment by GitSquared** [comment]
I did yeah, and it's an absolute mess that i'll need to write a custom parser for, and it doesn't have things like custom keyboard modifiers like we have on edex.

**Comment by clragon** [comment]
that's a fair point, but what about conversion? 
klc converted to a eDEX-UI keyboard file.

yeah that would need a custom parser

**Comment by GitSquared** [comment]
If you think it's worth it, feel free to make a converter :smile:
But adding it directly into edex would just be bloating it honestly.
