### ISSUE TITLE
Add support for 5:4 ratio

### ISSUE THREAD

**Issue by jrmain** [GitSquared/edex-ui#341]
I'm unable to find any method for adjusting the sizes of fonts. I use a 1280x1024 monitor on my Windows machine, and a lot of the text is wrapping around and getting variously overwritten by other text. The text would still be perfectly readable if it was smaller. 
![image](https://user-images.githubusercontent.com/1110694/49379030-0a7fbf80-f6c3-11e8-8e71-8a482b995e62.png)

**Comment by GitSquared** [comment]
This is because everything in eDEX is defined relative to device height and width - this allows the UI to be extremely scalable but at the cost of supporting only a few screen ratios (currently 16:9, 21:9 and 16:10).

I'll see if I can add support for yours - 5:4 ratio if I'm not mistaken.

**Comment by jrmain** [comment]
Understood. And it's definitely 5:4.
