### ISSUE TITLE
Command +C not working in mac : idea for V.2

### ISSUE THREAD

**Issue by didavid0609** [GitSquared/edex-ui#342]
The Command + C shortcut is not working within the shell, when the command c action was done, the letter c on the virtual keyboard is then always highlighted

**Comment by GitSquared** [comment]
Dumb question, but does it work in another terminal emulator and if so which one?

**Comment by didavid0609** [comment]
It works in the system terminal, but I think that it a nice idea to include this feature because it comes in handy when copying ip or results from some commands

**Comment by GitSquared** [comment]
Oohh you mean the "copy" keyboard shortcut. Sure thing, will check it out tomorrow :wink:

**Comment by didavid0609** [comment]
Thanks for answering

**Comment by GitSquared** [comment]
(I'll keep it open until i implement it, for organisation purposes)
