### ISSUE TITLE
Struggling to run alternate shells in windows

### ISSUE THREAD

**Issue by TheDemitrius** [GitSquared/edex-ui#344]
I've been trying to find alternative CLIs that'll run within EDEX-UI, but I've hit a fair few roadbumps. I can get both Powershell.exe and cmd.exe to run, but running other clis or emulators, even those recommended in the help file seem to lead to what I assume is a "file not found" error, except the error message is scrunched up into a corner and illegible. 

I've tried CMDER and ConEMU, browsh (which I understand has issues on Windows as it is), all via the SHELL entry in the settings, but can't Edex-ui to boot with any of them! Am I doing something wrong?

**Comment by GitSquared** [comment]
You're not doing anything wrong afaik, as long as the process can run in a TTY (on windows you could test that by launching em from the command line) it *should* work...

Shell handling is done by node-pty, maybe check with them.
