### ISSUE TITLE
Microfreeze during usage

### ISSUE THREAD

**Issue by PierfrancescoArdino** [GitSquared/edex-ui#345]
I experience some random micro freeze when using the application. The system (audio, mouse and keyboard) stop working for some millisecond. I'm using Arch Linux.

Is there a way to debug the application? It would be useful to inspect the log to check if the application raise some errors.

**Comment by GitSquared** [comment]
You can use Ctrl+Maj+I to open the debugger. Tell me if you see something there

**Comment by PierfrancescoArdino** [comment]
Mmm, no. I do not have any errors. Moreover, if a switch to another tab while the application is still open the problem persists. Maybe there are some incompatibilities between my desktop environment (gnome) and this application

**Comment by GitSquared** [comment]
Nah, I use Gnome too and don't have any issue. Would you mind sharing your system specs? Are you running any other app at the same time?

**Comment by PierfrancescoArdino** [comment]
Just edex, Chrome and Telegram. But I noticed the problem also with just edex + Spotify. 

This are my specs:

 OS: Arch Linux x86_64 
Kernel: 4.19.7-arch1-1-ARCH
CPU: Intel i7-6700HQ (8) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 960M 
GPU: Intel HD Graphics 530 
RAM: 16GB

**Comment by GitSquared** [comment]
Weird. System specs looks good. You're sure this happens only with edex?

**Comment by PierfrancescoArdino** [comment]
So, It happened few months ago with the system-monitor extension. There where some incompatibilities between gnome and the extension but then they solved. Dunno how, but they solved.

**Comment by GitSquared** [comment]
Should be fixed with 735b33e
