### ISSUE TITLE
how can I use power-line fonts?

### ISSUE THREAD

**Issue by harry890829** [GitSquared/edex-ui#347]
when I choose zsh, the fonts is messy code。
<img width="412" alt="image" src="https://user-images.githubusercontent.com/8288067/49707339-d9286600-fc65-11e8-9d4e-74ad2a5a62ef.png">

**Comment by YQqiang** [comment]
The issue solves my problem, and you can have a try  
[Unicode Glyphs and powerline symbols are not rendered correctly #220
](https://github.com/GitSquared/edex-ui/issues/220)

<img width="459" alt="2018-12-11 9 30 42" src="https://user-images.githubusercontent.com/19221508/49772355-f9205e00-fd27-11e8-96e9-366c36e7cd75.png">

**Comment by GitSquared** [comment]
As @YQqiang said.

**Comment by harry890829** [comment]
it worked. thanks
