### ISSUE TITLE
Cannot run on deepin 15.8

### ISSUE THREAD

**Issue by muzea** [GitSquared/edex-ui#348]
### Environment
deepin 15.8

When I try to run
```shell
./edex.AppImage 
/tmp/.mount_edex.AfDyt6B/edex-ui: symbol lookup error: /tmp/.mount_edex.AfDyt6B/edex-ui: undefined symbol: udata_setCommonData_59
```

I found a similar problem
https://vdr.jp/d/20181203.html

**Comment by GitSquared** [comment]
This is an issue with your system, sorry. Report it to AppImage if you can't figure it out.
