### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by doublealread** [GitSquared/edex-ui#349]
![image](https://user-images.githubusercontent.com/32104107/49785365-4cf86a80-fd5b-11e8-8bfb-f731ad2cda06.png)
in directory has electron 
![image](https://user-images.githubusercontent.com/32104107/49785435-84ffad80-fd5b-11e8-8209-c2735c6e5e7f.png)

**Comment by GitSquared** [comment]
Read the error message. You need `libgtk-3`.
