### ISSUE TITLE
Typing sound

### ISSUE THREAD

**Issue by FabianTe** [GitSquared/edex-ui#360]
Really like this project, well done!
I'd love to have custom key press sounds. Beeps and Bluubs 😉 😃

**Comment by GitSquared** [comment]
Holy shit. Working on adding multiple FX sounds right now.

You're going to love it.

**Comment by GitSquared** [comment]
Will continue to improve on this and ship audio in v2.0.0 (coming soon:tm:).

In the meantime you can test this by getting the code from github & running from source. Note that you need to set `"audio": true` in the config file to activate sound FX.
