### ISSUE TITLE
The application catches CTRL + TAB or CTRL + NUMBER even when minimized

### ISSUE THREAD

**Issue by phiter** [GitSquared/edex-ui#361]
I use CTRL + Tab and CTRL + 1,2,3 to switch tabs on google chrome. 

I noticed that these keys are used as well on edex to switch terminal tabs.

The thing is, whenever I have edex running and switch to chrome, I cannot use these keys. They are being globally listened by edex or something.

Any way to prevent this?

I'm on Ubuntu 18.10 btw

**Comment by GitSquared** [comment]
Oops. Fixing this ASAP.
