### ISSUE TITLE
Homebrew incompatible

### ISSUE THREAD

**Issue by didavid0609** [GitSquared/edex-ui#366]
First of all, I want to thank GirSquared for making this application and improving the app.
In MacOS, homebrew is not installed in the bash shell within the eDEX-UI. Do I need to reinstall Homebrew in the UI or is there a way to connect the system terminal to the eDEX-UI.
Note: I have installed homebrew already.
![screenshot 2018-12-27_07-51-44-323](https://user-images.githubusercontent.com/45569459/50469355-536a2180-09ac-11e9-9d1d-0136f93ab622.jpg)

**Comment by GitSquared** [comment]
This is essentially the same issue as #336 - on macOS, GUI apps like eDEX don't inherit the environment variables defined in the user's dotfiles, which is in your case bash can't find homebrew - it doesn't have the right `$PATH`.

I've added a workaround to this in #336 by adding the `env` configuration setting to `settings.json`, but after a bit of digging around I found [sindresorhus/shell-env](https://github.com/sindresorhus/shell-env) which could fix this for real.

I'll implement that ASAP and close this issue once I'm done. Thanks for the report!
