### ISSUE TITLE
customEnv is not defined

### ISSUE THREAD

**Issue by maggie-chen** [GitSquared/edex-ui#368]
`

> edex-ui@1.1.2 start /Users/maggie/maggie/tools/edex-ui
> electron src --nointro

▶  start     Starting eDEX-UI v1.1.2
ℹ  info      With Node 10.11.0 and Electron 4.0.0
ℹ  info      Renderer is Chrome 69.0.3497.106
▶  Startup   Initialized timer...
ℹ  info      Created config dir at /Users/maggie/Library/Application Support/eDEX-UI
☐  pending   Loading settings file...
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✖  fatal     ReferenceError: customEnv is not defined 
    at App.app.on (/Users/maggie/maggie/tools/edex-ui/src/_boot.js:166:14)
    at App.emit (events.js:187:15)`

**Comment by GitSquared** [comment]
Sh*t, thougth it would fallback with `||` since it is undefined but i guess not, will fix asap
