### ISSUE TITLE
[UI] [keyboard?] Provide copy and paste functions

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#37]
Currently you can't copy/paste something from/to the TTY.

**Comment by GitSquared** [comment]
Update:

"Copy" button: Use `window.term.term.getSelection()`
"Paste" button: Use `window.term.write(<data>)`

Currently i'm kind of blocked on this because of a weird bug when selecting text after more than one page of TTY text has been printed (selection happens from the beginning of the screen instead of where i'm actually pointing at). Needs further research.

**Comment by GitSquared** [comment]
OK, bug fixed in 2d2ac17 - expect this issue to be closed soon (FINALLY)

**Comment by GitSquared** [comment]
OK, so, seems we're not there yet. DOM access to clipboard is experimental and not implemented on the current Chromium version bundled with Electron, meaning i can't really build my own copy/pasting solution or whatever.

State of things: You can copy and paste using the CTRL+C and CTRL+V keys. When the shell is not in a ncurses-style application (forget vim and nano). And it probably doesn't work for touchscreens.

Marking as "ahead of it's time".

**Comment by GitSquared** [comment]
Damned, forgot i had a node process available. Shame on me.

**Comment by annogram** [comment]
This still doesn't work for me on Ubuntu

**Comment by GitSquared** [comment]
@annogram Use Shift+Ctrl+C/V keyboard shortcuts.

**Comment by unix4you2** [comment]
Hi there.
This is not working for me with Ctrl+C Ctrl+V or the tradditional shortcuts for terminals like Shit+Ctrl+C or Shit+Ctrl+V
Regards

**Comment by GitSquared** [comment]
@unix4you2 What version of eDEX are you using? This feature has been implemented for a long time now and I haven't heard of any issues with it.
The shortcuts are indeed shift+ctrl+c/v, and you can use them either with your physical keyboard or the on-screen one.

**Comment by unix4you2** [comment]
Hi @GitSquared 
I'm using the last version (eDEX-UI v2.1.0) in AppImage under Elementary (an ubuntu derivated).
But i have the same problem in my office desktop (Xubuntu)

If I try to use that shortcuts under an standar terminal that works fine, but not under edex.
And when I type it under edex I can see the keys pressed in the virtual keyboard.

Thanks for your time

**Comment by GitSquared** [comment]
@unix4you2 Does copying something from another window and pasting it into edex with the shortcut works?

**Comment by unix4you2** [comment]
Nop.
I tried to copy for example a simple command to install something from a web browser  "yum -y install httpd"  and try to copy that to edex using keyboard or mouse and doesnt work.

The only thing I can see different in the virtual keyboard (VK) is that:

- If you press only shift the VK shows it on
- If you press only ctrl the VK shows it on
- If you press  crtl first and then shift the VK shows only shift as on
- If you press  shift first and then ctrl the VK shows both on
- If you press shift + ctrl + V or C  in that order the VK only show shift and ctrl on, the C or V doesnt go on
- If you press ctrl or shift (only one of them) with the keys C or V  works fine and shows you ^C or ^V

Regards

**Comment by GitSquared** [comment]
The C or V not going on is because it's triggering the internal copy/paste functions instead of the regular keys.

Would you be willing to try and run edex from source to see if the issue has been resolved since v2.1? If you don't have `node` on your system, I can give you a prebuilt AppImage of the latest development version, but I'm afraid you will have to wait a bit.

**Comment by unix4you2** [comment]
Yeah, I supossed that.
The event of that keypressed is captured.  But the method that should copy or paste the clipboard content (writting to the terminal) is not working.
I dont have node here.  If you want to share another AppImage I can wait and test it.
Take your time and tell me if I can help in another way.
Regards.

**Comment by GitSquared** [comment]
I will get back to you with a test build, and do some testing myself in the meantime.
Thanks for reaching out.

**Comment by unix4you2** [comment]
Hi @GitSquared  an important info:

Copy and paste using Ctrl+Shit+C from eDEX to another application works fine.
**The problem is only when you copy from another app and try to paste into eDEX using Ctrl+Shit+V.**  

Regards.

**Comment by unix4you2** [comment]
Please excuse me again... too many messages I sent but I found a temporally sollution.

I already tested and in the other combination or shortcut that you can use in another terminals and editor works fine to paste:   **Shift + Insert**    So people that have the problem with  Ctrl+Shift+V  can use that shortcut instead.

Regards.

**Comment by GitSquared** [comment]
@unix4you2 Interesting. Internally eDEX uses [clipboardy](https://www.npmjs.com/package/clipboardy) to retrieve the system's clipboard content. Maybe that dependency is failing on Elementary..?

I use Debian myself and haven't had any issue with it, but maybe there is an additional package you need to install to make it work - i'm not sure. I'll look into it.

**Comment by GitSquared** [comment]
@unix4you2 [Here's a test build](https://send.firefox.com/download/b0d87d1cb8c8c5fd/#v1AH5f0tnvdfcsUQ4G64-A) from the latest dev branch.

**Comment by unix4you2** [comment]
Hi @GitSquared two things:

1)  I already tested the version that you shared to me.  The problem continues but Shift + Insert works again so I will use that shortcut instead.

2) I searched for the package clipboardy and doesnt exists as a packeage under ubuntu.  Should I install something more like nodejs or something to get that package in my system?   Maybe the problem is that the package requieres that the user have nodejs or something similar installed before to get the utility that you use to get clipboard content.   Because if you check the way to install it is using node package manager (npm) `npm install clipboardy`  and I dont have (and dont like) to install npm....   maybe include the library in your AppImage.

Regards.

**Comment by GitSquared** [comment]
@unix4you2 Sorry, I wasn't clear enough; `clipboardy` is a Node dependency that is included inside eDEX, not something that you should install yourself.

I'm going to replace that component with [another API](https://electronjs.org/docs/api/clipboard), hopefully that will work better on your system. Test build incoming.

**Comment by GitSquared** [comment]
@unix4you2 [This one should fix it.](https://send.firefox.com/download/8542765f50fd2624/#gbXASh9el4HI_-4jt6wUJQ)

**Comment by unix4you2** [comment]
Hi @GitSquared 

I already tested the new binary you shared to me and it works like a charm.  Using the new API is working everything.

Anyway I will be using the Shift+Insert shortcut in the middle because I supose this change will be available in the next stable release, so I will wait for that.

Thanks for your time.   Best regards.

**Comment by GitSquared** [comment]
@unix4you2 Glad we got this fixed. Thank you for your help, it will indeed ship in the next stable release.

**Comment by GitSquared** [comment]
@unix4you2 Glad we got this fixed. Thank you for your help, it will indeed ship in the next stable release.

**Comment by RamDerp** [comment]
hey man can you make it so you can use the short key to quit a command

**Comment by GitSquared** [comment]
@RamDerp ...what short key?
