### ISSUE TITLE
Colemak layout seems bugged with latest version

### ISSUE THREAD

**Issue by NawtNawt** [GitSquared/edex-ui#375]
Hey GitSquared, thanks for accepting my first ever pull request!

The 'prettified' version of COLEMAK.json currently looks like [this](https://i.gyazo.com/5ef67197b9c0f7f99e12a4c14dacbd92.png) when it looked fine on my version

Just a heads-up, cheers!

**Comment by GitSquared** [comment]
Oops. The minifier i use broke the tab character and replaced it with a blank space, so the key was misidentified by the keyboard parser as a spacebar. Fixed!
