### ISSUE TITLE
Add setting to override external network interface

### ISSUE THREAD

**Issue by dsokoloski** [GitSquared/edex-ui#376]
https://github.com/GitSquared/edex-ui/blob/70a0fc6d5a1a315b5412ddeb9f5bcf7830682ba6/src/classes/netstat.class.js#L46

It would be super-handy to have an option in settings.json to override the automatically detected external interface.  On my system, awdl0 is chosen (which has no address is isn't used), whereas my actual external interface is bond0 (bonded ethernet).

Very cool project! :)

**Comment by v2maxx** [comment]
Got the same(ish) problem in the Windows release : It doesn't bind to the correct NIC and therefore no Network Traffic shows up on the counter. Would be a useful addition to have a control panel (of sorts) to be able to change some basic settings. 
Other than that, it's a very cool project! :+1:   :)

**Comment by GitSquared** [comment]
Hey @dsokoloski @v2maxx, sorry for the delay, i'm going to take care of this now :P

I'm OK with adding an override option, but i'd also like to take the opportunity to improve the automatic choosing algorithm so that it'll work for more people without a hacky tweak.

I would really appreciate if you guys could run a test binary I made and show me what it outputs in a CLI (powershell or even CMD should do find if you're on windows). It should list all detected network interfaces and allow me to see how i could parse this data better for setups like yours.

[Link to download said binary](https://mega.nz/#F!k98XGISC!odwP9Jo0P4REpv7-Qp_dtA) | [Source code if you want to run it directly with Node](https://gist.github.com/GitSquared/ac34806914795252a811243cfc4daab1)

**Comment by dsokoloski** [comment]
@GitSquared Thanks for working on this!

Here's the output from my system (my external interface -- well, LAN interface to be precise, is **bond0**, and edex chooses the first "external", **awdl0**):
```[
  {
    "iface": "lo0",
    "ip4": "127.0.0.1",
    "ip6": "::1",
    "mac": "",
    "internal": true
  },
  {
    "iface": "awdl0",
    "ip4": "",
    "ip6": "fe80::20f2::dead:beef",
    "mac": "22:f2:4e:e4:fd:de",
    "internal": false
  },
  {
    "iface": "bond0",
    "ip4": "192.168.0.1",
    "ip6": "fe80::cf3::dead:beef",
    "mac": "00:11:22:33:44:55",
    "internal": false
  },
  {
    "iface": "utun0",
    "ip4": "",
    "ip6": "fe80::ef81::dead:beef",
    "mac": "",
    "internal": false
  }
]

**Comment by GitSquared** [comment]
@dsokoloski All right, i'll add a check for both "internal = false" and a valid IPv4 field, that should do it in most cases. Also a custom interface option.

Thanks for your help!

**Comment by GitSquared** [comment]
There's a new `iface` parameter in [settings.json][https://github.com/GitSquared/edex-ui/wiki/settings.json).

Also, the automatic networkInterface chooser has been modified to select the first interface with:
 - `internal` set to false
 - a non-empty `ip4` field
 - a non-empty `mac` field (mac address)

This should correctly select the right interface for most users.

Thanks again for your help!

**Comment by dsokoloski** [comment]
Wow!  Fantastic, thanks a lot -- much appreciated!  Works perfectly!

**Comment by GitSquared** [comment]
Oh, and @v2maxx:

> Would be a useful addition to have a control panel (of sorts) to be able to change some basic settings.

Working on it.

![image](https://user-images.githubusercontent.com/24496417/51086292-5c494a00-1745-11e9-8c8e-4d63c920f8cc.png)

**Comment by wolfen351** [comment]
What format does the override field expect the network name in (on windows?)?

I've tried typing the physical adaptor name and the name assigned in "network connections"..

**Comment by GitSquared** [comment]
@wolfen351 The override field expects a string with the interface name (like "wlan0")

**Comment by GitSquared** [comment]
@wolfen351 [you can use this to find the interface names](https://github.com/GitSquared/edex-ui/issues/376#issuecomment-453739555)

**Comment by GitSquared** [comment]
@dsokoloski I believed I fixed the problem that caused a weird IPv4 address to be shown on your system. I'm not sure that it will be sufficient, though - could you run the latest master and tell me if everything's all right?
