### ISSUE TITLE
eEDEX-UI failed to launch: EADDRINUSE 

### ISSUE THREAD

**Issue by Saturate** [GitSquared/edex-ui#377]
I'm running a application on port 3000, so when I try to launch edex-ui I get the following error:

```
eEDEX-UI failed to launch
listen EADDRINUSE :::3000
```

Could it maybe pick another port if port 3000 is already used?

**Comment by GitSquared** [comment]
Sure. There's a "port" option you can set in the settings file. [More info on the wiki.](https://github.com/GitSquared/edex-ui/wiki/settings.json)
