### ISSUE TITLE
Uncaught syntax error : invalid or unexpected token at file "path"

### ISSUE THREAD

**Issue by 3038922** [GitSquared/edex-ui#378]
Uncaught syntax error : invalid or unexpected token at file "path"
win10 1809
use Administrator mode open.
version: 1.1.2: for Windows

![image](https://user-images.githubusercontent.com/33926386/50910353-9a561d80-1468-11e9-955b-1cdc9262e2f3.png)
![image](https://user-images.githubusercontent.com/33926386/50910533-fd47b480-1468-11e9-8b6b-6e74eced64ae.png)

**Comment by GitSquared** [comment]
Dup' of #308 - fix coming in 2.0.0 in a few days™
