### ISSUE TITLE
current directory error

### ISSUE THREAD

**Issue by Zibri** [GitSquared/edex-ui#379]
Tested in ubuntu 17.10 on latest kernel,
the current directory view works while it's in it's starting dir and in .config
Stop working when I go to my home directory.
After starting the AppImage I do:
$ cd ..
and everything works, then
$ cd ..
and it says it can't access current directory (but obviously the directory works in the terminal shell)

**Comment by GitSquared** [comment]
Fixed in 3810f5c i believe.
