### ISSUE TITLE
bash_profil not loaded

### ISSUE THREAD

**Issue by gbarre** [GitSquared/edex-ui#384]
Hi,

On macOs, the _bash_profil_ is not loaded. So I lose all my aliases or customizations...
Is it possible to include it please ?

Thanks,
Guillaume

**Comment by core-process** [comment]
Try to change the shell to `bash -l` in `$HOME/Library/Application Support/eDEX-UI/settings.json`.

**Comment by gbarre** [comment]
It works perfectly !
Thanks for this application, I love it.

**Comment by GitSquared** [comment]
( @core-process thank you for providing a fix.)
