### ISSUE TITLE
Welcome Slogan Showing Wrong User

### ISSUE THREAD

**Issue by YuetAu** [GitSquared/edex-ui#386]
Try on MacOS 10.14.2
My Mac have two users and it seems show the user by alphabetical order.

**Comment by GitSquared** [comment]
Could you please post the output of running `who; echo "---"; w -ih` in a terminal?

**Comment by YuetAu** [comment]
yuetau   console  Jan 13 12:35
yuetau   ttys000  Jan 13 12:41
---
yuetau   s000     -                12:41       - w -ih
yuetau   console  -                12:35       5 -

**Comment by YuetAu** [comment]
But it seems it fixed after restarting.
Still huge thanks.

**Comment by GitSquared** [comment]
@YuetAu Maybe you were logged in with both users at the same time - is that possible on macOS?

Either way, glad it solved itself... feel free to reopen if you get this again.
