### ISSUE TITLE
There isn't a Matrix movie theme!

### ISSUE THREAD

**Issue by P3GLEG** [GitSquared/edex-ui#389]
So I built an almost there one...
`{
    "colors": {
        "r": 0,
        "g": 143,
        "b": 17,
        "black": "#0D0208",
        "light_black": "#090B0A",
        "grey": "#262827"
    },
    "cssvars": {
        "font_main": "Courier",
        "font_main_light": "Courier"
    },
    "terminal": {
        "fontFamily": "Courier New",
        "cursorStyle": "underline",
        "foreground": "#00ff41",
        "background": "#0D0208",
        "cursor": "#00ff41",
        "cursorAccent": "#00ff41",
        "selection": "#008f11"
    },
    "globe": {
        "base": "#008f11",
        "marker": "#008f11",
        "pin": "#008f11",
        "satellite": "#008f11"
    }
}
`

**Comment by GitSquared** [comment]
Thanks for this! I didn't have the time to look into it yet, sorry for the delay.

Would you want to open a Pull Request to add your matrix theme? PRs makes sure you are properly credited for your work, and it'll add you to the list of contributors - otherwise i'll just add it myself.

**Comment by GitSquared** [comment]
No response from author so I'm pushing it myself.
