### ISSUE TITLE
Running on vertical monitor doesn't render correctly

### ISSUE THREAD

**Issue by polds** [GitSquared/edex-ui#390]
I run a vertical monitor and pointed the config at it. The rendering had some issues.

Happy to provide any info.

![edex-ui](https://user-images.githubusercontent.com/2372558/51126018-e42b6480-17d6-11e9-9300-d4d85961fa8b.png)

**Comment by GitSquared** [comment]
Yeah, vertical monitors aren't supported at all at the moment... I'm not really sure how i would display the UI on them, too. Might look into it a bit but this may end up wontfix.

**Comment by mflux** [comment]
I, too, would love to use this in vertical mode. Please support this! I am using this at work and have dual monitors in vertical configuration.

The layout could look like this and would be really elegant:

![Screenshot from 2019-08-27 12-03-57](https://user-images.githubusercontent.com/1041360/63766313-d092c100-c8c2-11e9-9d55-e054e9e75e72.png)

**Comment by GitSquared** [comment]
@mflux Sadly I have more important stuff to prioritize right now so I don't think I will implement this myself.

If you know a bit about CSS and are willing to take the time, it should be easy to make a custom theme that will apply the layout you proposed. I can provide you with some instructions if you want to do it.
