### ISSUE TITLE
Blurry display

### ISSUE THREAD

**Issue by Paradigm0001** [GitSquared/edex-ui#395]
3 seconds after boot, eDEX-UI seems to blur at the bottom until a screen update occurs
![](https://user-images.githubusercontent.com/46477191/51266947-710a2580-1971-11e9-88d3-c5cea55976e8.png)

**Comment by GitSquared** [comment]
Now that's an interesting one. Could you please tell me your screen resolution and GPU?

Also, did you change any of eDEX's settings?

**Comment by Paradigm0001** [comment]
#### 1920 x 1080 for screen one (The one its opened on)
##### 1600 x 900 for second monitor (if its relevant)
##### ASUS Turbo GTX 1070, Not overclocked
##### 7700k, Overclocked to 4.9Ghz (Could be relevant?)

**Comment by Paradigm0001** [comment]
### Something else to note is that eDEX-UI isnt the only electron app to blur for me

#### The following electron applications blur for me as well:
* ##### Riot IM, Github Desktop
*However*
#### The following electron applications do `not` blur for me:
* ##### Discord messaging, Atom text editor, Doki Doki Mod manager

Im not sure if this problem is just related to my hardware specifically, as I dont have these problems on other computers, This could also perhaps be out of your hands

If this problem is out of your hands, sorry for wasting your time. However if not, I hope this information is helpful!

**Comment by GitSquared** [comment]
Welp, thanks for the additional info. That does make it an Electron/Chromium issue, so nothing I can directly act on myself.

There are a few minor updates of Electron that will ship with the next eDEX version (v2.0.1) this weekend, so that may be fixed then.

Still, thanks for the report!
