### ISSUE TITLE
Feature request: Make the globe display actually do stuff

### ISSUE THREAD

**Issue by wolfen351** [GitSquared/edex-ui#397]
Now that you have the base in place, I'd love it if the system could "look" at the terminal - at least at new text that is displayed. Anything that looks like an IP address or DNS name - geolocate it and then display a new *bright* pin on the globe there..

I can image me running a traceroute to 8.8.8.8, and a row of brightly coloured pins appears on the globe as the addresses resolve.. 

It would really up the "coolness" factor of this project (at least for me!)

**Comment by wolfen351** [comment]
Perhaps be worth fading them out over 5 mins or so, so the globe doesn't get too busy

**Comment by GitSquared** [comment]
Currently, active socket connections are geolocalised and displayed on the globe every 3 seconds. I'll try and experiment a bit with your idea but running a regex to identify IP adresses on terminal output would probably heavily slow down the term.

**Comment by wolfen351** [comment]
You could only consider the last line of output and look at it once a second, that should help reduce the load a bit.. (at the cost of losing ip and names that wrap)

**Comment by GitSquared** [comment]
![demo](https://user-images.githubusercontent.com/24496417/51791484-2b84fe00-21a4-11e9-863d-afc9565d6628.gif)

Performance is not too bad, it has some rendering bugs on the globe though so i'm keeping it behind a new `experimentalGlobeFeatures` setting (set it to true to activate this new feature).

**Comment by wolfen351** [comment]
Wow! Just wow! Thank you so much for implementing this! It's my new fav toy!
