### ISSUE TITLE
The network panel have a visual error and also doesn't show anything

### ISSUE THREAD

**Issue by jemd15** [GitSquared/edex-ui#398]
1.-The top of the panel shows a text "network status" over another text that i can't understand, but says something like "network adapter..."

2.-The network panel doesn't show me anything. I do not have a firewall blocking something or a proxy. 

P.S:My PC is running on Windows 10 x64.
P.S.2: I don't know if this information is useful, but I can make ssh connections without problems.

![network-panel](https://user-images.githubusercontent.com/19212855/51402085-4d8ada80-1b2b-11e9-9b6b-7b9123fda5b2.png)

**Comment by jemd15** [comment]
Now I know what the text is under the "Network State" ... it's the VMware Network Adapter VMnet1 and that's why I don't have network information. There is a way to change the network adapter to my wifi antenna?

**Comment by GitSquared** [comment]
Indeed, eDEX didn't find the right network interface to monitor. You can override the choosen interface, but you'll need its internal name (like "wlan0" or something). There's a text field in the Settings (Ctrl+Shift+S) to set it.
