### ISSUE TITLE
please support chinese

### ISSUE THREAD

**Issue by mengdodo** [GitSquared/edex-ui#400]
version: eDEX-UI v2.0.0 
os: mac pro 2017    10.14.3 (18D42)
shell: zsh
issue: 
1、chinese support, it will display ????
2、Automatic Completion of Instructions , when i press delete for a long command , i still show with no change
3、how can i clear screen, command+K is not good

i make a short video 
https://www.youtube.com/watch?v=C-5X6B3FL4E&feature=youtu.be

thx, i like edex-ui , it is very cool !

**Comment by libook** [comment]
I have read the source code.
There is no i18n support. So it seems only supporting English, for now.
If GitSquared wants to support i18n, it should be refactored with kind of i18n frameworks.

P.S. 
I personally didn't recommend to support Chinese, even though I'm chinese. (Is GitSquared from France？)
There can be Chinese UI, but you also need to type English commands on the shell. Well, it is a little bit weird.

**Comment by GitSquared** [comment]
As @libook pointed out in #370 ([link](https://github.com/GitSquared/edex-ui/issues/370#issuecomment-457143361)), problems with typing Chinese characters in your shell can generally be fixed within your shell configuration.

I will add a note about this in the readme's Q&A.

I have no plans to support translations of the whole UI - only keyboards and shell dispkay should be localised in my opinion. (Yes, I am from France, by the way.)

Also, to clear the terminal, use the `clear` command
