### ISSUE TITLE
about network

### ISSUE THREAD

**Issue by gangjiegj** [GitSquared/edex-ui#401]
I am a new developer and the network status always offline.What is wrong?How can I solve this problem?

**Comment by GitSquared** [comment]
What OS/network setup are you using?

In most cases this would mean that eDEX couldn't automatically detect the right network interface to monitor - that often happens with virtual machine setups or computers connected directly to wide area fiber networks. There is an override in the settings to set the right interface if that is the case.

**Comment by gangjiegj** [comment]
I am using windows. Should I enter the name of the local interface in the settings?

**Comment by GitSquared** [comment]
Yes. Should be something like "wlan0" (wifi) or "lan0" (wired).

**Comment by GitSquared** [comment]
Oops, my bad, I just checked and apparently Windows has full-length names for network interfaces.

You can list all of them by running `ipconfig /all` in a terminal (cmd.exe).

On my test machine I got `"Wireless Network Connection"` and the loopback interface.

**Comment by GitSquared** [comment]
Note: I added a dropdown menu in the settings so you more easily select the right network interface. See #403, shipping in v2.0.1 in a few hours.

**Comment by gangjiegj** [comment]
This is a very convenient improvement! Very friendly! But I chose the right interface and it still doesn't work, emmm..... I am sorry to say that I don’t know what to do now.
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Git² <notifications@github.com>
发送时间: Sunday, January 27, 2019 11:04:06 PM
收件人: GitSquared/edex-ui
抄送: gangjiegj; Author
主题: Re: [GitSquared/edex-ui] about network (#401)


Note: I added a dropdown menu in the settings so you more easily select the right network interface. See #403<https://github.com/GitSquared/edex-ui/issues/403>, shipping in v2.0.1 in a few hours.

**Comment by GitSquared** [comment]
@gangjiegj Did you click on `Save to disk`, `Reload UI`? The new settings will not apply until you do that.

**Comment by gangjiegj** [comment]
I have done it. Sorry, there is still no effect.

**Comment by GitSquared** [comment]
Could you tell me the interfaces you have and the one you tried to select?

**Comment by blackisle51** [comment]
I know this is closed but I had the same issue.
My problem was that the pfSense firewall was set to block all LAN -> WAN ICMP pings.
Without the correct rule set, the Worldview and Network status, Network Traffic would not function correctly even with the correct interface selected.

**Comment by Miguel238** [comment]
Maybe you need to change the iFace key in setting to your current network.

Open the eDEX-UI Program and wait it. When program is loaded, push CTRL + SHIFT + S (this open setting windows). Go to iface key and change to your current network.

Save and restart eDEX-UI Program.

Good Luck!
