### ISSUE TITLE
cpu tmep on macOS

### ISSUE THREAD

**Issue by gkl1368** [GitSquared/edex-ui#402]
the new 2.0.0 version show error cpu temp on macOS 10.14.3

**Comment by GitSquared** [comment]
Can you provide a screenshot?

**Comment by gkl1368** [comment]
<img width="235" alt="edex" src="https://user-images.githubusercontent.com/12904884/51795255-2b741500-221b-11e9-97dc-aec760d163dc.png">

**Comment by GitSquared** [comment]
Do you have Node.js installed? It'd be great if you could run something so we can find out what temperatures are your system reporting.

**Comment by Cabalist** [comment]
I'm seeing the same thing. Here it is compared with iStats:

<img width="941" alt="screen shot 2019-01-28 at 4 46 29 pm" src="https://user-images.githubusercontent.com/828557/51876093-4ed2b900-231c-11e9-89e9-3bf27a4f9421.png">

**Comment by syxanash** [comment]
I had the same problem on `macOS Mojave 10.14.3`
If it can help, at first I tried getting in node the cpu temperature with `systeminformation` and it actually returned `-1` as in the picture.
I then tried manually installing in the system `osx-temperature-sensor` which is the dependency used by `systeminformation` and suddenly the following script returned the correct CPU temperature. 
```js
const si = require('systeminformation');
si.cpuTemperature(function(data) {
  console.log(data);
});
```
Went to start edex-ui to check if it was fixed and now I have:
```
✖  fatal     TypeError: Cannot read property 'send' of undefined
    at dispatch (/Users/smarzulli/Desktop/edex-ui/src/_multithread.js:36:50)
```

**Comment by syxanash** [comment]
my bad the `_multithread.js` error was because of
```
Error: The module '/Users/syx/node_modules/osx-temperature-sensor/build/Release/smc.node'
was compiled against a different Node.js version using
```
so I guess there's some dependency problem with `osx-temperature-sensor`?
