### ISSUE TITLE
eEDEX-UI failed to launch - Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by SixFive7** [GitSquared/edex-ui#404]
Hi, when launching this awesome app I get this error:
![image](https://user-images.githubusercontent.com/6650122/51794160-fe991100-21cc-11e9-95a4-8ffe9067d5f6.png)

When running from the command line I get this debug log:
 Ôû║  start                        Starting eDEX-UI v2.0.0
i  info                         With Node 10.11.0 and Electron 4.0.1
i  info                         Renderer is Chrome 69.0.3497.106
Ôû║  Startup                      Initialized timer...
i  info                         Base config dir is C:\Users\MyUser\AppData\Roaming\eDEX-UI
[ ]  pending                      Loading settings file...
ÔêÜ  success                      Settings loaded!
[ ]  pending                      Creating new terminal process on port 6517
ÔêÜ  success                      Terminal back-end initialized!
[ ]  pending                      Starting multithreaded calls controller...
ÔêÜ  success                      Multithreaded controller ready
i  info                         Creating window...
...  watching                     Waiting for frontend connection...
├ù  fatal                        TypeError: Cannot read property 'send' of undefined
    at dispatch (C:\Users\MyUser\AppData\Local\MyUser\MyUser\eDEXUI\x32\resources\app.asar\_multithread.js:32:46)
    at EventEmitter.ipc.on.args (C:\Users\MyUser\AppData\Local\MyUser\MyUser\eDEXUI\x32\resources\app.asar\_multithread.js:56:13)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\MyUser\AppData\Local\MyUser\MyUser\eDEXUI\x32\resources\electron.asar\browser\api\web-contents.js:334:13)
    at WebContents.emit (events.js:182:13)

Any clue as to what this might cause?
Thanks!

**Comment by GitSquared** [comment]
Do you have anything running on local port 3000?

**Comment by GitSquared** [comment]
Does this happen constantly? How many CPU cores do you have on this machine?

**Comment by SixFive7** [comment]
Hi, this does indeed happen every single time. It even happens at exactly the same moment in the rendering. I tried changing all of the settings, none made any difference for this problem however.
The machine has just 1 CPU and is running Windows 7 32 bit with a completely new vanilla install. Since it's just a test VM I tried adding another core. That actually fixed the issue!
However, is it possible to get this to also work on old single core Windows 7 hardware?

**Comment by GitSquared** [comment]
I see the problem now. The multithreaded controller assumes the machine has at least a dual-core. I'll add a safeguard against this - but please not that running eDEX on a single core will probably get you near-unusable performance.

**Comment by SixFive7** [comment]
I just tried the new v2.0.1 build that contains the fix. However, it did not resolve the issue. Single core machines still can't run eDEX-UI.
Any clue?

**Comment by GitSquared** [comment]
Sorry, I commited a bad fix. Master should be rid of this issue now - shipping in next release, [or if you can't wait...](https://ci.appveyor.com/project/GitSquared/edex-ui/builds/21979276/artifacts)

**Comment by SixFive7** [comment]
Hi, thnx for the superfast response!
I couldn't wait, so I tried the link. However, it's not a fix yet. Same error.
Anything I can do to help test?

**Comment by GitSquared** [comment]
@SixFive7 [Does this one works?](https://ci.appveyor.com/project/GitSquared/edex-ui/builds/22005717/artifacts)

**Comment by SixFive7** [comment]
Awesome it works :-)
Thanks for the superfast fixes!

**Comment by DrCuriosity** [comment]
I'm seeing this error on a 4-core, Windows 8.1 machine. It gets as far as bringing up the keyboard and the "welcome back", then dies every time with the same error message.

Any thoughts on why that might be happening, or how I could look for info to track down the issue?

**Comment by GitSquared** [comment]
@DrCuriosity Could you launch eDEX from a cmd/powershell terminal and copy/paste the error message printed in the term here?

**Comment by DrCuriosity** [comment]
Okay. Error from the terminal is:
```sh
C:\Projects\edex-ui>npm start

> edex-ui@2.2.0-pre start C:\Projects\edex-ui
> electron src --nointro

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@2.2.0-pre start: `electron src --nointro`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edex-ui@2.2.0-pre start script.
```
Further error in the npm-cache log shows the following stack trace:
```
9 verbose lifecycle edex-ui@2.2.0-pre~start: CWD: C:\Projects\edex-ui
10 silly lifecycle edex-ui@2.2.0-pre~start: Args: [ '/d /s /c', 'electron src --
nointro' ]
11 silly lifecycle edex-ui@2.2.0-pre~start: Returned: code: 1  signal: null
12 info lifecycle edex-ui@2.2.0-pre~start: Failed to exec start script
13 verbose stack Error: edex-ui@2.2.0-pre start: `electron src --nointro`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_m
odules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_m
odules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:1001:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_proc
ess.js:266:5)
14 verbose pkgid edex-ui@2.2.0-pre
```
