### ISSUE TITLE
Copying text in ssh session is not saved to clipboard

### ISSUE THREAD

**Issue by willemdh** [GitSquared/edex-ui#405]
Hello,

First of all, very nice work on the edex-ui. I've been trying to use this for system administration, but for now I can't replace my current Cmder setup, as I really need to be able to copy text between ssh sessions.
I'm running the Windows version. Terminals launch powershell from which I ssh into some cloud servers. Text I try to copy from the ssh sessions (select text > right click) is not saved to clipboard, which is not really productive. Is this supposed to work or am I missing something? 

Grtz

Willem

**Comment by GitSquared** [comment]
The right click behavior (which is a specific feature of Windows terminal emulators, by the way) is not implemented on eDEX. You can use either the visual keyboard access buttons, or the `Ctrl+Shift+C` / `Ctrl+Shift+V` keyboard shortcuts.
