### ISSUE TITLE
"nointro": true,  has no effect but the --no-intro command line argument does work

### ISSUE THREAD

**Issue by SixFive7** [GitSquared/edex-ui#406]
Hi,

Changing "nointro": false, to "nointro": true, either through the user interface or directly in the settings.json has no effect. The intro always shows.
Starting eDEX-UI.exe from the command line with the --nointro argument however; does seem to work.

**Comment by GitSquared** [comment]
Thanks for the report. I forgot something when writing the handler for this option.
