### ISSUE TITLE
Feature Request: Window Manager

### ISSUE THREAD

**Issue by DJyStyler** [GitSquared/edex-ui#407]
I would like to suggest a function today that could quickly bring this project forward, what I have not read in any suggestion so far is a window management that edex-ui would use as a full desktop environment.
Since there are already many desktop environments brewing on Java, it should not be impossible.
A small taskbar and a task manager with service manager would further advance the project.

**Comment by GitSquared** [comment]
I'm sorry, this is way beyond the scope of this project and would require an entirely different codebase. I might look into making a futuristic desktop environment in a few years, but right now I'm going to have to dismiss the request.

Thanks for your enthusiasm, though.
