### ISSUE TITLE
Can I open a browser in this bad-ass terminal?

### ISSUE THREAD

**Issue by kingfengji** [GitSquared/edex-ui#409]
Hey yo!

extraordinary version 2.0.1!

Quick question: How can I like open a chrome or something that can display some images? Like you know would love to use juypter notebooks in my browser in my bad-ass terminal.

Thanks yo!

**Comment by GitSquared** [comment]
Hey there!

For web browsing in a terminal, my favorite software is [browsh](https://www.brow.sh/). Unfortunately, rendering images and graphics in a terminal is a complicated issue, and I don't think there are any terminal-based browsers that support graphics well enough to use advanced apps like Jupyter Notebooks.

There is an open issue about this on browsh, though: browsh-org/browsh#137

**Comment by kingfengji** [comment]
damm it. Browsh is awesome. 

Many thanks!

The world owes you, man.
