### ISSUE TITLE
No such file or directory when browse file with built-in file browser

### ISSUE THREAD

**Issue by ChipTechno** [GitSquared/edex-ui#410]
Hello.
Thank for very nice application.
 I get "No such file or directory" when browsing file with the built-in file browser. I can change directory, everything is work except the false error message.
Using 4.19.16-1-MANJARO kernel, the application is built from official AUR.
Thank you!

**Comment by GitSquared** [comment]
Can you provide a screenshot?

**Comment by ChipTechno** [comment]
My bad. I'm using double click to change folder, so the UI executed the cd command 2 times.
