### ISSUE TITLE
Add support for 4:3 (1024x768) aspect ratio displays

### ISSUE THREAD

**Issue by asterismo** [GitSquared/edex-ui#411]
Hi, i installed it on the Panasonic Toughbook CF-31 millitary laptop that has a 1200 nit screen brigtness and 1024x768 screen resolution, and the fonts appear quite big and  don't fit quite well. Maybe allow smaller font size? I see that keyboard layouts are only a few, is there any plan to add spanish dvorak layout?

Thanks and best regards

**Comment by GitSquared** [comment]
The size of about everything in the UI including fonts is defined with viewports units, which means they vary based on your screen's height and width. This allows better display scaling but means I need to add support for each aspect ratio individually. I'll look into adding support for yours - 4:3 i think.

As for keyboards, I am not making any new ones myself but contributions are most welcome.
