### ISSUE TITLE
Infected dependency

### ISSUE THREAD

**Issue by kohrVid** [GitSquared/edex-ui#412]
Not sure if this is something you need to worry about but ClamAV seems to think that one of eDEX-UI's dependencies is an infected file (specifically `Win.Virus.Triusor`). [An issue](https://github.com/develar/7zip-bin/issues/6) was raised for this a few days ago but I think there was a deleted question on Stack Exchange about this as well. Display issues on my machine prompted me to run a scan but this was probably a coincidence.

**Comment by GitSquared** [comment]
This project uses continuous dependencies monitoring provided by Snyk (you can find links to scan pages from the top of the README). I'm pretty confident that the dependencies used in this project are safe and that this is a false positive.
 
If a vulnerability as important as the one ClamAV claims to detect was to be revealed, the average delay between vuln disclosures and a patched hotfix release on this project is around 20 hours tops so far.

I'll keep an eye out on the issue you linked and reopen this if needed - thanks for providing all the relevant info, you rock.

*Note: here's the dependency path to the concerned package:
`[edex-ui builder]` > `electron-builder` > `builder-utils` > `7zip-bin`*
