### ISSUE TITLE
ENCOME Globe not loading on precompiled darwin binary v2.0.1

### ISSUE THREAD

**Issue by rcavaz** [GitSquared/edex-ui#420]
This issue was already reported on #373 and #217 which stated that would be fixed on v2.0.0 but seems to persist.

![captura de pantalla 2019-02-06 a la s 12 36 58](https://user-images.githubusercontent.com/6046647/52365180-8c1a0380-2a0c-11e9-8c30-8483ac9e55d9.png)
![captura de pantalla 2019-02-06 a la s 12 37 17](https://user-images.githubusercontent.com/6046647/52365183-8c1a0380-2a0c-11e9-9b40-44f1db79ec1b.png)

**Comment by GitSquared** [comment]
@rcavaz Could you tell me what your GPU is?

**Comment by rcavaz** [comment]
I have an Intel HD Graphics 3000 512 MB card.

**Comment by GitSquared** [comment]
@rcavaz Does accessing https://get.webgl.org/ in a web browser seems to work for you? What is your exact CPU model?

The issue in #217 was related to buggy support of Haswell generation integrated graphics in Intel CPUs. The GPU on your mac dates from the Sandy Bridge gen of processors, that is about 2 years older than Haswell.

**Comment by rcavaz** [comment]
@GitSquared Yes, I do see the spinning cube when accessing https://get.webgl.org/ on all browsers I have (Safari & Chrome).

I have a 2.7 GHz Intel Core i7 cpu.

**Comment by GitSquared** [comment]
@rcavaz I'm sorry, I couldn't find a workaround for your case and cannot fix the issue myself, as it originates from Chromium/electron. I'm going to have to close this, but I hope a future Electron patch might fix the situation and I'll update the thread if that happens.
