### ISSUE TITLE
Not hidden files

### ISSUE THREAD

**Issue by masivi** [GitSquared/edex-ui#421]
First of all, I wanted to thank @GitSquared for making eDEX-UI 👍🏻
Is it possible to hide the hidden files in the folder dock?
Thank's

**Comment by masivi** [comment]
Thank's!

It would be great!!!!

**Comment by GitSquared** [comment]
Usage: `CommandOrControl+Shift+H` keyboard shortcut or use settings option `hideDotfiles` (boolean)

Shipping in v2.1.
