### ISSUE TITLE
No exluding in top

### ISSUE THREAD

**Issue by masivi** [GitSquared/edex-ui#426]
edex-ui is not excluded in top process even when the param is set to true

![captura de pantalla de 2019-02-11 17-58-29](https://user-images.githubusercontent.com/15030073/52579653-e0ffb480-2e26-11e9-8457-2ce3bdd24241.png)

**Comment by GitSquared** [comment]
Did you press "save to disk" and then "reload UI"? Parameters can't hotswitch right now.

**Comment by masivi** [comment]
Yes, of course.
Maybe the problem could be that I've moved the AppImage file to another folder... the icon in the system went out, and the wizard to reasign the integration with the system does not appear anymore?

**Comment by GitSquared** [comment]
I don't think this is related...
Could you check that the file at `~/.config/eDEX-UI/settings.json` was correctly written?

I'll look into the logic behind this option to see if there's a bug somewhere.

**Comment by masivi** [comment]
The settings in ~/.config/eDEX-UI/settings.json are ok (true in "exclude...")
In the other hand, is it possible to launch the start wizard for system integration again?

Thank's a lot!

**Comment by GitSquared** [comment]
Weird. Will look into it.

I don't know much about how AppImage handles those things but I believe you can access this stuff from the command line by passing in flags. Try and run `./eDEX-UI.appimage --help` and see if you get anything useful.

**Comment by GitSquared** [comment]
I found the issue and will fix it in a moment. You'll have to wait for the 2.1 release if you're not running from source, though.

**Comment by masivi** [comment]
Perfect! I'll wait, thank's!!
