### ISSUE TITLE
Better audio FX

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#427]
Sound effects shipped in v2.0 are a fucking nightmare and they make me want to cut off my ears.

Luckily I got a friend of mine who happens to know a bunch of sound design stuff.

**Comment by MasterGeekMX** [comment]
Sorry for commenting on a closed issue, but some of us liked the old sounds.

Option to select new or old? Thanks.

**Comment by GitSquared** [comment]
Uh, didn't plan for that. Old sounds are no longer included in assets and adding them back would double the size of assets which i don't think is worth it for (hopefully) a minority a people wanting them back.

@MasterGeekMX what exactly do you prefer with the old ones? Perhaps we can work out some improvements.

**Comment by MasterGeekMX** [comment]
More beeps, less pluckls.
