### ISSUE TITLE
Freezes when running flood-output commands like `find .`

### ISSUE THREAD

**Issue by edgelord314** [GitSquared/edex-ui#428]
eDEX-UI freezes on my iMac when I run flood-output commands like find. I am not particularly sure if it's because of the flood on output or because of some access-rights but also the sound fx are going crazy when running `find .`

**Comment by edgelord314** [comment]
I have the model with the 3,6 GHz Intel Core i7 and the 16 GB ram, so my hardware should not be the issue.

**Comment by GitSquared** [comment]
Does setting `audio: false` in the settings fix the issue?

**Comment by edgelord314** [comment]
@GitSquared yes it does fix it. Maybe you should minimise the sound for flood-output commands?

**Comment by GitSquared** [comment]
Yeah, I'll add a timer to prevent this. I'll be rewriting most aspects of the sound effects for the next version, too. Thanks for the report!
