### ISSUE TITLE
Wrong network adapter

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#429]
![screenshot_1](https://user-images.githubusercontent.com/11785085/52916938-b6f63880-32e5-11e9-86a4-d40691a02bc8.png)

The network adapter displayed in the network status tab isnt actually the one my PC is using - but a virtual one from VMware.

Does the app just use the first adapter present?

It would be nice if there would be an automatic detection based on which network adapter is actually having up and download (if that is even possible).

**Comment by GitSquared** [comment]
There is an automatic detection but it doesn't work on all setups. You can override which interface is monitored in the settings - there's a graphical dropdown list to make it easier.
