### ISSUE TITLE
Folder display duplication

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#430]
![screenshot_2](https://user-images.githubusercontent.com/11785085/52916994-4b609b00-32e6-11e9-9a38-3bd00d097038.png)

Similar or duplicate of #277 

The issue should be reproducable with the following steps
- open a new tab
- press enter to intialize cmd
- exit cmd with `exit`
- switch tab
- switch back
- press enter again

This results in the FILESYSTEM tab displaying all entries duplicated; Also displaying that tracking failed (?)

**Comment by GitSquared** [comment]
I've seen this racing condition before. I'll try and set up something to prevent it from happening.
