### ISSUE TITLE
Filesystem path insertion failure

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#431]
![screenshot_3](https://user-images.githubusercontent.com/11785085/52917068-43edc180-32e7-11e9-882e-a8def2d01115.png)

Clicking on a file in the FILESYSTEM tab when it is detached results in the insertion of the file into the command line; - without it's path. Meaning you cannot open / execute it.

A potential fix is to simply disable the click to insert feature; Or maybe insert the whole path.

**Comment by GitSquared** [comment]
Inserting the full path when running in detached mode seems like a good workaround. I'll implement this for the next version.

**Comment by clragon** [comment]
Correction of my post above;

A simple fix would be to disable to click to insert feature when running detached.
