### ISSUE TITLE
Filesystem detachment not updating

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#432]
It seems like once detached from the terminal, the FILESYSTEM tab is able to reattach itself to a working terminal upon switching tab. 

It also seems like while this works just fine, it doesnt update the text with it saying "FILESYSTEM - TRACKNG FAILED, RUNNING DETACHED FROM TTY" when being reattached to a working tab.

**Comment by GitSquared** [comment]
It doesn't actually "reattach", it restarts the tracking subroutine for the new tab and defaults back to the current working directory selected in eDEX's settings. I'll try to make that behavior more obvious.

**Comment by clragon** [comment]
It might also be very convinient if the Filesystem tries to reattach itself when switching to a tab that has a terminal that is compatible?

**Comment by GitSquared** [comment]
Tracking availability depends on the OS, not the terminal.

**Comment by clragon** [comment]
Ah I see. So even tracking `wsl`, the linux subsystem wouldnt work, 
or is tracking for windows just not implemented?

**Comment by GitSquared** [comment]
Even wsl won't work. Tracking CWDs is done at OS level and i couldn't find a reliable way to get that information on Windows.
