### ISSUE TITLE
Prompt failure

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#434]
![screenshot_2](https://user-images.githubusercontent.com/11785085/52917350-a4323280-32ea-11e9-848f-dabe1938295a.png)

It seems like typing anything besides enter when opening a new terminal, does result in that being printed, but the prompt of the terminal will for whatever reason be invisible for that line.

This issue occurs on windows 10 with `cmd.exe`. Weirdly enough, this doesnt occur with `wsl`.
This might be an issue with cmd itself.

**Comment by GitSquared** [comment]
Indeed, this is an issue with how cmd/powershell handles output streams. Closing this one.
