### ISSUE TITLE
Snap package request

### ISSUE THREAD

**Issue by NatoBoram** [GitSquared/edex-ui#439]
Hello! I'd like to request a Snap package of eDEX-UI.

There's documentation on [electronjs.org](https://electronjs.org/docs/tutorial/snapcraft) and [snapcraft.io](https://docs.snapcraft.io/electron-apps/6748).

> Distributing an Electron application for Linux that reached the widest possible audience was historically difficult. How applications are packaged and delivered varies from distribution to distribution. There was no built-in mechanism for notifying users of available updates.
>
> Snaps address these issues and enable you to produce a Linux version of your app with minimal changes to your package.json.

> Snaps are containerized software packages that include required dependencies, auto-update, and work on all major Linux distributions without system modification.

**Comment by GitSquared** [comment]
I'm wondering if adding snap targets is worth it. The AppImages work just fine.

I would consider building distro-specific targets like .deb and/or snap packages if there were automatic updates or something, but right now this doesn't seem worth it to me. I'm open to contributions, but not interested in doing it myself.

**Comment by NatoBoram** [comment]
Are you looking for [this](https://snapcraft.io/build)?

[![Auto-build and publish software for any Linux system or device](https://assets.ubuntu.com/v1/ed6d1c5b-build.snapcraft.hero.svg)](https://build.snapcraft.io/auth/authenticate)

[![
How Snapcraft fits your workflow
](https://assets.ubuntu.com/v1/b70a5c55-workflow-illustration.svg)](https://build.snapcraft.io/auth/authenticate)
