### ISSUE TITLE
Keyboard synchronisation

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#440]
When using a hardware and the software keyboard at the same time, the behaviour of them isn't sycned.

For exmaple:
- Pressing the shift key physically and clicking on a letter on the touch keyboard doesnt produce a uppercase letter.
- Activating physical capslock and then pressing any letter on the touch keyboard doesnt produce an uppercase letter

I dont know if syncing those is anyhow useful but I kind of would expect this behaviour.

**Comment by GitSquared** [comment]
I never thought about the possibility of using both virtual and physical keyboards at the same time, but I guess there are octopuses among us now.

Jokes aside, this should be relatively easy to implement so why not.
