### ISSUE TITLE
Mac OS 10.14.3 CPU show -1C

### ISSUE THREAD

**Issue by BjornFjord** [GitSquared/edex-ui#445]
The Mac version running on os 10.14.3 is showing a CPU temp as -1C. 
![screen shot 2019-02-25 at 7 18 25 am](https://user-images.githubusercontent.com/30632354/53347624-57dc8900-38ce-11e9-920a-70b67399a2da.png)
iStat shows the temp at 61-64C 
![screen shot 2019-02-25 at 7 30 15 am](https://user-images.githubusercontent.com/30632354/53348142-595a8100-38cf-11e9-8fff-08e7eec8832a.png)
This looks like the same issue the Windows and Linux build reported.

**Comment by GitSquared** [comment]
@BjornFjord Are you using the latest release or running from source?

**Comment by BjornFjord** [comment]
I downloaded the latest release last week and the dmg is listed as 2.0.1.

**Comment by GitSquared** [comment]
Yeah, all right. This issue has been fixed but the fix hasn't been released yet (see #402 #415).

I'm hoping to release v2.1 next week which will include a patch for this.
Thanks for reporting!
