### ISSUE TITLE
fsDisp not displayed on windows - `CallStackSizeExceeded` error

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#446]
I'm currently holding off the `v2.1.0` release because of a nasty bug ~~related to `asar` support for unpacked dependencies on electron apps packaged for Windows.
Fix has already been implemented, waiting for it to swim down to electron so I can build new Windows assets.~~ ...that I'm currently investigating.

~~electron/asar#139 - original issue
electron/electron#17061 - PR rolling down the fix in Electron~~
Not the right issue? Where the hell is it coming from?

Info so far:
- ~~Only packaged binaries are affected~~ Only minified code run on Windows OS
- Error is thrown from node's `require` module, stack begins at _renderer.js:466 (instantiation of updateChecker module)(btw, renderer is not minified?)
- Removing the unuseful `require("electron")` in updateChecker module does not fix the issue 
- Disabling the module does not fix, so it isn't even related

**Comment by GitSquared** [comment]
I'm publishing v2.1.0 with non-minified javascript files on the windows release, which looks like it would fix the issue. Still investigating this.

**Comment by GitSquared** [comment]
Turns out the `file-icons-match.js` generated script was the one causing problems. This 1mb one-liner is too much for Windows to handle, apparently.

**Comment by BNWEIN** [comment]
Just to confirm version 2.1.0 does not fix the issue. Also to confirm the issue is not only related to the ROOT of the drive.

As as soon as you browse to another folder (for example simply typing "cd .."  you get error above the file system tracking that says "Filesystem- Tracking failed, running detached from TTY"

**Comment by GitSquared** [comment]
@BNWEIN Wrong issue, you're refering to #443, which has been fixed but as said in that thread the fix has not been released yet.

The "no tracking" mode is expected behavior on Windows.

**Comment by BNWEIN** [comment]
Is there a plan to keep tracking mode on Windows?


Ben Weinberg
Operations Director
Tel020 7443 5618
Mob07515 482 580
EmailBWeinberg@prime-networks.co.uk
www.prime-networks.co.uk
Kingsway House, 103 Kingsway, London, WC2B 6QX
This message is intended exclusively for the individuals to whom it is addressed and may contain information that is privileged, or confidential. 
​If you are not the addressee, you must not read, use or disclose the contents of this e-mail. If you receive this e-mail in error, please advise us 
​immediately and delete the e-mail. Prime & Modern LTD has taken every reasonable precaution to ensure that any attachment to this e-mail 
​has been swept for viruses. However, Prime & Modern LTD cannot accept liability for any damage sustained as a result of software viruses and 
​would advise that you carry out your own virus checks before opening any attachment. Prime & Modern Ltd is a limited company registered in 
​England and Wales. Registered Company No: 08403368 Registered Office: Palladium House, 1-4 Argyll Street, London, W1F 7LD.

**Comment by GitSquared** [comment]
@BNWEIN I'm still looking into it but so far I believe it is technically impossible. Windows lacks a way to track working directories of child processes.
