### ISSUE TITLE
npm ERR! electron@4.0.5 postinstall: `node install.js` npm ERR! Exit status 8

### ISSUE THREAD

**Issue by jebuscraisp** [GitSquared/edex-ui#447]
npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/home/foxelvoret/.nvm/v0.10.48/bin/node" "/home/foxelvoret/.nvm/v0.10.48/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! electron@4.0.5 postinstall: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the electron@4.0.5 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js

**Comment by jebuscraisp** [comment]
Now using node v0.10.48 (npm v2.15.1)

**Comment by GitSquared** [comment]
Sorry, this is an issue with either Electron or NVM and I can't help.
Are you sure you want to run eDEX from source?

**Comment by jebuscraisp** [comment]
When I run the precompiled binary it runs with Electron 4.0.2. I wanted to run  from source so I can customize stuff , like removing the keyboard , also I wanted to understand more how it works. Thank you! ill email the package owner then..

I was able to use anyway, pretty neat.. thanks again

**Comment by GitSquared** [comment]
@jebuscraisp Check out the [wiki](https://github.com/GitSquared/edex-ui/wiki), you can do a lot of customization without running from source :-)
Hope you find out how to work around this though. You might want to search electron's issues.

**Comment by jebuscraisp** [comment]
Roger that
Cheers!
