### ISSUE TITLE
[UI] C key not working on touchscreen

### ISSUE THREAD

**Issue by kelaun** [GitSquared/edex-ui#448]
I just tried to type using the touchscreen of my laptop and noticed all the keys work except the "c".

Kr,
Kelaun

**Comment by GitSquared** [comment]
What keyboard layout are you using?

**Comment by kelaun** [comment]
Just using everything default currently (keyboard is qwerty US)

**Comment by GitSquared** [comment]
Okay, thanks, I'll look into it.

**Comment by GitSquared** [comment]
@kelaun Found & patched. I'm pushing a new release in the next hour that will include a fix for this.
