### ISSUE TITLE
Cannot open a second terminal

### ISSUE THREAD

**Issue by LambdaXIII** [GitSquared/edex-ui#449]
When I click "empty" to open a second terminal, edex crashed and says "ioctl error".

I am using macos mojave and my login shell is fish.

**Comment by GitSquared** [comment]
Does this happen consistently or only sometimes?

**Comment by LambdaXIII** [comment]
everytime. 2.0.1 and 2.1.0
It happens for a while...
and the "empty" word turn to "::3002". The dialog says "ioctl(2) failed".

**Comment by GitSquared** [comment]
(Related: Microsoft/node-pty#220 )

**Comment by GitSquared** [comment]
Should work flawlessly on the latest versions.

**Comment by ZZZXXX0110** [comment]
I'm still experiencing this problem on the latest version 2.2.2

**Comment by rijnhard** [comment]
Fresh install v2.2.2 Linux mint 20, same issue.

**Comment by Animus-Surge** [comment]
Try compiling `master` branch as shown in the [readme](https://github.com/GitSquared/edex-ui#useful-commands-for-the-nerds).
