### ISSUE TITLE
How to add my name next to "Welcome back" on startup? 

### ISSUE THREAD

**Issue by greysonmb** [GitSquared/edex-ui#450]
In the reddit post, the creator had "Welcome Back Squared" on startup. How can I do that? I don't see an option in settings.json

**Comment by GitSquared** [comment]
The name is automatically detected from your system's username, when possible.
https://github.com/GitSquared/edex-ui/blob/b00b12cbb149f84e10e74e2c50a1e26a0eb08923/src/_renderer.js#L347-L351

I'm guessing you're on Windows - ignore this if I'm wrong. [Systeminformation](https://github.com/sebhildebrandt/systeminformation) internally uses the `query user` shell command on Windows to get the list of currently logged in users (see [code](https://github.com/sebhildebrandt/systeminformation/blob/667c7e8b9040b8e6d57884b86b83bbed528432dc/lib/users.js#L248-L254)). If you're not seeing your username in eDEX, you might be missing `query` on your system for some reason.

Linux & macOS should work fine as always.

**Comment by clragon** [comment]
Works just fine over here on Windows 10.
