### ISSUE TITLE
Support Tilde as dead key

### ISSUE THREAD

**Issue by darodrigues** [GitSquared/edex-ui#454]
The "Escaped Commands" section of the file `src/classes/keyboard.class.js` lacks a `case "TILDE":` which would set the property `this.container.dataset.isNextTilde` to true. As it is, even though the rest of the code required to use it is in place, it is impossible to use the tilde as a dead key.

**Comment by GitSquared** [comment]
Will look into this.

**Comment by GitSquared** [comment]
Thanks for spotting this!
