### ISSUE TITLE
Colors in terminal

### ISSUE THREAD

**Issue by masivi** [GitSquared/edex-ui#463]
*The following (lightweight) template is made to better understand your view and what you think about your request. You are free to ignore it, but are encouraged to complete it.
We've seen lots of feature requests on this project, some were perhaps [too ambitious](https://github.com/GitSquared/edex-ui/issues/456) and some were [literally implemented overnight](https://github.com/GitSquared/edex-ui/issues/260). Don't be afraid to propose your ideas either way, we'll look at every one of them ;)
You can delete this introduction message if you want to.*

**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [X] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [X] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

It would be great if the terminal shows colors. Most of text-based programs use them to simplify the ux. It would be possible to keep the terminal colors?

Thank's anyway!

**Comment by GitSquared** [comment]
Terminal colors can be defined on a per-theme basis. Some included themes like chalkboard and nord have terminal colors enabled.

See [this issue comment](https://github.com/GitSquared/edex-ui/issues/287#issuecomment-441426617) for more information on how to add term colors to a theme :)
