### ISSUE TITLE
Not working special leters in es-LAT Layout

### ISSUE THREAD

**Issue by masivi** [GitSquared/edex-ui#466]
*The following (lightweight) template is made to avoid recurring questions in new bug reports and to facilitate problem diagnosis. You are free to ignore it, but filling it correctly will help a lot. Either way, thanks for taking the time to write a report.
You can delete this introduction message if you want to.*

## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code)
 - [X] `latest` (latest release, currently `v2.0.1`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [X] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

The es-LAT layout is not working propiertly: the special letters are not show. Example: á, é, í, ó, ú.

Thank's.

**Comment by masivi** [comment]
I don't know if this helps, but 4 keys are wrong in Spanish layout.

The correct must be (changes in bold):

   {
      **"name": "`",
      "cmd": "`",
      "shift_name": "^",
      "shift_cmd": "^",
      "alt_name": "["
      "alt_cmd": "["**
      "ctrl_cmd": "~~~CTRLSEQ1~~~"
    },
    {
      "name": "+",
      "cmd": "+",
      "shift_name": "*",
      "shift_cmd": "*",
      **"alt_name": "]",
      "alt_cmd": "]",**
      "ctrl_cmd": "~~~CTRLSEQ3~~~"
    },
   {
      **"name": "'",
      "cmd": "'",
      "shift_name": """,
      "shift_cmd": """,
      "alt_name": "{",
      "alt_cmd": "{"**
    },
    {
      **"name": "ç",
      "cmd": "ç",
      "shift_name": "Ç",
      "shift_cmd": "Ç",
      "alt_name": "}",
      "alt_cmd": "}",**
      "ctrl_cmd": "~~~CTRLSEQ2~~~"
    },

**Comment by masivi** [comment]
I tried to change the .json but it not work (edex not load)

**Comment by GitSquared** [comment]
I'll check this tomorrow, but in the meantime, maybe it fails to load because of unescaped `"` characters in the json?

I think there are some lines in your fix where you'll need to escape those like so: `"shift_name": "\"",`

**Comment by masivi** [comment]
Yes, you're right!
But the problem persists... when you push a special key (acute accent, for example, the key next to the ñ) the sistem does not print anything. It is waiting for another key, like the "a" key and when you press it, the system prints the accented a "á". In edex when you push acute accent special key the system does not print anything (what is right) but when you push the second key, like "a" key, the system only prints the regular "a".

**Comment by GitSquared** [comment]
So, I fixed the issue with the special ("dead") keys not working.

I also figured out you were expecting the [Spanish (es-ES)](https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/KB_Spanish.svg/1280px-KB_Spanish.svg.png) keyboard, while only the [Latin-American Spanish (es-LAT)](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/KB_Latin_American.svg/1280px-KB_Latin_American.svg.png) keyboard was available. I added a new `es-ES` keyboard for you.

[Here is a pre-release AppImage build](https://send.firefox.com/download/3345d17fb3/#Bg3TVyuEHN3xBj-QAi5wxg) so you don't have to wait for the next release :+1:

**Comment by masivi** [comment]
Thank's friend!

**Comment by masivi** [comment]
Ouch! same problem :(
The layout is correct in screen, but if you push the ' key and then a "a" key (or some other) no "á" is shown, only "a" :'(

**Comment by GitSquared** [comment]
Oops... What key exactly? Everything seems to be working for me:

![Peek 2019-03-23 11-00](https://user-images.githubusercontent.com/24496417/54864683-dc4dea80-4d5a-11e9-820c-3ab215bae61e.gif)

**Comment by masivi** [comment]
Ok, the virtual keyboard works fine. The problem is the phisical one. I attach you a video where you can see the behavior in a gnome-terminal first, then in edex with phisical keyboard and then in edex with virtual keyboard. Thank's again!!!!
[video.zip](https://github.com/GitSquared/edex-ui/files/2999332/video.zip)

**Comment by GitSquared** [comment]
Oh, OK, I get it now. Opened a new issue for this: #469
