### ISSUE TITLE
No icon down key

### ISSUE THREAD

**Issue by masivi** [GitSquared/edex-ui#467]
*The following (lightweight) template is made to avoid recurring questions in new bug reports and to facilitate problem diagnosis. You are free to ignore it, but filling it correctly will help a lot. Either way, thanks for taking the time to write a report.
You can delete this introduction message if you want to.*

## Technical information
**Using version:**
 - [X] `master` (running from GitHub-published source code)
 - [ ] `latest` (latest release, currently `v2.0.1`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [X] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

There is no icon in down key (spanish layout) in master.

![Captura de pantalla de 2019-03-21 19-07-41](https://user-images.githubusercontent.com/15030073/54774931-1e691600-4c0d-11e9-9593-4eff77ec530c.png)

**Comment by GitSquared** [comment]
Made a naming error when writing keyboard icons handling. Thanks for spotting that!
