### ISSUE TITLE
Physical keyboard dead keys don't work

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#469]
## Technical information
**Using version:**
 - [X] `master` (running from GitHub-published source code, currently `v2.2.0-pre`)
 - [X] `latest` (latest release, currently `v2.1.0`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [X] Linux
 - [?] Windows
 - [?] macOS
---

Using dead keys to compose accentuated characters with a physical keyboard doesn't work. Reported on Linux by me and @masivi - see end of thread on #466.

**Comment by yozlet** [comment]
Not sure if this is related, but: on my Mac (running Mojave) not only is there no `Cmd`/⌘ key on the virtual keyboard, but using Cmd in a key combo then keeps the other keys lit (i.e. showing the solid keypress block), and their status doesn't change until I hit those keys again.

**Comment by GitSquared** [comment]
@yozlet That's unrelated but it sounds like an issue I fixed in master the other day and that should land in the next release.

Also I need to replace the Cmd shortcuts on macOS with Ctrl ones like on the other platforms; that will make everything easier... Plus you can't use Cmd+Tab on macOS because that's the system shortcut for switching windows.

**Comment by masivi** [comment]
Any news about this? I've been searching but nothing useful... :(

**Comment by GitSquared** [comment]
@masivi I'm currently (mostly) taking a break from open-source work as I got some final exams next week.

I started working on this issue already though, but it is way more complicated than I thought.
For some reason the terminal emulator does not receive correct key events data when dead keys are used.

I hope to find a way to fix this soon as it's also important for my language 😅 
I'll keep this thread updated.

**Comment by masivi** [comment]
Any news about this?
Thank's anyway!

**Comment by GitSquared** [comment]
Unfortunately not. I've tried a few times to fix this but couldn't find anything.

**Comment by GitSquared** [comment]
Looks related: https://github.com/xtermjs/xterm.js/issues/2151 https://github.com/xtermjs/xterm.js/issues/2479

Would appreciate if someone could test writing stuff like ô on VS Code's terminal, which uses the same underlying tech

**Comment by lowgos** [comment]
Here you go.
I hope it helps

https://user-images.githubusercontent.com/22097902/108694453-59fa7200-74ff-11eb-9619-94b447e5709b.mov

**Comment by GitSquared** [comment]
@lowgos Thanks, but I need to see it in VS Code's terminal drawer, not the editor window! :)

**Comment by pgramme** [comment]
@GitSquared I arrived here after browsing because I have the AltGr+tilde issue in VSCode terminal (see https://github.com/xtermjs/xterm.js/issues/2479). 

But I don't have any issue when typing `^` + `o` in the terminal: nothing is shown at first keystroke and ô appears at second. My setup: 
* Belgian Azerty keyboard
* Windows 10.0.18363
* VSCode: 1.55.2 (user setup)

Let me know if I can make other useful tests

**Comment by GitSquared** [comment]
@pgramme thanks for the help.

I've tried this again in edex and it seems some upstream changes have fixed the issue (took a long time, but hey! good news). This is on v2.2.7.

![Peek 2021-04-17 15-51](https://user-images.githubusercontent.com/24496417/115115446-d3a95c00-9f94-11eb-9c74-98af89f89741.gif)

Furthermore we don't have the VS Code issue you linked with AltGr (I use an FR-fr azerty keyboard).

Guess we can finally close this! Ping @masivi if you still care :sweat_smile:

**Comment by pgramme** [comment]
Great news. Do you mean you had observed the issue in VS Code before but no more now? And do you have an idea of which upstream update has solved the issue in eDEX?

**Comment by GitSquared** [comment]
I've actually never used VS Code so I wouldn't know. I referenced its terminal because it is built on the same stack as edex (electron + node-pty + xterm.js).

About which update has solved the issue, I'm not sure. I've dug in a bit in xterm.js's commit history but couldn't find anything relevant, so maybe this has something to do with a change in keyboard events handling at the Chromium level.

**Comment by pgramme** [comment]
No worry about VS Code.

You're probably right about the Chromium update, because I've just tested and I still observe the AltGr-tilde bug on <https://xtermjs.org/> with MS Edge. Thanks!
