### ISSUE TITLE
[macOS]environment variables in second shell are different from main shell

### ISSUE THREAD

**Issue by YanzheL** [GitSquared/edex-ui#472]
*The following (lightweight) template is made to avoid recurring questions in new bug reports and to facilitate problem diagnosis. You are free to ignore it, but filling it correctly will help a lot. Either way, thanks for taking the time to write a report.
You can delete this introduction message if you want to.*

## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.0-pre`)
 - [x] `latest` (latest release, currently `v2.1.0`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---
I use the latest version (2.1.0) for macOS from prebuild dmg package.
All settings except theme and cwd are default.
I changed theme to iron-notype and cwd to current user's home directory.

I found that environment variables in second (or third, etc) shell are different from main shell. And main shell contains correct environment variables.
More precisely, the outputs of `env` command are different in second shell, which are supposed to be same.

I tested it on ubuntu 18.04 LTS and started it from source on master branch, every thing works fine, `env` outputs are same.

This bug prevents me from running some commands in second shell because they are not in PATH variable.

**Comment by YanzheL** [comment]
Directly run from source on macOS uses:
```shell
npm run install-linux
npm start
```
solves this issue.


But if I build target from source on macOS, and run eDEX-UI.app, this issue still exist.
```shell
npm install
npm run build-darwin
```

**Comment by GitSquared** [comment]
Found & fixed on `master`. Thanks for reporting this!
