### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by xelarate86** [GitSquared/edex-ui#478]
## Technical information
**Using version:**
 - [X] `master` (running from GitHub-published source code, currently `v2.2.0-pre`)
 - [ ] `latest` (latest release, currently `v2.1.0`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [X] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [X] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

Not so much an issue as it is an observation - but I occasionally get rather high RAM usage, nearly 2GB. I'm not quite sure how to recreate the issue, but eDEX will often be at the top of my htop. I understand it's a fancy terminal but is it possible to be optimized further, or is this just a necessary side effect of using Electron?

**Comment by xelarate86** [comment]
Upon rebuilding it's down to a fluctuation between ~200 and ~400 MB. Probably just a transient issue I created by messing up somewhere along the way, or something with my environment. Testing on another system too and no issues.

**Comment by GitSquared** [comment]
Glad to hear that. Thanks for confirming this.
