### ISSUE TITLE
How do I make 'allow incoming connections' alert go away? (mac)

### ISSUE THREAD

**Issue by GrapeSodas** [GitSquared/edex-ui#480]
I allow the app to make incoming connections every time I start it up and i still get the alert every time. I even made sure to add it into my firewall settings. Is there an issue with the signature?

**Comment by GitSquared** [comment]
I've never seen this alert. What version of macOS are you using? Could you get me a screenshot?

**Comment by GrapeSodas** [comment]
![Screen Shot 2019-04-07 at 2 39 04 PM](https://user-images.githubusercontent.com/34319104/55690200-0c90ae00-5943-11e9-9074-160ed9b60255.jpg)

**Comment by GitSquared** [comment]
If you haven't tried it yet, try manually adding eDEX in the macOS firewall settings.

eDEX builds are unsigned ([here's why](https://squared.codebrew.fr/posts/code-signing/)), which as you've pointed out might be triggering this behavior from the OS, although that's the first time I've heard about it.

**Comment by GrapeSodas** [comment]
Yeah I've tried manually adding the app into my firewall settings and the message still pops up. I suppose it's not that big of a deal, it's just a little annoying.

**Comment by GitSquared** [comment]
I'm sorry that you have to deal with this. Unfortunately there's little I can do... Perhaps someday I'll invest in a developer certificate, which is clearly what Apple are pushing me to do - they are not the only ones, this kind of questionable practices have become industry standard for platform providers, sadly.

Thanks for reporting this.
