### ISSUE TITLE
Make terminal colored again!

### ISSUE THREAD

**Issue by jennasisis** [GitSquared/edex-ui#483]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [x] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it **(Possibly, I haven't messed with classes yet, and I haven't entirely nailed down the concept of modules yet.)**

---

Similar to #463 but not really? I was snooping through the code to see how ya dun it and I noticed, in src/classes/terminal.class.js, you've grayscaled the colors. I removed the grayscale method and was still muted a little bit, so I messed with the number in the mix method. Changed it to 1 and everything was black and white; no in-between like you had before. I changed it to 0.7 and it was slightly more muted than 0.3.. the default.
This sparked an idea.
Why not make that grayscale-ness customizable to the user? And I don't just mean in themes and such, I mean like as a setting or something.

![](https://i.imgur.com/RzgpG9i.png)
> A concept for the setting itself

![](https://i.imgur.com/o9Eh1LK.png)
> .grayscale() removed, setting at 0% colorified, actual value in code is `1`.

![](https://i.imgur.com/vMYWT7A.png)
> .grayscale() removed, setting at 40% colorified, actual value in code is `0.6`

... and so on and so forth.

Lmk what you think

**Comment by Xeddius** [comment]
This could definitely be useful for more colorful themes in the future, perhaps options to dynamically color themes can be added as well? (Like a slow color change/fade!) different colors per module would also be neat.

**Comment by GitSquared** [comment]
So far every visual setting and tweak is handled by themes (except font size, because it's something that you want to be able to change on-the-fly); I don't want to break that rule so eventual terminal color filters would have to be defined in a theme file.
I'm thinking about how we could use JSON strings to represent a full chain of [color](https://www.npmjs.com/package/color) functions, for even more awesome customization.

And @Xeddius - different colors per module will have to wait for #334.

**Comment by jennasisis** [comment]
That would be interesting, what would that look like?

**Comment by GitSquared** [comment]
@jennasisis Something like this:

```json
{
  "terminal":
    "colorFilter": [
      "saturate(120)",
      "hue(340)",
      "mix(0.3)"
    ],
    "colorFilterMixTarget": "#00FF00"
  }
}
```

**Comment by jennasisis** [comment]
Oh that’s interesting, I’ll see if I can work that in and open a PR when I have the time.

**Comment by GitSquared** [comment]
Implemented. I'm going to write some docs on this and push it to `master`.

Here are some examples, shown side-by-side with another terminal so you spot the color difference:

```json
        "colorFilter": [
            "negate()"
        ]
```
![image](https://user-images.githubusercontent.com/24496417/56910594-3ef97b00-6aab-11e9-8277-c8742310427d.png)

---

```json
        "colorFilter": [
            "rotate(180)",
            "saturate(0.5)",
            "mix(0.7)"
        ]
```
![image](https://user-images.githubusercontent.com/24496417/56911303-ecb95980-6aac-11e9-92e8-f5ea57253e8e.png)

---

```json
        "colorFilter": [
            "rotate(-40)",
            "desaturate(0.2)",
            "mix(0.4)"
        ]
```
![image](https://user-images.githubusercontent.com/24496417/56910878-dbbc1880-6aab-11e9-990a-60824f6097cf.png)

--- 

This is surely the most gadget feature I've ever made, lol. But it's 20 lines of code and you can probably get something good out of it, so why not?

I made all the necessary stuff to prevent abusing this for code injection, too. That's actually 99% of the commit, so I thought I'd mention it.

I'm going to include a new `tron-colorfilter` showcase theme, and I'll link the docs here once I'll be done with that.
