### ISSUE TITLE
File Browser fails when cd into home directory.

### ISSUE THREAD

**Issue by Xeddius** [GitSquared/edex-ui#486]
When I cd into my home folder the file browser stops functioning, it does not resume function even if I cd back into the start directory. 
![Error](https://user-images.githubusercontent.com/6382895/56523299-4e118380-6515-11e9-9f07-ad84b23a8142.png)
Attempted with a fresh install, cleared all configs under .config, still no luck. Launched directly with ./ and double-clicked, same result.

The issue doesn't occur when launching eDEX-UI as root, however that is obviously not an optimal solution.

**Comment by GitSquared** [comment]
Does any error pops out in the dev tools console (`Ctrl+Shift+I`)? Or perhaps in eDEX's `stdio` output, which you can see by starting it from a terminal?

**Comment by Xeddius** [comment]
No errors popped up in stdio output, but I noticed that when I tried it today (I've rebooted since the last time I used eDEX) it works now. Kind of weird. I'll keep on eye on it and if it starts doing this again I'll check the dev tools console.

**Comment by GitSquared** [comment]
Weird indeed. Maybe some kind of AppImage sandboxing related issue..?

@kamata1729 I noticed your reaction; did this happen to you as well?

**Comment by kamata1729** [comment]
Maybe this problem will  be solved by changing the path of setting file, but more simply, I upgraded edex-ui to v2.1.0 (from this page https://github.com/GitSquared/edex-ui/releases/tag/v2.1.0 ) and it does correctly work!
![スクリーンショット 2019-04-29 19 54 54](https://user-images.githubusercontent.com/26928144/56891795-9d792600-6ab8-11e9-82db-9580c2501172.png)

**Comment by GitSquared** [comment]
@kamata1729 OK, thanks for the info.

@Xeddius I'm going to consider this closed, as always reopen if it ever happens again.
