### ISSUE TITLE
On-screen keyboard toggle

### ISSUE THREAD

**Issue by dackdel** [GitSquared/edex-ui#487]
*The following (lightweight) template is made to better understand your view and what you think about your request. You are free to ignore it, but are encouraged to complete it.
We've seen lots of feature requests on this project, some were perhaps [too ambitious](https://github.com/GitSquared/edex-ui/issues/456) and some were [literally implemented overnight](https://github.com/GitSquared/edex-ui/issues/260). Don't be afraid to propose your ideas either way, we'll look at every one of them ;)
You can delete this introduction message if you want to.*

**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [x] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

*(Write your idea or feature request here)*

Since I have a non-touch screen laptop the on-screen keyboard feels redundant. Allow me a way to toggle that to turn it on/off. And possibly put something else in that space.

**Comment by GitSquared** [comment]
Soon™ you'll be able to move, remove, and add modules on eDEX's screen - that includes the keyboard. This feature is tracked on #334.

In the meantime, you can look into the `tron-notype` included theme; it demonstrates how using the existing theming feature you can hide the keyboard and enlarge the file browser.
