### ISSUE TITLE
Separate frontend to run backend on remote server

### ISSUE THREAD

**Issue by Egoscio-zz** [GitSquared/edex-ui#488]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [X] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [X] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Since this project is made with electron and is using web technologies, shouldn't it be pretty easy to have the frontend be hosted as a webapp and have the backend run on a remote computer?

I'd love to be able to run the main process on my server at home, then serve a frontend on the web that can be accessed from an iPad, for example.

An example of this in a different context is how [coder](https://github.com/cdr/code-server) allows you to host the backend of [vscode](https://github.com/Microsoft/vscode) on a server and then access the frontend from anywhere.

**Comment by GitSquared** [comment]
While eDEX's interface is indeed made with web technologies, it heavily relies on the integration with Node.js inside the renderer process allowed by Electron. That's not necessarily the "good practice" way, and completion of #334 will probably change that, but in the meantime separating the UI and the backend is a lot trickier than it sounds.

That being said, you aren't the first one to suggest this and I've been thinking about the possibility of what I call "remote monitoring" for a while now.

It might not allow you to access servers from your iPad just yet, but the current plans for this feature would allow you to use an `ssh` command to connect to a remote server - on which you would previously install an eDEX server component - and your UI would automatically shift to displaying the remote server's system information, filesystem, networking and clock.

If possible I would also like this system to be tab-specific, so you can just hit `Ctrl+Tab` and switch between monitoring and controlling your system and a remote endpoint in a matter of milliseconds.
Regarding security, public key cryptography would be used to authenticate and encrypt data in transit between server & client components. While the server component will run as `root`, it would use `setuid` to lock monitoring processes to the connected user's scope - to prevent a possible security breach originating from a rogue eDEX module.

While the actual code for this is not written yet, you can track the progress of the server component at the [edex-ui-server repository](https://github.com/GitSquared/edex-ui-server).

Now, this is not exactly what you were asking for, and I'm honestly not sure if I'll ever get around to porting eDEX to a webapp remote. But it's the closest thing I have in the works right now, and I thought I'd share with you how it's going. I'll pin the issue so the wall of text can be seen easily by anybody interested.

I'd be glad to hear from you if you have any remarks, suggestions, or feedback about this way of doing things. As always thanks for taking the time to fill in an issue.
