### ISSUE TITLE
Home-brew(package manager)

### ISSUE THREAD

**Issue by LEON0121** [GitSquared/edex-ui#490]
I installed home-brew in my pc.
It applied edex-ui's main bash.
but not applied 2~5 bash.
why is it? what should I do?

(my English is not good. sorry :D)

**Comment by GitSquared** [comment]
This is a known bug in the latest version - see #472.

The fix will be included in the next version (`v2.2.0`), you'll have to wait for that I'm afraid. Should be coming out soon.
