### ISSUE TITLE
.bash_profile is not loaded on macOS

### ISSUE THREAD

**Issue by jd-lara** [GitSquared/edex-ui#492]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.0`)
 - [ ] `vx.x.x` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

After replacing v0.2.1 with v0.2.2 the interface won't start and when hitting close I get an error 

![image](https://user-images.githubusercontent.com/16385323/56925046-4ad14700-6a83-11e9-8beb-b784a7281e13.png)

**Comment by GitSquared** [comment]
@jd-lara Does any part of the interface loads up or are you faced with a black screen?

**Comment by jd-lara** [comment]
Nothing loads

**Comment by GitSquared** [comment]
Sh*t. Do you know how to launch the app from a terminal? I'd need to check the `stdio` output.

**Comment by jd-lara** [comment]
```bash
jdlara@switch-workstn9:/Applications/eDEX-UI.app/Contents/MacOS$ ./eDEX-UI 
▶  start     Starting eDEX-UI v2.2.0
ℹ  info      With Node 10.11.0 and Electron 4.1.4
ℹ  info      Renderer is Chrome 69.0.3497.128
✖  fatal     Error: Another instance of eDEX is already running. Cannot proceed.
jdlara@switch-workstn9:/Applications/eDEX-UI.app/Contents/MacOS$ ./eDEX-UI 
▶  start     Starting eDEX-UI v2.2.0
ℹ  info      With Node 10.11.0 and Electron 4.1.4
ℹ  info      Renderer is Chrome 69.0.3497.128
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /Users/jdlara/Library/Application Support/eDEX-UI
☐  pending   Loading settings file...
✔  success   Settings loaded!
(node:15877) UnhandledPromiseRejectionWarning: Error: spawn bash -l ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:15877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15877) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
GVA info: Successfully connected to the Intel plugin, offline Gen9 
```

**Comment by GitSquared** [comment]
Great, thanks a lot. This line is interesting:
```
Error: spawn bash -l ENOENT
```

I'm assuming your eDEX config is set to use `bash`? Could you try and point that to the full path?
 (most likely `/bin/bash`, although I'm not sure about the directory structure under macOS)

You can find the config in `~/Library/Application Support/eDEX-UI`.

**Comment by jd-lara** [comment]
Same behavior here is my config file 

```JSON
{
    "shell": "/bin/bash -l",
    "cwd": "/Users/jdlara",
    "env": "/Users/jdlara/.bash_profile",
    "keyboard": "en-US",
    "theme": "tron-notype",
    "termFontSize": 22,
    "audio": false,
    "pingAddr": "1.1.1.1",
    "port": 3000,
    "monitor": 0,
    "nointro": false,
    "iface": "en0",
    "allowWindowed": false,
    "excludeSelfFromToplist": true,
    "hideDotfiles": false,
    "experimentalGlobeFeatures": false,
    "experimentalFeatures": false
}
```

**Comment by GitSquared** [comment]
Could you try and remove the `env` key in your config? The syntax you're using there is not supported and it might be causing some troubles

**Comment by jd-lara** [comment]
I just removed the whole `~/Library/Application Support/eDEX-UI` folder and it works now. It seems that the configuration won't load. How can I load my `.bash_profile`?

**Comment by GitSquared** [comment]
Ok, very good news, it's just a config mishap :sweat_smile:

*Normally,* with the changes in this new release, your `.bash_profile` config should be automatically imported into eDEX without any extra steps.

Is this not working?

**Comment by jd-lara** [comment]
No, nothing from my .bash_profile is loading. This is my new settings

```JSON
{
    "shell": "bash",
    "cwd": "/Users/jdlara",
    "keyboard": "en-US",
    "theme": "tron-notype",
    "termFontSize": 22,
    "audio": false,
    "disableFeedbackAudio": false,
    "pingAddr": "1.1.1.1",
    "port": 3000,
    "monitor": 0,
    "nointro": false,
    "nocursor": false,
    "iface": "en0",
    "allowWindowed": false,
    "excludeSelfFromToplist": false,
    "hideDotfiles": false,
    "experimentalGlobeFeatures": false,
    "experimentalFeatures": false
}
```

**Comment by GitSquared** [comment]
@jd-lara This is not a definitive fix, but setting your `shell` key in the config to something like `bash --login -c 'source ~/.bash_profile'` could do the trick.

**Comment by jd-lara** [comment]
After making the change then the problem of not loading happens again. Even if I set it to "bash -l"

**Comment by GitSquared** [comment]
Same error in `stdio`?

**Comment by jd-lara** [comment]
Yes, same everything. No display and later on to quit I get the error.

**Comment by GitSquared** [comment]
Weird. I'll do some testing myself tomorrow, get a patch release out if there's something to fix.

Could you send me your config with the fix I proposed, just to make sure?

**Comment by jd-lara** [comment]
Tried these 2 options 


```JSON
{
    "shell": "bash --login -c 'source ~/.bash_profile'",
    "cwd": "/Users/jdlara",
    "keyboard": "en-US",
    "theme": "tron-notype",
    "termFontSize": 22,
    "audio": false,
    "disableFeedbackAudio": false,
    "pingAddr": "1.1.1.1",
    "port": 3000,
    "monitor": 0,
    "nointro": false,
    "nocursor": false,
    "iface": "en0",
    "allowWindowed": false,
    "excludeSelfFromToplist": false,
    "hideDotfiles": false,
    "experimentalGlobeFeatures": false,
    "experimentalFeatures": false
}
```

```JSON
{
    "shell": "bash -l",
    "cwd": "/Users/jdlara",
    "keyboard": "en-US",
    "theme": "tron-notype",
    "termFontSize": 22,
    "audio": false,
    "disableFeedbackAudio": false,
    "pingAddr": "1.1.1.1",
    "port": 3000,
    "monitor": 0,
    "nointro": false,
    "nocursor": false,
    "iface": "en0",
    "allowWindowed": false,
    "excludeSelfFromToplist": false,
    "hideDotfiles": false,
    "experimentalGlobeFeatures": false,
    "experimentalFeatures": false
}
```

**Comment by GitSquared** [comment]
All right. Thanks for the report, will look into it first thing tomorrow.

**Comment by GitSquared** [comment]
![image](https://user-images.githubusercontent.com/24496417/56950437-c7bcf900-6b35-11e9-8de7-017f76591ecd.png)

@jd-lara I got automatic env loading to work as expected and fixed the error you were getting. eDEX automatically appends the `--login` option to the shell command and the correct env is set.

Will release a patch for this, `v2.2.1`.

**Comment by GitSquared** [comment]
[Patch is up.](https://github.com/GitSquared/edex-ui/releases/tag/v2.2.1) Thanks for your help.

**Comment by jd-lara** [comment]
Thanks, it works. I have one more question on loading the `.bash_profile`. I have the following lines in my profile to show my current branch in the terminal 

```Bash
# enables auto completion of git commands
if [ -f $(brew --prefix)/etc/bash_completion ]; then
  source $(brew --prefix)/etc/bash_completion
fi
 
# adds branch status information in the terminal path
source $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
#PS1="\h:\W \u\$(__git_ps1 \" (%s)\")\$ "
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$(__git_ps1 \"(%s)\")\$ "
```

So, my terminal looks like this 

![image](https://user-images.githubusercontent.com/16385323/56980082-4020bb80-6b30-11e9-80fb-7ea4e9c1c216.png)


But this setting is not being picked up by eDEX

<img width="1696" alt="image" src="https://user-images.githubusercontent.com/16385323/56980125-62b2d480-6b30-11e9-913e-5d1f1c7c6bd0.png">

**Comment by GitSquared** [comment]
In your second screenshot, it doesn't look like you are in a Git directory...?

**Comment by jd-lara** [comment]
It was an error in the `.bash_profile` sorry.

**Comment by GitSquared** [comment]
OK, np.
