### ISSUE TITLE
Git commands in spanish 

### ISSUE THREAD

**Issue by jd-lara** [GitSquared/edex-ui#493]
*The following (lightweight) template is made to avoid recurring questions in new bug reports and to facilitate problem diagnosis. You are free to ignore it, but filling it correctly will help a lot. Either way, thanks for taking the time to write a report.
You can delete this introduction message if you want to.*

## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.3.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.1`)
 - [X] `v2.2.1` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [X] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

For some reason, eDEX is showing my git in Spanish and my terminal is in English 

<img width="813" alt="image" src="https://user-images.githubusercontent.com/16385323/56980483-58450a80-6b31-11e9-8341-eb290bef41af.png">

![image](https://user-images.githubusercontent.com/16385323/56980527-714dbb80-6b31-11e9-9394-08d4c119beaa.png)

**Comment by GitSquared** [comment]
Is your system language set to Spanish?
Maybe setting `$LANG` to `en_US.UTF-8` would fix it.

**Comment by jd-lara** [comment]
I have 2 languages in my system, but I am not sure why is picking this one up by default now.

**Comment by GitSquared** [comment]
Some terminal emulators override the `LANG` env var to set the terminal to English.
eDEX doesn't do that, for various reasons.

In your `settings.json` config, you can do this:
```json
{
  (...)
    "env": {
        "LANG": "en_US.UTF-8"
    },
  (...)
}
```

That would override it.

**Comment by jd-lara** [comment]
Thanks that fixed it
