### ISSUE TITLE
On Win10, the network has been in the offline state, how to solve it?

### ISSUE THREAD

**Issue by yanzhao77** [GitSquared/edex-ui#495]
On Win10, the network has been in the offline state, how to solve it?
![微信图片_20190504222403](https://user-images.githubusercontent.com/43581117/57180471-6e4d2500-6ebb-11e9-9466-61923d0d479f.png)

**Comment by GitSquared** [comment]
Open Settings (`Ctrl+Shift+S`) and change `iface` to the correct interface with the dropdown menu.

Should be something like `Wi-Fi` or `Ethernet`, currently you have a VirtualBox "fake" network selected - this happens sometimes when VB is installed.

When you're done hit "Save to Disk" and "Reload UI".

**Comment by yanzhao77** [comment]
Thank you. That's the problem. I have an idea to put this UI into software so that it can really implement scientific and technological software. I hope I can get your authorization. My email is 756624050@qq.com. I hope to discuss this matter with you in detail.
