### ISSUE TITLE
Cannot work if settings shell is "fish"

### ISSUE THREAD

**Issue by bennettyuan18** [GitSquared/edex-ui#496]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.1`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

I change my shell settings with `fish`, and restart app.
The result is app cannot launch window (app is opened in dock).
I back to `bash` shell, everything is fine.

**Comment by GitSquared** [comment]
@bennettyuan18 Could you start a terminal and launch eDEX from there?

It should give more information on why it's failing to open a window.

**Comment by yozlet** [comment]
I'm having the same issue. However, when running from a terminal, eDEX starts fine and shows my fish prompt in its terminal. No extra messages logged when compared with `bash` start.

I tried starting the app using the icon, and kept an eye on the MacOS Console app. Bunch of different messages spewed, but the only difference I noticed was this message ~30s after start, when running the app with `fish` as the shell:

```
default	13:07:33.685427 -0700	eDEX-UI	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 483 vs 1381, 513, <private>
```

On a later attempt, got the same message ~25s after boot, different numbers:

```
default	13:16:15.524753 -0700	eDEX-UI	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 506 vs 1404, 512, <private>
```

**Comment by GitSquared** [comment]
Confirmed this behavior. One temporary solution is to put the full path in your settings file (`/usr/bin/local/fish` if you've installed fish from homebrew).

I'm working on a fix.

**Comment by GitSquared** [comment]
![image](https://user-images.githubusercontent.com/24496417/58752035-5233a800-84a8-11e9-83ce-3e4a24eb4003.png)

eDEX will now resolves the shell path internally to prevent this bug.
Shipping in the next release.

**Comment by flightcubs** [comment]
> Confirmed this behavior. One temporary solution is to put the full path in your settings file (`/usr/bin/local/fish` if you've installed fish from homebrew).
> 

Having the same issue, thanks for the workaround. It didn't work for me with that path, but this one worked:`/usr/local/bin/fish`
