### ISSUE TITLE
Please ask the blogger! How do you map terminal output to the web

### ISSUE THREAD

**Issue by JackMing0** [GitSquared/edex-ui#497]
*Before you write your question, make sure the answer you're looking for isn't in the [Q&A](https://github.com/GitSquared/edex-ui#qa) or the [wiki](https://github.com/GitSquared/edex-ui/wiki).*

**Comment by GitSquared** [comment]
@JackMing0 I'm sorry, I don't understand the question.

**Comment by JackMing0** [comment]
Hello, blogger! I read the project you wrote! I'm very interested!
Want to consult a blogger! How did you do it! Below the implementation of this pseudo-terminal function!
![QQ20190507-080502](https://user-images.githubusercontent.com/37831370/57262524-0b1be800-709f-11e9-90af-d550fd20b92e.png)

**Comment by JackMing0** [comment]
Excuse me, the blogger has written about the eDEX project!
Specific implementation steps of the article

**Comment by Chromecube** [comment]
Well, you are currently in the GitHub repository of the project. Just have a look at the code to see how it's done, e.g. in the [UI script](https://github.com/GitSquared/edex-ui/blob/master/src/_renderer.js#L425) or in the [Terminal class](https://github.com/GitSquared/edex-ui/blob/master/src/classes/terminal.class.js).
