### ISSUE TITLE
GUI Apps

### ISSUE THREAD

**Issue by oksoft-ondra** [GitSquared/edex-ui#499]
I like eDEX-UI, but i want to browse for example web here. Can I open Xorg windows in tabs or some kind of opening gui apps. It can be for linux only for now. Thank you.

**Comment by GitSquared** [comment]
I'm sorry but eDEX is not a WM *(Windows Manager)* and does not intend to be one.
I know many people like you would love to see something like this, but I'm just not ready to be that guy who made a whole desktop in Javascript. It's not a clean way of doing things and that's an understatement.

If you're looking to make yourself a Linux desktop that ressembles eDEX, you can do wonders with `i3` and `Conky`.

That said, a command line is a ***very*** powerful tool; and even if it might not fully replace GUIs, there aren't many things that you can't do in a CLI.
For browsing the web, I'd personnally recommend `browsh` or `links`.
