### ISSUE TITLE
Start new tabs with a different shell

### ISSUE THREAD

**Issue by aedelsten** [GitSquared/edex-ui#500]
Add ability to right-click on a terminal tab and select different shells to run (idea totally stolen from the new MS Windows Console). Could list the shells in the config file, use the first entry as the default but allow user to choose and then launch.

See: https://youtu.be/8gw0rXPMMPE?t=13

**Perceived idea awesomeness**
- [ ] Would be super cool.

**Perceived idea difficulty**
- [ ] Shouldn't be too hard to make.

**Comment by GitSquared** [comment]
This is a good idea indeed. However since eDEX targets touch surfaces we'd need to figure out some other user action instead of "right click". Thinking on it.

**Comment by clragon** [comment]
@GitSquared the touch translation of right clicking usually is long press

**Comment by GitSquared** [comment]
@clragon Long press sounds nice, I was thinking about double-finger tap but that's harder to implement and use.

After this trigger, perhaps some kind of pop-up could appear with a line prompt to input the desired shell name/path.

@Xeddius hey, since you've been doing all those crazy concept screenshots lately, could you give us something here? if you have the time to spare, of course.

On a slightly related note I need to do a big error handling overhaul with these kind of input-linked features coming in. Some work to be done.

**Comment by Hellzbellz123** [comment]
why not add a settings tab where you can set the 4 different windows shells

**Comment by Hellzbellz123** [comment]
like a simple skinned file broswer to keep immersion to point to the correct  .exe file?

**Comment by clragon** [comment]
@Hellzbellz123 that doesn't sound very expandable if we ever get more than 4 tabs

**Comment by Hellzbellz123** [comment]
i mean most people only use cmd anyway, but it would be easily expandable by just copy pasting the code and adding in tab 5,6,7 etc etc etc

**Comment by Hellzbellz123** [comment]
i mean most people only use cmd anyway, but it would be easily expandable by just copy pasting the code and adding in tab 5,6,7 etc etc etc

**Comment by clragon** [comment]
yeah that sounds like a hard coded way to do this, I'd rather have a pop up that lets you select it, thats way more adaptable to whatever situation you need a terminal in

**Comment by Xeddius** [comment]
@GitSquared I think I can come up with something, some devices allow right clicking by double tapping, could be as simple as setting up right click on the terminal area, this would also make it compatible with non-touch interfaces as well.

**Comment by Xeddius** [comment]
@aedelsten I'm trying to come up with some concept art, but I'm not sure what you mean when you refer to the shell, the video shows different linux distributions as options. Do you mean shells like Ash, Bash, Dash, zsh, tcsh? Or just custom named tabs with their own different shell?

**Comment by GitSquared** [comment]
@Xeddius I believe he meant different shell programs indeed. Zsh, fish, bash, and the like.

**Comment by Xeddius** [comment]
Hmm, while I can see the appeal, for the time being one can type the new shell name to start it. Though an option to have different tabs run a different shell in settings could probably be easily added.
