### ISSUE TITLE
Unecessary filesystem refresh

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#501]
## Technical information
**Using version:**
 - [x] `latest` (latest release, currently `v2.2.1`)

**Running on:**
 - [x] Windows

**How comfortable you are with your system and/or IT in general:**
 - [x] My machine is fully under my control, tell me what you need

---

The filesystem refreshes even when detached.
This seems to occur whenever the main terminal is activated, either at the start or when switching back to it from another tab. It also switches the folder the filesystem resides in to the one the main terminal is in.
Since the terminal is detached, I'd assume it wouldnt show this behaviour but rather not react to switching tabs or initializing main, just being used as a filebrowser normally.

**Comment by GitSquared** [comment]
Reproduced. Will look into it.

**Comment by GitSquared** [comment]
Fixed. Some code was ran before the noTracking mode being applied to the fsDisp, and resulted in an extra listener still being present on the main shell tab.

Thanks for spotting this!
