### ISSUE TITLE
List view for filebrowser

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#502]
**Perceived idea awesomeness**
- [x] I'm not sure a lot of people would use it, but I'd love to have it.

**Perceived idea difficulty**
- [x] Shouldn't be too hard to make.

---

It would be pretty neat if we could have a windows-explorer like information list view for the file browser.
Here's what it looks like;
![Screenshot_2](https://user-images.githubusercontent.com/11785085/57544512-d38b9500-7357-11e9-84e5-96d204a7f542.png)

**Comment by GitSquared** [comment]
👍 Will consider this as a new feature

**Comment by GitSquared** [comment]
![image](https://user-images.githubusercontent.com/24496417/57573976-12414e00-7431-11e9-87b8-155687c2f959.png)

There you go. The code already had access to some more advanced file stats and the filesystem module has a pretty recent css implementation that uses grid and flexbox, so it was quite easy to do.

Keyboard shortcut to switch between the original "grid" and the list view is `Ctrl+Shift+L`. There's also the `fsListView` setting, which defaults to false.

Shipping in next release :+1:

**Comment by GitSquared** [comment]
(Possible future improvements: Reduce/optimize time string, show file permissions/owner)

**Comment by clragon** [comment]
that's so cool!

only thing I'd still would wanna see is sort by type instead of just name. 

_I have everything sorted by type, sorting by type ftw_

**Comment by GitSquared** [comment]
Will look into it.

**Comment by GitSquared** [comment]
@clragon Just went over this thread again as I'm polishing this feature a bit; it seems that the module already sorts filesystem entries by type (folders then files then symlinks etc), is that not what you're expecting?

**Comment by clragon** [comment]
@GitSquared 
does it also sort by _file_ type? because thats what I meant.

**Comment by GitSquared** [comment]
@clragon Oh right. Sorry for the misunderstanding.
