### ISSUE TITLE
TypeError: Cannot read property 'getExtension' of null: Uncaught TypeError: Cannot read property 'getExtension' of null  on mac os x 

### ISSUE THREAD

**Issue by abrarjaved644** [GitSquared/edex-ui#504]
I saw issue #217 but that's for Linux and I can't understand how to fix it I try everything but I can't  get the globe to show up
![Screen Shot 2019-05-11 at 11 31 24 PM](https://user-images.githubusercontent.com/41078856/57574680-16c43180-7446-11e9-80b5-d73a5a832091.png)

**Comment by GitSquared** [comment]
@abrarjaved644 Can you give me the model and year of your laptop? (e.g MacBook Air 2011)

This issue is related to some graphics API support and I can't do much about it. While it is fixed for most users, you might still be experiencing this if your hardware is a little old.

**Comment by abrarjaved644** [comment]
> @abrarjaved644 Can you give me the model and year of your laptop? (e.g MacBook Air 2011)
> 
> This issue is related to some graphics API support and I can't do much about it. While it is fixed for most users, you might still be experiencing this if your hardware is a little old.

15 inch mid-2009 MacBook Pro

**Comment by GitSquared** [comment]
Yeah, that sounds like an "age" issue then, I'm sorry.
I'll update you if our upstream overlords add more legacy support, but I doubt that it will happen.

**Comment by abrarjaved644** [comment]
> Yeah, that sounds like an "age" issue then, I'm sorry.
> I'll update you if our upstream overlords add more legacy support, but I doubt that it will happen.

ok thanks
