### ISSUE TITLE
Sound spam

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#516]
## Technical information
**Using version:**
 - `latest` (latest release, currently `v2.2.2`)

**Running on:**
 - Windows

**How comfortable you are with your system and/or IT in general:**
 - My machine is fully under my control, tell me what you need

---

When pressing ctrl or shift, the typing sound continues to stack up until another button is pressed.
I'd expect that buttons like these which are part of combos and don't do much of their own to actually not have an increasing sound the longer you press them.

**Comment by GitSquared** [comment]
@clragon Can't reproduce this. Tested on Linux and Windows, the sound effect only fires once. Are you pressing any other keys before this bug shows up?

**Comment by clragon** [comment]
@GitSquared no, no other buttons. I can boot it up and immediatly press one of them and it will stack up

**Comment by GitSquared** [comment]
@clragon Would you be able to record your screen while this happens? With Windows' sound output if possible?
I'm trying different things but I still can't reproduce this so far.

**Comment by clragon** [comment]
@GitSquared it seems not so.
either shadow play or edex-ui seem to have a big problem with the other part. shadowplay doesnt record edex at all and when opening the overlay, edex starts to flicker horribly

**Comment by GitSquared** [comment]
@clragon Okay, thanks for trying anyway.

**Comment by clragon** [comment]
@GitSquared 
so I got OBS and made a video for you. 
The Quality is horrendous though because I didn't configure OBS correctly, so sorry for that.
I think it shows the issue though.

https://www.youtube.com/watch?v=og1zlVCQ68E

**Comment by GitSquared** [comment]
@clragon Thanks for the video, really helpful. I think I know where this is coming from, I'll push a fix soon - sorry for the delay.

**Comment by clragon** [comment]
In the newest version, the issue seems to have returned for CTRL and ALT-GR?

**Comment by GitSquared** [comment]
@clragon Indeed, something got renamed and this broke. Fixing.
