### ISSUE TITLE
Version 2.0 of Linux appimage in 2.2.2 announcement 

### ISSUE THREAD

**Issue by forest-hermit** [GitSquared/edex-ui#535]
When I downloaded eDex Linux Appimage 64 bits here: [https://github.com/GitSquared/edex-ui/releases/tag/v2.2.2] I got 2.0 instead.

**Comment by GitSquared** [comment]
The AppImage published on GitHub releases is correct - I just checked.

eDEX releases do not have the version number in the filename (which is something I should probably change), so you might have accidentally used an older file that you previously downloaded, or perhaps you have a bad cache between you and GitHub.

I'd advise you to delete any AppImages you have and download the latest one again. This will not affect your configuration/settings.

**Comment by forest-hermit** [comment]
Correct, I downloaded it from another browser (the 64 bits version again) and now it worked. Maybe it was cache or a dumb day, because I was almost sure of delete that appimage before download the new one (and it wasn't integrated until now). Thanks for your awesome work!
