### ISSUE TITLE
double tap isn't working !!

### ISSUE THREAD

**Issue by Rajchowdhury420** [GitSquared/edex-ui#536]
*The following (lightweight) template is made to avoid recurring questions in new bug reports and to facilitate problem diagnosis. You are free to ignore it, but filling it correctly will help a lot. Either way, thanks for taking the time to write a report.
You can delete this introduction message if you want to.*

## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [x] I attended [Defcon](https://defcon.org/) last year

---

*(Write your report here)*

**Comment by Rajchowdhury420** [comment]
In Linux App Image doesn't run by double Clicking

**Comment by GitSquared** [comment]
@Rajchowdhury420 Have you set the executable flag correctly on the file?

Try opening a terminal, navigating to the AppImage's folder and running `chmod +x eDEX-UI.Linux.x86_64.AppImage`.
You should then be able to double-click it.
