### ISSUE TITLE
Last line broken in font size lower than 15

### ISSUE THREAD

**Issue by masivi** [GitSquared/edex-ui#542]
Technical information

Using version:

master

Running on:

    Linux

When font size is lower than 15, the last line of the terminal is not seen. With size font 14 it shows partialy.

[Font 12](https://ibb.co/zsvFrCG)

[Font 14](https://ibb.co/h1Qhr5K)

[Font 15](https://ibb.co/k4d021q)

**Comment by GitSquared** [comment]
I just pushed a commit that should fix this to `master`. Could you try it?

**Comment by masivi** [comment]
Confirmed!
Fixed!
Thank's!
