### ISSUE TITLE
Black screen when typing

### ISSUE THREAD

**Issue by arquadrado** [GitSquared/edex-ui#544]
*The following (lightweight) template is made to avoid recurring questions in new bug reports and to facilitate problem diagnosis. You are free to ignore it, but filling it correctly will help a lot. Either way, thanks for taking the time to write a report.
You can delete this introduction message if you want to.*

## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

I downloaded the 64bit linux version and run it only to get my screen black as soon as I start typing on the terminal. Tried several times. The issue seems to happen when I use the physical keyboard instead of the digital one. It's unusable for me, unfortunately.

**Comment by GitSquared** [comment]
@arquadrado Could you share your system specs, especially CPU and dedicated GPU if any, and Linux distro+version?

A screenshot of the "black screen" or a video would also be really helpful, if you can spare the time.

**Comment by postables** [comment]
I'm also getting this issue, here's the logs from `syslog` that happen right before I get the black screen:

```
 appimagekit-edex-ui.desktop[10155]: ●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
 appimagekit-edex-ui.desktop[10155]: ⬤  debug     Error: SyntaxError: Unexpected token < in JSON at position 0
 appimagekit-edex-ui.desktop[10155]: ●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
 appimagekit-edex-ui.desktop[10155]: ⬤  debug     Error: SyntaxError: Unexpected token < in JSON at position 0
 appimagekit-edex-ui.desktop[10155]: ●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
 appimagekit-edex-ui.desktop[10155]: ⬤  debug     Error: SyntaxError: Unexpected token < in JSON at position 0
 appimagekit-edex-ui.desktop[10155]: ●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
 appimagekit-edex-ui.desktop[10155]: ⬤  debug     Error: SyntaxError: Unexpected token < in JSON at position 0
 appimagekit-edex-ui.desktop[10155]: ●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
 appimagekit-edex-ui.desktop[10155]: ⬤  debug     Error: SyntaxError: Unexpected token < in JSON at position 0
 appimagekit-edex-ui.desktop[10155]: ●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
 appimagekit-edex-ui.desktop[10155]: ⬤  debug     Error: SyntaxError: Unexpected token < in JSON at position 0
 appimagekit-edex-ui.desktop[10155]: ●  note      LocationGlobe: Error parsing data from ipinfo.now.sh
 appimagekit-edex-ui.desktop[10155]: ⬤  debug     Error: SyntaxError: Unexpected token < in JSON at position 0
 kernel: [406306.076458] traps: Chrome_ChildIOT[10351] trap int3 ip:559120836f8b sp:7fd330692870 error:0 in edex-ui[55911ec47000+4bfb000]
 appimagekit-edex-ui.desktop[10155]: ✖  error     Lost connection to frontend
 appimagekit-edex-ui.desktop[10155]: …  watching  Waiting for frontend connection...
```

**Comment by GitSquared** [comment]
@postables Thanks.

```
kernel: [406306.076458] traps: Chrome_ChildIOT[10351] trap int3 ip:559120836f8b sp:7fd330692870 error:0 in edex-ui[55911ec47000+4bfb000]
```

This looks like a Chrome crash. Could you tell me your linux distro, DE/WM with version, and eDEX version?

**Comment by postables** [comment]
OS:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Pop!_OS 18.04 LTS"
```

DE/WM should be the latest version of the gnome3 fork [here](https://github.com/pop-os/gnome-desktop3)

eDEX version is 2.2.2

**Comment by GitSquared** [comment]
This should be fixed and/or mitigated by the recent Electron (and Chromium) upgrade that I pushed to master.

@postables @arquadrado Could one of you guys try to run the latest dev version¹ and tell me if you still experience the issue?

[1]: [Here's a fresh AppImage.](https://send.firefox.com/download/88ebcbb7386c6acb/#NH3NXFC3wjtA1tzEmdfIlQ)
