### ISSUE TITLE
Add a Repology badge to README

### ISSUE THREAD

**Issue by luzpaz** [GitSquared/edex-ui#547]
*The following (lightweight) template is made to better understand your view and what you think about your request. You are free to ignore it, but are encouraged to complete it.
We've seen lots of feature requests on this project, some were perhaps [too ambitious](https://github.com/GitSquared/edex-ui/issues/456) and some were [literally implemented overnight](https://github.com/GitSquared/edex-ui/issues/260). Don't be afraid to propose your ideas either way, we'll look at every one of them ;)
You can delete this introduction message if you want to.*

**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [X] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [X] Like, *I* could do it.

---

Add a [repology badge](https://repology.org/project/edex-ui/badges) for edex-ui to show it's penetration in to the package ecosystem.

**Comment by GitSquared** [comment]
Interesting website. I won't add the badge itself, but I'll link it in improved download instructions.

Thanks for sharing.
