### ISSUE TITLE
Using Color Filter Broke Other Shell

### ISSUE THREAD

**Issue by opariffazman** [GitSquared/edex-ui#566]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v2.2.3-pre`)
 - [X] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [X] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

When using color filters, opening new tabbed shell will result in a Uncaught Type Error as below:-

![Error](https://user-images.githubusercontent.com/10364153/63094961-7f1e3400-bf9c-11e9-8ff8-49026cdc373b.png)
.

**Comment by GitSquared** [comment]
Thanks for the report. Fix will ship in next release, and is already available on the `master` branch.
