### ISSUE TITLE
Not loading after reboot

### ISSUE THREAD

**Issue by Destructor1702** [GitSquared/edex-ui#574]
Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [x] I attended [Defcon](https://defcon.org/) last year

---

*(Write your report here)*
It was working fine, just had a weird glitch when i was on ~ folder it keept reloading the file explorer widget (probably not related)

then I restarted my pc and couldn't get it to work.

Console log:

```
root@Diego ~/Downloads# ./eDEX-UI.Linux.x86_64.AppImage

(edex-ui:4356): Gtk-WARNING **: 20:06:09.041: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(edex-ui:4356): Gtk-WARNING **: 20:06:09.041: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(edex-ui:4356): Gtk-WARNING **: 20:06:09.041: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
▶  start     Starting eDEX-UI v2.2.2
ℹ  info      With Node 10.11.0 and Electron 4.2.0
ℹ  info      Renderer is Chrome 69.0.3497.128
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /root/.config/eDEX-UI
☐  pending   Loading settings file...
✔  success   Settings loaded!
(node:4356) UnhandledPromiseRejectionWarning: Error: Configured cwd path does not exist.
    at App.app.on (/tmp/.mount_eDEX-UxjTtmn/resources/app.asar/_boot.js:1:3910)
    at App.emit (events.js:187:15)
(node:4356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

***manual interrupt

```
^C✖  fatal     TypeError: Cannot read property 'close' of undefined 
    at App.app.on (/tmp/.mount_eDEX-UxjTtmn/resources/app.asar/_boot.js:1:6465)
    at App.emit (events.js:182:13)
root@Diego ~/Downloads#
```

**Comment by GitSquared** [comment]
`Error: Configured cwd path does not exist.`
Did you change some settings before you exited eDEX? Check that the `cwd` value in your [settings file](https://github.com/GitSquared/edex-ui/wiki/settings.json) is a valid path.

Also, it seems like you're running eDEX as root. You probably have reasons to do so, but I'd advise against it.

**Comment by Destructor1702** [comment]
```
{
    "shell": "fish",
    "cwd": "~/Downloads",
    "keyboard": "en-US",
    "theme": "tron-disrupted",
    "termFontSize": 15,
    "audio": true,
    "disableFeedbackAudio": false,
    "pingAddr": "1.1.1.1",
    "port": 3000,
    "monitor": 0,
    "nointro": false,
    "nocursor": false,
    "iface": "wlan0",
    "allowWindowed": false,
    "excludeThreadsFromToplist": true,
    "hideDotfiles": false,
    "fsListView": false,
    "experimentalGlobeFeatures": false,
    "experimentalFeatures": false
}

```

was working fine

**Comment by Destructor1702** [comment]
it has to do something with "~" on the path

and maybe relates to the other thing:
> , just had a weird glitch when i was on ~ folder it keept reloading the file explorer widget (probably not related)

**Comment by GitSquared** [comment]
I'm not sure that the `~` syntax is supported in the config file.
At what frequency did this reload glitch appear? Was anything being written to your home directory? The file explorer watches the directory it's in and reloads on changes.

**Comment by Destructor1702** [comment]
> I'm not sure that the `~` syntax is supported in the config file.

loks lik it was a problem with my system IO after all

> At what frequency did this reload glitch appear? Was anything being written to your home directory? The file explorer watches the directory it's in and reloads on changes.

it takes one loop and restarts but, it may be a script writing on a hidden file

**Comment by GitSquared** [comment]
> loks lik it was a problem with my system IO after all

OK. Issue closed then.

> it takes one loop and restarts but, it may be a script writing on a hidden file

That is most likely the case. `fuser` on Linux will help you trace what is writing to your home directory if you want to.
