### ISSUE TITLE
Support customizing keyboard shortcuts

### ISSUE THREAD

**Issue by ReagentX** [GitSquared/edex-ui#577]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [X] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [X] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Currently, all of the keyboard shortcuts are [hardcoded](https://github.com/GitSquared/edex-ui/blob/9263a6ccd79a98f66da3f8dca622be16735bbfd9/src/classes/keyboard.class.js#L327). I would like to rebind them without recompiling the app; so there should be some sort of preferences pane or config file where we can set these ourselves.

**Comment by GitSquared** [comment]
I'm actually working on implementing custom shortcuts for #564 - so far I didn't touch the old app shortcuts but it should be trivial to put them into the new shortcut system. Two birds one stone.
