### ISSUE TITLE
Support 12hr Time

### ISSUE THREAD

**Issue by ReagentX** [GitSquared/edex-ui#578]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [X] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [X] Like, *I* could do it.

---

Include 12hr time as well as the currently supported [24hr time](https://github.com/GitSquared/edex-ui/blob/c3e9490f0f1ab06723e6d96c7ca49f98f3825bb9/src/classes/clock.class.js).

**Comment by GitSquared** [comment]
![Screenshot_20190911_002444](https://user-images.githubusercontent.com/24496417/64654823-e69f9600-d419-11e9-83b8-156d89bd2a3b.png)

Done. Set `clockHours` to `12` in your [settings file](https://github.com/GitSquared/edex-ui/wiki/settings.json).
Only on `master` for now, of course. Will get bundled with all the other stuff in next release.
