### ISSUE TITLE
How to activate World View and Network Traffic?

### ISSUE THREAD

**Issue by DoggosGames** [GitSquared/edex-ui#584]
I've been using eDEX since 2 days ago and I've been having some trouble with the World View and Network Traffic.

I've made the network traffic thing work once (by setting my adapter from monitor mode to normal and then restarting the service), I also activated world view but now I don't know how to activate them.

How do I activate them/What services are they related to?

**Comment by GitSquared** [comment]
What version are you using? Latest release or `master`/`-git`?

**Comment by DoggosGames** [comment]
I downloaded it some days ago from the releases tab, so I'm guessing I'm using the latest version (2.2.2)

**Comment by GitSquared** [comment]
The network panel only needs to reach `1.1.1.1` (or an address specified in [settings](https://github.com/GitSquared/edex-ui/wiki/settings.json), `pingAddr`) for latency and WAN connectivity testing, and `freegeoip.app` (mostly for the world view) to locate remote IPs you are connected to.

Also, you need to specify the correct network interface in the settings if the autodetection doesn't work - you can see the current interface eDEX is using at the top of the network panel.

Like with most other apps monitor mode might provoke unexpected behavior and is not officially supported.

**Comment by DoggosGames** [comment]
Ok, I'm gonna check the settings file to see if somethings wrong, there.

Also, the default interface is wlan0, and It's correct as it's my network adapter that I use.

**Comment by GitSquared** [comment]
@DoggosGames Any firewalls or proxies in yoyr setup?

**Comment by DoggosGames** [comment]
for what I know I don't have any Proxies apart from Anonym8 (which I don't normally use) and there doesn't seem to be a firewall thats restricting access to eDEX

**Comment by DoggosGames** [comment]
@GitSquared also, one thing to notice is that World View and Network Traffic do work on some specific networks (such as my highschool's) which I think is interesting, maybe it could be because of the private IP class? (<- not probable)

**Comment by DoggosGames** [comment]
@GitSquared yes, I was talking about Anonym8. I'll try to boot into a live ISO of Ubuntu when I have some time. I'm running a Kali on my old laptop (I think it was i368, basically, 32 bit architecture).

Also, if Anonym8 really did leave some system-wide network configuration, I'll try to find it.

**Comment by GitSquared** [comment]
@DoggosGames Any update?

**Comment by DoggosGames** [comment]
@GitSquared This is weird, really weird. Aparentelly it works now. I guess it must've been because of some package I installed recently (maybe Python Scapy?), well It's fixed now!

Thanks!

**Comment by GitSquared** [comment]
Well, glad to hear it!

**Comment by j-tesla** [comment]
I am facing the same issue.
I don't use any proxies.

**Comment by rodrigovssp** [comment]
#up

Em Seg, 28 de dez de 2020 7:22 AM, Jayanth PSY <notifications@github.com>
escreveu:
