### ISSUE TITLE
v.3.0.0-pre [win]: powershell.exe not found

### ISSUE THREAD

**Issue by Chromecube** [GitSquared/edex-ui#589]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

After building eDEX-UI (`npm run install-windows`) I am not able to run it using `npm start`. Log:

```
 Ôû║  start     Starting eDEX-UI v3.0.0-pre
i  info      With Node 12.4.0 and Electron 6.0.10
i  info      Renderer is Chrome 76.0.3809.146
Ôû║  Startup   Initialized timer...
i  info      Base config dir is C:\Users\Niklas\AppData\Roaming\eDEX-UI
[ ]  pending   Mirroring internal assets...
[ ]  pending   Loading settings file...
[ ]  pending   Resolving shell path...
(node:13740) UnhandledPromiseRejectionWarning: Error: Could not find powershell.exe on your system;
    at C:\Users\Niklas\Downloads\edex-ui\src\node_modules\@wcjiang\whereis\index.js:13:16
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:13740) UnhandledPromiseRejectionWarning: Error: Could not find powershell.exe on your system;
    at C:\Users\Niklas\Downloads\edex-ui\src\node_modules\@wcjiang\whereis\index.js:13:16
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:13740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:13740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As you can see, the module `whereis` can not find `powershell.exe`. Obviously, powershell.exe is installed on my system and can be found on the system:

```
>where powershell.exe
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
```

### Recommendation:

This seems to be an issue with the `whereis` module. Could you switch to the [which](https://www.npmjs.com/package/which) module?

_Please ask me if you need further details. Thanks a lot!_

**Comment by GitSquared** [comment]
I made the switch to `which`, as you suggested.
I don't keep scores (maybe I should), but kudos for writing the best report I've seen in months.

**Comment by EgyptianPhantom** [comment]
Nicklas it me ZBlackPhantom the dud you help improve him self in Java with the mimecraft plugins remember me? I lost access to my old account but I have got a new discord it's
EgyptianPhantom#0185 add me if you can "D
