### ISSUE TITLE
eDex 90º portrait usability

### ISSUE THREAD

**Issue by NamasteJasutin** [GitSquared/edex-ui#590]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [x] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [x] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

I'm using my screens flipped 90º mostly for documentation and coding.
This also since some Windows tablets are in 90º portrait mode by default.
It would be cool if eDex supported the 90º setup.

**Comment by GitSquared** [comment]
See #390
