### ISSUE TITLE
Unable to show Network Stats

### ISSUE THREAD

**Issue by kalodis** [GitSquared/edex-ui#600]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
So i was tinkering with the UI and noticed that my Net stats and World view as well as the Network Traffic show "Offline" any idea?

**Comment by GitSquared** [comment]
See [#503](https://github.com/GitSquared/edex-ui/issues/503#issuecomment-492370332)
