### ISSUE TITLE
clicking file in file display pastes path without slashes into terminal

### ISSUE THREAD

**Issue by apoorvalal** [GitSquared/edex-ui#608]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ x] Windows
 - [ ] macOS

WSL1 on windows 10 build 18362

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Clicking on a file in file display pastes the path without any slashes into the console. Minor issue; would be good to be able to paste path into terminal to open in an editor or send to xdg open.

Here's an example of what happens:

![image](https://user-images.githubusercontent.com/12086926/67350016-62532f00-f4fe-11e9-8074-04409bde4a17.png)

**Comment by GitSquared** [comment]
I believed this was already fixed in `master`. I should publish a new release before the end of the year.
