### ISSUE TITLE
Windows 7 _64

### ISSUE THREAD

**Issue by slayerIzealot** [GitSquared/edex-ui#611]
Windows 7 _64. installation without problems, start is impossible, hangs in processes, but nothing happens, run from provershell displays such a screen, installation and start as
![123](https://user-images.githubusercontent.com/57087822/67662123-6a322980-f96b-11e9-911d-29d2fa91c71d.jpg)
 administrator

**Comment by GitSquared** [comment]
Seems like shell autodetection failed on your system and eDEX can't find a valid shell to start.

You should edit your [settings file](https://github.com/GitSquared/edex-ui/wiki/settings.json) and replace the `shell` value with a valid full path to powershell or cmd.

Check this: https://github.com/GitSquared/edex-ui/issues/505#issuecomment-527140337

**Comment by slayerIzealot** [comment]
Configured cwd path does not exist.
{"shell":"powershell.exe","C:\WINDOWS\system32\WindowsPowerShell\v1.0"
although the program is there

**Comment by GitSquared** [comment]
> {"shell":"powershell.exe","C:\WINDOWS\system32\WindowsPowerShell\v1.0"
Should be:
```json
{"shell":"C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe"}
```

**Comment by slayerIzealot** [comment]
[ ]  pending   Loading settings file...
тИЪ  success   Settings loaded!
(node:4580) UnhandledPromiseRejectionWarning: Error: Configured cwd path does not exist.
    at App.app.on (C:\Users\***\AppData\Local\Programs\edex-ui\resources\app.asar\_boot.js:168:56)
    at App.emit (events.js:187:15)
(node:4580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insi
de of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:4580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.
********
settings.json
{"shell":"powershell.exe","C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\powershell.exe":"C:\\Users\\***\\AppData\\Roaming\\eDEX-UI","keyboard":"en-US","theme":"tron","termFontSize":15,"audio":true,"disableFeedbackAudio":false,"pingAddr":"1.1.1.1","port":3000,"nointro":false,"nocursor":false,"allowWindowed":false,"excludeThreadsFromToplist":true,"hideDotfiles":false,"fsListView":false,"experimentalGlobeFeatures":false,"experimentalFeatures":false}

still doesn’t come out

**Comment by GitSquared** [comment]
Are you sure the path exists?

**Comment by slayerIzealot** [comment]
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
system path

**Comment by GitSquared** [comment]
Could run the following in powershell:
```
where.exe powershell.exe
```
It should give you the correct path to use for eDEX's config.

**Comment by slayerIzealot** [comment]
C:\Users\AAA>where.exe powershell.exe
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

**Comment by GitSquared** [comment]
`settings.json`:
```json
{
  "shell": "C:\\WINDOWS\\System32\\WindowsPowerShell1.0\\powershell.exe",
  "keyboard": "en-US",
  "theme": "tron",
  "termFontSize": 15,
  "audio": true,
  "disableFeedbackAudio": false,
  "pingAddr": "1.1.1.1",
  "port": 3000,
  "nointro": false,
  "nocursor": false,
  "allowWindowed": false,
  "excludeThreadsFromToplist": true,
  "hideDotfiles": false,
  "fsListView": false,
  "experimentalGlobeFeatures": false,
  "experimentalFeatures": false
}
```

This should work.

**Comment by slayerIzealot** [comment]
(node:4296) UnhandledPromiseRejectionWarning: Error: Configured cwd path does not exist.
    at App.app.on (C:\Users\AAA\AppData\Local\Programs\edex-ui\resources\app.asar\_boot.js:168:56)
    at App.emit (events.js:187:15)
(node:4296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing insi
de of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:4296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.
:(

**Comment by GitSquared** [comment]
¯\_(ツ)_/¯ I dunno man. Double-check the path, including capitalization and all. `where.exe` will help you. Perhaps try `cmd.exe` instead of `powershell.exe`.
