### ISSUE TITLE
External monitor support

### ISSUE THREAD

**Issue by bdgza** [GitSquared/edex-ui#612]
Running on a Mac with external displays this program only shows on the main display, and leaves external displays untouched. It would be cool if other monitors are also used, blacked out, or displaying something. Or have some option to choose what to do with external displays.

**Comment by GitSquared** [comment]
You can switch the monitor that the UI spawns in with the `monitor` setting (open the menu with `Ctrl+Shift+S`).

Multi-monitor support is a planned feature; I'll keep your issue around to track it.

**Comment by Zewwy** [comment]
> You can switch the monitor that the UI spawns in with the `monitor` setting (open the menu with `Ctrl+Shift+S`).
> 
> Multi-monitor support is a planned feature; I'll keep your issue around to track it.

Thank you GitSquared! This was exactly what I wanted so I can have eDEX-ui open on my secondary screen and play games on my primary. :) Great job.

**Comment by GitSquared** [comment]
> Multi-monitor support is a planned feature; I'll keep your issue around to track it.

Unfortunately not working on this anymore, see #769. Original issue resolved so i'm going to close this.
