### ISSUE TITLE
Globe not loading on MacOS

### ISSUE THREAD

**Issue by scriptkiddie3141** [GitSquared/edex-ui#619]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)
Loading the UI on a 2011 MacBook Pro causes the following error, and the globe will not render:
"TypeError: Cannot read property 'getExtension' of null"
I suspect a graphics/GPU compatibility problem.

**Comment by GitSquared** [comment]
> I suspect a graphics/GPU compatibility problem.

You're right. This issue should be fixed in the development version of eDEX, which has merged a lot of upstream framework (Electron) updates, notably a bunch of GPU-compat related stuff.

You can either wait for the next release or attempt to build the software yourself (instructions in README).
