### ISSUE TITLE
Filesystem scrollbars not functional (no mouse-click or mouse-drag)

### ISSUE THREAD

**Issue by Zireael07** [GitSquared/edex-ui#620]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

For folders with much stuff in them, filesystem pane is less than useful - the scrollbars do not work.

**Comment by GitSquared** [comment]
You can just use your scroll wheel or swipe with a touch screen. I'll see about fixing this bug though.

**Comment by Zireael07** [comment]
No scroll wheel or touch screen here, unfortunately :(

**Comment by GitSquared** [comment]
(Are you using a trackball or something?)

**Comment by Zireael07** [comment]
Trackpad on a 14" notebook

**Comment by GitSquared** [comment]
Doesn't two-finger scrolling work?

**Comment by MohammedAlbaqerH** [comment]
unsubscribe.

Sent from Mail for Windows 10

**Comment by Zireael07** [comment]
Two finger scrolling does work (just checked).

I updated issue title to reflect that the problem is only with typical mouse behavior.

**Comment by GitSquared** [comment]
Fixed on `master`. Wait for the next release, or build the git version from source. There's also the `edex-ui-git` AUR package on ArchLinux, or you can use two-finger scrolling :^)
