### ISSUE TITLE
Option to start windowed

### ISSUE THREAD

**Issue by Zireael07** [GitSquared/edex-ui#621]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [x] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

What it says on the tin. I work nearly exclusively windowed, so an option to start windowed would make my life easier. If not for the fact that I don't know how to develop on Electron itself, I could probably do it since I know JS ;)

**Comment by Chromecube** [comment]
Please refer to [this comment](https://github.com/GitSquared/edex-ui/issues/594#issuecomment-541075488) in #594 :smile: This feature already exists!

**Comment by GitSquared** [comment]
@Chromecube Indeed, but you can't *start* the app in windowed mode yet.

**Comment by Chromecube** [comment]
Sorry about that. I will make a PR tomorrow to add that feature.

**Comment by GitSquared** [comment]
> Sorry about that. I will make a PR tomorrow to add that feature.

@Chromecube It'd be great if you could make it so that previous window state is resumed when `allowWindowed` is on - i.e if the last time eDEX stopped it was windowed, start it windowed.
This would prevent adding yet another niche settings option.

**Comment by Chromecube** [comment]
Just created the PR, I hope the way I implemented this meets your expectations.
