### ISSUE TITLE
TypeError: e.IndexOf is not a function

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [GitSquared/edex-ui#626]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)
Hello I was testing the latest Edex-UI version (Planning to make a raspberry pi tablet), and while I was testing it out I decided to open another terminal. However, trying to do so results in a TypeError: e.IndexOf is not a function error. I will put a screen shot. 

P.S. Thank you.

![Screenshot at 2019-11-05 21-58-08](https://user-images.githubusercontent.com/45339160/68267441-1208c080-0018-11ea-8340-36f6955a66e1.png)

**Comment by GitSquared** [comment]
Did you modify any configuration? Does this happen on every attempt to open a new tab?

**Comment by KittyTechnoProgrammer** [comment]
this apparently happens every time i use the tron-colorfilter.json theme.

**Comment by docjuhnk** [comment]
I confirm. So far I have only seen this error using the tron-colorfilter.json theme.

**Comment by GitSquared** [comment]
This is the same issue as #566. This bug has been fixed in 88f5eed, which will ship with the next release, coming out before the end of the year.

In the meantime if you want to use terminal color filters without breaking the tabs feature, you can build the `master` source.
