### ISSUE TITLE
Supporting Cyber Security

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [GitSquared/edex-ui#627]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [x] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [x] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Hi it's me again. I've actually been using this user interface for a few months now, and I like it. However I do have a few requests / ideas.

The first idea being the file Lister or file explorer (whatever it's called). I would like there to be an option in the settings.json file to turn the "Loading animation off" were all the files come one by one (if this is really animation. If not than my computer has a problem).  

The second Idea being again the file Lister or file explorer (whatever it's called). The file explorer works on the local machine and changed for every terminal with the terminals current working directory. I have an idea for this to work over ssh. As in when you ssh into a remote system you can see all the files on the remote system through the file explorer. 

The third idea being for cyber security. I'm not going to lie. I like using the edex-UI when I need that "motivation" when I'm working on a project. However it has become more usable  over time. It would be nice to have a second (yes I said second) work space available for this UI dedicated to Cyber Security. As in the main window would take one work space, and the other would be taken by the cyber security window (log files, message alerts, metasploit, empire, etc...). I know that this is asking a lot. However would be a pretty nifty feature. 

P.S. Thanks for responding to my last post.

Sincerely KittyTechnoProgrammer

**Comment by clragon** [comment]
Have you done any "cyber security" yet?

I feel like the things you list don't need a seperate UI from edex, those can all be achieved by using using for example the different tabs it has, using something like tmux to split your terminal, using some bash scripts to update things etc...

And if you want to be really fancy with it, you can wait for the module system to be available, or even actively help @GitSquared by contributing to this project, and then code your own module that displays the log files, message alerts (?) and whatever other things you might want to have.

**Comment by KittyTechnoProgrammer** [comment]
Yes, I've tried creating GUI's as well for certain tools. I love hexchat for it allows easy control of devices over IRC. However metasploit, empire, etc... Allow connections over a multitude of protocols. I like going old school with the terminal most of the time, but when it's late you just wanna slow down, I had an idea. What if you made it look more like a video game. When I'm working on a target I kind of note everything I do as a game, because to me its just fun. 

This is the same Idea that some companies had to try making work more fun so their employees would want to keep working. 

However I can't program a gui to save my life. I can make back ends in python, nim, c/c++ (Would prefer not to do c/c++ as that just takes even longer), nim, etc.. 

Also trying to make something to make it easier to present to a client on how you broke in. If you so your client a paper and say "Here's the results now just give it to your IT" They don't understand. However present it to them like a movie or in a format they can see and understand, then you can actually show them the holes in there company, network, etc... 

This was just a suggestion. I would like to contribute, however I can only make back end code. While I know html, and JS for website security. I don't work with them enough to create full applications using electron (I tried using electron and angular).

**Comment by KittyTechnoProgrammer** [comment]
Also Like the idea of location tracking in the globe for connections being made, but I notice some bugs if you would want me to report it?

**Comment by GitSquared** [comment]
> The first idea being the file Lister or file explorer (whatever it's called). I would like there to be an option in the settings.json file to turn the "Loading animation off" were all the files come one by one (if this is really animation. If not than my computer has a problem).

What OS are you running this on? On Windows, I notice the UI tends to lag out a bit sometimes, causing rapid-firing animations like the one you're talking about to slow down.

> The second Idea being again the file Lister or file explorer (whatever it's called). The file explorer works on the local machine and changed for every terminal with the terminals current working directory. I have an idea for this to work over ssh. As in when you ssh into a remote system you can see all the files on the remote system through the file explorer.

This is WIP, see #488 - no ETA yet but I'm currently rushing through prototypes hoping to get this done for eDEX's 1 year anniversary

> The third idea being for cyber security.

No.

As @clragon rightfully pointed out, all you need is terminals - which eDEX already has plenty of. I will also add that if you're doing any serious cybersec work I wholeheartedly recommend that you keep the hell out of this project because it is largely an experimental gadget maintained by a one-man team and even though I am completely paranoid about the security of the software I release, [things have slipped through the cracks](https://gaby.dev/edex-vuln) and I cannot reasonably promise that it won't happen again.

Also, that just doesn't fit in the scope of this project and would require a massive amount of work that I'm just not willing to put in.
