### ISSUE TITLE
File browser issues

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#629]
## Technical information
**Using version:**
 - `master` (running from GitHub-published source code, currently `v3.0.0-pre`)

**Running on:**
 - Windows

**How comfortable you are with your system and/or IT in general:**
 - My machine is fully under my control, tell me what you need

---

## Problem

![36670456](https://user-images.githubusercontent.com/11785085/68544835-71275600-03c7-11ea-88c5-1226f1ba3284.png)

When clicking a folder with an apostrophe in its name, the file browser fails with the error message above. 

Another issue I have noticed which is version-unspecific since it seems to be the case even in the latest release, clicking on a file on windows will result in the path being pasted into the console, however without the backslashes, rendering it useless. Also, when pasting the path, it uses apostrophes to surround it, resulting in another issue with windows?

Here is a screenshot where the first path is the one pasted by edex, the second one is the correct, valid one. 

![63582106](https://user-images.githubusercontent.com/11785085/68544950-9ec0cf00-03c8-11ea-9675-9d7ec547357c.png)

(_by the way, there seems to be no way to paste into the console with CTRL+V or copy from the console, with anything at all, even when selecting something? This is very annoying_)

**Comment by clragon** [comment]
Another issues: pictures (png, jpg, gif) aren't displayed:
![35487712](https://user-images.githubusercontent.com/11785085/68545169-ca44b900-03ca-11ea-81e3-bb397d503436.png)
![28200642](https://user-images.githubusercontent.com/11785085/68545170-ca44b900-03ca-11ea-8bd9-eddb66d092cb.png)
Neither are videos:
![17587148](https://user-images.githubusercontent.com/11785085/68545173-ce70d680-03ca-11ea-9225-25541baf0084.png)
however, ico files are:
![84845048](https://user-images.githubusercontent.com/11785085/68545176-dcbef280-03ca-11ea-9b12-774480df30df.png)

**Comment by GitSquared** [comment]
> (by the way, there seems to be no way to paste into the console with CTRL+V or copy from the console, with anything at all, even when selecting something? This is very annoying)

Shift+Ctrl+C/V?

I'm looking into the other issues, hold on.

**Comment by clragon** [comment]
Found another issue:

Going up to the top level of your folders, so far that "go up" doesnt show anymore, then going to the disk display and _exiting_ it will result in a weird issue, where all folders are broken. 
like this:
![46070010](https://user-images.githubusercontent.com/11785085/68545246-89996f80-03cb-11ea-9194-3d993052e84d.png)

clicking them will paste their path, however things like "show disks" have no path and are just pasted as "C:ShowDisks" or something like that.

**Comment by GitSquared** [comment]
> if you go up enough times, you just end up in the disk display.
This might work for you depending on how your FS is set up but I don't want to go up 20 directories to access the USB I just plugged in.

**Comment by clragon** [comment]
Very fair point. The exit button could still be removed then, basically making it a directory. I do not know how compatible this is over OSes, like i said though

**Comment by GitSquared** [comment]
The exit button is useful because it allows you to go back to where you were previously - it's actually more like an "abort" button.
This UX allows you to list the disks without switching to them, or abort the operation if you missclicked/touched and did not want to go somewhere else.

**Comment by GitSquared** [comment]
@clragon I pushed some changes to the way paths are retrieved and printed to the term; does that solve the issues you described in this issue's first post?

**Comment by GitSquared** [comment]
Pictures *should be* fixed, too.

**Comment by clragon** [comment]
![68115184](https://user-images.githubusercontent.com/11785085/68546712-b0f73900-03d9-11ea-83c1-6ec9e452a4b7.png)

It seems to be impossible to use the "go up" button anymore, failing with this error.

**Comment by clragon** [comment]
edex pasting the path of a file into the terminal seems to be fixed now, and working well. Apostrophes seem to be handled correctly, too.

**Comment by GitSquared** [comment]
I'm installing dev tools on a Window VM to check out the "go up" and "missing )" issues.

**Comment by GitSquared** [comment]
@clragon I believe it's all fixed now. Tested on my shiny new VM. I'm closing this.
