### ISSUE TITLE
picture drag and drop

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#631]
## Technical information
**Using version:**
 - `master` (running from GitHub-published source code, currently `v3.0.0-pre`)

**Running on:**
 - Windows

**How comfortable you are with your system and/or IT in general:**
 - My machine is fully under my control, tell me what you need

---

## Problem

Pictures that have been openend in a pop up window can be dragged around, however there is no surface that would accept a drop. 

I suggest either making the terminal accept a file drop, which will then just insert the path of the file or disabling dragging.

**Comment by GitSquared** [comment]
> I suggest either making the terminal accept a file drop, which will then just insert the path of the file or disabling dragging.

This would be cool but might cause a bunch of conflicts with the xTerm renderer frontend - so I'm going with the easy solution for now.

Thanks for today's bug-hunting, by the way, you rock!
