### ISSUE TITLE
MacOS multiple desktop clipboard issue

### ISSUE THREAD

**Issue by kv96** [GitSquared/edex-ui#634]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

## Problem

Edex-UI is running in fullscreen mode and am currently working in another active desktop in my Mac. If am trying to copy a text say from google chrome and trying to paste it in VScode, the clipboard content is always getting pasted in the Edex-UI Terminal. The expected behaviour is the content should be pasted in the active desktop or application am using and should be pasted in Edex-UI window only when it is active and am using it.

**Comment by GitSquared** [comment]
Could you enable `allowWindowed` in eDEX settings, press `F11` to exit fullscreen mode and check if this still happens?

**Comment by kv96** [comment]
Enabling `allowWindowed` is solving the issue @GitSquared . Thanks for the solution!
