### ISSUE TITLE
Could you let me change the directory at the bottom with the powershell command? Thanks.

### ISSUE THREAD

**Issue by Shandun** [GitSquared/edex-ui#643]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

(Write your idea or feature request here)

**Comment by GitSquared** [comment]
Unfortunately no. On *nix operating systems the filesystem module at the bottom-left of the screen follows the terminal around, but this is currently impossible to do on Windows.

Providing a command line tool to remotely change the directory in edex is out of the scope of this project.
