### ISSUE TITLE
Graphs Frozen/Globe invisible

### ISSUE THREAD

**Issue by acul009** [GitSquared/edex-ui#650]
## Technical information
**Using version:**
 - [X] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [X] Linux (Manjaro KDE)
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [X] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

I'm using Edex behind all other windows as a "Desktop replacement". The Network and CPU graphs aren't working, but have some data in them, which might mean they did work for a few seconds. The globe is invisible, but markers and satellites are still visible and rotating. The Process display, network traffic display and CPU utilization are still working, it's just the graphs that are frozen. Memory is still fully functional.

**Comment by GitSquared** [comment]
Does this still happen when you focus the edex window? It might be some power-saving feature kicking in.

**Comment by acul009** [comment]
Unfortunately I can't tell anymore. I broke my installation and didn't have the time to fix it yet. right now I only get a black screen though the sound still works. Once I've repaired my installation I'll try to get it running again.

Thank you for the help :D
