### ISSUE TITLE
Network And World Globe Issue

### ISSUE THREAD

**Issue by tztl0** [GitSquared/edex-ui#654]
I'm using version 2.2.2 at Linux Mint 19.2, this is my `ifconfig` output:

eno1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 3c:a8:2a:b0:ad:c8  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 24326  bytes 1745453 (1.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24326  bytes 1745453 (1.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlo1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.43.150  netmask 255.255.255.0  broadcast 192.168.43.255
        inet6 fe80::6577:64b6:b52f:bb17  prefixlen 64  scopeid 0x20<link>
        ether d8:5d:e2:8f:f4:2b  txqueuelen 1000  (Ethernet)
        RX packets 45142  bytes 42802492 (42.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 85395
        TX packets 40540  bytes 6809902 (6.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 18
When I select "wlo1" at settings it shows me offline with a blinking ipv4 adress. When I select "lo" it shows state: unknown ipv4:-------- ping:-- with no endpoint location, but not offline. What can I do to fix this? I have no firewalls enabled.

lo=![Screenshot from 2019-12-10 00-13-27](https://user-images.githubusercontent.com/58708456/70473383-f9416e00-1ae1-11ea-929d-1849b2e76a42.png)
wlo1=![Screenshot from 2019-12-10 00-15-24](https://user-images.githubusercontent.com/58708456/70473483-3443a180-1ae2-11ea-8e14-805207da5b6c.png)

**Comment by GitSquared** [comment]
Weird that it shows the data graph on the loopback device. Anything else you could point out on your setup? Some vpn configs, proxy, anything?

You could also try running the latest master and checking if this still happens. I can provide built AppImages if you want.

**Comment by xzkeee** [comment]
I have this issue too. Version 2.2.2 at macOS 10.14 and 10.15, and firewall off. Says offline just like the picture. Every time open this app and system popup window ask if allow it connect the internet.

**Comment by GitSquared** [comment]
@xzkeee That's on windows, so separate issue. You should allow edex to connect in the firewall pop-up window.

**Comment by tztl0** [comment]
I solved this by adding `GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"` to `grub` file. It turns the wlan interface from wlo1 to wlan0 so app can detect the connection.
