### ISSUE TITLE
AppImage hanging on startup at "Settings Loaded" stage

### ISSUE THREAD

**Issue by NerdyKyogre** [GitSquared/edex-ui#655]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
Just installed from the AppImage on ubuntu 18.04 with deepin desktop environment. I'm using https://github.com/TheAssassin/AppImageLauncher to run this image, and it doesn't matter whether I integrate it or just run once (ignoring the launcher). Opening from dde launcher or cerebro spawns about 3 processes but no window(s), and running from terminal starts up, moans about some gtk errors, sets up, gets to Success: Settings Loaded and...hangs. Nothing appears except the processes in the system monitor. Not sure if this is an appimagelauncher problem or a system problem elsewhere.

**Comment by GitSquared** [comment]
What shell are you using and what's the output of running `[shell] -ilc echo -n "_SHELL_ENV_DELIMITER_"; env; echo -n "_SHELL_ENV_DELIMITER_"; exit`?

Related: #537

**Comment by NerdyKyogre** [comment]
using ZSH 5.4.2. Your command output the following (without the exit bit, that just closed my terminal):
COLORFGBG=15;0
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DEFAULTS_PATH=/usr/share/gconf/deepin.default.path
DESKTOP_SESSION=deepin
DISPLAY=:0
GDMSESSION=deepin
GDM_LANG=en_CA
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/org.kde.konsole.desktop
GIO_LAUNCHED_DESKTOP_FILE_PID=21416
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
GTK_MODULES=gail:atk-bridge
HOME=/home/colef
KONSOLE_DBUS_SERVICE=:1.183
KONSOLE_DBUS_SESSION=/Sessions/1
KONSOLE_DBUS_WINDOW=/Windows/1
KONSOLE_PROFILE_NAME=Kyogre
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LIBVIRT_DEFAULT_URI=qemu:///system
LOGNAME=colef
MANDATORY_PATH=/usr/share/gconf/deepin.mandatory.path
PATH=/home/colef/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PROFILEHOME=/home/colef
PWD=/home/colef
QT_ACCESSIBILITY=1
QT_SCALE_FACTOR=1
QT_STYLE_OVERRIDE=kvantum
SHELL=/usr/bin/zsh
SHELL_SESSION_ID=b8d0b5147e8a4d2ba867795513f7e96f
SHLVL=1
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
TERM=xterm-256color
USER=colef
WINDOWID=180355078
XAUTHORITY=/home/colef/.Xauthority
XDG_CONFIG_DIRS=/etc/xdg/xdg-deepin:/etc/xdg
XDG_CURRENT_DESKTOP=Deepin
XDG_DATA_DIRS=/usr/share/deepin:/home/colef/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/colef
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_DESKTOP=deepin
XDG_SESSION_ID=c3
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SESSION_TYPE=x11
XDG_VTNR=1
OLDPWD=/home/colef
ZSH=/home/colef/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=GxFxCxDxBxegedabagaced
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
P9K_SSH=0
CLICOLOR=1
P9K_TTY=old
_=/usr/bin/env
_SHELL_ENV_DELIMITER_%

**Comment by NerdyKyogre** [comment]
Interestingly, the same hanging occurs when compiled from source on 2.2.2 and 3.0.0-pre, and my virtual machine with ubuntu 18.04 and deepin did the same. However, the appImage works happily 
on an ubuntu 19.10 vm with gnome.

**Comment by GitSquared** [comment]
There's a `_SHELL_ENV_DELIMITER_` that's missing in the output you gave me - this is the same issue as #537 i think (but that one wasn't resolved).

Did the shell change on any of your test cases or where you always using zsh?

**Comment by NerdyKyogre** [comment]
Kernel update to 5.0.0-37 fixed it. No clue why. Closed.

**Comment by GitSquared** [comment]
Probably some Chromium sandboxing-related issue. Thanks for the update.
