### ISSUE TITLE
MaxMind EULA update is breaking builds & installs accross all platforms

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#664]
## Technical information
**Using version:**
 - [X] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)

**Running on:**
 - [X] Linux
 - [X] Windows
 - [X] macOS

---

## Problem

Updates to MaxMind's EULA resulted in the freely accessible GeoLite databases URL being taken down (`https://geolite.maxmind.com`). We used these to fetch GeoIP databases on install through [`runk/node-geolite2`](https://github.com/runk/node-geolite2).

Any attempt to install or build unreleased versions of eDEX will result in the following error:

```
Downloading maxmind databases...
events.js:282
      throw er; // Unhandled 'error' event
      ^
Error: getaddrinfo ENOTFOUND geolite.maxmind.com
```

Need to send patch to upstream modulee - or handle this locally? - ASAP

**Comment by GitSquared** [comment]
Upstream bug: https://github.com/runk/node-geolite2/issues/17

**Comment by thecakeisalie25** [comment]
Could we just issue a hotfix with no globe? It's been unable to build for a few months now iirc. (i'm typecasto from aur btw)

**Comment by GitSquared** [comment]
No, we should fix the issue upstream asap. Builds were working 72h ago, you might have been experiencing a different issue before this one.

**Comment by GitSquared** [comment]
Quick update: `node-geolite2` got a new release that requires each individual `npm install`-ing it to sign up on MaxMind's website and agree to a lengthy EULA.

I believe this would scare most new contributors away from open-source projects like eDEX, and doesn't add much value to MaxMind's efforts to limit propagation of older versions of their databases.

I'm looking into setting up a redistribution which would be easier to include in OSS projects while still enforcing upstream's EULA.

**Comment by GitSquared** [comment]
Work ongoing upstream at https://github.com/runk/node-geolite2/pull/19

**Comment by GitSquared** [comment]
[`geolite2-redist`](https://www.npmjs.com/package/geolite2-redist) published
