### ISSUE TITLE
WIndows 10 network tab

### ISSUE THREAD

**Issue by 6iix** [GitSquared/edex-ui#665]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [x] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

I just stumbled across this today from twitter. So far I gotta say this is a really cool idea. However I am running in an issue with the network display where it is looking at the ethernet port rather than the onboard wifi card. 

If it doesn't exist it would be cool if we could toggle between the two.

**Comment by GitSquared** [comment]
You can select which network interface to monitor in the settings (ctrl+shift+s).

**Comment by Draecal** [comment]
Having the same issue, changing the iterface doesn't fix it. Also using the correct one as my connection is Ethernet and the interface is named the same.
