### ISSUE TITLE
npm errors after running`makepkg` for edex-ui from AUR

### ISSUE THREAD

**Issue by jakewilliami** [GitSquared/edex-ui#666]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

I am downloading edex-ui from the [AUR](https://aur.archlinux.org/packages/edex-ui).  I download the .tar.gz and extract it, `cd edex-ui`, and run `makepkg -si`.  The latter command gets most of the way through but then throws a bunch of errors regarding npm.  Here is the [log file](https://pastebin.com/FvVdg2DX), but I don't know what to make of it sorry! 

Close this issue if you think this is a shell or client issue, not a bug with edex-ui.

**Comment by GitSquared** [comment]
Is that the full log? Do you have `rsync` installed?

**Comment by jakewilliami** [comment]
I do beleive it is the full log.  When I run `makepkg` and it fails, it tells me that the log can be found at `/home/jakeireland/.npm/_logs/2020-01-05T10_41_48_458Z-debug.log`, so that log I put on pastebin is just a copy of that file.  There is also a file named `edex-ui-2.2.2-1-x86_64-build.log` in the edex-ui directory, whose contents I have put [here](https://pastebin.com/LV9U30zA).  Are these the correct logs to be looking at?

I do have `rsync` installed.

**Comment by GitSquared** [comment]
Thanks, the full output contains more info.
eDEX v2 can't be built on node 10+, you should try with node 8.

You might be blocked by #664 later on in the make process, though. You'll have to either wait until this is sorted out or try a prebuilt AppImage.

**Comment by jakewilliami** [comment]
Thanks for this.

I managed this by installing Node Version Manager ([nvm](https://github.com/nvm-sh/nvm)):

```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash; \
source ${HOME}/.bashrc; \
nvm install 8; \
nvm use 8
```
