### ISSUE TITLE
Save app volume

### ISSUE THREAD

**Issue by KaKi87** [GitSquared/edex-ui#691]
**Perceived idea awesomeness**
- [x] Wow, you don't have this yet???
- [ ] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Hello,

I always have headphones and the audio effects are very loud by default.

When eDEX starts, I always set it down to 10%, but the app doesn't remember the setting : it comes back to 100% every time I close and re-open it.

Thanks

**Comment by GitSquared** [comment]
I will look into this. Thanks for filling a report!
