### ISSUE TITLE
UI crash after start up for few seconds (Manjaro Linux 5.5.2-1)

### ISSUE THREAD

**Issue by MrPeterJin** [GitSquared/edex-ui#697]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

I installed edex-ui from Github releases. My operating system is Manjaro Linux. After downloaded and executed the .appimage file, the ui started normally. However, after several seconds, the interface stuck and went completly black and I had to force stop the program. Restart works nothing.

**Comment by GitSquared** [comment]
Could you try this [appImage build from master](https://send.firefox.com/download/5fccca1fe25551fb/#aD1Qvnk4UdtESz9P87lbrw) and if it doesn't work tell me your hardware specs? (ram, cpu, gpu)

**Comment by MrPeterJin** [comment]
cool, it works!
