### ISSUE TITLE
Does edex-ui work with powershell core?

### ISSUE THREAD

**Issue by 2403772980ygy** [GitSquared/edex-ui#698]
FS: windows 10

I changed the settings.json "shell" value to my PowerShell core, and edex-ui stopped working and changing it back fixes the issue, I don't know why, so does edex-ui works with PowerShell core?

**Comment by GitSquared** [comment]
I haven't tested PowerShell Core so I'm not sure what's causing the crash. In theory any CLI shell should work.

Perhaps you are not using the right 
binary (i.e graphical term emulator instead of the shell itself)?

Could you give me some logs? Try starting edex from a command line to get stdout output.

**Comment by 2403772980ygy** [comment]
okay, here's the output
```log
►  start     Starting eDEX-UI v2.2.2
i  info      With Node 10.11.0 and Electron 4.2.0
i  info      Renderer is Chrome 69.0.3497.128
►  Startup   Initialized timer...
i  info      Base config dir is C:\Users\ygy\AppData\Roaming\eDEX-UI
[ ]  pending   Loading settings file...
√  success   Settings loaded!
[ ]  pending   Creating new terminal process on port 3000
(node:6736) UnhandledPromiseRejectionWarning: Error: Cannot create process, error code: 267
    at new WindowsPtyAgent (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:76:43)
    at new WindowsTerminal (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at Object.spawn (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\node_modules\node-pty\lib\index.js:29:12)
    at new Terminal (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\classes\terminal.class.js:1:8188)
    at App.app.on (C:\Users\ygy\AppData\Local\Programs\edex-ui\resources\app.asar\_boot.js:181:11)
(node:6736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I guess the warning is the error, and I'll test if PowerShell.exe has the same warning.

**Comment by 2403772980ygy** [comment]
The powershell.exe is don't have the promise warning.

**Comment by GitSquared** [comment]
> Error: Cannot create process, error code: 267

From the [Windows system error codes docs](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-), 267 is "invalid directory". Could you share the edex settings.json so I can see the shell path you've set up?

**Comment by 2403772980ygy** [comment]
```json
{
    "shell": "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe",
    "cwd": "C:\\Users\\ygy\\AppData\\Roaming\\eDEX-UI",
    "keyboard": "en-US",
    "theme": "tron",
    "termFontSize": 15,
    "audio": true,
    "disableFeedbackAudio": false,
    "pingAddr": "1.1.1.1",
    "port": 3000,
    "monitor": 0,
    "nointro": false,
    "nocursor": false,
    "iface": "vEthernet (Default Switch)",
    "allowWindowed": false,
    "excludeThreadsFromToplist": true,
    "hideDotfiles": false,
    "fsListView": false,
    "experimentalGlobeFeatures": false,
    "experimentalFeatures": false
}
```

Powershell Core installed in default location

**Comment by SonOfDiablo** [comment]
I just downloaded and tried out eDex-UI, first thing I did was switch the shell to Powershell Core (v6.2.4) install path is `C:\Program Files\PowerShell\6\pwsh.exe` and it worked fine for me. 
However I just put `pwsh.exe` in the `shell` variable as `pwsh.exe` is in my path.

Would that fix your issue @2403772980ygy ? simply make sure `pwsh.exe` is in your path and specify just the exe in the `shell` variable in the settings file.

**Comment by 2403772980ygy** [comment]
@SonOfDiablo It worked for me, Thanks!

**Comment by 2403772980ygy** [comment]
The conclusion is that try pwsh.exe instead of path\to\pwsh.exe.

**Comment by GitSquared** [comment]
@SonOfDiablo Thanks for your help.

**Comment by SonOfDiablo** [comment]
Happy to help.
Though there does seem to be an issue, specifically when providing a path that contains a space.
When replacing the `shell` variable with `C:\\Program Files\\PowerShell\\6\\pwsh.exe` I get the following error message: `(node:40144) UnhandledPromiseRejectionWarning: Error: File not found: C:\Program`

<details>
<summary>Full Output</summary>

```
►  start     Starting eDEX-UI v2.2.2
i  info      With Node 10.11.0 and Electron 4.2.0
i  info      Renderer is Chrome 69.0.3497.128
►  Startup   Initialized timer...
i  info      Base config dir is C:\Users\USERNAME\AppData\Roaming\eDEX-UI
[ ]  pending   Loading settings file...
√  success   Settings loaded!
[ ]  pending   Creating new terminal process on port 3000
(node:40144) UnhandledPromiseRejectionWarning: Error: File not found: C:\Program
    at new WindowsPtyAgent (D:\test2\Scoop Apps\edex-ui\2.2.2\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:50:36)
    at new WindowsTerminal (D:\test2\Scoop Apps\edex-ui\2.2.2\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:49:24)
    at Object.spawn (D:\test2\Scoop Apps\edex-ui\2.2.2\resources\app.asar\node_modules\node-pty\lib\index.js:29:12)
    at new Terminal (D:\test2\Scoop Apps\edex-ui\2.2.2\resources\app.asar\classes\terminal.class.js:1:8188)
    at App.app.on (D:\test2\Scoop Apps\edex-ui\2.2.2\resources\app.asar\_boot.js:181:11)
(node:40144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:40144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

Might be something that needs looking into.

**Comment by 2403772980ygy** [comment]
yeah, If some shell isn't inside PATH variable, then it'll be bad if we can't use it.

I'll test git bash later

**Comment by GitSquared** [comment]
I think handling of spaces has been fixed on master already - I'm trying to find the commit.

**Comment by 2403772980ygy** [comment]
> I think the handling of spaces has been fixed on master already - I'm trying to find the commit.

No, git bash has no space in the path but still got the same warning and don't start, Maybe this is related to impropriate path handling?

**Comment by GitSquared** [comment]
> No, git bash has no space in the path but still got the same warning and don't start, Maybe this is related to impropriate path handling?

Is this on v3 or v2 of edex?

**Comment by 2403772980ygy** [comment]
It seems to be v2.2.2
