### ISSUE TITLE
Show "shell not found" when targeting an invalid shell

### ISSUE THREAD

**Issue by 2403772980ygy** [GitSquared/edex-ui#699]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [x] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

(Write your idea or feature request here)

As the title says, adding "shell not supported" when targeting an invalid shell is much better than just showing nothing.

**Comment by GitSquared** [comment]
I don't have a list of supported shells so this isn't possible. In theory any shell should work.
