### ISSUE TITLE
Integrate hacker manifesto text and u*nix commands as show in Matrix movie's

### ISSUE THREAD

**Issue by tuxkernel** [GitSquared/edex-ui#703]
This is amazing!

Some year ago I type some bash scripts like screensaver text. Could you integrate into edex-ui?

Check a look around:

https://github.com/tuxkernel/hacker-manifesto-bash-script
https://github.com/tuxkernel/matrix-bash-script

Could be cool! 

Cheers,

Tuxkrnel

**Comment by GitSquared** [comment]
You can just launch those scripts in edex, no need to integrate them into the program itself...
