### ISSUE TITLE
SyntaxError: Unexpected token '}'

### ISSUE THREAD

**Issue by zenkbaries** [GitSquared/edex-ui#710]
## Technical information
**Using version:**
 `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 
**Running on:**
 macOS

**How comfortable you are with your system and/or IT in general:**
 
 My machine is fully under my control, tell me what you need
 
---

## Problem

When I click on one of the file in filesystem section (lower left), it show error `Syntax Error: Unexpected Token '}'`.
The error only show up whenever I click on any file. No issue when i click on folder or some file that it can handle like `*.JSON `or `*.jpg`. But file with no extenstion such as `.env` or other file.  As if some file that edex-ui can't handle bring up that errors.

See screenshot
![Screen Shot 2020-03-18 at 7 33 15 AM](https://user-images.githubusercontent.com/8967420/76966563-c8948000-68eb-11ea-86b2-9e00a70a10b6.jpg)

**Comment by GitSquared** [comment]
Fixed, thanks for reporting!
