### ISSUE TITLE
how did you made this ?! react native ?!

### ISSUE THREAD

**Issue by PrashanthKumar0** [GitSquared/edex-ui#711]
how did you made this ?! react native ?!

**Comment by GitSquared** [comment]
I wish I ever got to finish #272.
There is no other framework than Electron, eDEX uses a bastardization of components made with JS classes and setInterval timers.

I wish I knew React when I first started this! It's a pain to maintain and would need a full rewrite some day, which I unfortunately do not have time for as I'm working on bigger projects now.
