### ISSUE TITLE
Goes black after some time.

### ISSUE THREAD

**Issue by ccase01** [GitSquared/edex-ui#712]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Running for about 10 min of so with htop running in term the program doesn't crash but goes black and silent (htop beeps as processes scroll).  I have to exit ATL + F4 and open again.  Also has there been a fix for using additional tabs in tron color theme?

**Comment by ccase01** [comment]
UPDATE.  Doesnt matter what is running htop or nothing...still goes dark.

**Comment by GitSquared** [comment]
You should try using the development version (3.0-pre)
