### ISSUE TITLE
[Bug] Terminal tabs not reusable

### ISSUE THREAD

**Issue by KaKi87** [GitSquared/edex-ui#714]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

**How to reproduce :**

1. Open eDEX
2. Open a second tab
3. Close it (`exit`)
4. Re-open it

**Expected result :**

The tab re-opens

**Actual result :**

The app crashes with the following error :
> `Cannot resize a pty that has already exited`

**Thanks**

**Comment by GitSquared** [comment]
Thanks for reporting this! The issue has been fixed on the unreleased 3.0 version. If you can't wait for the release, you can check the README for build instructions.

**Comment by KaKi87** [comment]
Okay. Do you have an ETA on stable release ?

**Comment by GitSquared** [comment]
Unfortunately not yet. Release has been postponed as the codebase is starting to get to the point where a full rewrite would be welcome, and I'm too busy working on for-profit software (oughta make a living...)

One day though, one day.
