### ISSUE TITLE
uncaught type error : failed to execute 'attach shader' on 'webglrenderingcontext' :parameter 2 is not of type 'webglshader'. on kali linux

### ISSUE THREAD

**Issue by Web-Digger-Nuzrat** [GitSquared/edex-ui#715]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [x] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)

**Comment by GitSquared** [comment]
Most likely drivers problem or unsupported hardware - you need 3D GPU acceleration, and to be whitelisted on Chromium's ever-expanding list of gpu hardware.
