### ISSUE TITLE
Don't show password

### ISSUE THREAD

**Issue by call-cc** [GitSquared/edex-ui#717]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [X] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [X] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Hi,

It would be awesome if the on-screen keyboard wouldn't show what you type if it's a password. I'm not sure how you could detect it. Maybe it the terminal is set to noecho?

**Comment by GitSquared** [comment]
See discussion in #394

**Comment by GitSquared** [comment]
tl;dr: we don't have enough data from the terminal to trigger this automatically. You can use the ctrl+shift+p shortcut to disable input feedback when typing sensitive information.

**Comment by call-cc** [comment]
Thanks!
