### ISSUE TITLE
Having issue at moving UI to another monitor on windows 

### ISSUE THREAD

**Issue by master-0098** [GitSquared/edex-ui#718]
hey bro , 
i got some difficulty from moving the app to another monitor while I'm running dual monitor setup , i want use this UI on my second monitor , but i couldn't find any option for that 
i try to change my main monitor to second monitor, but after reconnecting my second monitor, it moves to first monitor with the size of second monitor , still can't move it 
i run pc , and win10 version 1909 build 18363
thank for helping 
BR

**Comment by GitSquared** [comment]
Check the [wiki](https://github.com/GitSquared/edex-ui/wiki/settings.json), there is a `monitor` option to control where the renderer is spawned.

**Comment by master-0098** [comment]
Thank for Helping me, i have another question , also a bug i guess
my questions are , 1- is this possible to add Graphic usage?
2-is this possible to change PS or File System  default location ?(for example start at Desktop)
or shell start at specific driver 
* and the bug or glitch, don't know how to call it , but after you typing something in shell, and try to clear it with command cls , it goes first line, but last command are still there 
[Pic of problem ](https://ibb.co/TvmpHzp)
thanks for helping

**Comment by GitSquared** [comment]
I don't work on this projet much anymore so its unlikely that i'll add a gpu usage monitor (also there pretty much is no space left on the screen rn).

To change the default location use the `cwd` option.

The glitch is interesting, i think it comes from how windows handles clearing the terminal (spoiler: not very well.) I'll look into it, thanks for reporting!
