### ISSUE TITLE
Can't clone repo.

### ISSUE THREAD

**Issue by yuvalabou** [GitSquared/edex-ui#719]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Trying to build from source but cannot clone the repo.
error on terminal -
```
fatal: pack has bad object at offset 779331: inflate returned -5
```

**Comment by GitSquared** [comment]
Could you give the output of:
- `uname -a`
- `git --version --build-options` ?

**Comment by yuvalabou** [comment]
uname -a =
Linux kali 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux

git =
git version 2.24.1
cpu: x86_64
no commit associated with this build
sizeof-long: 8
sizeof-size_t: 8

**Comment by RazuvaevDD** [comment]
This is clearly a problem on your side. Maybe you can help https://stackoverflow.com/questions/57250524/git-clone-fatal

**Comment by RazuvaevDD** [comment]
I think you can close the question, since this does not apply to edex-ui, but the git error.

**Comment by GitSquared** [comment]
Indeed. Thanks for clearing that up @RazuvaevDD
