### ISSUE TITLE
Make the globe map work with actual data

### ISSUE THREAD

**Issue by CrazyPython** [GitSquared/edex-ui#720]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [x] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

The ability to aggregate some sort of log file from each connected server and show it on the world map. Line-by-line JSON format in, aggregated onto the edex-ui map. This would help me monitor my service around the world and monitor bot activity / IDS output.

I'm not sure the most unix-y way way to handle a "side" tty for global/graphical output. It should be line-by-line so pipes can be used. Perhaps the world map is a function of a local file's contents.

**Comment by GitSquared** [comment]
The globe _*does*_ work with actual data (GeoIP and active sockets).
The idea of monitoring log files was previously explored but it turned out too complex (in the context of a cross-platform & unprivileged app). Remote log files? That's going to be tricky.
