### ISSUE TITLE
[feature request] Sixel support!

### ISSUE THREAD

**Issue by Xeddius** [GitSquared/edex-ui#721]
https://github.com/saitoha/libsixel

Most terminal applications already support sixels, I think it'd be a great addition to edex-ui! It can even be used to load graphical applications inside of the terminal.

**Comment by GitSquared** [comment]
We completely rely on [xtermjs/xterm.js](https://github.com/xtermjs/xterm.js), the same terminal frontend that is used by Microsoft's VS Code, to render the terminal in edex.
I've looked around and indeed they seem not to support it. You should open an issue there!

**Comment by Xeddius** [comment]
Unfortunately they've decided to focus on "more important" tasks despite the fact that someone added the feature in a pull request. It's really a bummer because sixel support actually would make the browser-in-edex a viable option along with playing sdl based games like quake directly in the terminal.

**Comment by GitSquared** [comment]
Well, that's a shame. I won't fork xterm just to add this myself...
You should know that this project is in a pretty dormant state right now and it's likely to be labeled as unmaintained soon. I might rewrite everything some day but i have other priorities.
Thanks for opening an issue nonetheless.

**Comment by Xeddius** [comment]
There is an experimental branch that I've discovered with support, it seems to be of a similar codebase to your current setup and should be simple enough to act as a drop-in improvement.

Thank you for working on this project with your free time, life has been quite busy for me lately, hope all is well.
