### ISSUE TITLE
Cant open firefox while edex is running

### ISSUE THREAD

**Issue by Death916** [GitSquared/edex-ui#722]
Anytime i open firefox while edex is running firefox locks up and wont fully open. I haven't been able to find a way around thiis. IM using newest firefox version on windows 10

Technical information
Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

Running on:**
 - [ ] Linux
 - [ x] Windows
 - [ ] macOS

How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

**Comment by GitSquared** [comment]
This is most likely unrelated to the edex software.
