### ISSUE TITLE
Sound bug

### ISSUE THREAD

**Issue by D4rk3rkali** [GitSquared/edex-ui#723]
Im new on kali and i can't hear any sound inside the ui if i run as root i get the error:
XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)
any idea how i can change the permission or any other way to fix it?

**Comment by d4rk3rk4li** [comment]
i lost that account you can close it after i reinstalled now it works

**Comment by d4rk3rk4li** [comment]
reinstalled the OS
