### ISSUE TITLE
edex-ui-git on current manjaro displays black screen

### ISSUE THREAD

**Issue by klandrith** [GitSquared/edex-ui#724]
Displays a black screen, nothing else. No build errors. Ctrl+Q works to quit. Any ideas?

**Comment by GitSquared** [comment]
Probaby a GPU drivers problem. Does Chromium or another electron app work?

**Comment by klandrith** [comment]
Atom is electron isn't it? I can't remember. It works fine.

**Comment by GitSquared** [comment]
It is. Do you get anything on edex when opening the debug tools? (ctrl+shift+i)

**Comment by klandrith** [comment]
Its all blank and says devtools couldn't connect

**Comment by GitSquared** [comment]
Okay. What about in the terminal you launched it from? (if you used a GUI, type `edex-ui` in a term, see what logs it outputs.)

**Comment by klandrith** [comment]
Here you go...Looks like it's unable to start a terminal instance?

[kyle@kyle-z390aorusmaster ~]$ edex-ui
▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.13.0 and Electron 8.2.3
ℹ  info      Renderer is Chrome 80.0.3987.163
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/kyle/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
ℹ  info      Multithread worker started at 2904
ℹ  info      Multithread worker started at 2905
ℹ  info      Multithread worker started at 2907
(electron) The default value of app.allowRendererProcessReuse is
deprecated, it is currently "false".  It will change to be "true" in
Electron 9.  For more information please check
https://github.com/electron/electron/issues/18397
ℹ  info      Multithread worker started at 2910
ℹ  info      Multithread worker started at 2900
ℹ  info      Multithread worker started at 2906
ℹ  info      Multithread worker started at 2909
ℹ  info      Multithread worker started at 2912
ℹ  info      Multithread worker started at 2920
(node:2846) UnhandledPromiseRejectionWarning: Error: listen EADDRINUSE:
address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1300:14)
    at listenInCluster (net.js:1348:12)
    at Server.listen (net.js:1436:7)
    at new WebSocketServer
(/opt/eDEX-UI/resources/app.asar/node_modules/ws/lib/websocket-server.js:75:20)
    at new Terminal
(/opt/eDEX-UI/resources/app.asar/classes/terminal.class.js:1:8389)
    at App.<anonymous> (/opt/eDEX-UI/resources/app.asar/_boot.js:1:6335)
(node:2846) UnhandledPromiseRejectionWarning: Error: listen EADDRINUSE:
address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1300:14)
    at listenInCluster (net.js:1348:12)
    at Server.listen (net.js:1436:7)
    at new WebSocketServer
(/opt/eDEX-UI/resources/app.asar/node_modules/ws/lib/websocket-server.js:75:20)
    at new Terminal
(/opt/eDEX-UI/resources/app.asar/classes/terminal.class.js:1:8389)
    at App.<anonymous> (/opt/eDEX-UI/resources/app.asar/_boot.js:1:6335)
(node:2846) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function
without a catch block, or by rejecting a promise which was not handled with
.catch(). (rejection id: 1)
(node:2846) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function
without a catch block, or by rejecting a promise which was not handled with
.catch(). (rejection id: 1)
(node:2846) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.
(node:2846) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.
ℹ  info      Multithread worker started at 2931
ℹ  info      Multithread worker started at 2908
ℹ  info      Multithread worker started at 2902
ℹ  info      Multithread worker started at 2913
ℹ  info      Multithread worker started at 2924
ℹ  info      Multithread worker started at 2911
☒  complete  Terminal exited { exitCode: 0, signal: 1 } undefined
[kyle@kyle-z390aorusmaster ~]$

**Comment by GitSquared** [comment]
```
Error: listen EADDRINUSE:
address already in use :::3000
```

You have something using up the local port 3000 - probably a development server or something.
You can either find out what it is and shut it down, and change the port eDEX is using for interprocess communications, via the [port option in the settings](https://github.com/GitSquared/edex-ui/wiki/settings.json).

**Comment by klandrith** [comment]
Thanks, I'll give that a go. It may be grafana instance.
