### ISSUE TITLE
Changing settings.json causes edex to fail

### ISSUE THREAD

**Issue by michaelpitts** [GitSquared/edex-ui#725]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [ x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Everything works great when i start edex up for the first time. Only when I change the settings file (I set the default shell to 'fish') and then restart edex, it fails. There is no error message until I go to "quit" the app because the UI doesn't appear. When i quit the app I get an error that says "eDEX-UI crashed - cannot read property 'close' of undefined."

I've found that deleting the UserData/eDEX-UI folder allows the app to start again, but with default settings of course.

How can I change edex settings without causing the app to crash on restart?

Crash screenshots:
<img width="292" alt="Screen Shot 2020-07-06 at 1 10 06 PM" src="https://user-images.githubusercontent.com/30473498/86620446-53c47f00-bf8a-11ea-96a7-36606e4a7243.png">
<img width="532" alt="Screen Shot 2020-07-06 at 1 10 11 PM" src="https://user-images.githubusercontent.com/30473498/86620452-558e4280-bf8a-11ea-9371-9aa3406973c3.png">

**Comment by GitSquared** [comment]
Try launching edex from a terminal and checking the log output there - you might have a formatting issue in the JSON file, or need to put the whole absolute path for the `fish` binary.
