### ISSUE TITLE
Could not install Visual Studio Build Tools.

### ISSUE THREAD

**Issue by kingvagabond** [GitSquared/edex-ui#726]
tried on windows, git clone repo and run npm run install-windows, then hit this error saying

Could not install Visual Studio Build Tools.
Please find more details in the log files, which can be found at
C:\Users\Administrator\.windows-build-tools

**Comment by GitSquared** [comment]
`C:\Users\Administrator.windows-build-tools`

Could you check what's in that folder?

**Comment by WolfeeLuo** [comment]
I also got this error, but when I open the `C:\Users\Administrator.windows-build-tools` path, only found things below.
python-2.7.15.msi and vs_BuildTools.exe, no log file.
But this error didn't break the install process, until it hit another error `'css' is not recognized as an internal or external command, operable program or batch file.`
...

**Comment by GitSquared** [comment]
no answer from OP, likely bad PATH configuration, closing...
