### ISSUE TITLE
Panel overlap on ultrawide screen (21:9 aspect ratio)

### ISSUE THREAD

**Issue by TheNetAdmin** [GitSquared/edex-ui#727]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

I'm using an ultrawide screen (Dell AS3418DW), it's 21:9 aspect ration instead of commonly used 16:9 or 4:3.

When I run the latest eDEX-UI, I find the network panel seems to be overlapped with other panels, see screenshots below. I tried a few built-in themes but none of them works.

I'm pretty new to eDEX-UI, so I'm not sure which part is causing the problem. But it seems the network panel tries to maintain its aspect ration while providing the same width as the system panel.

Maybe the 'world view' and 'network traffic' can be squeezed a little bit to accommodate this overlapping?

Also, is it possible to solve this problem by modifying the theme files, or does it require source code fixes?

![image](https://user-images.githubusercontent.com/18525442/86658979-55983d80-bf9e-11ea-9a69-93641ad425a2.png)
![image](https://user-images.githubusercontent.com/18525442/86659065-6648b380-bf9e-11ea-8ae3-d07f867e4e42.png)
![image](https://user-images.githubusercontent.com/18525442/86659335-a019ba00-bf9e-11ea-9a3b-cbf87a1500ec.png)

**Comment by TheNetAdmin** [comment]
I experimented with `injectCSS` and now completely hide the filesystem and keyboard:

```
"injectCSS": "section#filesystem{display:none;} section#keyboard{display:none;} section#main_shell{height:92vh}"
```

![image](https://user-images.githubusercontent.com/18525442/86665421-782d5500-bfa4-11ea-89ca-2556f720ea9b.png)

This seems to work for now. But I still have some questions:

1. How to configure the number of entries in `mod_toplist_table` in the config files?
2. How to calculate the proper relative height and width for `network panel` in `injectCSS` to prevent overlapping?

**Comment by TheNetAdmin** [comment]
I just played with `injectCSS` and came up with a hacky but usable theme:

1. Make the terminal panel 100% height
2. Put the filesystem panel to the bottom left corner
3. Hide keyboard as my screen is not touch screen

The complete `injectCSS` is:

```
"injectCSS": "section#filesystem{position:absolute; left:0.26vw; top:28vw; width:16vw} section#filesystem>h3.title, section#filesystem>div{width:15.5vw} section#filesystem>h3.title:first-child>p:first-child{display:none} section#filesystem>h3.title:first-child>p:last-child{width:14.5vw; text-align:left} div#fs_space_bar>h3{width:50%} div#fs_space_bar>progress{width:50%} section#main_shell{height:92vh} section#keyboard{display:none;}"
```

The screenshot
![image](https://user-images.githubusercontent.com/18525442/86672813-e1649680-bfab-11ea-8d68-2e5764d3bcb8.png)

**Comment by GitSquared** [comment]
I think 21:9 support was added in the unreleased version (`v3.0.0-pre`).

> How to configure the number of entries in mod_toplist_table in the config files?

This is not currently possible.

**Comment by GitSquared** [comment]
(Thanks for sharing the injectCSS theme!)

**Comment by armadillocommander** [comment]
Another injection I used to keep the keyboard:

`"injectCSS": "section#filesystem{position:absolute; left:0.26vw; top:28vw; width:16vw} section#filesystem>h3.title, section#filesystem>div{width:15.5vw} section#filesystem>h3.title:first-child>p:first-child{display:none} section#filesystem>h3.title:first-child>p:last-child{width:14.5vw; text-align:left} div#fs_space_bar>h3{width:50%} div#fs_space_bar>progress{width:50%} div#mod_conninfo_innercontainer>canvas{height:18vh}  section#main_shell{} section#keyboard{}"
`
