### ISSUE TITLE
Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by evpgh** [GitSquared/edex-ui#730]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [X] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [X] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

I tried installing both from the mac release file and through brew. In both cases, it crashes a second after the UI is shown with the following error message:
![Screenshot 2020-07-07 at 15 53 28](https://user-images.githubusercontent.com/1405162/86784763-8fcf1100-c06a-11ea-8817-22d8aae7e672.png)

**Comment by GitSquared** [comment]
Anything running on local port :3000?

**Comment by evpgh** [comment]
Nope, not this time

**Comment by GitSquared** [comment]
OK. Can you launch the program through a terminal window and tell me what logs you get?

**Comment by evpgh** [comment]
sure
```
/Applications/eDEX-UI.app/Contents/Resources/app.asar/node_modules/systeminformation/lib/cpu.js:254
          result.speed = modelline.split('@')[1].trim();
```
It seems it's because I'm running a hackintosh it fails with the CPU info.

**Comment by GitSquared** [comment]
Unsupported hardware then. You can open an issue [upstream](https://github.com/sebhildebrandt/systeminformation) if you wish.

**Comment by mlch911** [comment]
I'm facing the same issue. Could I run edex-ui without these cpu-info ?

**Comment by GitSquared** [comment]
Well it's open-source, you can always fork it.

**Comment by wishie** [comment]
Simply unpack to app.asar archive inside the eDEX-UI.app edit cpu.js and repackage the app.asar

Here is the changes I made to the cpu.js (the relevant part)

`if (_darwin) {
        exec('sysctl machdep.cpu hw.cpu_frequency hw.cpufrequency_max hw.cpufrequency_min hw.packages hw.physicalcpu_max hw.ncpu', function (error, stdout) {
          // if (!error) {
          let lines = stdout.toString().split('\n');
          const modelline = util.getValue(lines, 'machdep.cpu.brand_string');
          const speedline = util.getValue(lines, 'hw.cpufrequency');
          result.brand = modelline.split('@')[0].trim();
          result.speed = parseFloat(speedline);
          _cpu_speed = result.speed;
          result = cpuBrandManufacturer(result);
          result.speedmin = (util.getValue(lines, 'hw.cpufrequency_min') / 1000000000.0).toFixed(2);
          result.speedmax = (util.getValue(lines, 'hw.cpufrequency_max') / 1000000000.0).toFixed(2);
          result.vendor = util.getValue(lines, 'machdep.cpu.vendor');
          result.family = util.getValue(lines, 'machdep.cpu.family');
          result.model = util.getValue(lines, 'machdep.cpu.model');
          result.stepping = util.getValue(lines, 'machdep.cpu.stepping');
          const countProcessors = util.getValue(lines, 'hw.packages');
          const countCores = util.getValue(lines, 'hw.physicalcpu_max');
          const countThreads = util.getValue(lines, 'hw.ncpu');
          if (countProcessors) {
            result.processors = parseInt(countProcessors) || 1;
          }
          if (countCores && countThreads) {
            result.cores = parseInt(countThreads) || util.cores();
            result.physicalCores = parseInt(countCores) || util.cores();
          }
          // }
          cpuCache().then(res => {
            result.cache = res;
            resolve(result);
          });
        });
      }`
