### ISSUE TITLE
Sudo passwords are made visible due to the on-screen keyboard

### ISSUE THREAD

**Issue by TR-SLimey** [GitSquared/edex-ui#731]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need (also, wants to go to Defcon)
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

As cool as the keys highlighting on screen as you type are, they make it very easy to see someone's password. There's a reason sudo hides it after all. This feature should probably be disabled by default if not removed altogether, though alternatively, there could be a switch to control it (again, off by default).

Other than that, this is a really cool project, thanks for making it. Time to freak some people out :P

**Comment by GitSquared** [comment]
See #394 - you can use Ctrl+Shift+P to enter "Password Mode" and temporarily hide visual keyboard feedback.

**Comment by TR-SLimey** [comment]
Ah yes. Should have check beforehand. Thanks!
