### ISSUE TITLE
How do I manage outgoing traffic? How do I disable ip mapping for uncontrolled traffic leaks?

### ISSUE THREAD

**Issue by RazuvaevDD** [GitSquared/edex-ui#732]
This application reaches the Internet without control and sends tcp packets to unknown ip addresses, although I only prescribed "1.1.1.1" by default. What components require such uncontrolled connection? How do I disable these components? How do I localize data as much as possible?

**Comment by RazuvaevDD** [comment]
P.S. I am delighted with this application, but for some reason, my trust in uncontrolled network applications is undermined. Let's put it this way: by default, except for arp packets, I have nothing running idle on the network. And here is a bunch of tcp packets with unknown content to unknown servers, and i can't stop this mess...

**Comment by GitSquared** [comment]
The only network requests are to the 1.1.1.1 DNS servers to check external network connectivity. You can change the address used for this through the settings - check the github wiki. There might also be some network requests at startup to check for updates.

**Comment by RazuvaevDD** [comment]
Yes, the services the program accesses are freegeoip.app (very active) and api.github.com (at the very beginning). I became calmer, and although I do not trust api.github.com, since the requests go only from the beginning, this is really most likely an update. Thank you, I close the question.
