### ISSUE TITLE
Windows on-screen touch keyboard appears on any touch press

### ISSUE THREAD

**Issue by obezuk** [GitSquared/edex-ui#733]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Hi folks,

I'm testing edex-ui on a Surface Pro 7 and every touch input automatically opens the windows on-screen keyboard interface. This occurs for any press on the entire UI even if it doesn't appear to be a text input (such as touching the clock or globe).

Any idea how to disable it completely while using edex-ui?

**Comment by GitSquared** [comment]
The terminal input is always re-focused to allow for physical keyboard input. I have no control over the OS-level keyboard, but perhaps there is a setting somewhere in Windows you could use to disable the keyboard, perhaps for this specific app...

I don't use Windows myself so I won't be of much help, but if I remember correctly on those kind of 2-in-1 devices there is a "tablet mode" switch which might disable the on-screen keyboard.

**Comment by GitSquared** [comment]
Found a way to fix this!

**Comment by dudeisbrendan03** [comment]
I'm still hit with this issue

**Comment by GitSquared** [comment]
@dudeisbrendan03 what version/hardware?

**Comment by dudeisbrendan03** [comment]
Latest stable, Lenovo IdeaPad Flex 5

**Comment by GitSquared** [comment]
Could you try [this test](https://siennafarflungfield.gitsquared.repl.co/) ?

**Comment by dudeisbrendan03** [comment]
Doesn't trigger my on-screen kb
