### ISSUE TITLE
[MacOS] Can not move the window to another display

### ISSUE THREAD

**Issue by fgheorghe** [GitSquared/edex-ui#735]
Hi all

Couldn't find an answer to this question - I have a 4 monitor set-up and would like to move edex's window to a display other than the main one.

Any clue on how to achieve this? As I can't minimise the window, I can't drag / drop it to a different screen.

I am using MacOS Mojave.

Thank you

**Comment by fgheorghe** [comment]
Nevermind, I found the solution:

- In settings.json, set allowWindowed to true
- Start the app and zoom out
- Drag to desired screen
- Set back to zoom in

**Comment by GitSquared** [comment]
In settings.json, you can also change the `monitor` option to automatically spawn the window somewhere else. Check the github wiki for all the available settings & some explanations.

**Comment by fgheorghe** [comment]
Very nice - thanks for this. My apologies for raising this issue before reading the Wiki. This is an awesome app!

**Comment by GitSquared** [comment]
No problem. Cheers!
