### ISSUE TITLE
[Bug report] Messy hard disk UI

### ISSUE THREAD

**Issue by creativenoobie** [GitSquared/edex-ui#737]
Hey,

Great job! I just tested this and it was really fun to use.

I just wanted to let you know a bug that's ruining UI experience for me.

![Screenshot from 2020-07-09 21-35-29](https://user-images.githubusercontent.com/23532769/87064165-f69c2800-c22c-11ea-89c3-95260bd12ac6.png)

I have attached around 3 disks. Multiple partition. I guess virtual machines partitions are showing up as well. But anyway, I suggest you to add a scrollbar instead of row view for hard disk.

**Comment by GitSquared** [comment]
Wow, that's a *lot* of partitions - indeed didn't think of that edge case yet.

**Comment by creativenoobie** [comment]
Haha. I am sure my virtual images are showing up as well.

**Comment by RazuvaevDD** [comment]
Wow 8O

**Comment by jrens** [comment]
Those look like /snap mounts. One of the very annoying aspects of snaps. I've got the same problem.

**Comment by N1KN1M** [comment]
@GitSquared if the same grid display is fine for disks, I'll put in a pull request.
![grid](https://user-images.githubusercontent.com/37730685/98439223-72907900-2116-11eb-940c-2346de3c7b35.png)

As this is my first experience with open source, it'd be a great first issue too!

**Comment by GitSquared** [comment]
@N1KN1M yes, this would be fine, feel free to submit a PR!
