### ISSUE TITLE
How I Config eDEX-UI For Cygwin64

### ISSUE THREAD

**Issue by Vhenrique05** [GitSquared/edex-ui#739]
I Have A Windows 8 with cygwin on ``D:/cygwin64``<br>
the ``shell`` = ``D:/cygwin64/bin/bash.exe``<br>

my config :
```json
{
    "shell": "D:\\cygwin64\\bin\\bash.exe",
    "cwd": "D:\\cygwin64\\home\\VHenrique05",
    "env": "D:\\cygwin64\\bin",
    "keyboard": "pt-BR",
    "theme": "tron",
    "termFontSize": 15,
    "audio": true,
    "disableFeedbackAudio": false,
    "pingAddr": "1.1.1.1",
    "port": 3000,
    "monitor": 0,
    "nointro": false,
    "nocursor": false,
    "iface": "Npcap Loopback Adapter",
    "allowWindowed": true,
    "excludeThreadsFromToplist": true,
    "hideDotfiles": false,
    "fsListView": false,
    "experimentalGlobeFeatures": false,
    "experimentalFeatures": false
}
```
but when i open eDEX-UI if i try a command : 
```bash
$ ls
```
he say ``bash: ls: command not found``

how i fix ?

**Comment by GitSquared** [comment]
I'm not sure how cygwin works, but i suggest you let `env` be empty and try just putting `"bash.exe"` in the `shell` setting.
Edex's env auto-forwarding might pass your $PATH better.

**Comment by Vhenrique05** [comment]
when i change to ``"shell": "D:\\cygwin64\\bin\\bash.exe"`` opens but not found commands.
when i change to ```"shell": "bash.exe"`` don't open
with ``"env": ""`` and ``"cwd": "D:\\cygwin64\\home\\VHenrique05"``

**Comment by Vhenrique05** [comment]
Fixed ! 
I use :
```bash
 $ set TERM "cygwin"
```

It's all right !
