### ISSUE TITLE
Not starting up

### ISSUE THREAD

**Issue by aritropaul** [GitSquared/edex-ui#740]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

MacBook Air 2017, macOS Catalina 10.15.5

Nothing happens on starting the app.

Console.log reports : Failed to copy signing info for 13718, responsible for file:///Applications/eDEX-UI.app/Contents/MacOS/eDEX-UI: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"

system.log reports : com.apple.xpc.launchd[1] (com.edex.ui.50268[95914]): Service exited with abnormal code: 1

On trying on close the App, I get this.
![Screenshot 2020-07-10 at 11 52 53 AM](https://user-images.githubusercontent.com/15200774/87123180-e5423280-c2a3-11ea-9718-e9048bbbfbd0.png)

**Comment by GitSquared** [comment]
Could you start the app through a terminal and give me the log output from there?

**Comment by aritropaul** [comment]
I tried, but the app just opens, and I don't get any output on the terminal. Is there any particular command that you recommend?

**Comment by aritropaul** [comment]
Got it.
![Screenshot 2020-07-10 at 3 00 08 PM](https://user-images.githubusercontent.com/15200774/87139737-0fa0e980-c2be-11ea-9908-64dec99d636e.png)

**Comment by GitSquared** [comment]
Weird. Normally the next step is to create the terminal process and spawn your shell. Could you give me the contents of `/Users/aritropaul/Library/Application Support/eDEX-UI/settings.json` ?

**Comment by aritropaul** [comment]
```json
{
    "shell": "bash",
    "cwd": "/Users/aritropaul/Library/Application Support/eDEX-UI",
    "keyboard": "en-US",
    "theme": "tron",
    "termFontSize": 15,
    "audio": true,
    "disableFeedbackAudio": false,
    "pingAddr": "1.1.1.1",
    "port": 3000,
    "nointro": false,
    "nocursor": false,
    "allowWindowed": false,
    "excludeThreadsFromToplist": true,
    "hideDotfiles": false,
    "fsListView": false,
    "experimentalGlobeFeatures": false,
    "experimentalFeatures": false
}
```

**Comment by GitSquared** [comment]
OK, pretty standard. Would you have anything running on localhost:3000 by any chance?

**Comment by aritropaul** [comment]
Nope

**Comment by GitSquared** [comment]
Shite. You have node installed?

**Comment by aritropaul** [comment]
Yeah, v14.4

**Comment by aritropaul** [comment]
I tried the 2.2.1 release too, same status.

**Comment by GitSquared** [comment]
The unreleased version might work better, so if you feel like it:

```
git clone https://github.com/GitSquared/edex-ui.git && cd edex-ui
npm run install-linux
npm start
```

**Comment by aritropaul** [comment]
Cool, lemme try this.

**Comment by aritropaul** [comment]
![Screenshot 2020-07-10 at 3 28 00 PM](https://user-images.githubusercontent.com/15200774/87142275-f306b080-c2c1-11ea-9273-9fd4f19d8965.png)

Gets stuck at the same point.

**Comment by GitSquared** [comment]
Well that's disappointing.

You're stuck here: https://github.com/GitSquared/edex-ui/blob/b462528dfda6c90ca6e2e4f3ce0b3c310b2b9766/src/_boot.js#L224

So [shell-env](https://github.com/sindresorhus/shell-env) is fucking up somehow.

You can try the following to hopefully get more info:
```
mkdir test && cd test
npm i shell-env
echo "console.log(require('shell-env').sync('/bin/bash'))" > index.js
node index.js
```

**Comment by aritropaul** [comment]
no output at all

**Comment by GitSquared** [comment]
Can you submit an issue over there then?

**Comment by GitSquared** [comment]
Closed as dependency-related.
