### ISSUE TITLE
Windowed mode is acting all weird.

### ISSUE THREAD

**Issue by chabad360** [GitSquared/edex-ui#743]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Whenever I enter windowed mode I get this weird wobbling: https://imgur.com/kcvKyqI

**Comment by GitSquared** [comment]
It's trying to stay in a 16:9 aspect ratio to not break the UI. Try resizing down the window.

**Comment by chabad360** [comment]
that isn't exactly possible, but disabling 16:9 works.

P.S. Can that be mentioned in the wiki somewhere?
