### ISSUE TITLE
Broken GUI on 49 inches monitor format 32:9 resolution 3840x1080

### ISSUE THREAD

**Issue by alemani** [GitSquared/edex-ui#747]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Using a 49 inches monitor display with 32:9 aspect ratio and a resolution of  3840x1080 pixels.

The GUI is broken on the right side, the keyboard is overlapping the network traffic. Between the file-browser and the keyboard there seems to be extra space.

![eDEX-UI_2020-07-12_overlapping](https://user-images.githubusercontent.com/64167/87249089-63960480-c45d-11ea-82aa-7abab2b06866.png)

**Comment by TheNetAdmin** [comment]
I had a similar problem on 21:9 screen #727 

It is said the 21:9 support is in unreleased code, but I'm not sure about 32:9.

If you'd like a workaround, you may play with the `injectCSS` to customize the UI. I did this and shared my 21:9 `injectCSS` in #727.

**Comment by GitSquared** [comment]
In fact, I have never seen a 32:9 before, so if you'd like to share a photo...

I'll see what I can do for the GUI support.

**Comment by TheNetAdmin** [comment]
Nothing related to tech issues: I always want a 32:9 screen, the 21:9 is already too small for me...

**Comment by alemani** [comment]
> I had a similar problem on 21:9 screen #727
> 
> It is said the 21:9 support is in unreleased code, but I'm not sure about 32:9.
> 
> If you'd like a workaround, you may play with the `injectCSS` to customize the UI. I did this and shared my 21:9 `injectCSS` in #727.

Thanks, will check that (:

**Comment by alemani** [comment]
> In fact, I have never seen a 32:9 before, so if you'd like to share a photo...
> 
> I'll see what I can do for the GUI support.

You mean a photo of the device? I can do that if you really want that but maybe these videos will show it better

This one is in French:
https://youtu.be/KZitwn9ydho?t=19

This one in English same screen but rebranded or maybe mine is the one rebranded:
https://youtu.be/zhdbYAWllF4?t=119

There are not many reviews of this screen right now.

Thanks!

**Comment by Desmo5574** [comment]
I have the same problem.
I have a 37.5" monitor with a resolution of 3840x1600...says it's 21:9
I'll see what I can tinker with in the injectcss

**Comment by GitSquared** [comment]
Will now track this in #832
