### ISSUE TITLE
Upload artifacts to Travis-CI

### ISSUE THREAD

**Issue by TheNetAdmin** [GitSquared/edex-ui#748]
**Perceived idea awesomeness**
- [x] Wow, you don't have this yet???
- [ ] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [x] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

I noticed this repo is using Travis-CI for Windows, macOS, and Linux CI tests.

Would it be possible to build installer packages in CI and upload them as [Travis-CI artifacts](https://docs.travis-ci.com/user/uploading-artifacts/)?

In this case, users do not need to build from source if they want the latest unreleased edex-ui, they can just download installers from Travis-CI.

**Comment by Jabster28** [comment]
Should be closed now, since we've moved to GH Actions
