### ISSUE TITLE
On-screen keyboard shows typing during password input, prevent this?

### ISSUE THREAD

**Issue by redbrain** [GitSquared/edex-ui#751]
I assume this is more of an idea or feature request, but it seems smart to prevent the on-screen keyboard from showing keypresses while a user is entering their password. For example, while using sudo to run a program as root, the password entry is shown on the on-screen keyboard. A possible solution is to detect when the program running is sudo or the like and stop displaying keypresses during that time.

**Comment by GitSquared** [comment]
Duplicate of #394
