### ISSUE TITLE
Xfinity warning that I'm participating in a targeted attack

### ISSUE THREAD

**Issue by ErkanSensei** [GitSquared/edex-ui#752]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

So my xfinity app kept telling me that my device was part of a targeted attack against a certain IP, and for a few days the IP was the same, but then today it informed me that I was attempting to attack yet another IP. After some digging, I've determined that the IP in question is being "attacked" by edex-ui. Any idea why this might be happening?

![Screen Shot 2020-07-19 at 2 50 50 PM](https://user-images.githubusercontent.com/17013914/87886052-e6bfd900-c9ce-11ea-9466-00a635379276.png)

**Comment by amahlaka** [comment]
It looks like that ip belongs to https://freegeoip.app website.
I think that the connection map is making so many requests there that it may trigger a DOS filter on your ISP's system

**Comment by amahlaka** [comment]
It would be best if edx would use a local geoip database instead of an api to get the rough location of IP addresses to show on the map, to avoid these sort of issues in the future

**Comment by GitSquared** [comment]
> It looks like that ip belongs to https://freegeoip.app website.

Yup, that's it.

> I think that the connection map (The globe on the sidebar) is making so many requests to the website that it may trigger a DOS filter on your ISP's system

It is using the geoip service to locate and position on the globe the IP addresses of everything you currently have an open socket with on the WAN.

Locations are cached to avoid overloading the service, but it is indeed making requests very frequently.

> It would be best if edx would use a local geoip database instead of an api to get the rough location of IP addresses to show on the map, to avoid these sort of issues in the future

This is how it works in the current (yet unreleased) version (cf. commit 24b9142, issue #564).
