### ISSUE TITLE
Setting for default monitor is ignored

### ISSUE THREAD

**Issue by jsuelwald** [GitSquared/edex-ui#755]
Hi,

Using Ctrl-Shift-S I tried to set the default Monitor (i have 3 Monitors, so "0","1","2" is availible. Regardless of the setting Edex-ui always starts on Display "0"

## Technical information
**Using version:**
 - [x] `latest` (latest release, currently `v2.2.2`)

**Running on:**
 - [x] Windows, 20.04, Pro, Build 19041.388, German, 64bit

Having 3 displays:
0 - 3840x2160 (landscape)
1- 1920x1080 (landscape)
2 - 1080x1920 (portrait, rotated)

**Comment by GitSquared** [comment]
(closing as v2 will not be supported, see #769... sorry)
