### ISSUE TITLE
Application won't start on Windows 10

### ISSUE THREAD

**Issue by clavis33** [GitSquared/edex-ui#756]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)

Application will straight-up not run. Used installer. Windows 10, 32 bit, 10.0.18362 build 18362.
Shows up on task manager for 3 seconds, then disappears. Lasts for 6-7 seconds when running as Administrator.

**Comment by GitSquared** [comment]
No support for v2 unfortunately. See #769.
