### ISSUE TITLE
Enable customization of Mfr., Model and Chassis description

### ISSUE THREAD

**Issue by Strykar** [GitSquared/edex-ui#757]
On a self-assembled machine like mine (and a majority of linux desktop users I'd imagine), there is no data shown for `Manufacturer`, `Model` and `Chassis`.
It would be nice if the user could add this in themselves instead of being blank.

See https://i.imgur.com/1mDbgWw.png

**Comment by geosp** [comment]
I will be submitting a PR for this feature soon. I have the same issue.

**Comment by furriephillips** [comment]
Seems like those values are from the BIOS, set by OEMs, I'd love it if the rubbish ones I have, could be overridden & my desired values displayed, instead.

Here's where they're probably harvesting the data from: -
`% sudo dmidecode -t system
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 3.1.1 present.

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: System manufacturer
	Product Name: System Product Name
	Version: System Version
	Serial Number: System Serial Number
	UUID: 88eafb58-bdbc-22d8-9e2e-049226d4b4b8
	Wake-up Type: Power Switch
	SKU Number: SKU
	Family: To be filled by O.E.M.
`
