### ISSUE TITLE
Sounds when changing directory don't stop

### ISSUE THREAD

**Issue by Kruemmelspalter** [GitSquared/edex-ui#758]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
The harddrive sound when the contents of the current directory are listed don't stop.
[Video](https://drive.google.com/file/d/1fbQg8VuKvLywGnRyo_cbdXb9X8ADmlOz/view?usp=sharing)

**Comment by saleh1100** [comment]
Hi

**Comment by saleh1100** [comment]
Gh

**Comment by saleh1100** [comment]
Hi

**Comment by saleh1100** [comment]
T@[](https://accounts.livechat.com/join?access_token=dal:5PbK42QfT6m-d-cYRGTQcQ)

**Comment by sfjuocekr** [comment]
I get the exact same thing, it is refreshing the directory over and over.

**Comment by wrac4242** [comment]
I am also getting this issue, from a fresh install of mint, and a fresh install of the software.
Occurs only in the users home directory as far as i can tell, in entering another directory the sounds do stop

**Comment by rodrigovssp** [comment]
#up

Em Ter, 10 de nov de 2020 20:11, Gaby <notifications@github.com> escreveu:
