### ISSUE TITLE
remote SSH clear doesn't clear the screen

### ISSUE THREAD

**Issue by Hackmastr** [GitSquared/edex-ui#761]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [x] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Hello, 

When ssh'ing into a remote unix server, using the command [clear ](https://linux.die.net/man/1/clear), using normal command line apps (powershell, cmd...) this command works as it should: clear the screen. However, using Edex doesn't, it returns to the first line on the window, but the previous text remains on the screen.

Running v2.2.2.

Thanks.

![image](https://user-images.githubusercontent.com/9281515/92331842-ba911200-f079-11ea-9908-581376b249a0.png)

**Comment by GitSquared** [comment]
Should be fixed with recent xterm.js upgrades. Please reopen if needed.
