### ISSUE TITLE
CPU(s)

### ISSUE THREAD

**Issue by Tomcatt** [GitSquared/edex-ui#764]
**Perceived idea awesomeness**
- [*] Wow, you don't have this yet???
- [*] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [*] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

(Write your idea or a feature request here)

Hello, I run quad or dual setup CPU systems and would like to see your UI support them, please?

Thanks,
-TomCatT

**Comment by GitSquared** [comment]
They are supported, although for UI reasons the app doesn't display more than 2 graphs (it adds multiple lines in each graph that are synced to each cpu).
