### ISSUE TITLE
Onscreen keyboard arrow keys result typeError.

### ISSUE THREAD

**Issue by ZZZXXX0110** [GitSquared/edex-ui#765]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Below errors show up when touching any of the arrow keys on the on-screen keyboard.
![Screenshot 2020-09-14 at 13 57 22](https://user-images.githubusercontent.com/37162057/93121142-677b1880-f692-11ea-806c-754fe9e9d804.png)

**Comment by GitSquared** [comment]
What keyboard layout are you using?

**Comment by SamLukeYes** [comment]
> What keyboard layout are you using?

The same problem with both `edex-ui` and `edex-ui-git` installed from AUR.
My keyboard layout is en-US. Also tried en-GB with `edex-ui-git` but that didn't help.

**Comment by janhellmig** [comment]
The same problem only by using Touch not mous or keyboard.

**Comment by GitSquared** [comment]
v2 is not supported anymore, unfortunately, this is unlikely to get fixed. See #769.
