### ISSUE TITLE
quit unexpectedly mac catalina

### ISSUE THREAD

**Issue by piyushwalia** [GitSquared/edex-ui#766]
Process:               eDEX-UI [6965]
Path:                  /Applications/eDEX-UI.app/Contents/MacOS/eDEX-UI
Identifier:            eDEX-UI
Version:               2.2.2 (2.2.2.1702)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           eDEX-UI [6965]
User ID:               501

Date/Time:             2020-09-15 04:13:14.886 +0530
OS Version:            Mac OS X 10.15.5 (19F101)
Report Version:        12
Anonymous UUID:        8F9B0AE8-0690-6D80-6B51-19BA58E56269

Sleep/Wake UUID:       73BEE65D-1C83-4C7F-8B64-4A599DF969DD

Time Awake Since Boot: 71000 seconds
Time Since Wake:       7000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000600020000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [6965]

## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [X] macOS

**Comment by GitSquared** [comment]
Sorry, closing as v2 is now unsupported - see #769
