### ISSUE TITLE
Improved brightness and settings functionality

### ISSUE THREAD

**Issue by SergioTar** [GitSquared/edex-ui#770]
I would like to suggest that you pay more attention to the brightness of the result labels in "World View" and "Network Traffic" - it is difficult to read the values ​​even in the dark, regardless of the chosen theme.
And also make the "default" active panel not on the whole screen and the "minimize" function.
If possible, consider how you can return the "previous" panel - set the arrow (function) "back". When you select one of the themes, the icons disappear and it is not possible to continue working with the program fully, and with such a function, everything could be quickly restored.
Thank you for your attention and your great Sai-Fi looks like program.

**Comment by GitSquared** [comment]
> And also make the "default" active panel not on the whole screen and the "minimize" function.

Could you elaborate on this? I don't really understand

**Comment by GitSquared** [comment]
Closed as stale...
