### ISSUE TITLE
Support Cmder Terminal/Shell on Windows

### ISSUE THREAD

**Issue by milesje** [GitSquared/edex-ui#771]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [X] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [X] Shouldn't be too hard to make.
- [X] Like, *I* could do it.

---
It would be really nice to have support for using Cmdr (https://cmder.net/) as the shell. I use this shell/terminal exclusively on Windows as it has git-for-windows and most *nix commands work out of the box with it. At the moment if you set the "shell" to Cmder in the settings it launches the Cmdr window and e-DEX-ui attempts to start and then just closes with no visible error or warning.

**Comment by GitSquared** [comment]
eDEX's interactions with the shell of your choosing are very low-level & standardized (std[in/err/out] pipes).
What you're experiencing is that Cmdr is a shell and a terminal emulator bundled together - you need to tell it to lose the terminal emulator part as that will be provided by eDEX.

From a quick search through their documentation, I found [instructions for setting Cmdr up with Hyper](https://github.com/cmderdev/cmder/wiki/Seamless-Hyper-integration) that should help you.
Hyper is built with pretty much the same tech as eDEX, all you need is to find the corresponding configuration settings, [our documentation is here](https://github.com/GitSquared/edex-ui/wiki/settings.json).

Hope this helps!

**Comment by AldenBluetenberger** [comment]
okay so i'm doing what they say to do in the hyper instructions but it fucks up on finding the shell.

> (node:1592) UnhandledPromiseRejectionWarning: Error: not found: Cmder.exe /k D:\cmder\vendor\init.bat
    at getNotFoundError (C:\Users\merk a holic\edex-ui\src\node_modules\which\which.js:10:17)
    at C:\Users\merk a holic\edex-ui\src\node_modules\which\which.js:57:18
    at new Promise (<anonymous>)
    at step (C:\Users\merk a holic\edex-ui\src\node_modules\which\which.js:54:21)
    at C:\Users\merk a holic\edex-ui\src\node_modules\which\which.js:71:22
    at new Promise (<anonymous>)
    at subStep (C:\Users\merk a holic\edex-ui\src\node_modules\which\which.js:69:33)
    at C:\Users\merk a holic\edex-ui\src\node_modules\which\which.js:80:22
    at C:\Users\merk a holic\edex-ui\src\node_modules\isexe\index.js:42:5
    at C:\Users\merk a holic\edex-ui\src\node_modules\isexe\windows.js:36:5

**Comment by Ahmad53Bello** [comment]
Great
