### ISSUE TITLE
Panic when entering directories containing Chinese characters

### ISSUE THREAD

**Issue by chriscainx** [GitSquared/edex-ui#774]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)

See the screenshot: very self-explanatory...
<img width="1792" alt="Screen Shot 2020-09-27 at 17 52 43" src="https://user-images.githubusercontent.com/8361080/94361972-abd2d380-00ea-11eb-868e-f6e571198089.png">
<img width="1792" alt="Screen Shot 2020-09-27 at 17 52 49" src="https://user-images.githubusercontent.com/8361080/94361977-b42b0e80-00ea-11eb-8631-812c219259ab.png">

**Comment by GitSquared** [comment]
Apologies, v2 is unsupported, see #769
