### ISSUE TITLE
[macOS] press Command + "some key" will stuck the key on virtual keyboard.

### ISSUE THREAD

**Issue by VergeDX** [GitSquared/edex-ui#775]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

In the software, press `Command + some key` will stuck the key on the virtual keyboard, like this:
(I press the `Command + w` and the w key is stuck, but press the w key again will fix it)

![image](https://user-images.githubusercontent.com/25173827/94362626-53520500-00ef-11eb-8522-55f4f0f67c0c.png)

**Comment by VergeDX** [comment]
@GitSquared

**Comment by GitSquared** [comment]
Noticed, but please see #769

**Comment by saleh1100** [comment]
Do you know PUBG￼
