### ISSUE TITLE
UI Components overlap on ultra-wide display

### ISSUE THREAD

**Issue by armadillocommander** [GitSquared/edex-ui#776]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

On 21:9 ultra-wide display, the network monitor overlaps with the keyboard. This effects all the build-in theme with keyboard.

![Screen Shot 2020-09-29 at 10 55 07 PM](https://user-images.githubusercontent.com/35280275/94648584-b5ee0100-02a7-11eb-99aa-ad9fe5c6aade.png)

**Comment by bjtho08** [comment]
I can confirm this also exists on Ubuntu 18.04 with v2.2.2

**Comment by Jr7000750** [comment]
Oké i will download that.


Verstuurd vanaf mijn iPhone

**Comment by GitSquared** [comment]
Will now track this in #832
