### ISSUE TITLE
Set cwd to some path in WSL

### ISSUE THREAD

**Issue by FlyinCow** [GitSquared/edex-ui#778]
**Perceived idea awesomeness**
- [x] Wow, you don't have this yet???
- [ ] Would be super cool.
- [x] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Currently I can set `shell` to `wsl.exe` to use wsl, but I can't set `cwd` to, like, `~`, or `\\wsl$\home\<username>`, just like windows terminal. And sadly there seems no way to infer paths in wsl under Windows.

**Comment by renanyanez** [comment]
@FlyinCow  i set my shell to wsl.exe and left the cwd alone.. with the preset windows directory and i can load the UI in my wsl kali distro and pulls up my MNT user directory to that app data folder.

not sure if you were able to get this going with your set up.  here is what i have on the json file:
```
    "shell": "wsl.exe",
    "cwd": "C:\\Users\\<namehere>\\AppData\\Roaming\\eDEX-UI",
    "keyboard": "en-US",
```

**Comment by G1itcher** [comment]
Use the windows location for the folder, i.e.:
To use my account home I've set it to:
```\\wsl$\Ubuntu\home\g1itcher```

**Comment by dudeisbrendan03** [comment]
> @FlyinCow i set my shell to wsl.exe and left the cwd alone.. with the preset windows directory and i can load the UI in my wsl kali distro and pulls up my MNT user directory to that app data folder.
> 
> not sure if you were able to get this going with your set up. here is what i have on the json file:
> 
> ```
>     "shell": "wsl.exe",
>     "cwd": "C:\\Users\\<namehere>\\AppData\\Roaming\\eDEX-UI",
>     "keyboard": "en-US",
> ```

Have you managed to get the tracking to work?

**Comment by GitSquared** [comment]
> Have you managed to get the tracking to work?

If you're talking about file browser CWD tracking, it's impossible on Windows so... don't get your hopes up

@FlyinCow did any of the solutions proposed here worked for you?

**Comment by dudeisbrendan03** [comment]
> > Have you managed to get the tracking to work?
> 
> If you're talking about file browser CWD tracking, it's impossible on Windows so... don't get your hopes up
> 
> @FlyinCow did any of the solutions proposed here worked for you?

If there are plans to add features for WSL should I be fine to open an issue for a feature request, tracking paths in wsl?

**Comment by GitSquared** [comment]
Tracking cwd just can't be done on Windows, it's a platform limitation. Unix has sysfs file descriptors where we can read cwd's of TTY processes, but the NT kernel is much less focused on TTYs so the information is simply not available afaik.

Only recently has Microsoft started working on improving the terminal experience on win, *nix platforms have been built for and with CLI interfaces for the past three decades. There's not much I can do.
