### ISSUE TITLE
Touching screen causes OS virtual keyboard to pop up

### ISSUE THREAD

**Issue by MCSeekeri** [GitSquared/edex-ui#779]
**Perceived idea awesomeness**
- [x] Wow, you don't have this yet???
- [ ] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---
When I used eDEX UI on a touch screen Windows 10 device, I found that the keyboard on the interface was not usable. After clicking, the osk.exe that comes with Windows would appear, which greatly affected the user experience.
I hope to make the keyboard on the interface a real *keyboard*, not just a decoration.

I am very sorry that I cannot speak English fluently, so I used Google Translate. I am sorry for the low readability caused by the translation.

**Comment by MdBillalKazi191** [comment]
mdbillalkazi191@gmail.com

**Comment by GitSquared** [comment]
#733
