### ISSUE TITLE
Possibility to use cmd as administator as the shell.

### ISSUE THREAD

**Issue by Julienraptor01** [GitSquared/edex-ui#780]
I can use cmd as shell and i am on a administator account but even if i launch eDEX-UI with administrator rights i can't execute commands who needs administrator rights.
So did i missed something or is there a possibility to set a parameter for the shell setting to be able to execute commands who needs administrator rights ?
"Edited" (i'm on Win 10)

**Comment by NyTR0SGaM1NG** [comment]
I too would like to know if this is possable. im trying to connect to a bbs but it wont let me as i get the "could not open connection to the host, on port 23 connection failed" error. probably something entirely different but idk.

**Comment by GitSquared** [comment]
The default windows terminal/shell experience is - to be polite - absolute trash. If you can't use something like WSL or "Git bash", I recommend trying [gsudo](https://github.com/gerardog/gsudo) for elevating permissions in a shell.
