### ISSUE TITLE
Latest Release (Windows) is Running Terribly

### ISSUE THREAD

**Issue by NK01** [GitSquared/edex-ui#781]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
The problem is basically a repeat of issue #238 . After starting it immediately redlined the CPU at a constant 100% with 60-75% of that being the exe. On my machine it chewed up over 2 GB of RAM before I closed it.
![IssueWithCurrentRelease](https://user-images.githubusercontent.com/52008914/96673691-038af480-13a2-11eb-84a8-03e60719e0a8.JPG)

WMIC/wmiprvse runs wild.
(Write your report here)

**Comment by NK01** [comment]
Sorry, forgot to mention system spec

OS: Windows 10 x64
CPU: intel core i5-5200U (2 cores-4 threads) (2.2GHz)
RAM: 16 GB
GPU: GeForce 940M

**Comment by GitSquared** [comment]
Sorry, no support for v2... see #769
