### ISSUE TITLE
Vim causes clicking sound to loop

### ISSUE THREAD

**Issue by ManBearPigg** [GitSquared/edex-ui#782]
If you press enter in the terminal to generate a new line, it does a clicking sound. On Ubuntu, when I open vim, it repeats that same sound quickly on a loop. I like the sounds and don't want to disable them but can't listen to that.

**Comment by Abdullah-Asaad** [comment]
Good

**Comment by GitSquared** [comment]
Disable audio feedback sounds in the settings, its bcuz vim keeps printing a new screen which is picked up by edex as terminal output
