### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by abood1703** [GitSquared/edex-ui#787]
Can we change the theme of edex?? Like completely shades of red?

**Comment by yochliu8** [comment]
> Can we change the theme of edex?? Like completely shades of red?

**Comment by Darateja** [comment]
Please help I need 10000, thousands money urgently please help

**Comment by 69DarkHunter69** [comment]
Ok im back

**Comment by 69DarkHunter69** [comment]
Me need ur help guys

**Comment by anjodewis82** [comment]
what do you need?

Em sáb, 24 de out de 2020 6:30 PM, 69DarkHunter69 <notifications@github.com>
escreveu:
