### ISSUE TITLE
Hu

### ISSUE THREAD

**Issue by Lcswtl** [GitSquared/edex-ui#792]

**Comment by parkerlreed** [comment]
What's up with all these spam issues?

**Comment by GitSquared** [comment]
> What's up with all these spam issues? 

@parkerlreed I have no clue. Reported some to GitHub Support but there isn't much one can do.

**Comment by parkerlreed** [comment]
> > What's up with all these spam issues?
> 
> @parkerlreed I have no clue. Reported some to GitHub Support but there isn't much one can do.

I think it's people/bots spamming for Hacktoberhest. I saw a little at the beginning of the month but jeeze it sure seems to be picking up.

**Comment by Jr7000750** [comment]
My kodi is not connected en i cant log in To watch mobiel with the OPEC / Exodus program
