### ISSUE TITLE
No Intro

### ISSUE THREAD

**Issue by SkeleBones** [GitSquared/edex-ui#793]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

The toggle for the intro animation is blocked with a CLI flag. [Screenshot](https://imgur.com/a/wIuRcwg)

**Comment by Darateja** [comment]
Please give me 10000 money 💰 help me

**Comment by HydraMaster** [comment]
same problem, it doesn't open

**Comment by GitSquared** [comment]
Edit the package.json file https://github.com/GitSquared/edex-ui/blob/11bd576a0fcc62679b1d653cf38018d407b46b63/package.json#L16 and remove the `--nointro` flag there. Apologies, that's a leftover from before the NoIntro saved option was added to settings, and when hacking on the software you don't want to see the intro sequence every 5s.

I'll accept any PR removing the flag from there, if you want.

**Comment by HydraMaster** [comment]
I removed the --nointro flag but it still doesn't open, it runs but doesn't
show anything. What sould i do? I'm at win8.1

Em ter., 27 de out. de 2020 às 17:11, Gaby <notifications@github.com>
escreveu:

**Comment by GitSquared** [comment]
Separate issue.

**Comment by SkeleBones** [comment]
That worked, thanks.
