### ISSUE TITLE
Settings and Shortcuts Pop-ups

### ISSUE THREAD

**Issue by SkeleBones** [GitSquared/edex-ui#794]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

The settings and shortcuts pop-ups do not appear in the middle of the screen. Instead, they sometimes appear in the bottom right corner or semi in the middle but too far down to where the save and reload functions are not visible.

**Comment by GitSquared** [comment]
Fixed in #841
