### ISSUE TITLE
frezez mid load but sound efects continue then the window frezes completelly with error about filesystem

### ISSUE THREAD

**Issue by LucaTheHackerAndMusician** [GitSquared/edex-ui#797]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ *] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [* ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [* ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)
![image](https://user-images.githubusercontent.com/73563434/97372343-56d1db00-18ab-11eb-803a-de34617e8213.png)

when I open the app, everything is normal until it frezes mid load(visuals) but the sounds finish as if the program did not freze up. then it spits out an eror mesage below.
![image](https://user-images.githubusercontent.com/73563434/97372492-add7b000-18ab-11eb-8388-48f890494c6f.png)
this completely could just be my fault as I had to fix windows with medea creation tool (because of a "corrupted windows image")
I am also having some other random problems loading (other) apps but it is highly likely it is just bugs in the win10 20h2 update I just did(with medea creation tool for reasons above).

**Comment by LucaTheHackerAndMusician** [comment]
Oh yeah, I really like the app so keep it up but plz fix the problem. email me @ lb111222j@ gmail.com if u find a fix :D

**Comment by ristar571** [comment]
Hello I'm new in hacking please please help me to learn coding
