### ISSUE TITLE
Uncaught Error: connect ECONNREFUSED 0.0.0.0:443

### ISSUE THREAD

**Issue by Boltzmachine** [GitSquared/edex-ui#798]
Get an error pop-up
in the original terminal:
```
✖  error     Error: connect ECONNREFUSED 0.0.0.0:443: Uncaught Error: connect ECONNREFUSED 0.0.0.0:443
⬤  debug     at events.js 200:7
 ECONNREFUSED 0.0.0.0:443
```

system:
Arch Linux 5.8.7

**Comment by GitSquared** [comment]
Did you change the `port` setting?

**Comment by Boltzmachine** [comment]
No. Is it the problem of my network?

**Comment by GitSquared** [comment]
Probably. Edex doesn't try to connect to :443-anything. Please reopen if reproduced on master in a sane env.
