### ISSUE TITLE
How can i make it use my PS1?

### ISSUE THREAD

**Issue by Bynar0b11001001** [GitSquared/edex-ui#801]
The dark blue color is really hard to see in the PS1. How can i customize the PS1 or make it use mine? (PS1 is the prompt string 1 in bash)

**Comment by GitSquared** [comment]
Use true colors terminal codes to style your PS1, edex is true color-compatible.

**Comment by Bynar0b11001001** [comment]
Yea but where do i put them? What file does edex keep the PS1 style in? And is there a way to just make it use my actual ps1 style? (the one in the ~/.bashrc file)

**Comment by GitSquared** [comment]
Same as your usual bash config. eDEX doesn't change any of that, it just applies a filter to all the colors in the ascii 256-colors range.

**Comment by Bynar0b11001001** [comment]
is there a way to make it not apply a filter to the ps1?

**Comment by GitSquared** [comment]
Nope. Just modify the color sequences in your PS1 (`\033[e3;m` and the like) to output 24-bit colors instead. See [this stackoverflow answer](https://unix.stackexchange.com/a/404415/278039), and [more technical info on wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#24-bit).

**Comment by Bynar0b11001001** [comment]
I use this, isn't it 24 bit?
`PS1='\[\e[38;5;195m\][\[\e[38;5;226m\]\u@\[\e[91m\]\h \[\e[38;5;118m\]\w\[\e[38;5;195m\]]\[\e[38;5;87m\]$ '`
