### ISSUE TITLE
"TypeError: e.indexOf is not a Function" when opening another console tab

### ISSUE THREAD

**Issue by TikkaSenpai** [GitSquared/edex-ui#803]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows 10
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Cant open more console tabs. The only tab available is the main one. The Problem only occurs when any form of colorfilter is used on a theme.
Error Message:

"TypeError: e.indexOf is not a Function
at file///C:/Users\[ME]/AppData/Local/Programs/edex-ui/resources/app.asar/classes/terminal.class.js 1:776"

**Comment by GitSquared** [comment]
v2 is not supported: #769
