### ISSUE TITLE
Segfault on ARM64 and ARMV7L

### ISSUE THREAD

**Issue by coreyfro** [GitSquared/edex-ui#804]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [X] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Thanks to the fine work of @thallada, I was able to get edex-ui compile on Raspberry Pi under both ARM64 and ARMV7L.  Under either architecture, when I execute the 'AppImage' I get to the status "pending Creating new terminal process on port 3000". Shortly thereafter, it segfaults.

Apart from some path changes and having to "#include <sys/sysmacros.h>" in both mksquashfs.c and unsquashfs.c, I followed their instructions to the T.

I understand @GitSquared is very busy (no doubt bringing their awesomeness to more important problems ;-) and does not have such a platform to work from.  Please let me know what information I can extract from the system regarding the segfault to aid in more easily debugging this problem.

`▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.14.1 and Electron 9.3.1
ℹ  info      Renderer is Chrome 83.0.4103.122
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/pi/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
Segmentation fault
pi@raspberrypi:~/build/edex-ui/dist $`

**Comment by paulwratt** [comment]
@coreyfro where are you on this. I cant see a repo on your end. I can probably fix #818 (which builds further that v2.2.2 without the bogus errors)

**Comment by GitSquared** [comment]
https://github.com/GitSquared/edex-ui/issues/818#issuecomment-721233195

Looks like it works on v3 with some tweaking. Closing this.
