### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by Bynar0b11001001** [GitSquared/edex-ui#806]
I tried overriding my username in eDEX, but the settings is missing. The last settings option i see is `experimentalFeatures`. I tried adding `"username": "new_name"` into `settings.json` but that didn't work.How can i fix?

**Comment by GitSquared** [comment]
There is no such setting. See #450

**Comment by Bynar0b11001001** [comment]
yes there is, the wiki says so. Also i meant to say that the settings between `experimentalFeatures` and `allowWindowed` are missing

**Comment by GitSquared** [comment]
@Bynar0b11001001 apologies, that actually exists, but it's v3 only.

**Comment by Bynar0b11001001** [comment]
How do i get v3?

**Comment by GitSquared** [comment]
you have to compile from source, check the readme... it's a bit more involved than just downloading binaries unfortunately.
