### ISSUE TITLE
UTF-16 support

### ISSUE THREAD

**Issue by jonathanschaaij** [GitSquared/edex-ui#807]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
The terminal does not support UTF-16 (chinese characters and emoji) yet, They are rendered, but they are overlapping half way. Should not be a very difficult fix I assume

**Comment by i0ntempest** [comment]
I haven't tried emojis but Chinese characters display just fine for me. I'm on macOS .

**Comment by oobe** [comment]
Can not input Chinese characters in command line, also can not show correct Chinese characters(show as "????").

Platform: MacOS 10.15.7
Version: 2.2.2

**Comment by GitSquared** [comment]
If this still doesn't work on v3, you'll have to check upstream with the [xterm project](https://github.com/xtermjs/xterm.js).
