### ISSUE TITLE
Log checking

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [GitSquared/edex-ui#809]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [x] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [x] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

(Write your idea or feature request here)

Every sysadmin has one thing they should check every now and then. That's the LOGS! The logs show us what users have been doing, if there's been an intrusion and where, etc. For linux there's the famous /var/log/auth.log. This shows failed logon attempts from local system, ssh, etc. That can be used to detect bruteforce attempts (Personally ran an ssh server, had a lot of bruteforce attempts from china for some reason). Snort can detect malicious traffic, portscans, signitures, etc (snort is amazing for sysadmins). 

Point is. Can we have a log checking system? Maybe pop an alert if bruteforce has been detected? Im just throwing ideas here.

**Comment by GitSquared** [comment]
I toyed with this idea years ago (9b55675) before anyone noticed what i was doing in this github repo lol.
Unfortunately, it's very hard to develop a cross-platform solution for this, so the widget was eventually scrapped.

Cross-platform interoperability is very important for this project as it's one of the big differences it has with the original DEX-UI, and a lot (~50%) of people trying this out are on Windows. ~~Poor them.~~

> Personally ran an ssh server, had a lot of bruteforce attempts from china for some reason)

Got to love bots! That's why most people install something like fail2ban.

**Comment by KittyTechnoProgrammer** [comment]
By cross-platform solution do you mean one function that can work on both Windows, linux, etc. Without having to check the OS that eDEX is running on, thus not needing to use a different method of log checking ?

P.S. ~50% of people trying this are on Windows!  When (not saying if, because I have faith in you) eDEX becomes more of a sysadmin tool. I can understant that. As most corporate computer systems are running windows. However I would've expected a project like this to have more fans that run Linux.

**Comment by GitSquared** [comment]
> Without having to check the OS that eDEX is running on

No, doing that is not problem, but i struggled to find some interesting logs that i could programmatically show on win32 - the platform doesn't have a real good cli equivalent of `dmesg` or `journalctl`.

> However I would've expected a project like this to have more fans that run Linux.

Me too! But i've learned that the "wow factor" of edex attracts a lot of unexperienced people. If you saw that I recently started partnering with an online programming courses startup, that's also a strong motivator: over the years a lot of people have been motivated to try & dig deeper into the hacking world thanks to this project, and that's something i'm really happy about.

**Comment by KittyTechnoProgrammer** [comment]
I don't know if you know memes, but you are a good man. Thank you.

Now. I really am not good in JavaScript cause my field doesn't require it. It's more backend. Golang being my current favorite. However, I do know that golang can be used as a backend for electron applications.

If I were to pitch in on this. Would it matter if I used golang, or do you want to keep this completely JavaScript?

**Comment by GitSquared** [comment]
It's going to be a real pain to write a go module with javascript interoperability, but by all means feel free to try it!..

**Comment by KittyTechnoProgrammer** [comment]
If i may ask. How did you do the CSS? Did you use software like dreamweaver, or did you code it all by hand?

**Comment by focosin93** [comment]
By hand

**Comment by KittyTechnoProgrammer** [comment]
If i may ask. How did you do the CSS? Did you use software like dreamweaver, or did you code it all by hand?

**Comment by KittyTechnoProgrammer** [comment]
That must've took a long time. If, and when I pitch in I'll have to remember that,
