### ISSUE TITLE
Network related UI Tools

### ISSUE THREAD

**Issue by deathjHK** [GitSquared/edex-ui#810]
Hey!
So I came across eDEX a few days ago and everything is working like a charm and I'm really pleased with it, except for one thing.
As soon as I connect to my vpn (NordVPN // Double_VPN Group) all the network related ui tools just switch to telling me that I'm offline, which I'm not.
I've tried to work around it but I don't seem to get it working with my vpn.
I would be really glad if someone could help me to get this working.

+ Latest eDEX version (2.2.2)
+ Kali Linux 2020.3
+ Correct network interface is selected (wlan0)

**Comment by GitSquared** [comment]
If your VPN app is using OpenVPN under the hood, it might be creating a new network interface to proxy all traffic through... You should double-check that you don't have a new available iface if you launch edex after activating the vpn.

**Comment by CMProjects7-8** [comment]
I have the same bug on mine

**Comment by deathjHK** [comment]
> 
> 
> If your VPN app is using OpenVPN under the hood, it might be creating a new network interface to proxy all traffic through... You should double-check that you don't have a new available iface if you launch edex after activating the vpn.

Worked for me, thank you. OpenVPN actually created a new one that didn't show up when eDEX is already running. 
Network status is still unavailable but that doesn't really matter to me.
