### ISSUE TITLE
Paths break when putting to TTY (when clicking on a file) in file explorer on Windows

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [GitSquared/edex-ui#811]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [X] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [X] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

So when I click on a file in the file explorer (for example: Z:\.ssh\autorized_keys) it puts it into my terminal, but instead of putting it like:
"Z:\.ssh\autorized_keys"
it puts it like:
'Z:.sshautorized_keys'
which is just wrong. What i think is happening here it the backslashes are escaped? Also, Windows uses " not ' and with ' it doesn't work (I typed "type 'Z:\.ssh\autorized_keys'" (without the ") to confirm this).

**Comment by GitSquared** [comment]
I'm sorry, this is fixed in the latest version, but it's unreleased... (related: #769).

You can try to compile from source if you want, instructions are in the readme. In the meantime i'm going to have to close this.
