### ISSUE TITLE
Disable keyboard highlighting when entering passwords on command line

### ISSUE THREAD

**Issue by therenney** [GitSquared/edex-ui#815]
When entering a password or any other hidden input, the built in graphical keyboard should not highlight the entered credentials as visual notifications on the ui's keyboard. Thats a security risk that me and Jack Bauer spotted. ;)

**Comment by GitSquared** [comment]
Dup #394, [implemented](https://github.com/GitSquared/edex-ui/issues/394#issuecomment-484571538) a year ago. [Discussion](https://github.com/GitSquared/edex-ui/issues/394#issuecomment-454878924) of why it's not possible to automate this.
