### ISSUE TITLE
Build from source fails on ARM

### ISSUE THREAD

**Issue by paulwratt** [GitSquared/edex-ui#818]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

I am on a RPi4 with RaspberryPiOS Buster (32bit). I tried _Building_ from the README.md
```
- `npm install` (NOT `install-linux` or `install-windows`)
- `npm run build-linux` or `build-windows` or `build-darwin`
```
Both the _Master_ (GitHub Repo) and the _v2.2.2_ (.tgz) fail to build (with different errors).

I wont paste the **.tgz** build error, but it looked stupid. Lots of:
```
/home/pi/.cache/node-gyp/14.15.0/include/node/v8.h:6475:46: note:   candidate expects 1 argument, 0 provided
../src/unix/pty.cc:714:68: error: no matching function for call to 'v8::_function-name_'
```

Building from the repo gets further, but it fails with the following error:
```
> edex-ui@3.0.0-pre build-linux /home/pi/fix-repo/edex-ui
> electron-builder build -l -p never

  • electron-builder  version=22.8.0 os=5.4.72-v7l+
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=node-pty@0.9.0 platform=linux arch=x64
  ⨯ cannot execute  cause=exit status 1
                    out=
    > node-pty@0.9.0 install /home/pi/fix-repo/edex-ui/prebuild-src/node_modules/node-pty
    > node scripts/install.js
    
    make: Entering directory '/home/pi/fix-repo/edex-ui/prebuild-src/node_modules/node-pty/build'
      CXX(target) Release/obj.target/pty/src/unix/pty.o
    make: Leaving directory '/home/pi/fix-repo/edex-ui/prebuild-src/node_modules/node-pty/build'
    
                    errorOut=g++: error: unrecognized command line option ‘-m64’
    make: *** [pty.target.mk:113: Release/obj.target/pty/src/unix/pty.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/pi/n/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    gyp ERR! System Linux 5.4.72-v7l+
    gyp ERR! command "/home/pi/n/bin/node" "/home/pi/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/pi/fix-repo/edex-ui/prebuild-src/node_modules/node-pty
    gyp ERR! node -v v14.15.0
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok 
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! node-pty@0.9.0 install: `node scripts/install.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the node-pty@0.9.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/pi/.npm/_logs/2020-11-03T12_27_22_559Z-debug.log
    
                    command=/home/pi/n/bin/node /home/pi/n/lib/node_modules/npm/bin/npm-cli.js rebuild node-pty@0.9.0
                    workingDir=
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edex-ui@3.0.0-pre build-linux: `electron-builder build -l -p never`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the edex-ui@3.0.0-pre build-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-11-03T12_27_22_634Z-debug.log
```
I dont know about you but:
`  • rebuilding native dependencies  dependencies=node-pty@0.9.0 platform=linux arch=x64`
seems to me like it will always fail on ARM (actually anything _NOT_ x64 - which is everything else)

This seems like it is not picking up a setting from somewhere, or making a presumption.

Presuming this is the only thing in the _Master_ Repo that needs fixing, can another release be made asap

I installed Node.js (14.15.0) & NPM (6.14.8) using `curl -L https://git.io/n-install | bash`.

Cheers

Paul

**Comment by GitSquared** [comment]
ARM is unsupported. See #804 for somebody trying to make it work, but it's really hacky.

> This seems like it is not picking up a setting from somewhere, or making a presumption.

It is, something like `x32 ? X : Y`, meaning default to x64. As said above ARM is not handled.

> can another release be made asap

Nope. #769

**Comment by paulwratt** [comment]
So I used the right command line to build it? Would it be any different if I used v15 of Node.js (I dont think so)?

If you point me to the right place(-ish) I can at least try some (non-hacky) patches, so (at least) this error will not occur, and then it can work on any architecture (including RISC-V)

**Comment by GitSquared** [comment]
eDEX has some native dependencies written in C/C++, like [node-pty](https://github.com/microsoft/node-pty)... and others I think, I don't really remember as i haven't seriously worked on this repo for about a year now. You should look into arm support in those projects first.

**Comment by paulwratt** [comment]
it appears v2.2.2 has some issues with headers.

Am I right in understanding that `electron-builder` is a seperate project that may be failing, or (my guess) a configuration is being passed to `electron-builder` which _is_ in the **edex-ui** repo?

**Comment by GitSquared** [comment]
> a configuration is being passed to electron-builder which is in the edex-ui repo?

Yup, from this line onwards:

https://github.com/GitSquared/edex-ui/blob/459e50e48581d4059e798434db7b5d9a85af2527/package.json#L45

See also the scripts section in this same file.

> am I actually building an AppImage version of edex-ui?

Yes, that's what "building" means in the context of this repo, packaging dependencies, eDEX source code and assets and Electron white-label binaries into a single executable.

> Should maybe I rather be using Starting from source instead

Normally you try starting it before bundling it (which what "build" really means here).

If dependencies successfully installed, `npm start` will start the app in development mode.

**Comment by paulwratt** [comment]
Bah, _Starting from source_ instructions works fine!

**Comment by parkerlreed** [comment]
I was able to compile master on AArch64 just fine.

It fails because electron-builder is dumb and tries to use the fpm x86_64 on ARM to build the package.

All that was needed was to 

* Build fpm from source and install.
* Compile with `USE_SYSTEM_FPM="true"` somewhere in your environment.

![Untitled](https://user-images.githubusercontent.com/841440/98012393-0c7abd80-1dc7-11eb-8c92-10eb4e1619dc.jpg)

**Comment by paulwratt** [comment]
@parkerlreed cheers. I just edited that post again, and I think its simpler than that

**Comment by GitSquared** [comment]
@parkerlreed That photo looks dope. Well done!

**Comment by marceltoma** [comment]
Raspberry Pi 4 + Ubuntu Mate 
I just changed the package.json to make it work
`    "linux": {
      "target": [
        {
          "target": "AppImage",
          "arch": [
            "arm64"
          ]
        }
      ],`

![123951145_10224721077400246_1791131814938718594_o](https://user-images.githubusercontent.com/2895189/98131095-b460bb80-1e99-11eb-9d4d-7ba91ced8624.jpg)

**Comment by paulwratt** [comment]
A note in a file/readme would help out here I think, a RaspberryPi text specific or "ToubleShooting" text (either should be fine), or simply just mention it on the front page (README.md) - thanks for everyones help and screenshots btw.

**Comment by rekab72** [comment]
> Raspberry Pi 4 + Ubuntu Mate
> I just changed the package.json to make it work
> ` "linux": { "target": [ { "target": "AppImage", "arch": [ "arm64" ] } ],`
> ![123951145_10224721077400246_1791131814938718594_o](https://user-images.githubusercontent.com/2895189/98131920-8e87e680-1e9a-11eb-9dc1-ca53a65d8395.jpg)

@marceltoma Can you post your build instructions or your working build as a release?
