### ISSUE TITLE
Set it as a wallpaper

### ISSUE THREAD

**Issue by aa89227** [GitSquared/edex-ui#820]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [X] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [X] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

Add an option to set it as a computer wallpaper. Maybe use some key combinations to lock the input.

**Comment by GitSquared** [comment]
Oh boy your CPU is not gonna like this.

**Comment by aa89227** [comment]
Why?

**Comment by GitSquared** [comment]
Running all those background system checks and frontend animations that you have on edex is quite cpu-intensive, even if all that has been carefully optimized over the years.

It's uncommon for a wallpaper to eat 25% of your available processing power.

**Comment by aa89227** [comment]
You can set a hotkey to suspend, or to suspend when the desktop is not visible. This will reduce wasted resources
