### ISSUE TITLE
Choose the installation path

### ISSUE THREAD

**Issue by Arutosio** [GitSquared/edex-ui#821]
It would be really good to add the possibility to choose the installation path

**Comment by Animus-Surge** [comment]
While I agree with this, the way eDEX is setup is to use the AppData folder (or equivalent for other platforms) to store everything that it needs, and thats how a lot of other apps do this, especially ones that install to the local user like eDEX. Not saying that it isn’t a bad idea, it would probably require a bit of a rewrite to make sure everything works no matter the folder it’s installed to.

**Comment by GitSquared** [comment]
Windows builds on v2.2.4 and above support specifying a custom install dir during the install process. *nix builds will keep using the standard app dir because the ecosystem is less of a clusterfuck there.
