### ISSUE TITLE
Custom keyboard "layouts"

### ISSUE THREAD

**Issue by porky11** [GitSquared/edex-ui#836]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [x] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [x] Like, *I* could do it.

---

Not sure, how it's called exactly. I'm not talking about the order in which the characters appear, but about the key sizes, spacing and so on.
So you could make a ortholinear keyboard (non staggered).

**Comment by GitSquared** [comment]
(If you're interested in this and want to start hacking on the idea, check the github wiki for how to do CSS injection)
