### ISSUE TITLE
Settings modal may overflow

### ISSUE THREAD

**Issue by flleeppyy** [GitSquared/edex-ui#841]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux (KUbuntu 20.04.1)
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

As stated in the title, when trying to edit the configuration, the window is too large and cannot see the buttons at the bottom
![image](https://user-images.githubusercontent.com/18307183/98226779-579de900-1f0b-11eb-88ac-7567ae19895a.png)

**Comment by GitSquared** [comment]
What's your screen resolution?

**Comment by flleeppyy** [comment]
1920*1080

**Comment by parkerlreed** [comment]
Same here 

![image](https://user-images.githubusercontent.com/841440/98283138-2eae4000-1f6d-11eb-833d-c9aa403f0ce1.png)

I just now realized the top of the settings windows is draggable

![image](https://user-images.githubusercontent.com/841440/98283179-408fe300-1f6d-11eb-8f06-86a8734ae225.png)

**Comment by GitSquared** [comment]
> I just now realized the top of the settings windows is draggable

Yeah, but this is obv not ideal... Looks we've reached features overflow haha. PRs welcome if anyone wants...

**Comment by dinarauf** [comment]
Hello. I do not know how to speak English. I am writing to you with google
translator. can you tell me how to crack someone's instagram facebook
password

5 Kas 2020 Per 22:46 tarihinde parkerlreed <notifications@github.com> şunu
yazdı:
