### ISSUE TITLE
v2.2.2 ucaught typeerror at terminal.class.js 1:776

### ISSUE THREAD

**Issue by Animus-Surge** [GitSquared/edex-ui#842]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Whenever you try to open multiple terminals at the same time, it throws the following error:

```
Uncaught TypeError: e.indexOf is not a function
at ..../edex-ui/resources/app.asar/classes/terminal.class.js 1:776
```

When I looked at the packed code, it came up with this line at the specified location:

```js
let r=e.slice(0,e.indexOf("("));
```

I don't know the program as well as you, so I'm not sure what's supposed to really be happening on that line. The issue seems to be happening on [line 34](https://github.com/GitSquared/edex-ui/blob/master/src/classes/terminal.class.js#L34) in master. I'm using the latest released version, not master.

(edit: little better understanding (maybe))

**Comment by parkerlreed** [comment]
Please test against master as noted in the stickied issue 

https://github.com/GitSquared/edex-ui/issues/769

**Comment by GitSquared** [comment]
Closed as v2 is unsupported, please reopen if this can be reproduced on master
