### ISSUE TITLE
What is like the line we put it in top to bottom bottom to top? 

### ISSUE THREAD

**Issue by saeternes** [GitSquared/edex-ui#845]

**Comment by parkerlreed** [comment]
Are you referring to file sorting in the file manager, the terminal, or something else? 

A bit more description would be helpful in this case.

**Comment by saeternes** [comment]
> Are you referring to file sorting in the file manager, the terminal, or something else? 
> 
> A bit more description would be helpful in this case. 

I mena like we put this into right? What is the order we put the code inside?

**Comment by saeternes** [comment]
@parkerlreed

**Comment by GitSquared** [comment]
@parkerlreed Thanks for the help, and sorry you had to deal with spam.
