### ISSUE TITLE
Alt keyboard layout

### ISSUE THREAD

**Issue by jwulf** [GitSquared/edex-ui#848]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [ X ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ X ] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

I use the Halmak keyboard layout, and this has QWERTY hard-coded, by the look of it. 

Can you make the keyboard layout configurable via a JSON map or something?

**Comment by GitSquared** [comment]
> Can you make the keyboard layout configurable via a JSON map or something?

it is, check the github wiki.
