### ISSUE TITLE
World map is a globe - shouldn't it be flat?

### ISSUE THREAD

**Issue by jwulf** [GitSquared/edex-ui#849]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [X] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [ X ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

The world map in the terminal is some kind of rotating globe. Shouldn't it be flat? That will make it possible to see the whole thing at once - and also, would be more accurate, no?

**Comment by PoorPocketsMcNewHold** [comment]
> and also, would be more accurate, no?

![image](https://user-images.githubusercontent.com/13170204/98359131-a177f380-201f-11eb-945d-eba57c1b13e2.png)
It wouldn’t, but a planisphere optional customization option would be a good idea.

**Comment by ProjectHSI** [comment]
Yeah.
> and also, would be more accurate, no?
The earth isn't flat. _God please don't turn this into a flat earth debate_

**Comment by GitSquared** [comment]
It would be easier to see, but it also would be much less cool, and eDEX is more about the latter i'm afraid.

**Comment by PoorPocketsMcNewHold** [comment]
> Yeah.
> 
> > and also, would be more accurate, no?
> 
> The earth isn't flat. _God please don't turn this into a flat earth debate_

Out of topic. I hope @jwulf was referencing to what they thought the Encom UI was looking like,

**Comment by GitSquared** [comment]
I think he might just have been tired of waiting for the globe to spin to the part of the world he wanted to look at, which is a valid UX concern.
