### ISSUE TITLE
I DONT RUN NPM BS COMMANDS GIVE ME A REAL STRING!

### ISSUE THREAD

**Issue by jamieduk** [GitSquared/edex-ui#856]
I DONT RUN NPM THEY ARE BAD COMMANDS! MAKE AN INSTALLER.SH LIKE SETUP.SH FUCK NPM! BS W.E IT IS!

## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)

**Comment by EstoyMejor** [comment]
What's up with all the trolls in the issues here lately? It's getting quite insane.

**Comment by GitSquared** [comment]
> What's up with all the trolls in the issues here lately? It's getting quite insane.

Yeah, it's a real pain. I've contacted Github Support about this.

There are tools to limit interaction with the repository but I don't like the idea of potentially blocking meaningful issues & discussions so I try to use them as little as possible.
