### ISSUE TITLE
Strange screen resize bug

### ISSUE THREAD

**Issue by KjartanOli** [GitSquared/edex-ui#858]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

### Description
I just cloned the repository and ran 'npm run install-linux' without issue. I had to make a small modification to the 'start' command in 'package.json', I might make a seperate issue about that. Once I get eDEX-UI running everything seems to be working untill my mouse cursor leaves the window, at which point it goes into a constant cycle of resizing three of four times a second.
```
[3251959:1107/144447.689932:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x4bdd0796000] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[3251959:1107/144447.690156:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x4bdd0796000] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
ℹ  info      UpdateChecker: Running an unreleased, development version.
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: _renderer.js:1136:13
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: _renderer.js:1136:13
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: _renderer.js:1136:13
ℹ  info      Resized TTY to  137 029
[3251959:1107/144510.697193:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x4bdd0796000] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[3251959:1107/144510.697949:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x4bdd0796000] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[3251959:1107/144510.698080:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x4bdd0796000] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[3251959:1107/144510.698183:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x4bdd0796000] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: _renderer.js:1114:13
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: _renderer.js:1114:13
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: _renderer.js:1114:13
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: _renderer.js:1114:13
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: _renderer.js:1114:13
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: _renderer.js:1114:13
```
This is a small part of the output printed on my terminal after the mouse cursor left the eDEX-UI window.

### System Information
In case this might have something to do with my particular setup. I am running Debian Bullseye (11), using i3 as my window manager. Just let me know if you need more specifics about my hardware and I'l find them.

**Comment by GitSquared** [comment]
> using i3 as my window manager.

eDEX isn't really made for running in a window, and when it does it tries to keep a 16:9 aspect ratio to make sure the UI isn't broken. You might be experiencing a conflict between i3's tiling and that behaviour.

**Comment by KjartanOli** [comment]
Maybe, strange if that happens though, because the window's size does not change, this problem also does not appear in v2.2.2.

**Comment by GitSquared** [comment]
Should be fixed by disabling `keepGeometry` in the settings.

**Comment by KjartanOli** [comment]
Yes that seems to fix it. I have also found that just keeping it in its own workspace and having it fullscreen works. As long as one is fine with reserving a workspace for it and nothing else.
