### ISSUE TITLE
App tries to bind to port 3000, no config to change it?

### ISSUE THREAD

**Issue by lmarianski** [GitSquared/edex-ui#859]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

So I haven't looked at the source code here yet, but why does an electron app try to start a WebSocket server :thinking: . Anyways if that's absolutely necessary add a config option to change it!

```
✖  fatal     Error: listen EADDRINUSE: address already in use :::3000 
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at new WebSocketServer (/opt/eDEX-UI/resources/app.asar/node_modules/ws/lib/websocket-server.js:74:20)
    at new Terminal (/opt/eDEX-UI/resources/app.asar/classes/terminal.class.js:1:8389)
    at App.<anonymous> (/opt/eDEX-UI/resources/app.asar/_boot.js:1:6395)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by GitSquared** [comment]
Check the [settings.json](https://github.com/GitSquared/edex-ui/wiki/settings.json) `port` value

**Comment by lmarianski** [comment]
AH sorry, just noticed the setting dir, still i wonder why you need the server

**Comment by GitSquared** [comment]
It's used internally to communicate between the GUI frontend and the terminal process we launch in the background.
