### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by RobinSchapendonk** [GitSquared/edex-ui#861]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux (Arch)
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

When I navigate to `/themes` and click on a theme, I get the error:
```
Uncaught SyntaxError: Unexpected end of input at file://opt/eDEX-UI/resources/app.asar/ui.html
```

**Comment by EstoyMejor** [comment]
Had the same happen to me, just changing the theme in the settings instead works fine!

**Comment by el-germi** [comment]
Confirmed on Windows(master v3.0.0-pre) too

**Comment by EstoyMejor** [comment]
> Confirmed on Windows(master v3.0.0-pre) too
> 
> the file explorer can't change theme nor keyboard

Oh yeah I should mention im on Windows and MacOS. Only happens on 3.0.0-pre, 2.2.2 works fine.

**Comment by Animus-Surge** [comment]
Can confirm that this is happening, I'll look into it now. Tested on Windows and Raspbian (Debian) Linux

**Comment by rodrigovssp** [comment]
#up

Em Seg, 9 de nov de 2020 10:44, Gaby <notifications@github.com> escreveu:
