### ISSUE TITLE
ARM64 release

### ISSUE THREAD

**Issue by rekab72** [GitSquared/edex-ui#863]
Would it be possible to provide a ARM64 release to run on Ubuntu 20.10 Raspberry Pi4 8GB?
The reference `Can this run on a Raspberry Pi / ARM device?
Running eDEX on ARM is not officially supported, but some users have attempted to compile it for the platform. See this issue comment, and the thread on issue #818.` link is incorrect to issue #818 in README.md

**Comment by modul8com** [comment]
Check this out ! https://youtu.be/DJOAmYlDQuM

**Comment by GitSquared** [comment]
> link is incorrect to issue #818 in README.md

Fixed, thanks for reporting.

**Comment by GitSquared** [comment]
> Would it be possible to provide a ARM64 release to run on Ubuntu 20.10 Raspberry Pi4 8GB?

I don't have any arm device to test a potential release with so I don't want to "officially" support it. Besides, edex is optimized for computers with a large thread count and afaik performs quite terribly on Pi devices & the like...

I know a lot of people have been toying with this on arm, so I might consider investing into a Pi device and more perf optimizations. But then, you also have to consider #769.
