### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by xcodz-dot** [GitSquared/edex-ui#865]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [ ] Would be super cool.
- [x] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [x] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

It seems like we need a optimization option which might:
* reduce resolution
* disable extra panels
* everything you need to stop lagging

**Comment by GitSquared** [comment]
Out of scope. What we truly need is a rewrite and that is more or less tracked in #769.

**Comment by xcodz-dot** [comment]
ok, but the problem is it lags and crashes on windows but on linux it works like charm.

I have dual booted PC, windows and linux are installed on same spec machine.

**Comment by EstoyMejor** [comment]
That's in you chief. Works fine on all of my machines. Windows, Linux and MacOS

**Comment by xcodz-dot** [comment]
It seems you have a powerful PC @EstoyMejor . My PC is not much powerful so i was able to spot the great difference on both OS.

**Comment by GitSquared** [comment]
> That's in you chief. Works fine on all of my machines. Windows, Linux and MacOS

No, he has a point... I'd like to be neutral but the fact is Windows' handling of sub-processes and system information querying is complete crap. On Linux edex just has to read some files in sysfs to get things like current cpu frequency and temperature, on Win' it has to spawn a built-in utility called Wmic which queries stuff between the Registry and the drivers, sometimes both.

We could optimize this software further and it may happen at some point, but there will always be a difference between nix-based and nt-based OSs in performance.

**Comment by xcodz-dot** [comment]
Ok Thanks, I am better with Linux for now
