### ISSUE TITLE
My network status, network traffic and worldview shows offline all the time. Do I need to set something ?

### ISSUE THREAD

**Issue by aahnik** [GitSquared/edex-ui#866]
Note: I don't know anything about js or networking. 

![Screenshot from 2020-11-08 19-25-21](https://user-images.githubusercontent.com/66209958/98466936-a2b04880-21f8-11eb-85dc-2c37081f9704.png)

What should I do to fix this? 

My OS: Ubuntu 20.04

eDEX-UI v2.2.2

**Comment by GitSquared** [comment]
Check this: https://github.com/GitSquared/edex-ui/issues/665#issuecomment-570770055

**Comment by aahnik** [comment]
@GitSquared thanks a lot.

Experimentally I changed the pingAddr to `8.8` and iface to `lo`.

Now it looks like this

![Screenshot from 2020-11-08 20-15-17](https://user-images.githubusercontent.com/66209958/98468149-2836f700-21ff-11eb-887f-86b26f7397b3.png)

World view and network traffic are now showing :smiley: 

but network status is showing unknown :cry:

**Comment by GitSquared** [comment]
lo is not the one you want, it means localhost.

**Comment by aahnik** [comment]
changing lo to wlp2s0 makes this:

![Screenshot from 2020-11-08 20-30-37](https://user-images.githubusercontent.com/66209958/98468662-7fd66200-2201-11eb-80b0-1f5be4f5ad4e.png)

@GitSquared thanks a lot again for your help
