### ISSUE TITLE
Username feature in Windows 

### ISSUE THREAD

**Issue by saurav3199** [GitSquared/edex-ui#870]
## Technical information
**Using version:**
 - [x] `latest` (latest release, currently `v2.2.2`)

**Running on:**
 - [x] Windows

**How comfortable you are with your system and/or IT in general:**
 - [x] My machine is fully under my control, tell me what you need

---

## Problem

As suggested in wikis I looked for to change the username that is being displayed in the welcome message. I tweak the settings.json file to add `{"username": "myname"}` field but nothing changed and it's also not visible in UI as well.

Is this feature still not available in stable release.

**Comment by GitSquared** [comment]
> Is this feature still not available in stable release.

Yes, that's it, it's only in the unreleased version for now. Related: #769.
