### ISSUE TITLE
Build Failure in Windows 10 Enterprise

### ISSUE THREAD

**Issue by mrparag94** [GitSquared/edex-ui#872]
• rebuilding native dependencies  dependencies=node-pty@0.9.0, osx-temperature-sensor@1.0.7 platform=win32 arch=x64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path C:\Users\Mendax47\Desktop\DevHome\WEB\Packages\edex-ui\prebuild-src\node_modules\osx-temperature-sensor
    npm ERR! command failed
    npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "node-gyp rebuild"
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@7.1.2
    npm ERR! gyp info using node@15.1.0 | win32 | x64
    npm ERR! gyp info find Python using Python version 2.7.18 found at "C:\Users\Mendax47\.windows-build-tools\python27\python.exe"
    npm ERR! gyp info find VS using VS2019 (16.7.30621.155) found at:
    npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
    npm ERR! gyp info find VS run with --verbose for detailed information
    npm ERR! gyp info spawn C:\Users\Mendax47\.windows-build-tools\python27\python.exe
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   'C:\\Users\\Mendax47\\Desktop\\DevHome\\WEB\\Packages\\edex-ui\\node_modules\\node-gyp\\gyp\\gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'msvs',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\Mendax47\\Desktop\\DevHome\\WEB\\Packages\\edex-ui\\prebuild-src\\node_modules\\osx-temperature-sensor\\build\\config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\Mendax47\\Desktop\\DevHome\\WEB\\Packages\\edex-ui\\node_modules\\node-gyp\\addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   'C:\\Users\\Mendax47\\.electron-gyp\\10.1.5\\common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Mendax47\\.electron-gyp\\10.1.5',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Mendax47\\Desktop\\DevHome\\WEB\\Packages\\edex-ui\\node_modules\\node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Mendax47\\\\.electron-gyp\\\\10.1.5\\\\<(target_arch)\\\\node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Mendax47\\Desktop\\DevHome\\WEB\\Packages\\edex-ui\\prebuild-src\\node_modules\\osx-temperature-sensor',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'C:\\Users\\Mendax47\\Desktop\\DevHome\\WEB\\Packages\\edex-ui\\prebuild-src\\node_modules\\osx-temperature-sensor\\build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp: C:\Users\Mendax47\.electron-gyp\10.1.5\common.gypi not found (cwd: C:\Users\Mendax47\Desktop\DevHome\WEB\Packages\edex-ui\prebuild-src\node_modules\osx-temperature-sensor) while reading includes of binding.gyp while trying to load binding.gyp
    npm ERR! gyp ERR! configure error
    npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Mendax47\Desktop\DevHome\WEB\Packages\edex-ui\node_modules\node-gyp\lib\configure.js:351:16)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:327:20)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
    npm ERR! gyp ERR! System Windows_NT 10.0.19041
    npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mendax47\\Desktop\\DevHome\\WEB\\Packages\\edex-ui\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    npm ERR! gyp ERR! cwd C:\Users\Mendax47\Desktop\DevHome\WEB\Packages\edex-ui\prebuild-src\node_modules\osx-temperature-sensor
    npm ERR! gyp ERR! node -v v15.1.0
    npm ERR! gyp ERR! node-gyp -v v7.1.2
    npm ERR! gyp ERR! not ok

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\Mendax47\AppData\Local\npm-cache\_logs\2020-11-09T13_18_10_680Z-debug.log

                    command='C:\Program Files\nodejs\node.exe' 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js' rebuild node-pty@0.9.0 osx-temperature-sensor@1.0.7
                    workingDir=
npm ERR! code 1
npm ERR! path C:\Users\Mendax47\Desktop\DevHome\WEB\Packages\edex-ui
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c "node_modules\.bin\electron-builder build -w -p never"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Mendax47\AppData\Local\npm-cache\_logs\2020-11-09T13_18_10_873Z-debug.log

**Comment by GitSquared** [comment]
> osx-temperature-sensor@1.0.7 platform=win32

That should not happen, I'll look into this. In the meantime, are you sure you don't want to download a [pre-packaged release](https://github.com/GitSquared/edex-ui/releases)?

**Comment by mrparag94** [comment]
The pre-packaged release doesn't seem to work well in my machine... it crashes here and there and if I change powershell.exe -> cmd.exe then it doesn't even start...

**Comment by GitSquared** [comment]
> `node -v v15.1.0`
