### ISSUE TITLE
Crash when changing to a tab where the terminal has been previously opened and then closed

### ISSUE THREAD

**Issue by Blue3agle** [GitSquared/edex-ui#873]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows (Powershell in terminal)
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Short description: Opening a terminal, then exiting it and re-opening it crashes eDEX-UI with error "eDEX-UI crashed" "Cannot resize a pty tha has already exited"

Reproduction:
Start eDEX-UI
Press CTRL+2 to open terminal 2
Type 'exit' to terminate powershell and return to the main shell
Press CTRL+2 to open terminal 2
Crash

My guess is that eDEX-UI doesn't un-flag a terminal as being open when it is closed. It appears to register that a terminal is closed because the tab title goes from "#2 -" to "EMPTY". Also before it crashes the title of the tab is changed to "::3002". When it then attempts to re-open the tab it thinks that there is a tty there, when there is not. In any case it is important to assert that there is a tty linked to the terminal before attempting to resize it, and if there is not a new terminal has to be attached to the tab.

Thank you for a very fun product.

**Comment by Animus-Surge** [comment]
Can confirm that this is happening. Happens in `master` and `v2.2.2`. Doesn't happen with just powershell either, also happens with cmd. I tested on raspbian and didn't have any problems, worked as it should.
