### ISSUE TITLE
Is there a GPU stats section just like CPU, if yes how to enable it?

### ISSUE THREAD

**Issue by askaydevs** [GitSquared/edex-ui#879]
On the left, there is the CPU thread section. (See image)
![image](https://user-images.githubusercontent.com/25882403/98803829-543ebc00-243b-11eb-9a33-89edaa22d9e9.png)

I was wondering if there is a similar section I can enable for GPU.

**Comment by GitSquared** [comment]
There isn't! Contributions welcome.

**Comment by rodrigovssp** [comment]
#up

Em Qua, 11 de nov de 2020 7:59 AM, Shubham Singh <notifications@github.com>
escreveu:
