### ISSUE TITLE
vim syntax highlighting 

### ISSUE THREAD

**Issue by Weilory** [GitSquared/edex-ui#880]
Bro, this is incredible.

I wonder if I can use vim editor inside eDEX with syntax colour highlighting, I have read following issues:

* [#287 ]
* [#483 ]

I did not find a very practical way. I am currently on MacOS and have installed the disc image file rather than node js build. 

What I did next, was installing [horizon theme](https://github.com/GitSquared/horizon-edex-theme), however, when I rum vim I still cannot see any colour highlighting. 

<img width="1792" alt="Screen Shot 2020-11-12 at 12 23 04 am" src="https://user-images.githubusercontent.com/54391313/98817515-4d856880-247e-11eb-8880-b3ee20f825fc.png">

It's an awesome app and I will be so appreciated if you offer some help.

**Comment by Weilory** [comment]
You mentioned `Nord` and `Chalkboard` has colour feature enabled in [463](https://github.com/GitSquared/edex-ui/issues/463#issuecomment-473930382), but it did not work on my machine, neither on nano nor on vim.

<img width="1792" alt="Screen Shot 2020-11-12 at 1 01 21 am" src="https://user-images.githubusercontent.com/54391313/98820867-e1f1ca00-2482-11eb-972d-a498f16172df.png">

**Comment by Animus-Surge** [comment]
Have you tried reading this: https://linuxhint.com/vim_syntax_highlighting/ ?

Maybe the syntax highlighting's off for your version of vim.

**Comment by Weilory** [comment]
@Animus-Surge Thanks for your suggestion, I have thought about it, I am certain that my vim syntax highlighting is enabled. 

<img width="1792" alt="Screen Shot 2020-11-12 at 1 01 21 am" src="https://user-images.githubusercontent.com/54391313/98878796-fca25e00-24d7-11eb-8883-bd5470c747a0.png">

**Comment by Weilory** [comment]
I also doubt if that will be due to my customise shell appearance setting? However, after I restore it to default, the syntax is still not highlighted.

**Comment by Weilory** [comment]
```bash
🌹 vim -version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  5 2020 21:30:37)
Garbage after option argument: "-version"
More info with: "vim -h"
```

with a reference to [enable vim syntax highlighting SO](https://stackoverflow.com/questions/11272501/enable-vim-syntax-highlighting-by-default), I have enabled it.

**Comment by Weilory** [comment]
My first test run was on `python`, now I I have run tests on `node js`, `c`, `ruby`. notice my theme is `horizon-full`, and the result of **whether syntax highlighting works** in eDEX-UI vim editor followed by:

1. `python` NOT working
1. `javascript` working
1. `json` working
1. `ruby` NOT working
1. `c` working

and **whether syntax highlighting works** in terminal vim editor followed by:

1. `python` working
1. `javascript` working
1. `json` working
1. `ruby` working
1. `c` working

**Comment by GearHead001** [comment]
Hause est 93⁰
