### ISSUE TITLE
CPU Temperature on Laptops with acpi 

### ISSUE THREAD

**Issue by Kruemmelspalter** [GitSquared/edex-ui#882]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
On my laptop (Lenovo 81YM) it shows `-1°C` under `TEMP` in the Panel under `CPU USAGE`.

> I tried getting the temperature manually with `lm_sensors` but it said one would use acpi for temperature on laptops so I used acpi and got the temperature how I wanted.

**Comment by GitSquared** [comment]
Try with v3, you'll need to follow the instructions edex's README to start it.

**Comment by GitSquared** [comment]
Please reopen if you can reproduce on v3.

**Comment by Kruemmelspalter** [comment]
Works on v3.
