### ISSUE TITLE
FOR cycle is throwing an error

### ISSUE THREAD

**Issue by AlastorStrixEfuartus** [GitSquared/edex-ui#883]
## Technical information
**Using version:**
 - [X] `latest` (latest release, currently `v2.2.2`)

**Running on:**
 - [X] Windows

**How comfortable you are with your system and/or IT in general:**
 - [X] My machine is fully under my control, tell me what you need
---

## Problem

When going with command such as FOR /R %A IN (*.*) DO DEL "%A"
I am getting error such as 
![image](https://user-images.githubusercontent.com/13890278/98882325-4c5b3800-248c-11eb-9367-a72b192efb72.png)
while very same command in same folder works in good old cmd from windows

**Comment by GitSquared** [comment]
This is not `cmd.exe`, it's Powershell, a more sane windows shell. You should refer to Powershell's documentation on how to do this.
