### ISSUE TITLE
Cannot launch app from dock on macOS

### ISSUE THREAD

**Issue by ChristophePRAT** [GitSquared/edex-ui#887]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [x] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)
When I try to launch Edex-UI from the dock or the Applications folder on macOS Big Sur, the app launches but with no screen (as if it had been hidden). The only way to open Edex-UI is to summon it from the terminal with `open /Applications/eDEX-UI.app/`.

**Comment by ChristophePRAT** [comment]
It seems the only way to open edex-UI is from the terminal. Even after running an automation that runs a shell script in Automator, the app won't launch.

**Comment by takoyaro** [comment]
I'm running Catatlina 10.15.7 and edex-UI launches fine from both the Dock and the Application folder.
Could be Big Sur related rather than macOS as a whole.

**Comment by GitSquared** [comment]
Launching from the CLI probably triggers Rosetta 2 x84_64 emulation, which is why it only works this way... Until a new release comes out I'm afraid I have no other solution for you.
