### ISSUE TITLE
crashes immediately at start

### ISSUE THREAD

**Issue by hoegge** [GitSquared/edex-ui#890]
## Technical information
**Using version:**
`v2.2.2`

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

As soon as I start dex-ui it crashes 

![image](https://user-images.githubusercontent.com/15846310/99043234-55343280-258e-11eb-85f9-8688e36cc5ce.png)

First install

**Comment by rodrigovssp** [comment]
#up

Em sex, 13 de nov de 2020 4:59 AM, hoegge <notifications@github.com>
escreveu:

**Comment by wrac4242** [comment]
hi, 
which version are you using, master (running from GitHub-published source code) or latest (latest release)?
and which operating system is this on?

**Comment by hoegge** [comment]
Hi
I put all that in the description but forgot to remove the commenting tags at the beginning so it was all hidden, sorry, I have edited it now. Thanks

**Comment by wrac4242** [comment]
try running it as admin, and if that doesnt work try using the master branch.

**Comment by GitSquared** [comment]
@hoegge Stop whatever you have running on port 3000.

**Comment by hoegge** [comment]
> @hoegge Stop whatever you have running on port 3000.

I can't see anything running on port 3000 using netstat. Have turned off firewall also, no difference.
´netstat -ano | findstr :3000´
gives no output.

Running as admin does not help either.

**Comment by fragolinux** [comment]
same here...
port was free, and it crashed anyway
changed to 3001 or 3002, same...
