### ISSUE TITLE
TypeError: Cannot read propery 'set' of undefined

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [GitSquared/edex-ui#891]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

So I tried to connect to nordvpn, and an error pops up. I find it necessary to report it.
![error](https://user-images.githubusercontent.com/45339160/99138769-ece75e80-262a-11eb-9f6a-0ea36e676531.png)

**Comment by Animus-Surge** [comment]
Please try to reproduce in master. See #769 for more information
