### ISSUE TITLE
Long bootup on AppImage compressed builds

### ISSUE THREAD

**Issue by lebarde** [GitSquared/edex-ui#893]
I just discovered eDEX-ui yesterday, and I am very fond of it! Especially the sounds are incredible. I like very much the way it behaves. Below are some information of my system.

Actually I have used Conky and Gnu Screen a lot. And I think that edex-ui is filling a gap because the look and feel is just awesome. I don't know if eDEX is intended as a joke, but to my mind it might be very usable on a daily basis with few enhancements.

Especially, the bootup is way too long. See this:
```bash
~$ time eDEX-UI.Linux.x86_64.AppImage
[...]
☒  complete  Frontend window created!
…  watching  Waiting for frontend connection...
✔  success   Connected to frontend!
◼  Startup   Timer run for: 14.47s
ℹ  info      Resized TTY to  138 030
ℹ  info      All windows closed
☒  complete  Shutting down...
☒  complete  Terminal exited 0 1

real	0m22,680s
user	0m1,377s
sys	0m0,446s
```
I shot `Alt-F4` just as since my terminal became usable. I turned the eDEX bootup logo OFF (`nointro` true).

I have to wait 22 seconds before having a shell. In comparison xfce4-terminal is usable in less than 0.1 sec:

```bash
~$ time xfce4-terminal

real	0m0,052s
user	0m0,020s
sys	0m0,004s
```
For now this bootup time is way too much for my needs, especially considering my system characteristics. I think that it would be usable for me if the first logs are shown within maybe 1-5 seconds (when `nointro` is set to `false`).

Do you think that it could be done technically? Or is NodeJS a bottleneck?

Thanks!

## Information
I am currently running v2.2.2.

Here are some of my system characteristics:
- CPU: Core i7 3770K
- GPU: Nvidia Quadro 4000
- Ram: 20GB of DDR3 1666
- eDEX and the system are hosted on SSD

Running on Debian Buster (`Linux my-computer 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux`)

I am a relatively power user (20 years of Linux use and former developer).

**Comment by wrac4242** [comment]
can you see if it takes this long from the master branch?

**Comment by GitSquared** [comment]
> Or is NodeJS a bottleneck?

AppImage's the bottleneck here. It packs the edex binaries in a very aggressively compressed format and has to extract the whole archive to /tmp before it can launch it.

I'll see if there are some parameters we can tweak in the bundler's config... In the meantime, running from source launches in barely 2 seconds, it really is night and day.

**Comment by lebarde** [comment]
Ooooh nice, thanks for your answers!

**Comment by lebarde** [comment]
> > Or is NodeJS a bottleneck?
> 
> AppImage's the bottleneck here. It packs the edex binaries in a very aggressively compressed format and has to extract the whole archive to /tmp before it can launch it.
> 
> I'll see if there are some parameters we can tweak in the bundler's config... In the meantime, running from source launches in barely 2 seconds, it really is night and day.

@GitSquared You are right, here is what I get with @master and Node LTS:

```bash
adrien@White-Hat:~/dev/edex-ui$ node -v
v14.15.1
adrien@White-Hat:~/dev/edex-ui$ time npm start

> edex-ui@3.0.0-pre start /mnt/home-black/adrien/dev/edex-ui
> electron src --nointro

▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.16.3 and Electron 10.1.5
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/adrien/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
☒  complete  Frontend window created!
…  watching  Waiting for frontend connection...
ℹ  info      Multithread worker started at 19098
ℹ  info      Multithread worker started at 19107
ℹ  info      Multithread worker started at 19097
ℹ  info      Multithread worker started at 19100
ℹ  info      Multithread worker started at 19115
ℹ  info      Multithread worker started at 19106
ℹ  info      Multithread worker started at 19123
[19025:1117/103536.324313:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x19c293c9700] GL_INVALID_OPERATION: Framebuffer is incomplete.
[19025:1117/103536.324629:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x19c293c9700] GL_INVALID_OPERATION: Framebuffer is incomplete.
[19025:1117/103536.328352:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x19c293c9700] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[19025:1117/103536.328493:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x19c293c9700] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[19025:1117/103536.439153:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x19c293c9700] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[19025:1117/103536.439299:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x19c293c9700] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✔  success   Connected to frontend!
◼  Startup   Timer run for: 4.15s
[19025:1117/103536.612304:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x19c293c9700] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
ℹ  info      Resized TTY to  138 028
ℹ  info      All windows closed
☒  complete  Shutting down...
☒  complete  Terminal exited { exitCode: 0, signal: 1 } undefined

real	0m5,318s
user	0m2,533s
sys	0m0,460s
adrien@White-Hat:~/dev/edex-ui$ 
```
So I have a shell within 5,3s if I turn intro OFF. And if I stop eDEX when I get the first boot screen, it is less than 1 second:
```bash
adrien@White-Hat:~/dev/edex-ui$ time npm start

> edex-ui@3.0.0-pre start /mnt/home-black/adrien/dev/edex-ui
> electron src --nointro

▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.16.3 and Electron 10.1.5
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/adrien/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
☒  complete  Frontend window created!
…  watching  Waiting for frontend connection...
ℹ  info      Multithread worker started at 22564
ℹ  info      Multithread worker started at 22566
ℹ  info      Multithread worker started at 22565
ℹ  info      Multithread worker started at 22589
ℹ  info      Multithread worker started at 22582
ℹ  info      Multithread worker started at 22572
ℹ  info      Multithread worker started at 22580
ℹ  info      All windows closed
☒  complete  Shutting down...
☒  complete  Terminal exited { exitCode: 0, signal: 1 } undefined

real	0m0,972s
user	0m0,848s
sys	0m0,221s
adrien@White-Hat:~/dev/edex-ui$ 
```
My own issue is solved, as I found a workaround. I created a launcher and it works like a charm. Thanks!
So now, maybe we should see if the Appimage can start faster, as it is probably the first user experience and (worst of all :-)) I had to install Node, which needs to add a new repository on Debian (the official Debian package won't work to build eDEX). What turning off compression in the Appimage?

**Comment by GitSquared** [comment]
https://github.com/GitSquared/edex-ui/blob/048feb502b2b3b1ccd3ad8e3484d1b22cfe8766a/package.json#L49

We should try tweaking this and testing if the generated images launch faster or not ([documentation's here](https://www.electron.build/configuration/configuration)).

**Comment by lebarde** [comment]
OK, I tested the 3 options (only on amd64). First conclusion, compression is actually the bottleneck. (Just to add: on my Debian I had to install `g++-multilib` and run `sysctl kernel.unprivileged_userns_clone=1` in order to make eDEX launchable with Appimages).

I am on master at 048feb502b2b3b1ccd3ad8e3484d1b22cfe8766a.

| Compression | Size (MB) |    Time until first window    |      Time until Shell       |
| ----------- |:---------:|:-----------------------------:|:---------------------------:|
| maximum     |    87     | 30,4 s. and 30,5 s. (2 tests) | 55,3 s. and 56 s. (2 tests) |
| normal      |    114    |       1,6 s. (3 tests)        |      6,2 s. (3 tests)       |
| store       |    114    |       1,6 s. (3 tests)        |      6,1 s. (3 tests)       |

My conclusions:
- nearly no difference between `store` and `normal`
- the `normal` compression Appimage is 31% bigger than the `maximum` compression Appimage, but **the launch time decreases by 88,8%**.
- at 048feb502b2b3b1ccd3ad8e3484d1b22cfe8766a with `maximum` compression, **eDEX got fatter than on v2.2.2 : 48% bigger, and the launch time increased by 145% (22,7s to 55,65s)**.

My personal thought is that we should set compression to `normal` or `store` and start focusing on speed, especially to get the shell more responsive. Actually, if I compare to xfce4-terminal (version 0.8.7.4 on my machine), when I press the Return key the next line comes quasi instantly. On eDEX-UI it is fast but not instantaneous (though it is far usable!).

In any way I think the first issue is solved. I give below the logs for information.

# compression: store

## Appimage sizes:
```bash
113M 113M nov.  20 08:18 'eDEX-UI Linux (i386).AppImage'
114M 114M nov.  20 08:18 'eDEX-UI Linux (x86_64).AppImage'
```
## Bootup times

If I put `"compression": "maximum"` in the `packages.json` file, I get 6 seconds until shell:
```bash
adrien@White-Hat:/mnt/home-black/adrien/dev/edex-ui$ time dist/eDEX-UI\ Linux\ \(x86_64\).AppImage 
▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.16.3 and Electron 10.1.5
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/adrien/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
ℹ  info      Multithread worker started at 7398
ℹ  info      Multithread worker started at 7397
☒  complete  Frontend window created!
ℹ  info      Multithread worker started at 7399
…  watching  Waiting for frontend connection...
ℹ  info      Multithread worker started at 7400
ℹ  info      Multithread worker started at 7404
ℹ  info      Multithread worker started at 7401
ℹ  info      Multithread worker started at 7407
[7332:1120/082326.399069:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x32291f865e00] GL_INVALID_OPERATION: Framebuffer is incomplete.
[7332:1120/082326.399420:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x32291f865e00] GL_INVALID_OPERATION: Framebuffer is incomplete.
[7332:1120/082326.417112:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x32291f865e00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[7332:1120/082326.417244:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x32291f865e00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[7332:1120/082326.421683:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x32291f865e00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[7332:1120/082326.421800:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x32291f865e00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[7332:1120/082326.629450:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x32291f865e00] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✔  success   Connected to frontend!
◼  Startup   Timer run for: 4.65s
ℹ  info      Resized TTY to  138 028
ℹ  info      All windows closed
☒  complete  Shutting down...
☒  complete  Terminal exited { exitCode: 0, signal: 1 } undefined

real	0m6,075s
user	0m2,721s
sys	0m0,472s
adrien@White-Hat:/mnt/home-black/adrien/dev/edex-ui$ 
```
If I stop eDEX when I get the first boot screen I get 1,6s:
```bash
adrien@White-Hat:/mnt/home-black/adrien/dev/edex-ui$ time dist/eDEX-UI\ Linux\ \(x86_64\).AppImage 
▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.16.3 and Electron 10.1.5
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/adrien/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
ℹ  info      Multithread worker started at 8645
ℹ  info      Multithread worker started at 8644
ℹ  info      Multithread worker started at 8646
☒  complete  Frontend window created!
…  watching  Waiting for frontend connection...
ℹ  info      Multithread worker started at 8647
ℹ  info      Multithread worker started at 8648
ℹ  info      Multithread worker started at 8649
ℹ  info      Multithread worker started at 8650
ℹ  info      All windows closed
☒  complete  Shutting down...
☒  complete  Terminal exited { exitCode: 0, signal: 1 } undefined

real	0m1,644s
user	0m0,646s
sys	0m0,222s
adrien@White-Hat:/mnt/home-black/adrien/dev/edex-ui$ 
```

**Comment by GitSquared** [comment]
@lebarde Thanks a lot for crunching the numbers! Indeed, using the maximum compression is not worth it at all. I wonder why AppImage devs don't have a "compress for distribution, decompress once on first run" setting :thinking:

I think `normal` would be a reasonable choice in light of those tests you ran. I was about to commit it myself, but maybe you'd like to submit a PR so you can join the list of contributors? ;)

**Comment by lebarde** [comment]
Oh that is sweet from you!
