### ISSUE TITLE
Toggle full-terminal

### ISSUE THREAD

**Issue by lebarde** [GitSquared/edex-ui#894]
Hello,

Sometimes you need more space on your terminal. IMHO eDEX-ui would be more usable if we could toggle several interfaces. For instance, `CTRL-SHIFT-J` (or `CTRL-SHIFT-T` as I am on a `bépo` keyboard) would toggle **interface 1**, then **2**, then **3**.

- **Interface 1**: The way it looks right now (depending on theme)
- **Interface 2**: Disable filesystem, all network information (right panel), keyboard (may be configurable), manufacturer/model/chassis, memory and top processes. Then, Date/hour/uptime and a minimized cpu usage would go on a bottom panel on a single line (like Gnu Screen is often tuned into). See below for a GNU Screen example.
- **Interface 3**: Wide screen for terminal without distraction.

What do you think? Don't you think this could make eDEX-ui more usable on a daily basis?
Thanks!

GNU Screen example:
![](https://i.stack.imgur.com/JTqg6.png)

**Comment by GitSquared** [comment]
Interesting idea, we could also leverage some common layouts used in window tiling managers.
