### ISSUE TITLE
multiple diffrent shells

### ISSUE THREAD

**Issue by KonniLol** [GitSquared/edex-ui#895]
After I found out myself, how I can change the settings in a way, it opens a WSL2 (ubuntu) shell, instead of the standard powershell, I realized, that I can't find a way to change the settings, so it opens diffrent shells (cmd, Ubuntu(WSL2) and Kali(WSL2)). 
Is there any way to do this or doesn't the Program support such a thing (yet)?

Thanks in advance.

**Comment by wrac4242** [comment]
if you want to change the terminal opened by default, read the settings.json page in the wiki, [https://github.com/GitSquared/edex-ui/wiki/settings.json](url)

**Comment by KonniLol** [comment]
> if you want to change the terminal opened by default, read the settings.json page in the wiki, [https://github.com/GitSquared/edex-ui/wiki/settings.json](url)

I've already changed the default terminal, but I want to open two diffrent terminals in the same edex instance. For exaple cmd and Ubuntu (via WSL2).

**Comment by GitSquared** [comment]
@KonniLol this is not possible at the moment.
