### ISSUE TITLE
Won't start if keychain asks for password

### ISSUE THREAD

**Issue by lebarde** [GitSquared/edex-ui#898]
Hello,
My `~/.bashrc` file contains a call to `keychain`, which hangs on the first terminal launch. On bootup, whenever I first open a terminal, `keychain` asks for a private key password. If I start edex from terminal (*and if I have killed `keychain`*), then `keychain` asks for the password during edex bootup. In that case, I can either interrupt it (Ctrl-C) or give the password, and edex continues to boot.

If `keychain` has not run yet and I start edex from Whisker Menu or anything else than a terminal, then the program will remain in the background, silently waiting for an answer (poor boy).

## How to reproduce (linux only)
- Install the following packets: `ssh-askpass`, `keychain` and `openssl` (`# apt install ssh-askpass keychain openssl` for debian-based distros)
- Generate a private SSL key. Give it a password (important!).
```bash
ssh-keygen -t rsa -b 4096 -f key.pem
# Give it a password (or else the bug won't reproduce)
```
- Configure `.bashrc`. Add the following to ~/.bashrc
```bash
keychain -q ~/key.pem
. ~/.keychain/$HOSTNAME-sh
```
- Start edex-ui (from terminal or else). Don't forget to kill ssh-agent if you have already answered the password correctly:
```bash
killall ssh-agent
```
## Workaround
If it can't be solved, here is a workaround: open any console (term or tty), and answer to the password. This way `ssh-agent` will run until next reboot. An other workaround (but not recommended) is to give the SSL key an empty password (BOOOOH !).

## Technical information
Using version v2.2.2
Running on Linux Debian

**Comment by wrac4242** [comment]
Please try to reproduce in master

**Comment by GitSquared** [comment]
Does keychain block the launch of eDEX or does the UI appear?

**Comment by lebarde** [comment]
Thanks for your answers!
@wrac4242 I am going to clone master to see if it behaves the same way this morning and I will tell you :-)
@GitSquared The UI does not appear, but I still see the process:

```bash
:~$ ~/Téléchargements/eDEX-UI.Linux.x86_64.AppImage 
▶  start     Starting eDEX-UI v2.2.2
ℹ  info      With Node 10.11.0 and Electron 4.2.0
ℹ  info      Renderer is Chrome 69.0.3497.128
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/adrien/.config/eDEX-UI
☐  pending   Loading settings file...
✔  success   Settings loaded!
Enter passphrase for /home/adrien/key.pem: 
```

And in another term while eDEX hangs:

```bash
Enter passphrase for /home/adrien/key.pem: 
adrien@White-Hat:~$ ps aux | grep eD
adrien    5055  0.5  0.4 839840 97144 pts/0    Sl   09:55   0:00 /tmp/.mount_eDEX-U8jrs4s/edex-ui
adrien    5058 14.6  0.0  15876  3892 ?        Ssl  09:55   0:09 /home/adrien/Téléchargements/eDEX-UI.Linux.x86_64.AppImage
adrien    5134  0.0  0.1 209240 39804 pts/0    S    09:56   0:00 /tmp/.mount_eDEX-U8jrs4s/edex-ui --type=zygote --no-sandbox
adrien    5157  0.2  0.3 334976 76020 pts/0    Sl   09:56   0:00 /tmp/.mount_eDEX-U8jrs4s/edex-ui --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=9401141006378768005
adrien    5232  0.0  0.0   6092   888 pts/1    S+   09:57   0:00 grep eD
adrien@White-Hat:~$ 
```

**Comment by lebarde** [comment]
Still hangs with Master:
```bash
adrien@White-Hat:~/dev/edex-ui$ killall ssh-agent 
adrien@White-Hat:~/dev/edex-ui$ npm start

> edex-ui@3.0.0-pre start /mnt/home-black/adrien/dev/edex-ui
> electron src --nointro

▶  start     Starting eDEX-UI v3.0.0-pre
ℹ  info      With Node 12.16.3 and Electron 10.1.5
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/adrien/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
Enter passphrase for /home/adrien/key.pem: 
```

**Comment by GitSquared** [comment]
It seems that keychain is interrupting the foreground process... I'm not sure what we can do about it.
Have you ever tried that setup with something like Hyper?

**Comment by GitSquared** [comment]
Closing as stale, please reopen if needed
