### ISSUE TITLE
Multiple shells in the same eDEX instance

### ISSUE THREAD

**Issue by Animus-Surge** [GitSquared/edex-ui#902]
**Perceived idea awesomeness**
- [ ] Wow, you don't have this yet???
- [x] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [x] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [ ] Like, *I* could do it.

---

There have been several ideas in the past regarding using multiple shells in the same instance of eDEX (such as #895). I have an idea on this, shouldn't be too hard to do (I can do this if you'd like). When a user clicks (or taps) on an empty tab, they'd be confronted by a dropdown that asks them which shell they'd like to use in that tab. There could be several different options, like one for powershell, another for bash, even ones for the git cli and nodejs, and then a "Other Terminal" option, which when clicked would display a dialogue that asks for the path (or command if the shell is on the PATH) of the desired shell executable.

This could be configured in the settings to show or never show (which would default to launching the shell specified in the settings), and then also have an option where users can add or remove shells to a list, and each entry is shown in the dropdown when clicking on a tab. Maybe even a separate file that stores all that information.

Dunno how it'll actually turn out yet. I just know it's most likely going to be useful, especially for people who like to have powershell and bash open at the same time.

**Comment by Animus-Surge** [comment]
Ok I figured out stuff while trying this out. For starters, this won't work how I thought it would. I now see that before everything starts, it spawns a tty server which all the clients connect to, so you can't just specify several terminals through using this method. To anyone reading this, if you're running a Windows machine and want to use bash, you should be able to just start it by running `bash` in the cli. Same I believe with powershell. I'm going to close this for now.

**Comment by GitSquared** [comment]
Sorry, I somehow completely overlooked this issue! You're right, it's a bit more tricky than just switching arguments on the frontend code, but it could be done even if the current architecture as we have IPC (interprocess comms) - which i believe is used to signal the backend to create a new term instance?

But yeah, might want to consider if the investment is worth it at this point. It's no small feat.
