### ISSUE TITLE
How about a new release?

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#907]
On May 19, 2019 I released [v2.2.2](https://github.com/GitSquared/edex-ui/releases/tag/v2.2.2), an emergency release branched out from what was already supposed to be v3, to patch a [security issue](https://gaby.dev/edex-vuln).

Life happened, and I never got around to finishing the remote monitoring feature that was supposed to be the key change in v3... And now we're in this weird situation where the latest release is unsupported and everyone interested has to go run the thing from source. And [the diff is only growing](https://github.com/GitSquared/edex-ui/compare/v2.2.2...master)...

![image](https://user-images.githubusercontent.com/24496417/99781925-c63c9280-2b18-11eb-9a36-bb7ad34bbab0.png)

The situation as described in #769 hasn't changed, but, out of respect for the 20+ contributors who've contributed a patch since the latest release and the 30k unique monthly visitors to this repository... I'm starting to think I should release a v2.2.3.

Any thoughts on this?

(Pinging some recent contributors and active commenters: @Animus-Surge @wrac4242 @lebarde )

### New release to-do list:
 - [x] Explore the diff and draft a changelog - thanks a lot to @lebarde!
	- [x] List all contributors since v2.2.2
		```
		Surge, qsniyg, wrac4242, D4rkia, Bodo Graumann, Emir Sarı, Freddie Runnding, Ivan Torres Fally, Jabster28, Le Barde, Maxim Mazurok, Michael de Silva, Nikhil, Niklas Arndt, Val, shine, theunbound, timescam
		```
	- [x] Confirm new version number (patch or minor?) **Patch!**
 - [x] Repair the [CI pipeline](https://travis-ci.org/github/GitSquared/edex-ui) (or build a new one?) - See #912 - thanks @Jabster28 !
 - [x] Get packaged assets for all platforms
	- [x] linux32 (maybe scrap this one?)
	- [x] linux64
	- [x] macOS ~~(check Big Sur compat...)~~ Can't support apple silicon yet.
	- [x] win32_64
	- [x] linux_arm?
 - [x] Write release notes draft
 - [x] Tag & Release
 - [x] Release AUR package
 - [x] Update README
	- [x] Direct download links
	- [x] Q&A, notably the part about ARM
 - [x] Update project status pinned issue
 - [x] Set master package version back to `v3.0.0-pre`

**Comment by lebarde** [comment]
Indeed that would make a lot of relevant changes, especially for users that take the Appimages.

**Comment by wrac4242** [comment]
I agree that there should be a new release soon

**Comment by Animus-Surge** [comment]
Yeah, definitely a good idea to do one soon, especially with the fixes and features that have been added/updated since v2.2.2

**Comment by parkerlreed** [comment]
At the very least it will squash a ton of bug reports that only tested against 2.2.2 :)

**Comment by GitSquared** [comment]
> Maybe perhaps it could be v2.3, as it's not major enough to make it v3.0.0, but not small enough to count as a maintenance release. Just a thought though

I will need to dig into diff at some point but I don't think there is actually any new "feature", which is what the middle number has been used for on this repo so far.

I'll add a tasklist to this issue's desc so we can track what's needed before doing this.

**Comment by GitSquared** [comment]
Done. If anyone wants to help out, especially with the build targets stuff...

As for the changelog, I'll probably take a weekend off other projects and dig into it. I don't think the commit messages are sufficiently similar to automate this process - maybe i'll take the opportunity to install [komit](https://github.com/GitSquared/komit).

**Comment by lebarde** [comment]
# Contributors
Thanks to `git-shortlog`, I list contributors from v2.2.2 to aef706c1f644955b2f2342a8243f45e4b8d3b38c.
```bash
~/dev/edex-ui$ git shortlog -sne v2.2.2..HEAD
```
So after some cleaning to remove duplicates, here are the contributors by contributions: GitSquared, Surge, qsniyg, wrac4242, D4rkia, Snyk bot, Bodo Graumann, Emir Sarı, Freddie Runnding, Ivan Torres Fally, Jabster28, Le Barde, Maxim Mazurok, Michael de Silva, Nikhil, Niklas Arndt, Val, shine, theunbound, timescam.

And best contributor: Dependabot with 129 contributions :-)

# Changelog

Thanks to [git-changelog](http://lkdjiin.github.io/blog/2013/09/04/generer-un-fichier-changelog-avec-git/), I was able to generate a changelog.
Note: I removed the Dependabot and Snyk automatic commits (automatic dependancy upgrades).

[changelog_edex.txt](https://github.com/GitSquared/edex-ui/files/5596976/changelog_edex.txt)
> * 2020-11-24 Fix: fix travis cli for manos &amp; linux (#911)  
> * 2020-11-23 Fix issue #833 (#910)  
> * 2020-11-21 Update README.md  
> * 2020-11-20 Set Appimage compression rate to `normal` (#906)  
  Appimage construction used to compress files aggressively. Using roughly no compression reduces the start time by ~90%.
>   
>   Closes #893
> * 2020-11-20 fix logic error in last commit (#905)  
> * 2020-11-20 :zap: limit multithreading to 7 extra threads  
  see #904
> * 2020-11-17 :bug: separate shell and shellArgs #791  
> * 2020-11-15 Fix #873 (#892)  
> * 2020-11-12 Implement a text editor feature (#875)  
> * 2020-11-12 Added chalkboard-notype theme (#886)  
> * 2020-11-10 Fixed issue #758 (#877)  
>   #758 - Don&#39;t refr
[changelog_edex.txt](https://github.com/GitSquared/edex-ui/files/5596978/changelog_edex.txt)
esh file view if only file contents have changed.
>   On my machine, I observed the view constantly refreshing when in my home directory.  This was due to a file being frequently updated (.xsession-errors).  Each time this file was updated, the fw.watch callback was triggered and the view was refreshed.
> * 2020-11-09 Fix issue #861 (#869)  
> * 2020-11-09 Add standard danish keyboard (#868)  
> * 2020-11-08 Fix issue where images wouldn&#39;t load from general filesystem on Windows (#862)  
> * 2020-11-08 Fix arm issue link #863  
> * 2020-11-08 Fix #857  
> * Changed disk layout to use inherited grid layout, added some padding for spacing from border.
>   
> * Added back display: flex and added flex-wrap to account for list views with disks. Simply using the inherited grid display breaks for list views.
> * 2020-11-07 :bug: Fix #841  
>   Add a scrollable settings table
> * 2020-11-06 Network Traffic Upload and Downlaod value (#850)  
> * 2020-11-05 Create SECURITY.md  
> * 2020-11-05 Remove Fossa integration in CI  
> * 2020-11-05 Add ARM notice to readme #818  
> * 2020-11-04 Add the option to disable fullscreen mode (#830)  
> * 2020-11-04 Add standard Italian keyboard layout (#827)  
> * 2020-11-03 fixed start script for windows (#817)  
> * 2020-11-01 added padding at the terminal bottom (#789)  
> * 2020-11-01 :package: Update file icons  
> * 2020-11-01 :sparkles: Add ui.dev Bytes sponsorship to README  
>   This will help support a comeback to this project!
> * 2020-10-31 Add Linux For Everyone to Featured By section (#799)  
> * 2020-09-23 Add status warning in Readme  
> * 2020-09-08 New featured in entry  
> * 2020-08-09 :package: (fsDisp): update file icons  
> * 2020-07-11 :package: update file icons  
> * 2020-07-11 Don&#39;t refresh filesystem if path hasn&#39;t changed (#746)  
> * 2020-07-11 Fix media with hashtags in their filenames (#745)  
> * 2020-07-11 Add option to configure the displayed welcome username (#744)  
> * 2020-07-08 Add new featured link  

If that helps :-)

**Comment by lebarde** [comment]
[changelog_edex.txt](https://github.com/GitSquared/edex-ui/files/5596983/changelog_edex.txt)

**Comment by GitSquared** [comment]
> And best contributor: Dependabot with 129 contributions :-)

Wish GitHub had a way to separate bots and human contributors in the lists...

> If that helps :-)

It does, thanks a lot!!

**Comment by Jabster28** [comment]
On the topic of changelogs, if we were to use a commit standard such as [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#specification). we'd be able to use packages such as [standard-version](https://github.com/conventional-changelog/standard-version) or [release-please](https://github.com/googleapis/release-please) to automate changelogs and what not for releases

**Comment by GitSquared** [comment]
Indeed, I've been using conventional commits in more recent projects and even developed a [commit message helper](https://github.com/GitSquared/komit) for it. I think we're going to transition this repo after this release, that'll be a good start for saner CI practices from now on.

**Comment by Jabster28** [comment]
Oh, komit looks cool! 

Does it skip the prompt if you've already added a commit message? I don't think things like GitKraken or VSCode would work otherwise.

**Comment by GitSquared** [comment]
No but you can just ctrl-c. It's pretty barebones, there's a lot of cool feats I could add to it but didn't find the time to. I also use Vim and git on the CLI so... I unfortunately don't have much experience with modern GUI workflows.

**Comment by GitSquared** [comment]
I think we're going to forget the Apple M1 build for this one, as there are blocking upstream issues (https://github.com/microsoft/node-pty/issues/441 ...)

**Comment by GitSquared** [comment]
The release is ready but I'm waiting on more info about a security issue downstream, expected ETA tomorrow morning.

**Comment by GitSquared** [comment]
And we're gold! Thanks to everyone involved. Will cleanup some stuff and close this, release will be up in a few minutes at https://github.com/GitSquared/edex-ui/releases/tag/v2.2.3

**Comment by Jabster28** [comment]
@GitSquared is the homebrew repo updated automatically? it still says v2.2.2 for me...

**Comment by GitSquared** [comment]
Thanks! Forgot about this one. https://github.com/Homebrew/homebrew-cask/pull/93788
