### ISSUE TITLE
Change text in start animation

### ISSUE THREAD

**Issue by ThatTeamElrant** [GitSquared/edex-ui#909]
**Perceived idea awesomeness**
- [-] Wow, you don't have this yet???
- [ ] Would be super cool.
- [ ] I'm not sure a lot of people would use it, but I'd love to have it.
- [ ] Kind of a gadget, honestly, but why not?

**Perceived idea difficulty**
- [ ] Quit your job first.
- [ ] Would need some work, but nothing impossible.
- [ ] Shouldn't be too hard to make.
- [-] Like, *I* could do it.

---

(Write your idea or feature request here)

Changing the Text displayed in the start Animation

**Comment by wrac4242** [comment]
this doesn't seem to be that complicated, but will the text be a setting in the config? how will it format with the username?

**Comment by wrac4242** [comment]
although i have no clue how to properly change it through the settings, the displayed text is easy to change manually, [here is the function that sets the output to be displayed in the latest commit](https://github.com/GitSquared/edex-ui/blob/30590c6dc69cda38ba3f77da3bd60d4f3b03f3c7/src/_renderer.js#L386),

**Comment by Animus-Surge** [comment]
I think changing that text is already available in master

**Comment by GitSquared** [comment]
Nah, he's talking about the starting boot log I think.

**Comment by lebarde** [comment]
In order to completely tune the way it displays at startup you may want to add colors/highlights (why not even markdown). And to make it perfect it would be needed to pause, or even display HTML5 animations...

**Comment by GitSquared** [comment]
This is starting to sound like [features overload.](https://xkcd.com/2139/)

**Comment by lebarde** [comment]
Completely agreed, sorry @ThatTeamElrant this thread sparked my imagination :flushed:

**Comment by GitSquared** [comment]
I'm closing this as something really niche that i doubt will bring much to the project. Plus, the Hacknet-sourced boot log is part of the identity of this software, tbh.
