### ISSUE TITLE
How do turn off the world globe window?

### ISSUE THREAD

**Issue by dcstrange** [GitSquared/edex-ui#913]
The world globe seems to be consuming a GPU that cannot be ignored on my AMD APU 3400G. How to turn off the globe window? 😃Thx.

![Screenshot 2020-11-24 231346](https://user-images.githubusercontent.com/19701927/100112923-c0dda000-2eaa-11eb-99f7-e783fc17bf14.png)

**Comment by GitSquared** [comment]
You can't. The fact that it uses your GPU is a good thing; edex is tuned for performance, not power efficiency.
