### ISSUE TITLE
clear and cls don't work in bash for windows

### ISSUE THREAD

**Issue by Siah-All** [GitSquared/edex-ui#914]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

If I use bash for git (latest version) and want to use `clear`, the cursor goes back to the first line, but the screen is not clear at all.
After that, even when I quit bash then `clear` and `cls` don't work, with the same result.

**Comment by wrac4242** [comment]
can you try reproducing this on master? see the readme for more details

**Comment by wrac4242** [comment]
i have tried to reproduce this in master myself, on a windows laptop, but it doesnt seem to be having that issue, but please do check if the issue is still present in master

**Comment by Siah-All** [comment]
Failed at the edex-ui@3.0.0-pre prebuild-windows script.

[2020-11-25T14_34_03_308Z-debug.log](https://github.com/GitSquared/edex-ui/files/5597374/2020-11-25T14_34_03_308Z-debug.log)

That's why i use v2.2.2 in first place.

**Comment by GitSquared** [comment]
@Siah-All We're working on enabling pre-built packages for the latest version, in the meantime, here's a binary link for v3 on windows: https://github.com/Jabster28/edex-ui/suites/1560661528/artifacts/27999014

**Comment by Siah-All** [comment]
I have no such problem in this version.

**Comment by GitSquared** [comment]
Great! Thanks for testing it. We'll have a new release in a few days!
