### ISSUE TITLE
How to colorize the terminal?

### ISSUE THREAD

**Issue by lebarde** [GitSquared/edex-ui#916]
Hi,
I have seen [here](https://github.com/GitSquared/edex-ui/wiki/Terminal-color-filters) that we can colorize the terminal. But where do I put that code (and the one from [that thread](https://github.com/GitSquared/edex-ui/issues/287#issuecomment-441426617))?

Thanks by advance!

**Comment by Animus-Surge** [comment]
You would put that in a json document in the themes folder.

**Comment by GitSquared** [comment]
yup! see [themes](https://github.com/GitSquared/edex-ui/wiki/Themes) section in the wiki. The "chalkboard" included theme has term colors enabled, you can use that for reference if you prefer to learn by example.

**Comment by lebarde** [comment]
Oh nice! Thanks :-)
