### ISSUE TITLE
Install the app per machine

### ISSUE THREAD

**Issue by xmha97** [GitSquared/edex-ui#917]
Hi,
I want to install the app for all users to %ProgramFiles% instead of %LocalAppData%

**Comment by GitSquared** [comment]
Will be possible in the new release coming in a few hours.

**Comment by xmha97** [comment]
> 
> 
> Will be possible in the new release coming in a few hours.

I installed the new version but the program still installs on %LocalAppData%.
![image](https://user-images.githubusercontent.com/23485114/100388581-375fd680-3040-11eb-94bc-9060c0033245.png)
Please open this issue.
