### ISSUE TITLE
Not starting outside of terminal

### ISSUE THREAD

**Issue by robinsrk** [GitSquared/edex-ui#919]
When I am launching edex-ui inside any terminal, it launches without any problems. but when I am trying to launch with dmenu or other app launchers, it isn't launching the app.

**Comment by wrac4242** [comment]
quick question, is this from the master branch, or v2.2.2 release? and which operating system?

**Comment by robinsrk** [comment]
I am on arch, tried both git and non git version. both causes the same problem.

**Comment by GitSquared** [comment]
What's your ENV? (run `env` in a terminal)

**Comment by robinsrk** [comment]
tried in i3wm and other distro also, same problem

**Comment by robinsrk** [comment]
![image](https://user-images.githubusercontent.com/50480143/100428417-22298d00-30be-11eb-82a3-ac4ea4de18ae.png)

**Comment by GitSquared** [comment]
Does Chrome/Chromium/Brave works?

**Comment by robinsrk** [comment]
chromium, brave works perfectly without issues. edex also works when I launch it through terminal. but when I launch it through any dmenu or other stuff, it doesn't work

**Comment by Animus-Surge** [comment]
I’ll have a look. Might be an issue with shortcuts, can’t say for certain though

**Comment by wrac4242** [comment]
do you run it using sudo on the terminal? and can you possibly see if the latest release works on it, 
v2.2.3 came out earlier today, i doubt it would fix anything, but a few things were updated so it might work

**Comment by robinsrk** [comment]
I don't run it with sudo. just the edex-ui command in the terminal. and I updated today, but nothing changed. same problem

**Comment by GitSquared** [comment]
Please reopen if this still happens in v2.2.6
