### ISSUE TITLE
Windows - Opening in non-fullscreen

### ISSUE THREAD

**Issue by S-DRE** [GitSquared/edex-ui#920]
## Technical information
**Using version:**
   Latest - v2.2.3

**Running on:**
 - [x] Windows 10

**How comfortable you are with your system and/or IT in general:**
 - [x] My machine is fully under my control, tell me what you need

---

## Problem
Since the last update, the program opens "In fullscreen" (no upper bar, minimize, maximize or close buttons) but with the windows toolbar present. I tried the usual shortcuts for fullscreen like f11 and they don't seem to work.

**Comment by xmha97** [comment]
+1
I also face this problem.
The taskbar is on the app.
![eDEX-UI](https://user-images.githubusercontent.com/23485114/100490699-7d956280-3132-11eb-81da-0975e762362f.png)

**Comment by wrac4242** [comment]
first make sure that the enabled windowed setting is enabled in the settings.json, and then try clicking onto a different app, then clicking pack

**Comment by xmha97** [comment]
Hi @S-DRE 
By default, the eDEX-UI running in full-screen mode.
When you change the `settings.json` file in eDEX-UI, "forceFullscreen" will be removed.
Add below line to `settings.json`:
```
    "forceFullscreen": true,
```

**Comment by GitSquared** [comment]
https://github.com/GitSquared/edex-ui/blob/master/src/_boot.js#L183

Looks like forceFullscreen defaults to `false`, maybe it should be `true`? Could we first confirm that enabling this fixes the issue?

**Comment by xmha97** [comment]
I think forceFullscreen default should be `true`.
In this case, the problem is solved. 👍

**Comment by GitSquared** [comment]
After taking a second look, it seems like `forceFullscreen=true` is already the default, but it will apply only on new installations where the config hasn't been written yet...

I advise all affected to either add the `"forceFullscreen": true` line to their [settings.json](https://github.com/GitSquared/edex-ui/wiki/settings.json) or delete the file altogether and let edex fill in the new defaults.
