### ISSUE TITLE
Support Microsoft Store version of PowerShell on eDEX-UI

### ISSUE THREAD

**Issue by xmha97** [GitSquared/edex-ui#921]
Hi,
I installed PowerShell from Microsoft Store.
https://www.microsoft.com/store/productId/9MZ1SNWT0N5D
On settings.json, I entered this:
```json
{
    "shell": "C:\\Users\\Alireza\\AppData\\Local\\Microsoft\\WindowsApps\\pwsh.exe"
}
```
Now eDEX-UI can't run :(

But this worked:
```json
{
    "shell": "C:\\Program Files\\WindowsApps\\Microsoft.PowerShell_7.1.0.0_x64__8wekyb3d8bbwe\\pwsh.exe"
}
```

**Comment by GitSquared** [comment]
Could you try just entering `"pwsh.exe"` and seeing if eDEX can figure out the right path by itself?

**Comment by xmha97** [comment]
> 
> 
> Could you try just entering `"pwsh.exe"` and seeing if eDEX can figure out the right path by itself?

I try it. The problem persists.

**Comment by GitSquared** [comment]
Please re-open if this still happens on v2.2.6
