### ISSUE TITLE
Uncaught type error in process list when modal is closed

### ISSUE THREAD

**Issue by Animus-Surge** [GitSquared/edex-ui#929]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ ] `latest` (latest release, currently `v2.2.3`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Not the biggest problem in the world as it doesn't spawn an error modal or crash the app, but I've noticed in the dev console (ctrl+shift+i), when you close the process list modal, it spawns errors that relate to the modal not being in the HTML hierarchy anymore. 

```
Uncaught TypeError: Cannot read propery 'append' of null
```

I know where and why this is happening, and I'm working on a fix now. Just wanted to let you know that this is happening.

**Comment by GitSquared** [comment]
Thanks for the PR.
