### ISSUE TITLE
Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

### ISSUE THREAD

**Issue by bhismrajjoshi** [GitSquared/edex-ui#936]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ 1] `latest` (latest release, currently `v2.2.2`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ 1] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [1 ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(While giving permission to eDEX-UI. While running it; I am getting the bug of "[7391:1203/192721.758086:FATAL:electron_main_delegate.cc(254)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
zsh: trace trap  ./eDEX-UI-Linux-x86_64.AppImage"
I am not able to enjoy eDEX. How to fix this problem. I am using Kali linux version latest from kali website.
)**

**Comment by GitSquared** [comment]
Do as it says - eDEX is not supposed to be ran as root.

**Comment by bhismrajjoshi** [comment]
Yes it says; I got the answer for this. 
We need to type --no-sandbox after the command
