### ISSUE TITLE
filesystem path insertion failure 2

### ISSUE THREAD

**Issue by clragon** [GitSquared/edex-ui#938]
## Technical information
**Using version:**
 - `latest` (latest release, currently `v2.2.3`)

**Running on:**
 - Windows

**How comfortable you are with your system and/or IT in general:**
 - My machine is fully under my control, tell me what you need

---

## Problem

I am unable to insert file paths into the console. 
Opening files with left click works, but only for supported files.
Clicking unsupported files will do nothing.

I also noticed that its not possible to insert folders.
This is not a problem on linux, because the explorer will not run in detached mode.

I would suggest having right click insert file or folder paths, 
while left click just opens it, leaving it like it is right now.

**Comment by atharvabirtharia** [comment]
i don't understand a thing

**Comment by wrac4242** [comment]
so, you want to create folders in the file explorer easily? and also better support for opening/running files?

**Comment by GitSquared** [comment]
See #564 and https://github.com/GitSquared/edex-ui/commit/9263a6ccd79a98f66da3f8dca622be16735bbfd9 for path insertion - it now uses ctrl+click.

**Comment by GitSquared** [comment]
(By the way @clragon - nice seeing you hanging around again.)
