### ISSUE TITLE
Shows an error during startup

### ISSUE THREAD

**Issue by xmha97** [GitSquared/edex-ui#940]
Hi, I'm using eDEX-UI v2.2.4 on Windows.
This version shows an error during startup.
![image](https://user-images.githubusercontent.com/23485114/101108234-571b6f80-35e9-11eb-8c6c-d5dc6f6874dd.png)
Please fix this issue.
Thanks.

**Comment by Animus-Surge** [comment]
Please state which operating system you are using. Thanks in advance!

**Comment by wrac4242** [comment]
they said they are using windows.
can you check if your internet is connected, and see if a reinstall works?

**Comment by xmha97** [comment]
Hi, apparently there was a problem with my internet.
And now everything is working properly.

**Comment by Animus-Surge** [comment]
> they said they are using windows.

Apologies.. clearly I can’t read
