### ISSUE TITLE
Cannot read property 'en' of undefined

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [GitSquared/edex-ui#942]
## Technical information
**Using version:**
 - [x] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.4`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)
![image](https://user-images.githubusercontent.com/64138578/101125030-34ae4400-3633-11eb-943a-3bd2cf9c30e1.png)
Error just after opening up the app, no problem on the last version.

**Comment by wrac4242** [comment]
similar issue then to #924, so that probably needs reopening then

**Comment by GitSquared** [comment]
Will continue discussion there
