### ISSUE TITLE
doesn't start on RaspberryPi running Ubuntu 20.10 arm64

### ISSUE THREAD

**Issue by Itai-Nelken** [GitSquared/edex-ui#944]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.4`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux (Rpi 4 Ubuntu 20.10 arm64)
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

when running the AppImage (using this command: `    `)  it seems as if it's starting regularly, but it gets stuck on this line:
```
(node:58876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

here is the full Terminal output:
``` 
itai@UbuntuPi4-ultra-4gb:~/eDEX-UI-RPi$ ./eDEX-UI-Linux-arm64.AppImage 
▶  start     Starting eDEX-UI v2.2.4
ℹ  info      With Node 12.16.3 and Electron 10.1.6
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/itai/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /usr/bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/classes/terminal.class.js
- /tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/_boot.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/classes/terminal.class.js',
    '/tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/_boot.js',
    undefined
  ]
}
(node:58876) UnhandledPromiseRejectionWarning: Error: /tmp/.org.chromium.Chromium.Uu2ki9: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/tmp/.mount_eDEX-UZ8HvP5/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
(node:58876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:58876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by wrac4242** [comment]
hi, did you use the prebuild [linked in the Q&A](https://github.com/GitSquared/edex-ui#qa)?

**Comment by Itai-Nelken** [comment]
I used the arm64 version from here: https://github.com/GitSquared/edex-ui/releases/tag/v2.2.4

**Comment by GitSquared** [comment]
Could give the output of `uname -a`?

**Comment by Itai-Nelken** [comment]
```
Linux UbuntuPi4-ultra-4gb 5.8.0-1007-raspi #10-Ubuntu SMP PREEMPT Thu Nov 5 17:52:40 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by GitSquared** [comment]
Possibly related: https://github.com/microsoft/vscode/pull/106656

Could you get me the `ldd --version` on the Pi?

**Comment by Itai-Nelken** [comment]
```
ldd (Ubuntu GLIBC 2.32-0ubuntu3) 2.32
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by Botspot** [comment]
How's progress coming on this issue?

**Comment by GitSquared** [comment]
Haven't reproduced because i don't have an arm device, so, nothing to share for now...

**Comment by Botspot** [comment]
> Haven't reproduced because i don't have an arm device, so, nothing to share for now...

I have a spare Raspberry Pi that you can play around with. Interested?  
If so, I'll send you an email.

**Comment by olivertaxi** [comment]
Yes please

**Comment by Myscripku** [comment]
I now speaking english

Pada tanggal Min, 27 Des 2020 22.06 olivertaxi <notifications@github.com
menulis:

> Yes please
>

**Comment by GitSquared** [comment]
Damn spam. Thanks for the offer but I'm afraid I don't have the time to schedule a synchronous remote debugging session. Keep in mind this repo is, officially at least, unmaintained...

**Comment by Botspot** [comment]
> Thanks for the offer but I'm afraid I don't have the time to schedule a synchronous remote debugging session.
> Keep in mind this repo is, officially at least, unmaintained...

I would leave my Pi on 24/7 so you could login to it anytime you wanted to. (So no scheduling required)  
But if that's not something you're interested in, I understand.

**Comment by GitSquared** [comment]
You might want to check in v2.2.6, which has updated C libs and more ARM support (also an armv7 target, wich might work on the Pi)

**Comment by Itai-Nelken** [comment]
thanks!

**Comment by Itai-Nelken** [comment]
the release isn't appearing, how much time does it take until it appears on the releases page?

**Comment by GitSquared** [comment]
Check back in a few minutes, I'm just finishing writing the changelog ;)

**Comment by GitSquared** [comment]
@Itai-Nelken Just released. https://github.com/GitSquared/edex-ui/releases/tag/v2.2.6

**Comment by Botspot** [comment]
> @Itai-Nelken Just released. https://github.com/GitSquared/edex-ui/releases/tag/v2.2.6

See issue #1051. Hopefully it's an easy fix.

If you'd like, I can lend you one of my Pies as a remote desktop for you.

**Comment by GitSquared** [comment]
@Botspot I'm gonna take you up on that offer. I can send you my ssh key's fingerprint if you'd like - drop me a mail: gabriel@saillard.dev
