### ISSUE TITLE
Wrong Date

### ISSUE THREAD

**Issue by melchiorsjean** [GitSquared/edex-ui#945]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.4`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

(Write your report here)

My terminal eDEX-UI is showing a wrong hour, more specifically, 1 next the machine hour.

**Comment by wrac4242** [comment]
hey, this is possibly caused by a timezone being wrongly set somewhere, possibly forgetting to change for daylight saving in you region, but can you try running from source

**Comment by GitSquared** [comment]
could you provide a screenshot after running `date` in edex's terminal?
