### ISSUE TITLE
High consumption of ram memory on windows 10

### ISSUE THREAD

**Issue by Cesio137** [GitSquared/edex-ui#946]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [ X] `latest` (latest release, currently `v2.2.4`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x ] Windows 10

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ X] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

1. It seems that project does not have a good ram control on windows 10, if a command takes a certain time to execute, the program will consumes all the ram memory (8GB in my case) 

2. I tested cloning my repository: https://github.com/Cesio137/DOOM
size: 1gb
time 5 minutes before freeze my system, may vary depending on luck. 

3. I see in the task manager the program starts  thousands of cmd, and command line manager

**Comment by wrac4242** [comment]
can you try running from source, as i havent experienced this issue of ram usage being as high

**Comment by GitSquared** [comment]
> the program starts thousands of cmd, and command line manager

These are WMIC instances, the program which allows us to get a bunch of system information on windows (on *nix, we can just read sysfs, but sadly windows requires us to spin up new threads).

What you might be experiencing is CPU starvation, meaning whatever you're running is overloading your CPU so much that edex's WMIC instances don't have time to execute before new ones are spun up - and this creates a vicious cycle where more load -> more instances -> more load, you get the point. All of this can pretty much be attributed to Windows' shitty handling of threads. But I digress.

Could you get me your CPU model, and perhaps a task manager screenshot while this is happening?

**Comment by Cesio137** [comment]
@GitSquared strange because in linux it ran perfectly, i will send a FT give me a second

**Comment by GitSquared** [comment]
> All of this can pretty much be attributed to Windows' shitty handling of threads.

> strange because in linux it ran perfectly

...as I said. :)

**Comment by Cesio137** [comment]
@GitSquared looking deeper I found the problem, it was windows defender that was kind of congesting the processes.

I repeated the same steps but with the antivirus on and off, with it on after a while, edex and antivirus consumed 2gb of ram (total = 4gb) and kept going up. With the antivirus disabled, the process was in the range of 300 to 400mb only.

**Comment by GitSquared** [comment]
Interesting find, thanks for keeping me up to date. I think we can close this then?

**Comment by Cesio137** [comment]
yep
