### ISSUE TITLE
Introducing Discussions!

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#948]
It seems like this repo has been granted beta access to one of GitHub's latest features, [Discussions](https://github.com/home#home-community).

I think it would be a great opportunity to re-organize issue tracking on this repo (as we approach ticket #1000).
Here's a roadmap / wishlist:

- [x] Move all [idea] issues that aren't sufficiently refined to Discussions in the Ideas category.
- [x] Change the issue template config:
	- [x] point to Discussions instead of Issues for questions and ideas (also link to the right category if possible?) #954
	- [x] remove the [bug] label from the bug issue template - since all issues will now be potential bugs, we might leverage this label for confirmed issues only instead
- [x] See if there's any relevant Discussions template or setting we could use.
- [ ] Delete all legacy labels like [idea], [question].

**Comment by Animus-Surge** [comment]
I can help with a few things, notably pointing questions and ideas to the discussions tab

**Comment by GitSquared** [comment]
> Move all [idea] issues that aren't sufficiently refined to Discussions in the Ideas category.

You referring to this? or redirecting new issues? Because the latter should be handled by setting up new issue creation templates.

I put up this issue to track this, but I might not get working on it just now, so... apologies if i'm a bit unresponsive here.

**Comment by Animus-Surge** [comment]
> point to Discussions instead of Issues for questions and ideas (also link to the right category if possible?)

Moreso thinking of this, but I can do that as well

> apologies if i'm a bit unresponsive here

Not a problem! I've got a few other things I'm working on as well as this

**Comment by GitSquared** [comment]
![Screenshot_20201213_141344](https://user-images.githubusercontent.com/24496417/102012958-6f0f9380-3d4d-11eb-8b03-36b3572e214b.png)

Thanks for your help @Animus-Surge, new config looks great! Now only to migrate the previous idea discussions from issues to Discussions. I'll start working on this.

**Comment by GitSquared** [comment]
Turns out there's a "convert to discussion" button, thanks github!

**Comment by GitSquared** [comment]
All right, new templates are up, labels are cleaner than ever and the 20-something "issues" about feature ideas have been moved to Discussions. Closing this!
