### ISSUE TITLE
Futex error on startup, new install on Ubunto

### ISSUE THREAD

**Issue by bobbib92** [GitSquared/edex-ui#950]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.4`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

I'm running Ubuntu 20.04.1 LTS, under Windows Subsystem for Linux (WSL) 2. I downloaded and ran the eDEX-UI-Linux-x86_64.AppImage binary, which said I was missing a library. I installed it, tried again, and it said I was missing another one, so I kept doing that:
sudo apt-get install -y libxcursor1
sudo apt-get install -y libnss3
sudo apt-get install -y libgbm-dev
sudo apt-get install -y libatk-bridge2.0-0
sudo apt-get install -y libgdk-pixbuf2.0
sudo apt-get install -y libgtk-3-0
sudo apt-get install -y libgbm-dev

Now it runs, but displays a few messages where it is in the startup process, then aborts with an error about the futex facility returning an unexpected error. It runs and aborts in the blink of an eye. I'm running it from a bash shell. Output:

▶  start     Starting eDEX-UI v2.2.4
ℹ  info      With Node 12.16.3 and Electron 10.1.6
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/arg/.config/eDEX-UI
☐  pending   Mirroring internal assets...
The futex facility returned an unexpected error code.
Aborted

I am a bit of a noob, I know how to use command line utilities and what not, but I'm not experienced manually installing libraries for packages, so maybe I messed up something with that. Googling the futex error message, it seems to result in some cases from passing a messed up sem_t semaphore pointer to sem_init() or sem_wait().

**Comment by wrac4242** [comment]
futex is short for `fast user-space locking`

some other people are having [this issue](https://github.com/google/gvisor/issues/3635), they are using a docker container for it, and that seems to cause issue, possibly try `sudo apt update && sudo apt full-upgrade`to see if any packages were fixed
but the issue is possibly with the kernal, make sure that is the latest version

**Comment by bobbib92** [comment]
I tried the apt update & upgrade, which did update a few files, but eDEX halts on the same error. Thanks for the suggestion anyway.

**Comment by GitSquared** [comment]
Does WSL support running GUI apps? I'm not familiar with this stack but I think you should rather use the eDEX windows app and start a bash shell under WSL from there.
