### ISSUE TITLE
Error after running for a while

### ISSUE THREAD

**Issue by jcartner-young** [GitSquared/edex-ui#952]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.4`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need (provided the request is clear and concise)
 - [ ] I attended [Defcon](https://defcon.org/) last year

## System

$ inxi -Gv 2
System:    Host: Black-Box Kernel: 5.0.0-32-generic x86_64 bits: 64 Desktop: Xfce 4.14.1 Distro: Linux Mint 19.3 Tricia 
Machine:   Type: Desktop System: Gigabyte product: N/A v: N/A serial: <root required> 
           Mobo: Gigabyte model: J3455N-D3H serial: <root required> UEFI: American Megatrends v: F3 date: 11/16/2018 
CPU:       Quad Core: Intel Celeron J3455 type: MCP speed: 2194 MHz min/max: 800/2300 MHz 
Graphics:  Device-1: Intel driver: i915 v: kernel 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080i~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 500 (APL 2) v: 4.6 Mesa 20.0.8 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
Drives:    Local Storage: total: 208.68 GiB used: 124.63 GiB (59.7%) 
Info:      Processes: 227 Uptime: 2d 23h 03m Memory: 7.64 GiB used: 4.81 GiB (63.0%) Shell: bash inxi: 3.0.32 

---

## Problem

1. When initially launching, the console outline is drawn immediately but incorrectly, twice, before it jumps up into place to display the console.  If it is just a visual bug then it's not important, but if it is linked to other bugs, it could be important.

2. After an indeterminate amount of time, the app reports 'TypeError' errors in a dialogue in the middle of the window.  I understand a large number were fixed due to a randomly missing library, iirc?  The console log is as follows...

:~$ cd Apps/ && ./eDEX-UI.Linux.x86_64.AppImage 
▶  start     Starting eDEX-UI v2.2.4
ℹ  info      With Node 12.16.3 and Electron 10.1.6
ℹ  info      Renderer is Chrome 85.0.4183.121
▶  Startup   Initialized timer...
ℹ  info      Base config dir is /home/<username>/.config/eDEX-UI
☐  pending   Mirroring internal assets...
☐  pending   Loading settings file...
☐  pending   Resolving shell path...
ℹ  info      Shell found at /bin/bash
✔  success   Settings loaded!
☐  pending   Creating new terminal process on port 3000
✔  success   Terminal back-end initialized!
☐  pending   Starting multithreaded calls controller...
✔  success   Multithreaded controller ready
ℹ  info      Creating window...
☒  complete  Frontend window created!
…  watching  Waiting for frontend connection...
ℹ  info      Multithread worker started at 5724
ℹ  info      Multithread worker started at 5728
ℹ  info      Multithread worker started at 5731
[5663:1208/051254.124238:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_OPERATION: Framebuffer is incomplete.
[5663:1208/051254.142303:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_OPERATION: Framebuffer is incomplete.
[5663:1208/051254.180262:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[5663:1208/051254.183075:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[5663:1208/051255.106895:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✔  success   Connected to frontend!
◼  Startup   Timer run for: 8.59s
[5663:1208/051255.262089:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
[5663:1208/051255.263908:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
ℹ  info      Resized TTY to  154 033
ℹ  info      UpdateChecker: Running latest version.
☐  pending   Creating new TTY process on port 3002
✔  success   New terminal back-end initialized at 3002
[5663:1209/010639.312576:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✔  success   TTY 3002 connected to frontend (process PID 28290)
☐  pending   Creating new TTY process on port 3003
✔  success   New terminal back-end initialized at 3003
[5663:1209/043735.996762:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✔  success   TTY 3003 connected to frontend (process PID 30183)
[5663:1209/044838.973394:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
ℹ  info      Resized TTY to  185 036
☐  pending   Creating new TTY process on port 3004
✔  success   New terminal back-end initialized at 3004
✔  success   TTY 3004 connected to frontend (process PID 24133)
[5663:1209/060525.130043:ERROR:gl_utils.cc(316)] [.RendererMainThread-0x14d67b6e4100] GL_INVALID_FRAMEBUFFER_OPERATION: Framebuffer is incomplete.
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
✖  error     TypeError: Cannot read property 'set' of undefined: Uncaught TypeError: Cannot read property 'set' of undefined
⬤  debug     at /tmp/.mount_eDEX-UqhKhuL/resources/app.asar/assets/vendor/encom-globe.js 1:474144
●  note      NetStat: Error parsing data from myexternalip.com
⬤  debug     Error: SyntaxError: Unexpected token < in JSON at position 1
●  note      NetStat: Error parsing data from myexternalip.com
⬤  debug     Error: SyntaxError: Unexpected token < in JSON at position 1
☒  complete  TTY exited at 3004 { exitCode: 255, signal: 0 } undefined
☒  complete  TTY exited at 3003 { exitCode: 255, signal: 0 } undefined
☒  complete  TTY exited at 3002 { exitCode: 255, signal: 0 } undefined
☒  complete  Terminal exited { exitCode: 0, signal: 0 } undefined
☒  complete  Shutting down...

It looks like a JavaScript error and some basic parsing errors.  (Is it using a JS engine? Chrome browser? lol)

I get a dialogue on the screen over the console which mirrors the "Uncaught Type Error" console error.

This *could* be eDEX not coping with the system suspending after a couple of hours.   May be useful to recreate the suspend on another machine to see if is eDEX.

Lastly, is there any way to improve performance or generally decrease CPU usage and maybe customise the console module layout?  Or even create custom modules?

Thanks.

**Comment by jcartner-young** [comment]
Would it be possible to implement timestamps on the console output?  It would help match other system events to the console output easily, imho.

**Comment by wrac4242** [comment]
can you try running off master

**Comment by jcartner-young** [comment]
Thank you.  I will try the Master branch.

Before I do, can I ask why?

**Comment by jcartner-young** [comment]
wrac4242, I am sorry for being suddenly thick, but I can't remember where I saw the master branch of eDEX...  I've been looking through the GitHub pages but can't find it.  Do you have a link on hand?

Many thanks.

**Comment by Animus-Surge** [comment]
> Before I do, can I ask why?

There might be things that are already fixed on master, so we have people test through master to see if their specific issue has already been fixed.

As for finding the master branch, it should automatically come up when you click the "code" tab. From there you can download a zip or clone the repository to your computer and follow the building instructions in the readme

**Comment by jcartner-young** [comment]
> > Before I do, can I ask why?
> 
> There might be things that are already fixed on master, so we have people test through master to see if their specific issue has already been fixed.
> 
> As for finding the master branch, it should automatically come up when you click the "code" tab. From there you can download a zip or clone the repository to your computer and follow the building instructions in the readme

Fantastic, thank you so much for that elucidation.

I'll get on with it on the morrow. :+1:

**Comment by jcartner-young** [comment]
> > Before I do, can I ask why?
> 
> There might be things that are already fixed on master, so we have people test through master to see if their specific issue has already been fixed.
> 
> As for finding the master branch, it should automatically come up when you click the "code" tab. From there you can download a zip or clone the repository to your computer and follow the building instructions in the readme

Fantastic, thank you so much for that elucidation.

I'll get on with it today when I get chance lol :+1: 

Thanks again for your help.

**Comment by jcartner-young** [comment]
> > Before I do, can I ask why?
> 
> There might be things that are already fixed on master, so we have people test through master to see if their specific issue has already been fixed.
> 
> As for finding the master branch, it should automatically come up when you click the "code" tab. From there you can download a zip or clone the repository to your computer and follow the building instructions in the readme

Right.  I've got the zip file.

Do I need to compile it or something?  Not sure what you want me to do with this zip file :/

**Comment by jcartner-young** [comment]
I don't think I know enough about compiling/minifying JS and the instructions don't give me much confidence in installing these packages and possibly breaking my system if I get it wrong... The commands don't work on my computer without messing with extra packages.  I'd rather not break my system - Linux is not the most forgiving OS lol.  I don't even know NodeJS.

I will just wait until it gets fixed :/

Sorry for not being the most confident in these specific set of skills.

Thank for your help and I am terribly sorry for wasting your time.

**Comment by GitSquared** [comment]
Hey! Sorry I couldn't get to this thread sooner. From what I can gather from your issue report, I think this might be an error we already fixed - see #941. We have not released a new version with the fix yet but i'm starting to consider it.

> Lastly, is there any way to improve performance or generally decrease CPU usage and maybe customise the console module layout? Or even create custom modules?

I invite you to browse the open issues with the [idea] label to find where we're tracking all this crazy features ideas, and also to check #769. Regarding perf, the software is tuned for performance which is why you might see a constant cpu usage. Keep in mind, if you're reading values in edex, 100% = one core, not your whole CPU.
