### ISSUE TITLE
Question/Idea? Read this first!

### ISSUE THREAD

**Issue by Animus-Surge** [GitSquared/edex-ui#954]
### Got a question? We've got an answer. Got an idea? We'd love to hear it!

As of several days ago, we now have access to the Github Discussions beta, which means that we will be utilizing that for any ideas or questions that you might have. This is to save the issues page for any bugs that you find, and cleans up the place a bit. Below are links to their respective pages as well so it's easier to find.

Questions: https://github.com/GitSquared/edex-ui/discussions?discussions_q=category%3AQ%26A
Ideas: https://github.com/GitSquared/edex-ui/discussions?discussions_q=category%3AIdeas

**Comment by GitSquared** [comment]
Thanks for putting this up! I've pinned it. In the future, we may want to leverage [the new issue template chooser config](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser).

**Comment by Animus-Surge** [comment]
> we may want to leverage the new issue template chooser config

That's a good point. I'll see what I can do
