### ISSUE TITLE
Disable GitHub new version notification

### ISSUE THREAD

**Issue by Weilory** [GitSquared/edex-ui#956]
Hi man, I wonder if I can disable github new version notification. Could you please make a checkbox "don't show this again" on the pop up box next to OK button? Appreciate it.

**Comment by GitSquared** [comment]
Curious about why you'd need this? Updates often bring security patches and other bugfixes which I'd like everyone to get ASAP, which is why the notification exists in the first place.

**Comment by Weilory** [comment]
Due to CPU power consuming (the application solution I provided to implement certain cores on MacOS does not work, which you were right, MacOS hardware won't let us do it), I cannot use eDex as main code editor, so that I **use it as a start-up application** to run alias that I have coded in `.bash_profile` to set up my development rapidly. I would like to keep an eye on new version release, because I love this app. However, the main functionality I can use for now, is a start-up run. the **new version notification** is somehow annoying. It will be much more efficient if allowing user to dismiss notification.

**Comment by GitSquared** [comment]
[hmmm](https://xkcd.com/1172/). I'm sorry, but I can't add that in. New updates are infrequent (there was a 1.5 years span without a single one), should be quick to install, and might fix serious bugs and vulnerabilities that I don't want people to miss. Finally, if you're not using edex as it's meant to be used, I'd invite you to fork it. If you bump the version number on your fork in `src/package.json` to something higher than the current release, you will never see this notification.
