### ISSUE TITLE
Error: ENOENT: no such file or directory... / unexpected end of file

### ISSUE THREAD

**Issue by iTonyYo** [GitSquared/edex-ui#962]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [X] `latest` (latest release, currently `v2.2.4`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [ ] Windows
 - [X] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [X] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
![image](https://user-images.githubusercontent.com/5499703/102211649-dde81a80-3f0e-11eb-9609-d4d4ac4179a0.png)

**Comment by GitSquared** [comment]
Lmao you def didn't get lucky with this one. Your connection most probably broke up triggering #941. This has been fixed on master but not released yet - I'm expecting to ship it this week. In the meantime, you can click "Panic" to close the error pop-ups and you should be good to go.

Thanks for submitting a report.
