### ISSUE TITLE
IP Address and location does not work

### ISSUE THREAD

**Issue by xAllObj** [GitSquared/edex-ui#964]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.5`)
 - [x]  `v2.2.4`
 - [x] `v2.2.3`

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

---

## Problem

Starting with release of 2.2.3 the location an IP address does not work anymore.
It still works in 2.2.2, installed again for testing purpose.

- Network state shows online, but IPv4 Address is not shown.
- Location just shows unknown.

I tried on 3 different system, Windows 10 20H2, all the same.

**Comment by jeffrussell37** [comment]
I also have this issue with version 2.2.5 running on Fedora 33 (fresh install) on a MacBook Pro 2015.

**Comment by GitSquared** [comment]
Note that since recently the databases used for local geoip tracking aren't bundled with edex but need to be retrieved at launch. Watch for a spike in the network monitor, and if after it's done you still have no info on the displays, delete [config dir](https://github.com/GitSquared/edex-ui/wiki/userData)/geoIPcache (or geoIPcache-tmp) and relaunch edex to try again.

Databases are ~70mb, might take some time depending on your internet connection.

**Comment by xAllObj** [comment]
I tried the suggested workaraounds, deleted both folders, after a restart ...\AppData\Roaming\eDEX-UI\geoIPcache stays empty even after no network activity.
I checked and disabled Windows firewall for testing purpose, even it should not interupt the downloading process.
Also the update to 2.2.5 did not change anything, reset all settings in \AppData\Roaming\eDEX-UI\.
BTW: As of jeffrussel37 the same issue seems to exist on different kind of systems, I check the issue on Mac OS Calalyna, it's working there.

**Comment by GitSquared** [comment]
Welp I'm afraid I can't reproduce this so far. Tried both my dev build and the v2.2.5 binary, deleting the geoIP caches, corrupting them, cutting my internet halfway through, and in the end it always restored itself back to a working state... :/

| - | - |
| - | - |
| ![image](https://user-images.githubusercontent.com/24496417/102767929-9e8f5300-4380-11eb-9679-2867c5b30524.png) | ![image](https://user-images.githubusercontent.com/24496417/102767874-86b7cf00-4380-11eb-947f-8bb7be0bb8a8.png) |

Can you confirm that you see the same spike in network traffic at launch, and perhaps check the filesizes of the downloaded databases in the cache folder?

**Comment by xAllObj** [comment]
Ich tried to delete the folder and it was rercreated.
The filesize on the windows computers... 0. The files just don't exist.
Monitoring the network activity, I cannot see any tries to connect to the internet from eDEX-UI.exe
I also tried to copy the downloaded files from macOS to the directory, but it didn't change anything.
Does eDEX-UI use a browser component to download files? I use the latest Version of EDGE (chromium based)

**Comment by xAllObj** [comment]
I finally installed on my business laptop Windows 10 20H2 Build 19042.685, same version like others.
The geoIPcache folder is crated during startup, but is still empty.

**Comment by SiscoMajada** [comment]
Try in settings (ctrl-shift-S) and set "Toogle experimental features for
the network globe" set it to true. and delete the files as mentioned by
Gaby. Then restart edex again. Worked for me (windows 10 pro)

**Comment by xAllObj** [comment]
THX SiscoMajada, this did the trick for me on one computer. I already tried this feature in earlier releases, but it did not work, so I didn't try it again... But it only worked once.

Now it does not work on any computer anymore.
Computer 1:
It worked once after the change of the setting, not all 3 files are still in geoIPcache
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        21.12.2020     18:30        7007104 GeoLite2-ASN.mmdb
-a----        21.12.2020     18:30       65725278 GeoLite2-City.mmdb
-a----        21.12.2020     18:30        3954991 GeoLite2-Country.mmdb
During startup geoIPcache-tmp is created, download starts and up to 2 files are shown, but it breaks the process and the folder is deleted, not moving the files to geoIPcache.

Computer 2:
I can see that the geoIPcache-tmp is created, sometimes I see up to 2 files, but they are not moved to geoIPcache.
The setting are identical on both systems now, only changes are the language and the theme (I also tried with no changes)

It seems that the download process is broken.

**Comment by GitSquared** [comment]
> Try in settings (ctrl-shift-S) and set "Toogle experimental features for
the network globe" set it to true.

Unless I'm missing something here I don't see how this could affect the whole geoIP situation.

> I can see that the geoIPcache-tmp is created, sometimes I see up to 2 files, but they are not moved to geoIPcache.

There should be 3 of them before it renames -tmp to cache and reloads the data in-memory. Agree with you that something's fucking up at the download step, still not sure why though...

**Comment by GitSquared** [comment]
If anyone fancies digging deeper on this, here's the [actual library][https://github.com/GitSquared/node-geolite2-redist) that handles databases downloads and updates, and the relevant call in edex is here:

https://github.com/GitSquared/edex-ui/blob/b19c4bc263a13f870a02b1d2f1537eb60a704798/src/classes/netstat.class.js#L44-L57

**Comment by SiscoMajada** [comment]
Sometimes i have to wait a few minutes b4 it shows the lat/lon, depend on
the strength of you wifi signal, but it eventualy pops up. When i moe my pc
close to the route it is there the moment i start up eDEX_UI but when i go
back to my hobbyroom i hsve to wait for a while for it to pop up because of
to far away from the wifi signal. Try this, move the router closer to you
and see if that changes anything. Works for me everytime.
I hope this helps.
Francisco.

**Comment by xAllObj** [comment]
It does not depend on the connection, and if, it is the other way round.
The connection to the router is stable with 1,51Gbit/s on Computer 2 (which never worked) on Computer 1 (it worked once) it is much slower, as it is an old Surface Pro Tablet.
It seems that the process does not wait long enought till the files are downloaded and put to the correct directory. Also I see the folder geoIPcache-tmp in eDEXUI, even it is already deleted, so the ls process of the interface does start before the interface is displayed.
Nevermind, I still use 2.2.2 and will look at the project at a later point.
It worked onece on one WIN Computer, but stopped immediatly at the 2nd try and still works on macOS  at the same location with less connection speed (doesn't matter in this way, as it is limited by the internet speed of 100Mbit/s).

**Comment by SiscoMajada** [comment]
I just moved away from the kitchen where the routeris and the lat&lon says
"unkown" when i go back to the kitchen is pops up again immediately, when i
move away from it again it-s gone again. coincidence ??? I don't know, but
we have a very weak wifi here in spain so the closer i sit to my router the
better it works.This on windows 10 pro. With my laptop on which i have
Linux Mint installed same thing. This time i didn't delete the files. They
keep coming back anyways but the lat/lon stil shows when im close to the
router.  Im not a programmer so i can't help you any further. Maybe some
one can dig in and find out what is actualy going on, but with me it is the
signal for sure.[image: offline hobbyroom.jpg][image: kitchen.jpg]

**Comment by j-tesla** [comment]
My signal strength is good, I don't use any proxies. Yet, something is not working.

![image](https://user-images.githubusercontent.com/58279279/103208010-aa9d8680-4925-11eb-911b-375c6eaf121f.png)

**Comment by GitSquared** [comment]
Updates on this to clear up a bit of confusion:

- If your signal strength is too low/internet connection times out, the network monitor will go in an offline state, and it may lose your IPv4 display before completely going dark.
- Since a few updates ago the geoIP databases we need for the globe & IP stuff to display have been excluded from edex's binary release (for various technical & legal reasons). **Those are now downloaded in the background when you start the UI, and when/if the download is succesfull the UI updates with the data appearing on the globe and in the IP box.**
However, one issue I've noticed is that whenever you restart the UI, the databases will be fully refreshed regardless of whether there's an already up-to-date version cached on disk. So that's not ideal and definitely something I should fix.

**Comment by xAllObj** [comment]
The IP Address is not shown, not depending on the network state.
All other connections work perfectly, it is not a problem of the enviroment (Testet on 4 Laptops, does work on 1 macOS Laptop, sometimes on the very slow old Surface Tablet, but never on fast Windows Laptops)

**Comment by xAllObj** [comment]
Having a look at the code, maybe you should go the async path with this project and add:

await geolite2.downloadDbs()

Just an idea, as the slow notebook works sometimes.

**Comment by GitSquared** [comment]
We're already doing this asynchronously, just without the await syntax. What's your internet speed?

**Comment by xAllObj** [comment]
116,8 Mbit/s, and they are really useable.
But on the Subface, where it works sometimes, it is limited by an old network adapter, so sometimes I just have 54Mbit/s.

**Comment by GitSquared** [comment]
Weird, these are good numbers. Would you happen to have any kind of firewall on your LAN, or perhaps on your WAN (where do you live?)

**Comment by j-tesla** [comment]
> 116,8 Mbit/s, and they are really useable.
> But on the Subface, where it works sometimes, it is limited by an old network adapter, so sometimes I just have 54Mbit/s.

My network is at least 5 MB/s almost all time, it ain't working on my linux device too. (irrespective of my network strength)

**Comment by xAllObj** [comment]
Sometimes it works on the slow Windows Notebook.
It works on the macOS Notebook in the same Network Environment. I already in estimated all Windows setting (file permission, Firewall setting (also tied with completely disabled Firewall).
Also I could investigate, that 2 of the 3 geoIP DB files are downloaden to the tmp folder, it only takes some seconds, but the tmp folder Was deleted before the 3rd file is downloade completely.
I guess, that an other thread already ties to access the files and the download prosess is interupted. On the slow Notebook it works Sometimes.

**Comment by xAllObj** [comment]
The are no access limitations to the Internet, I live in Munich, Germany.

**Comment by GitSquared** [comment]
> but the tmp folder Was deleted before the 3rd file is downloade completely.

that's interesting. I'm starting to think of a saner rewrite of the underlying geoip library. might work on this in jan-feb 2021, but I still have other things cooking i need to take care of.

**Comment by GitSquared** [comment]
v2.2.6 releasing in a few mins has an updated version of the geoip lib which should optimize the database downloads and prevent/reduce the frequency of these kind of issues. Please reopen if needed
