### ISSUE TITLE
Build targets

### ISSUE THREAD

**Issue by GitSquared** [GitSquared/edex-ui#97]
Before 1.0 final release:

**LINUX**
- [x] Add AppImage build target
- [x] Check if Snap works, perhaps remove it entirely
- [x] Include the AppImage in AppImageHub

**WINDOWS**
- [x] Try to find a solution for FS' CWD tracking on this OS
- [x] Fail
- [x] Find a fallback solution
- [x] Test and debug

**MAC OS**
- [x] Get a mac VM
- [x] Perform a gross evaluation of the codebase to look for os-specific stuff that needs to be modified (notably check systeminformation's compatibility)
- [x] Add MacOS build targets to the package.json
- [x] See if it builds in CI
- [x] Test and debug
- [x] Update the Wiki

**Comment by probonopd** [comment]
Please ping me once the AppImage is available for download so that I can include it in the AppImageHub central directory of available AppImages. Thanks.
