### ISSUE TITLE
Jhh

### ISSUE THREAD

**Issue by mistrzu350** [GitSquared/edex-ui#974]

**Comment by kamalov69** [comment]
Hi

**Comment by wrac4242** [comment]
hey, are you having any issues with edex-ui?

**Comment by kamalov69** [comment]
?

нд, 20 груд. 2020, 23:49 користувач wrac4242 <notifications@github.com>
пише:

**Comment by wrac4242** [comment]
@GitSquared it happened again

**Comment by GitSquared** [comment]
Great....
