### ISSUE TITLE
[macOS]can't load ip 151.101.228.133:443

### ISSUE THREAD

**Issue by meclus** [GitSquared/edex-ui#982]
[macOS]

download from brew

Error: connect ECONNRESET 151.101.228.133:443

**Comment by ajian2002** [comment]
[linux]
i also have this problem

**Comment by hxhlb** [comment]
me too!

Ubuntu 20.04.1 LTS
✖  error     Error: connect ECONNREFUSED 127.0.0.1:443: Uncaught Error: connect ECONNREFUSED 127.0.0.1:443
⬤  debug     at events.js 287:7

**Comment by rayest** [comment]
[macos]
 I also have this problem

**Comment by wyfang** [comment]
[macos]
I also have this problem

**Comment by wrac4242** [comment]
may i ask which version you are on?

**Comment by hxhlb** [comment]
My environment:

Ubuntu 20.04.1 LTS
node version: 14.15.3
npm version: 6.14.10
yarn version: 1.22.5
eDEX-UI v2.2.5, download from release page, eDEX-UI-Linux-x86_64.AppImage

**Comment by chengs2035** [comment]
so how to fix it?

**Comment by Chad97** [comment]
![image](https://user-images.githubusercontent.com/42793079/103342738-4b767800-4ac5-11eb-8bc4-1f6283c78927.png)

I am like this, how to solve it?

**Comment by wrac4242** [comment]
can someone try building from source, to see if the issue is with the app image

**Comment by Glonee** [comment]
same problem

**Comment by GitSquared** [comment]
I think this comes from here: https://github.com/GitSquared/edex-ui/blob/a8e29ce5a2501ece4369ea901d10092fbdf58034/src/classes/terminal.class.js#L172-L175

...where the frontend terminal viewer is attempting to establish a websocket connection to the background TTY process.

My first instinct would be to hazard a guess about some macOS "safety/security" whatever feature blocking connections from edex (even local ones apparently... go figure why), but the `:443` part of the address is unexpected. The code I linked is supposed to connect to `127.0.0.1:3000`.

**Comment by wrac4242** [comment]
0.0.0.0 is an error/invalid ip address, so something is wrong there

**Comment by wrac4242** [comment]
can someone who is having this issue please run it from source, to rule out it being a build issue

**Comment by GitSquared** [comment]
See #1050
