### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by Samuel20354** [GitSquared/edex-ui#983]
I have downloaded and i have ran `mpn run install-linux` but when i try to run it, it says:
```
> edex-ui@3.0.0-pre start
> electron src --nointro

[3278:1222/221125.442496:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/samuel20354/edex-ui/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
/home/samuel20354/edex-ui/node_modules/electron/dist/electron exited with signal SIGTRAP
npm ERR! code 1
npm ERR! path /home/samuel20354/edex-ui
npm ERR! command failed
npm ERR! command sh -c electron src --nointro

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-22T22_11_25_461Z-debug.log
```
I have also try running it with sudo but it comes back with the same error

**Comment by wrac4242** [comment]
can you give the full logs from the bottom, i would recommend reinstalling now, as running as sudo breaks some stuff

**Comment by wrac4242** [comment]
just checking this is on linux right?

**Comment by Samuel20354** [comment]
yes this is on kali linux and what do you mean by, can you give the full logs from the bottom, that was the whole error

**Comment by wrac4242** [comment]
the logs that are linked at the bottom of the error
`npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-22T22_11_25_461Z-debug.log`

**Comment by GitSquared** [comment]
> The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/samuel20354/edex-ui/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.
/home/samuel20354/edex-ui/node_modules/electron/dist/electron exited with signal SIGTRAP


Check this out: https://github.com/GitSquared/edex-ui/issues/588#issuecomment-538114654
