### ISSUE TITLE
Error: read ECONNRESET at events.js 287:7

### ISSUE THREAD

**Issue by yihuajack** [GitSquared/edex-ui#989]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [x] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
(no matter running as administrator or not:)
(using whatever shells)
(other parts seem normal)
Error: read ECONNRESET
Uncaught Error: read ECONNRESET
at events.js 287:7
![image](https://user-images.githubusercontent.com/23608500/103140534-9f2e3d80-4722-11eb-80a3-e4722a801985.png)

**Comment by zengdabo** [comment]
I have the same problem too! Win10 20H2

**Comment by wrac4242** [comment]
can you try running from source, just to rule out build issues

**Comment by yihuajack** [comment]
If executing
```
npm run install-windows
npm run start
```
then running will get stuck at
```
------------------- Python --------------------
Successfully installed Python 2.7
```
Building with
```
npm install
npm build-windows
```
is a success, however, running `edex-ui\dist\win-unpacked\eDEX-UI.exe` shows the exactly the same error as before.

**Comment by wrac4242** [comment]
looks like it is a build error, somewhere, somehow, that might also be causing other errors

**Comment by Hitler711** [comment]
> 
> 
> 
> ## Technical information
> **Using version:**
>  - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
>  - [x] `latest` (latest release, currently `v2.2.5`)
>  - [ ] `vX.X.X` (specify other version)
> 
> **Running on:**
>  - [ ] Linux
>  - [x] Windows
>  - [ ] macOS
> 
> **How comfortable you are with your system and/or IT in general:**
>  - [ ] I'm kind of lost, honestly
>  - [x] I know what's up, I could help you run some commands or checks
>  - [ ] My machine is fully under my control, tell me what you need
>  - [ ] I attended [Defcon](https://defcon.org/) last year
> 
> ---
> 
> ## Problem
> (no matter running as administrator or not:)
> (using whatever shells)
> (other parts seem normal)
> Error: read ECONNRESET
> Uncaught Error: read ECONNRESET
> at events.js 287:7
> ![image](https://user-images.githubusercontent.com/23608500/103140534-9f2e3d80-4722-11eb-80a3-e4722a801985.png)
> 
>

**Comment by Wongboo** [comment]
have the same problem, using homebrew cask version in MacOS

**Comment by BowenTan-China** [comment]
Mee too!

**Comment by BowenTan-China** [comment]
Me too!

**Comment by GitSquared** [comment]
Could any of you try downloading [this file](https://github.com/GitSquared/node-geolite2-redist/raw/master/redist/GeoLite2-City.tar.gz) directly and tell me:

- if the download starts
- what's the download speed, and what's your internet connection speed (speedtest.net or other nominal test)
- what's the size of the downloaded file

**Comment by BowenTan-China** [comment]
40.0 KB/s - 2.3 MB，total 30.3 MB
download 3.3 Mbps


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GitSquared/edex-ui"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 晚上7:23
收件人:&nbsp;"GitSquared/edex-ui"<edex-ui@noreply.github.com&gt;;
抄送:&nbsp;"448903637"<448903637@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [GitSquared/edex-ui] Error: read ECONNRESET at events.js 287:7 (#989)





 
Could any of you try downloading this file directly and tell me:
  
if the download starts
 
what's the download speed, and what's your internet connection speed (speedtest.net or other nominal test)
 
what's the size of the downloaded file

**Comment by yihuajack** [comment]
- The download does start
- Download speed:
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   166  100   166    0     0    166      0  0:00:01 --:--:--  0:00:01   231
Internet connection speed: 95.54 Mbps download, 184.81 Mbps upload (speedtest.cn)
- The size of the downloaded file: 166 bytes

**Comment by nd002723** [comment]
please check the dns record to set the hosts of the `raw.githubusercontent.com` hosts

#### IP list
```
103.245.222.133
151.101.0.133
151.101.100.133
151.101.108.133
151.101.128.133
151.101.136.133
151.101.192.133
151.101.48.133
151.101.64.133
151.101.76.133
151.101.8.133
185.31.19.133
199.232.96.133
```

**Comment by nd002723** [comment]
> ## Technical information
> **Using version:**
> 
> * [ ]  `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
> * [x]  `latest` (latest release, currently `v2.2.5`)
> * [ ]  `vX.X.X` (specify other version)
> 
> **Running on:**
> 
> * [ ]  Linux
> * [x]  Windows
> * [ ]  macOS
> 
> **How comfortable you are with your system and/or IT in general:**
> 
> * [ ]  I'm kind of lost, honestly
> * [x]  I know what's up, I could help you run some commands or checks
> * [ ]  My machine is fully under my control, tell me what you need
> * [ ]  I attended [Defcon](https://defcon.org/) last year
> 
> ## Problem
> (no matter running as administrator or not:)
> (using whatever shells)
> (other parts seem normal)
> Error: read ECONNRESET
> Uncaught Error: read ECONNRESET
> at events.js 287:7
> ![image](https://user-images.githubusercontent.com/23608500/103140534-9f2e3d80-4722-11eb-80a3-e4722a801985.png)

please check the dns record to set the hosts of the `raw.githubusercontent.com`

#### IP list
```
103.245.222.133
151.101.0.133
151.101.100.133
151.101.108.133
151.101.128.133
151.101.136.133
151.101.192.133
151.101.48.133
151.101.64.133
151.101.76.133
151.101.8.133
185.31.19.133
199.232.96.133
```

**Comment by AoEiuV020** [comment]
> Could any of you try downloading [this file](https://github.com/GitSquared/node-geolite2-redist/raw/master/redist/GeoLite2-City.tar.gz) directly and tell me:
> 
> * if the download starts
> * what's the download speed, and what's your internet connection speed (speedtest.net or other nominal test)
> * what's the size of the downloaded file

We cannot connect to github in mainland China, please support system proxy or support setting manual proxy,

**Comment by GitSquared** [comment]
> We cannot connect to github in mainland China, please support system proxy or support setting manual proxy,

will look into this

**Comment by GitSquared** [comment]
> > Could any of you try downloading [this file](https://github.com/GitSquared/node-geolite2-redist/raw/master/redist/GeoLite2-City.tar.gz) directly and tell me:
> > 
> > * if the download starts
> > * what's the download speed, and what's your internet connection speed (speedtest.net or other nominal test)
> > * what's the size of the downloaded file
> 
> We cannot connect to github in mainland China, please support system proxy or support setting manual proxy,

Now tracked in #1050

**Comment by TENX-S** [comment]
I had the same problem.
