### ISSUE TITLE
Core Count Windows

### ISSUE THREAD

**Issue by ivanjrt** [GitSquared/edex-ui#990]
## Technical information
**Using version:**
 - [ ] `latest` (latest release, currently `v2.2.5`)

**Running on:**
 - [ ] Windows

**How comfortable you are with your system and/or IT in general:**
 - [ ] I know what's up, I could help you run some commands or checks
---

## Problem
on the Windows side for the processors we have 3 values:
CPU Count            - _aka Sockets specially in Workstations and servers_
Cores                     -  _How many cores are within the CPU(s)_
Logical Processors -  _How many logical processors are within a Core_

it would seem that you guys are referring to the Logical Count , and -not the actual Core Count, no worries this is common mistake : )
![ERR](https://user-images.githubusercontent.com/44326428/103147868-b10de180-471e-11eb-9088-7bc05b007217.jpg)

##Potential Fix,  I'm not sure how are you guys getting this Telemetry on the backend so:
**On PowerShell**  _--Tested_
`(Get-CimInstance -ClassName 'Win32_Processor').NumberOfCores`

**On C#:**  -- _No tested but below is a short article, I was having issues loading using System.Management...;_
          `int coreCount = 0;
            foreach (var item in new System.Management.ManagementObjectSearcher("Select * from Win32_Processor").Get())
            {
                coreCount += int.Parse(item["NumberOfCores"].ToString());
            }
            Console.WriteLine("Number Of Cores: {0}", coreCount);`

full source app sln, can be found here
source : [http://referencedesigner.com/blog/how-to-find-the-number-of-cores-and-logical-processors-using-c-net/1999/](url)

**Comment by GitSquared** [comment]
It's not a mistake, most modern CPUs with HyperThreading or similar techs do indeed report more cores to the OS than there are physical cores on the die.

But those have optimized scheduling at the hardware level and are effectively capable of running tasks nearly in parallel, so as a user you shouldn't care about the difference.

What matters to you as a user is how many threads can run in parallel on your system and the "cores" display in edex tells you just that.
