### ISSUE TITLE
Trying to run latest version on Ubuntu 20.10: "TypeError: Cannot read property 'getExtension' of null

### ISSUE THREAD

**Issue by pmarreck** [GitSquared/edex-ui#993]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [x] Linux
 - [ ] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [ ] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [x] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem
Here's the full error:
TypeError: Cannot read property 'getExtension' of null
at /tmp/.mount_eDEX-UVSPHKY/resources/app.asar/assets/vendor/encom-globe.js 29516:34

Maybe I don't have any extensions installed and this is why this error is cropping up?

**Comment by pmarreck** [comment]
@GitSquared Threadripper 3990x and two 2080ti's 😮

**Comment by wrac4242** [comment]
ok, are you using the official nvidia drivers?

**Comment by GitSquared** [comment]
> two 2080ti

Nice rig, but the SLI config might be the reason you're experiencing trouble here... do you have VDPAU video acceleration drivers? (also, wrac's question is important)

**Comment by pmarreck** [comment]
@wrac4242 Yes, the proprietary ones.
@GitSquared I’m afraid I don’t know what that is.

**Comment by GitSquared** [comment]
GPU video acceleration drivers. How to check for/install them will depend on your distro but the Arch wiki has some good information you should be able to use anywhere: https://wiki.archlinux.org/index.php/Hardware_video_acceleration

**Comment by wrac4242** [comment]
and the proprietary ones work in mysterious ways, and are one of the only things that has crashed my arch install

**Comment by pmarreck** [comment]
Ah, forgot to mention, the 2 GPU's are not actually set up in an SLI config. They're literally just plugged into separate PCI slots and not connected to each other. I use one to offload some computing tasks

**Comment by pmarreck** [comment]
@wrac4242 Unfortunately, gaming was one of the priorities on this particular setup, hence the proprietary drivers due to performance reasons. I totally get the "open source everything" philosophy though.

**Comment by officialshubhamgupta** [comment]
RUN AT CMD
GITHUB PROGRAM

**Comment by GitSquared** [comment]
@pmarreck of course. You should be able to setup video acceleration packages with the proprietary drivers, using NVENCODE / VDPAU packages, on your distro. I think this should help fix the issue in edex as it will provide better interoperability between the browser instance we use and the two GPUs. Check the wiki link I sent you earlier.
