### ISSUE TITLE
“eDEX-UI” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by RealLau** [GitSquared/edex-ui#995]
can not open edex-ui even from terminal with sudo.

tried with sudo but still get the same error as below:
![image](https://user-images.githubusercontent.com/16678624/103259020-9ebbce00-49d2-11eb-81c5-a5b1d6dbc094.png)

OSX: macOS Catalina version 10.15.7

**Comment by goldenspy** [comment]
I have the same problem

**Comment by Animus-Surge** [comment]
The reason behind this is because no binaries are signed. You can look at the FAQ for the reasoning behind this.

You can work around this error as stated in a section of [this Apple support page](https://support.apple.com/en-us/HT202491).

**Comment by meet234** [comment]
move to trash
