### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RichardcLee** [GitSquared/edex-ui#996]
**Running on:**
Windows 10

---

## Problem
![image](https://user-images.githubusercontent.com/28611665/103399184-b635bb00-4b7a-11eb-9ad1-78aec7406d06.png)

**Comment by kionglp** [comment]
``

**Comment by wrac4242** [comment]
can you try running from source to see if that is an issue, as events.js seems to be having a lot of issue lately

**Comment by GitSquared** [comment]
Note that events.js is internal (not in edex's code, a layer below that). I think all those issues might be related / the same problem.
