### ISSUE TITLE
Report An Error:ECONNRESET

### ISSUE THREAD

**Issue by PheonixHkbxoic** [GitSquared/edex-ui#999]
## Technical information
**Using version:**
 - [ ] `master` (running from GitHub-published source code, currently `v3.0.0-pre`)
 - [x] `latest` (latest release, currently `v2.2.5`)
 - [ ] `vX.X.X` (specify other version)

**Running on:**
 - [ ] Linux
 - [x] Windows
 - [ ] macOS

**How comfortable you are with your system and/or IT in general:**
 - [x] I'm kind of lost, honestly
 - [ ] I know what's up, I could help you run some commands or checks
 - [ ] My machine is fully under my control, tell me what you need
 - [ ] I attended [Defcon](https://defcon.org/) last year

---

## Problem

Just Report An Error as the following:
```text
Error: read ECONNRESET
Uncaught Error:read ECONNRESET
at event.js 287:7

```

**Comment by wrac4242** [comment]
see #989 for others having the problem
